[package]
name = "dayz-community-hub-bin"
version.workspace = true
edition.workspace = true

[[bin]]
name = "dayz-community-hub"
path = "src/main.rs"

[dependencies]
dayz-community-hub-core.workspace = true
dayz-community-hub-ui.workspace = true
tokio.workspace = true
termion = "4"
ratatui = { version = "0.30.0", default-features = false, features = ["termion"] }
