[workspace]

[package]
name = "dayz-community-hub"
version = "0.2.0"
description = "DayZ Community Hub"
authors = ["thoxy"]
edition = "2021"

[lib]
name = "dayz_community_hub_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["native-tls"] }
tauri-plugin-opener = "2"
tauri-plugin-shell = "2"
tauri-plugin-http = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
dayz-community-hub-core = { path = "../../dayz-community-hub-core" }
a2s = { version = "0.6.1", features = ["async"] }
tokio-stream = { version = "0.1.18", features = ["full"] }
reqwest = { version = "0.13.2", features = ["rustls", "json", "query"] }
base64 = "0.22"
zstd = "0.13"
zip = { version = "8.1.0", default-features = false, features = ["deflate"] }
which = "8.0.0"
tauri-plugin-dialog = "2"
tauri-plugin-clipboard-manager = "2.3.2"
tauri-plugin-single-instance = "2"
clap = { version = "4", features = ["derive"] }

[target."cfg(windows)".dependencies]
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
thiserror = "2"

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.26"

[profile.dev]
incremental = true # Compile your binary in smaller steps.

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true # Enables link-time-optimizations.
opt-level = "s" # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort" # Higher performance by disabling panic handlers.
strip = true # Ensures debug symbols are removed.
