name: CI image

on:
  push:
    branches:
      - master
    paths:
      - '.forgejo/ci-image/Dockerfile'
  workflow_dispatch:

concurrency:
  group: ci-image
  cancel-in-progress: true

jobs:
  build-push:
    name: Build and push CI image
    runs-on: docker
    container:
      image: docker:27
      options: --privileged -v /run/user/1001/podman/podman.sock:/var/run/docker.sock
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Login to registry
        env:
          REGISTRY_PASS: ${{ secrets.FORGEJO_TOKEN }}
        run: |
          echo "$REGISTRY_PASS" | \
            docker login git.thoxy.xyz -u thoxy --password-stdin

      - name: Build and push
        run: |
          docker build \
            -t git.thoxy.xyz/thoxy/dayz-community-hub/ci:latest \
            .forgejo/ci-image/

          docker push git.thoxy.xyz/thoxy/dayz-community-hub/ci:latest
