//! Tauri's build step, plus the app's own command permissions and the
//! Windows application manifest (`windows/app.manifest`).
//!
//! Every command is declared to Tauri's ACL so a window may only call the
//! commands its capability grants. The main window gets them all (the
//! `all-commands` set, generated here); the hidden dayz.com window, which
//! runs remote content, gets only the one it returns the news through.
//!
//! The list is read from `src/ipc.rs`'s `collect_commands!`, the one place
//! commands are registered, so a new command cannot be left out of the ACL.

use std::fs;

fn commands() -> Vec<&'static str> {
    let ipc = fs::read_to_string("src/ipc.rs").expect("reading src/ipc.rs");
    let start = ipc
        .find("collect_commands![")
        .expect("collect_commands! in src/ipc.rs");
    let body = &ipc[start + "collect_commands![".len()..];
    let body = &body[..body.find(']').expect("end of collect_commands!")];
    body.split(',')
        .map(str::trim)
        .filter(|s| !s.is_empty() && !s.starts_with("//"))
        .map(|path| path.rsplit("::").next().unwrap_or(path).trim())
        .map(|name| &*Box::leak(name.to_owned().into_boxed_str()))
        .collect()
}

fn main() {
    println!("cargo:rerun-if-changed=src/ipc.rs");
    println!("cargo:rerun-if-changed=windows/app.manifest");
    let commands = commands();

    // The set the main window's capability grants: every command.
    let set = format!(
        "# Generated by build.rs from src/ipc.rs - DO NOT EDIT.\n\n[[set]]\nidentifier = \"all-commands\"\ndescription = \"Every command the app registers, for the main window.\"\npermissions = [\n{}]\n",
        commands
            .iter()
            .map(|c| format!("  \"allow-{}\",\n", c.replace('_', "-")))
            .collect::<String>()
    );
    fs::create_dir_all("permissions").expect("creating permissions/");
    let path = "permissions/all-commands.toml";
    if fs::read_to_string(path).ok().as_deref() != Some(set.as_str()) {
        fs::write(path, set).expect("writing permissions/all-commands.toml");
    }

    let commands: &'static [&'static str] = Box::leak(commands.into_boxed_slice());
    // The Windows manifest: DPI awareness, Windows 10/11, long paths, no
    // elevation (Tauri's default only asks for Common Controls v6).
    let windows = tauri_build::WindowsAttributes::new()
        .app_manifest(fs::read_to_string("windows/app.manifest").expect("windows/app.manifest"));
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .windows_attributes(windows)
            .app_manifest(tauri_build::AppManifest::new().commands(commands)),
    )
    .expect("tauri build step");
}
