// @generated from apps/gui/src-tauri by `make bindings`. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Whether this is the first launch (no profile yet), asked before
	 *  `initialize` so the wizard can show at once.
	 */
	checkFirstLaunch: () => __TAURI_INVOKE<boolean>("check_first_launch"),
	/**
	 *  Create the controller and load the server list: from the on-disk cache
	 *  when there is one (the window refreshes it in the background), else from
	 *  the API. The profile and the cache are read at the same time.
	 * 
	 *  Called when the window mounts, and again when it reloads (the "Retry"
	 *  after a failed start): a second call replaces the state in place.
	 */
	initialize: () => __TAURI_INVOKE<InitResult>("initialize"),
	/**  One server with its mods, by query port. */
	getServerDetails: (ip: string, port: number) => __TAURI_INVOKE<ServerDto>("get_server_details", { ip, port }),
	/**
	 *  Fetch the list from the API again. Returns how many servers it holds;
	 *  the browser re-queries on the `servers-changed` that follows.
	 */
	refreshServers: () => __TAURI_INVOKE<number>("refresh_servers"),
	/**  The title bar's counters. */
	getAppStats: () => __TAURI_INVOKE<AppStatsDto>("get_app_stats"),
	/**  A filtered, sorted window of the server list, with totals. */
	serversQuery: (query: ServerQuery) => __TAURI_INVOKE<ServerPage>("servers_query", { query }),
	/**
	 *  Full rows for "ip:port" keys (query or game port), in the same order;
	 *  null for a server that is not in the list.
	 */
	serversLookup: (keys: string[]) => __TAURI_INVOKE<(ServerRow | null)[]>("servers_lookup", { keys }),
	/**  Every map in the list, busiest first. */
	serverMaps: () => __TAURI_INVOKE<MapCount[]>("server_maps"),
	/**
	 *  Ping the whole list in the background (replacing a running scan).
	 *  Progress arrives on `on_progress` at most four times a second; the rows
	 *  themselves change through `servers-changed`.
	 */
	startScan: (onProgress: Channel<ScanProgress>) => __TAURI_INVOKE<null>("start_scan", { onProgress }),
	/**
	 *  Ping a small explicit list (favorites, history) and stream the results.
	 *  Runs beside the whole-list scan, not instead of it.
	 */
	pingServers: (targets: string[], concurrency: number | null, timeoutMs: number | null, onProgress: Channel<PingResultDto[]>) => __TAURI_INVOKE<null>("ping_servers", { targets, concurrency, timeoutMs, onProgress }),
	/**  Known results for `targets` ("ip:port"); targets never pinged are left out. */
	getPings: (targets: string[]) => __TAURI_INVOKE<PingResultDto[]>("get_pings", { targets }),
	/**  Ping one server, with the long manual timeout. Returns the RTT in ms. */
	pingSingle: (ip: string, port: number, timeoutMs: number | null) => __TAURI_INVOKE<number>("ping_single", { ip, port, timeoutMs }),
	/**  Stop the whole-list scan and clear the pause. */
	cancelPing: () => __TAURI_INVOKE<null>("cancel_ping"),
	/**  Pause or resume scanning. Returns whether it is now paused. */
	togglePingPause: () => __TAURI_INVOKE<boolean>("toggle_ping_pause"),
	/**  Query a server's live details (cached for 30 s). */
	queryA2s: (ip: string, queryPort: number, gamePort: number | null) => __TAURI_INVOKE<A2sDetailsDto>("query_a2s", { ip, queryPort, gamePort }),
	/**  Find a server on BattleMetrics by IP and ports, falling back to its name. */
	fetchBattlemetricsServer: (ip: string, port: number, queryPort: number, name: string) => __TAURI_INVOKE<BattleMetricsServer>("fetch_battlemetrics_server", { ip, port, queryPort, name }),
	/**  What DayZ Metrics knows about the server at `ip`, by game or query port. */
	fetchServerMetrics: (ip: string, gamePort: number, queryPort: number) => __TAURI_INVOKE<ServerMetrics>("fetch_server_metrics", { ip, gamePort, queryPort }),
	/**  The current profile. */
	getProfile: () => __TAURI_INVOKE<ProfileDto>("get_profile"),
	/**  Save the account and ping settings. */
	saveProfileSettings: (settings: ProfileSettingsInput) => __TAURI_INVOKE<null>("save_profile_settings", { settings }),
	/**  Add a favorite (or update its name and password). */
	addFavorite: (name: string, ip: string, port: number, password: string | null) => __TAURI_INVOKE<null>("add_favorite", { name, ip, port, password }),
	removeFavorite: (ip: string, port: number) => __TAURI_INVOKE<null>("remove_favorite", { ip, port }),
	removeHistoryEntry: (ip: string, port: number) => __TAURI_INVOKE<null>("remove_history_entry", { ip, port }),
	clearHistory: () => __TAURI_INVOKE<null>("clear_history"),
	/**  Hide an IP's servers from the browser. */
	addExcludedIp: (ip: string) => __TAURI_INVOKE<null>("add_excluded_ip", { ip }),
	removeExcludedIp: (ip: string) => __TAURI_INVOKE<null>("remove_excluded_ip", { ip }),
	/**  Export all settings files from the data directory as a zstd-compressed bundle. */
	exportProfile: (path: string, includeMods: boolean) => __TAURI_INVOKE<null>("export_profile", { path, includeMods }),
	/**
	 *  Import a profile bundle, replacing the settings files. The bundle is read
	 *  and checked in full first, so a bad file leaves the current settings alone.
	 */
	importProfile: (path: string) => __TAURI_INVOKE<ProfileDto>("import_profile", { path }),
	/**  Wipe the entire data directory so the app looks brand-new on next boot. */
	resetProfile: () => __TAURI_INVOKE<null>("reset_profile"),
	/**
	 *  Restart the application immediately (into the new version after an
	 *  update: an AppImage restarts from `$APPIMAGE`).
	 */
	restartApp: () => __TAURI_INVOKE<void>("restart_app"),
	/**
	 *  Get installed mods. Uses spawn_blocking for filesystem scan.
	 *  Enriches each mod with `remote_updated` / `update_available` from the in-memory cache.
	 */
	getInstalledMods: () => __TAURI_INVOKE<InstalledModDto[]>("get_installed_mods"),
	/**
	 *  Fetch `time_updated` for all installed mods from the Steam Workshop API and
	 *  cache the results. Returns the enriched mod list (same as `get_installed_mods`).
	 */
	checkModUpdates: () => __TAURI_INVOKE<InstalledModDto[]>("check_mod_updates"),
	/**
	 *  Delete a mod by ID: the launcher's copy and its link, and the Steam
	 *  account's subscription to it (Steam then removes its own copy). Returns
	 *  true when a copy in a Steam library remains: Steam was not running, or
	 *  would not unsubscribe (the launcher never deletes in a Steam library).
	 */
	deleteMod: (modId: number) => __TAURI_INVOKE<boolean>("delete_mod", { modId }),
	/**
	 *  Delete several mods by ID, then unsubscribe from them in one Steam
	 *  session. Returns the ids whose Steam copy remains.
	 */
	deleteModsBulk: (modIds: number[]) => __TAURI_INVOKE<number[]>("delete_mods_bulk", { modIds }),
	/**  Toggle managed status of a mod. */
	toggleModManaged: (modId: number) => __TAURI_INVOKE<boolean>("toggle_mod_managed", { modId }),
	/**
	 *  Delete every mod the launcher downloaded and every `@` link; mods in
	 *  Steam libraries stay.
	 */
	cleanupMods: () => __TAURI_INVOKE<string>("cleanup_mods"),
	/**
	 *  Open the launcher's workshop folder (where SteamCMD downloads) in the
	 *  system file manager.
	 */
	openWorkshopDir: () => __TAURI_INVOKE<null>("open_workshop_dir"),
	/**  Open the directory of the copy of a mod in use in the system file manager. */
	openModDir: (modId: number) => __TAURI_INVOKE<null>("open_mod_dir", { modId }),
	/**  Create the `@<id>` links a listed server's mods need. */
	setupModSymlinks: (ip: string, port: number) => __TAURI_INVOKE<null>("setup_mod_symlinks", { ip, port }),
	/**  Flip a launch option. Returns whether it is now enabled. */
	toggleLaunchOption: (key: string) => __TAURI_INVOKE<boolean>("toggle_launch_option", { key }),
	/**  Set a launch option's value; a value also enables it. */
	setLaunchOptionValue: (key: string, value: string | null) => __TAURI_INVOKE<null>("set_launch_option_value", { key, value }),
	/**
	 *  Join a listed server by its query port. Returns at once; the outcome
	 *  arrives as a `launch-done` or `launch-error` event.
	 */
	launchServer: (ip: string, port: number, password: string | null) => __TAURI_INVOKE<null>("launch_server", { ip, port, password }),
	/**
	 *  Join by address, whether or not the server is listed. Returns at once;
	 *  the outcome arrives as a `launch-done` or `launch-error` event.
	 */
	launchDirect: (ip: string, gamePort: number, password: string | null, extraArgs: string[] | null) => __TAURI_INVOKE<null>("launch_direct", { ip, gamePort, password, extraArgs }),
	/**
	 *  Start a mod operation in the background; its progress streams over
	 *  `on_progress` and ends with a `finished` step.
	 */
	startModOperation: (opType: ModOpType, ip: string | null, port: number | null, modId: number | null, modName: string | null, modIds: number[] | null, modNames: string[] | null, onProgress: Channel<ModProgressEvent>) => __TAURI_INVOKE<null>("start_mod_operation", { opType, ip, port, modId, modName, modIds, modNames, onProgress }),
	/**  Send input (password or Steam Guard code) to the running steamcmd PTY. */
	sendSteamcmdInput: (input: string) => __TAURI_INVOKE<null>("send_steamcmd_input", { input }),
	/**  Cancel the running mod operation. */
	cancelModOperation: () => __TAURI_INVOKE<null>("cancel_mod_operation"),
	/**  Where SteamCMD downloads and keeps its login. */
	steamcmdDirs: () => __TAURI_INVOKE<SteamcmdDirsDto>("steamcmd_dirs"),
	/**  Open SteamCMD's install directory in the system file manager. */
	openSteamcmdDir: () => __TAURI_INVOKE<null>("open_steamcmd_dir"),
	detectSteamcmd: () => __TAURI_INVOKE<SteamcmdStatusDto>("detect_steamcmd"),
	/**
	 *  Start a background task that polls for steamcmd every 3 seconds.
	 *  Each tick re-reads `steamcmd_path` from the live profile, so a user
	 *  editing the path during the wizard takes effect immediately rather than
	 *  being stuck with the value captured at watch start.
	 */
	watchSteamcmd: () => __TAURI_INVOKE<null>("watch_steamcmd"),
	/**  Windows-only: download steamcmd.zip from Valve and unzip it. */
	downloadSteamcmdWindows: () => __TAURI_INVOKE<string>("download_steamcmd_windows"),
	/**  Choose what downloads mods; the next operation uses it. */
	setModDownloader: (downloader: ModDownloaderDto) => __TAURI_INVOKE<null>("set_mod_downloader", { downloader }),
	/**
	 *  Load Valve's library (the first call writes it to disk) and look for a
	 *  running Steam, without connecting to it.
	 */
	steamworksStatus: () => __TAURI_INVOKE<SteamworksStatusDto>("steamworks_status"),
	/**
	 *  Connect to Steam as DayZ and disconnect at once: rejects with the
	 *  sentence a download would fail with.
	 */
	steamworksCheck: () => __TAURI_INVOKE<null>("steamworks_check"),
	/**
	 *  The DayZ Workshop items the Steam account is subscribed to, with what
	 *  Steam is doing with each (installed, downloading, waiting), and the
	 *  Workshop's details (title, required items) of those and of `ids` (the
	 *  mods on disk). Asks the running Steam client in a short session (Steam
	 *  shows DayZ running for a moment), at most every few seconds; while
	 *  another session is open (a download through Steam), the last answer.
	 */
	steamSubscriptions: (ids: number[]) => __TAURI_INVOKE<SteamSubscriptionsDto>("steam_subscriptions", { ids }),
	/**  Get available offline missions. */
	getOfflineMissions: () => __TAURI_INVOKE<string[]>("get_offline_missions"),
	/**  Download/update DayZCommunityOfflineMode. */
	updateOfflineMode: () => __TAURI_INVOKE<null>("update_offline_mode"),
	/**  Remove all DayZCommunityOfflineMode mission folders from DayZ/Missions/. */
	removeOfflineMode: () => __TAURI_INVOKE<number>("remove_offline_mode"),
	/**  Remove a single mission. */
	removeMission: (mission: string) => __TAURI_INVOKE<null>("remove_mission", { mission }),
	/**  Delete storage_-1/ save directories inside each offline mission folder. */
	clearOfflineSaves: () => __TAURI_INVOKE<number>("clear_offline_saves"),
	/**  Open the missions directory in the file manager. */
	openMissionsDir: () => __TAURI_INVOKE<null>("open_missions_dir"),
	/**  Open a specific offline mission's folder in the system file manager. */
	openMissionDir: (mission: string) => __TAURI_INVOKE<null>("open_mission_dir", { mission }),
	/**  Launch an offline mission. */
	launchOfflineMission: (mission: string) => __TAURI_INVOKE<null>("launch_offline_mission", { mission }),
	/**
	 *  Fetch the latest news articles.
	 * 
	 *  Tries a direct HTTP request first (browser-shaped, to clear Cloudflare). If
	 *  dayz.com ever serves a challenge instead, we fall back to fetching it inside
	 *  a WebView (see [`fetch_news_via_webview`]).
	 */
	fetchNews: () => __TAURI_INVOKE<ArticleDto[]>("fetch_news"),
	/**  IPC target invoked by the in-page script with the fetched JSON body. */
	newsWebviewResult: (payload: string) => __TAURI_INVOKE<void>("news_webview_result", { payload }),
	/**
	 *  Fetch an image URL through Rust (bypasses WebKit TLS cert validation),
	 *  cache it to disk, and return the local file path.
	 */
	fetchImage: (url: string) => __TAURI_INVOKE<string>("fetch_image", { url }),
	/**
	 *  Resolve multiple image URLs at once. Returns a Vec of (url, local_path)
	 *  for every URL that is already cached on disk — no network requests.
	 */
	resolveCachedImages: (urls: string[]) => __TAURI_INVOKE<([string, string])[]>("resolve_cached_images", { urls }),
	/**  Fetch the Steam avatar for the configured account and cache it as a data: URI. */
	fetchSteamAvatar: () => __TAURI_INVOKE<string | null>("fetch_steam_avatar"),
	/**  Fetch Steam player count for DayZ. */
	fetchSteamPlayerCount: () => __TAURI_INVOKE<number>("fetch_steam_player_count"),
	/**  Return the CLI args that were passed when this instance started. */
	getCliArgs: () => __TAURI_INVOKE<CliArgs>("get_cli_args"),
	/**  Read a `.dzch` server-connection file and return its contents. */
	readDzchFile: (path: string) => __TAURI_INVOKE<DzchConfig>("read_dzch_file", { path }),
	/**  Write a `.dzch` server-connection file to disk. */
	writeDzchFile: (path: string, config: DzchConfig) => __TAURI_INVOKE<null>("write_dzch_file", { path, config }),
	/**  Parse a `dzch://` URL into a DzchConfig. */
	parseDzchUrl: (url: string) => __TAURI_INVOKE<DzchConfig>("parse_dzch_url", { url }),
	/**
	 *  Detect the machine's CPU/RAM specs so the UI can recommend tuned DayZ launch
	 *  options (`-cpuCount`, `-exThreads`, `-maxMem`, …).
	 */
	getSystemSpecs: () => __TAURI_INVOKE<SystemSpecsDto>("get_system_specs"),
	/**
	 *  Look for a newer version. `null` when this one is the latest. Works on
	 *  every kind of copy, so a package user still learns a release is out.
	 */
	checkForUpdate: () => __TAURI_INVOKE<{
	version: string,
	currentVersion: string,
	/**  Release notes. */
	body: string | null,
	/**  Release date, ISO 8601. */
	date: string | null,
} | null>("check_for_update"),
	/**
	 *  Download, verify and install the version `check_for_update` found. Ends
	 *  with a `Finished` event; the window then calls `restart_app`.
	 */
	installUpdate: (onEvent: Channel<DownloadEvent>) => __TAURI_INVOKE<null>("install_update", { onEvent }),
	/**  Whether this copy can update itself. */
	updateSupport: () => __TAURI_INVOKE<UpdateSupport>("update_support"),
	/**  Open a web page (or a steam:// link) in the system's handler. */
	openUrl: (url: string) => __TAURI_INVOKE<null>("open_url", { url }),
	/**  Copy text to the clipboard. */
	copyText: (text: string) => __TAURI_INVOKE<null>("copy_text", { text }),
	/**
	 *  A file (or a folder, with `directory`) the player chose; null if they
	 *  cancelled.
	 */
	pickFile: (title: string, directory: boolean, filters: FileFilter[]) => __TAURI_INVOKE<string | null>("pick_file", { title, directory, filters }),
	/**  Where the player wants a file written; null if they cancelled. */
	saveFile: (title: string, defaultName: string, filters: FileFilter[]) => __TAURI_INVOKE<string | null>("save_file", { title, defaultName, filters }),
	/**  The player's approximate location, from ip-api.com. */
	geolocateIp: () => __TAURI_INVOKE<GeoLocation>("geolocate_ip"),
	/**  The pads, and whether a controller UI is to be expected. */
	gamepadStatus: () => __TAURI_INVOKE<GamepadStatus>("gamepad_status"),
};

/** Events */
export const events = {
	cliArgs: makeEvent<CliArgs>("cli-args"),
	gamepadInput: makeEvent<GamepadInput>("gamepad-input"),
	gamepadPads: makeEvent<GamepadPads>("gamepad-pads"),
	launchDone: makeEvent<LaunchDone>("launch-done"),
	launchError: makeEvent<LaunchError>("launch-error"),
	offlineModeError: makeEvent<OfflineModeError>("offline-mode-error"),
	offlineModeUpdated: makeEvent<OfflineModeUpdated>("offline-mode-updated"),
	serversChanged: makeEvent<ServersChanged>("servers-changed"),
	steamcmdDetected: makeEvent<SteamcmdDetected>("steamcmd-detected"),
};

/* Types */
/**  What DayZ states about itself in A2S_INFO's keywords. */
export type A2sDayzDto = {
	battleye: boolean,
	/**  Third-person view is off. */
	first_person_only: boolean,
	/**  A shard of Bohemia's public hive: not a community server, no private hive. */
	official: boolean,
	/**  The server keeps its own characters. */
	private_hive: boolean,
	whitelisted: boolean,
	/**  The server needs a DLC map. */
	dlc: boolean,
	shard: string | null,
	/**  Players waiting in the login queue. */
	login_queue: number | null,
	/**  How many times faster than real time the day passes. */
	time_accel: number | null,
	/**  The same, at night. */
	night_time_accel: number | null,
	/**  The in-game clock, `HH:MM`. */
	game_time: string | null,
};

export type A2sDetailsDto = {
	server_name: string,
	game: string,
	/**  Human players (bots subtracted). */
	players: number,
	max_players: number,
	/**
	 *  Bots reported by A2S_INFO. DayZ servers commonly pad this to equal
	 *  `players` to fake a full server.
	 */
	bots: number,
	map: string,
	version: string,
	players_list: A2sPlayerDto[],
	/**  Mods from the server list; empty for a server that is not listed. */
	mods: ModDto[],
	/**  Mod names from the A2S rules, in load order. */
	mods_from_a2s: string[],
	/**
	 *  The mods the server announces over A2S, with their Workshop ids: what
	 *  an unlisted server needs to be joined.
	 */
	mods_a2s: ModDto[],
	/**  The settings from A2S_INFO's keywords; `None` when it sent none. */
	dayz: A2sDayzDto | null,
	/**  Server rules/cvars other than the mods. */
	rules: A2sRuleDto[],
	/**  The query port that was used. */
	query_port: number,
	/**  The game port: from the server list, else from A2S's extended info. */
	game_port: number | null,
};

export type A2sPlayerDto = {
	name: string,
	score: number,
	duration: number | null,
};

export type A2sRuleDto = {
	name: string,
	value: string,
};

/**  The title bar's counters. */
export type AppStatsDto = {
	server_count: number,
	total_players: number,
	player_name: string | null,
	steam_login: string | null,
	has_steamcmd: boolean,
};

/**  One article, ready to render. */
export type ArticleDto = {
	title: string,
	slug: string,
	excerpt: string | null,
	content_text: string,
	content_html: string,
	date: string,
	url: string,
	image_url: string | null,
	category: string | null,
	author: string | null,
};

/**  BattleMetrics server info fetched on demand for the detail panel. */
export type BattleMetricsServer = {
	/**  BattleMetrics server ID (used to build the BM page URL). */
	id: string,
	/**  Server name from BattleMetrics. */
	name: string,
	/**  Global rank (1 = most popular). None if not ranked. */
	rank: number | null,
	/**  Server status: "online" | "offline" | "dead" */
	status: string,
	/**  ISO 3166-1 alpha-2 country code, e.g. "DE", "US". */
	country: string | null,
	/**  Server coordinates (longitude, latitude). None if unavailable. */
	location: [number | null, number | null] | null,
	/**  Uptime percentage over the last 30 days (0–100). */
	uptime: number | null,
	/**  Whether the server is private (password protected). */
	private: boolean | null,
	/**  Whether this is an official server. */
	official: boolean | null,
	/**  Whether third-person view is allowed. */
	third_person: boolean | null,
	/**  Whether the server is modded. */
	modded: boolean | null,
	/**  Query status: "valid", "invalid", etc. */
	query_status: string | null,
	/**  Server's Steam ID. */
	server_steam_id: string | null,
	/**  When the server was first seen on BattleMetrics (ISO 8601). */
	created_at: string | null,
	/**  Player count data points for the last 24 h: (unix_secs, player_count) pairs. */
	player_history: ([number, number])[],
	/**  Current player count from BattleMetrics. */
	players: number | null,
	/**  Max players from BattleMetrics. */
	max_players: number | null,
};

/**  DayZ Community Hub launcher. */
export type CliArgs = {
	/**
	 *  Open the Direct Connect tab and pre-fill this IP address.
	 *  Accepts "ip" or "ip:port" (port defaults to 2302).
	 */
	connect: string | null,
	/**  Immediately reconnect to the last server from history. */
	reconnect: boolean,
	/**
	 *  A `.dzch` file path or `dzch://` URL to open.
	 *  When provided, the app switches to Direct Connect and auto-connects
	 *  to the server described in the file / URL (downloading missing mods
	 *  if the user agrees).
	 */
	open: string | null,
};

/**
 *  How far an update's download has got, sent over a `Channel`, in the shape
 *  tauri-plugin-updater's JS side uses: `{ event: "Started", data: { contentLength } }`.
 */
export type DownloadEvent = { event: "Started"; data: {
	contentLength: number | null,
} } | { event: "Progress"; data: {
	chunkLength: number,
} } | 
/**  Downloaded, verified and in place: restart to use it. */
{ event: "Finished" };

/**  The `.dzch` server connection config. */
export type DzchConfig = {
	/**  Format version (currently 1). */
	version: number,
	/**  Server IP or hostname. */
	ip: string,
	/**  Game port (default 2302).  Used to connect. */
	port: number,
	/**
	 *  Query port (A2S).  Used to fetch live server info.
	 *  When absent the receiver can fall back to heuristics.
	 */
	query_port?: number | null,
	/**  Server display name (informational). */
	name?: string,
	/**  Connection password (empty / absent = no password). */
	password?: string | null,
	/**  Required Workshop mods. */
	mods?: DzchMod[],
};

/**  A mod entry inside a `.dzch` file. */
export type DzchMod = {
	id: number,
	name?: string,
};

export type FavoriteDto = {
	name: string,
	ip: string,
	port: number,
	/**  Saved join password, filled into Direct Connect. */
	password: string | null,
};

/**  A file-type filter of a file dialog: a label and its extensions (no dot). */
export type FileFilter = {
	name: string,
	extensions: string[],
};

/**  A pad asked the window to do something. */
export type GamepadInput = {
	action: PadAction,
	/**  Fired again because the button or stick is still held. */
	repeat: boolean,
};

/**  The pads connected now; sent whenever one comes or goes. */
export type GamepadPads = PadInfo[];

/**  What the window needs to know at start-up. */
export type GamepadStatus = {
	/**  Pads could be opened at all. */
	available: boolean,
	pads: PadInfo[],
	/**
	 *  Running inside Steam's big-screen interface, a Steam Deck's Game Mode
	 *  or Big Picture, where Steam's on-screen keyboard is there to type with.
	 */
	steam_ui: boolean,
};

/**  Where the player is, approximately, from their IP address. */
export type GeoLocation = {
	lat: number | null,
	lon: number | null,
	city: string,
	country: string,
	country_code: string,
};

export type HistoryDto = {
	name: string,
	ip: string,
	port: number,
	/**  Unix seconds of the last join. */
	ts: number,
	relative_time: string,
};

/**  Response from the `initialize` command. */
export type InitResult = {
	server_count: number,
	from_cache: boolean,
	/**  True when no profile existed yet (the setup wizard should run). */
	is_first_launch: boolean,
	/**  Why there is no list: no cache and the API could not be reached. */
	list_error: string | null,
};

export type InstalledModDto = {
	name: string,
	id: number,
	/**  When steamcmd last wrote the mod (Unix seconds). */
	local_updated: number,
	size: number,
	size_human: string,
	/**  An `@<id>` link in the DayZ directory loads it. */
	managed: boolean,
	/**
	 *  Whose folder the copy in use is in: the launcher's, which it updates
	 *  and deletes, or a Steam library's, which it only reads.
	 */
	source: ModSourceDto,
	/**  The copy's directory. */
	path: string,
	/**  Another, older copy is in the other kind of folder. */
	other_copy: boolean,
	/**  `time_updated` on the Workshop; null until checked. */
	remote_updated: number | null,
	/**  True when `remote_updated > local_updated`. */
	update_available: boolean,
};

/**  A launch reached Steam; carries the server's name. */
export type LaunchDone = string;

/**  A launch failed; carries the error. */
export type LaunchError = string;

export type LaunchOptionDto = {
	key: string,
	enabled: boolean,
	value: string | null,
	description: string,
};

/**  A map and how many servers run it. */
export type MapCount = {
	map: string,
	count: number,
};

/**  A link the server lists on its page. */
export type MetricsLink = {
	label: string,
	url: string,
};

/**  What downloads mods. */
export type ModDownloaderDto = 
/**  SteamCMD, into the launcher's folder (the default). */
"steamcmd" | 
/**  The running Steam client, into the user's Steam library. */
"steamworks";

export type ModDto = {
	name: string,
	steam_workshop_id: number,
};

/**  Which mod operation to run. */
export type ModOpType = 
/**  Install what a listed server needs (`ip`, `port`). */
"install_server" | 
/**  Re-download every mod a listed server uses (`ip`, `port`). */
"update_server" | 
/**  Re-download every installed mod. */
"update_all" | 
/**  Re-download the mods the last Workshop check found stale. */
"update_stale" | 
/**  Re-download one mod (`mod_id`, `mod_name`). */
"update_one" | 
/**  Re-download these mods (`mod_ids`, optionally `mod_names`). */
"update_selected" | 
/**  Install these mods by Workshop id (`mod_ids`, `mod_names`). */
"install_manual" | 
/**
 *  Download these mods again and check every file (`mod_ids`,
 *  optionally `mod_names`): slow, for a mod that does not load.
 */
"repair" | 
/**  Log SteamCMD in and quit, so later downloads use its cached login. */
"login";

/**  One step of a mod operation, as the progress dialog receives it. */
export type ModProgressEvent = {
	kind: ModProgressKind,
	current: number,
	total: number,
	mod_id: number,
	name: string,
	ok: number,
	failed: number,
	hint: string | null,
	log_line: string | null,
};

/**  What a [`ModProgressEvent`] reports. */
export type ModProgressKind = 
/**  SteamCMD logged in; its login is cached from now on. */
"logged_in" | "steam_guard_mobile_required" | "password_required" | "log_line" | "log_progress" | "starting" | "done" | "failed" | "finished";

/**  Whose folder a mod is in. */
export type ModSourceDto = "launcher" | "steam";

/**  The offline mode download failed; carries the error. */
export type OfflineModeError = string;

/**  The offline mode finished downloading. */
export type OfflineModeUpdated = null;

/**
 *  What the window is asked to do. Named after what they do, not after the
 *  buttons, so the interface reads the same whatever the pad.
 */
export type PadAction = "up" | "down" | "left" | "right" | 
/**  A (Xbox), Cross (PlayStation): the bottom face button. */
"accept" | 
/**  B, Circle: the right face button. */
"back" | 
/**  X, Square: the left face button. */
"primary" | 
/**  Y, Triangle: the top face button. */
"secondary" | 
/**  Start, Options, ≡. */
"menu" | 
/**  Back/View, Share/Create, ⧉. */
"view" | 
/**  LB, L1. */
"prevTab" | 
/**  RB, R1. */
"nextTab" | 
/**  LT, L2. */
"pageUp" | 
/**  RT, R2. */
"pageDown";

/**  A connected pad. */
export type PadInfo = {
	name: string,
	kind: PadKind,
};

/**  What kind of pad, for the glyphs the window draws. */
export type PadKind = "xbox" | "playStation" | "nintendo" | "steamDeck" | "generic";

/**  One ping, as the window receives it. */
export type PingResultDto = {
	ip: string,
	port: number,
	ms: number,
	players: number | null,
	max_players: number | null,
	/**  Bots reported by A2S_INFO (DayZ servers often pad this to fake a full server). */
	bots: number | null,
	/**  True when the query failed (timeout or error). */
	failed: boolean,
};

export type ProfileDto = {
	steam_login: string | null,
	/**
	 *  A password an earlier version saved is still to be typed once at
	 *  SteamCMD's prompt (never sent back to the window).
	 */
	has_saved_password: boolean,
	/**  The account SteamCMD last logged in as; its login is cached. */
	steamcmd_logged_in: string | null,
	steam_root: string | null,
	steamcmd_enabled: boolean,
	/**  What downloads mods: SteamCMD or the Steam client. */
	mod_downloader: ModDownloaderDto,
	/**  Explicit path to the steamcmd binary (overrides auto-detection). */
	steamcmd_path: string | null,
	player: string | null,
	steam_api_key: string | null,
	steam_id: string | null,
	battlemetrics_api_key: string | null,
	/**  The user's location for distances, as (longitude, latitude). */
	user_location: [number | null, number | null] | null,
	favorites: FavoriteDto[],
	history: HistoryDto[],
	options: LaunchOptionDto[],
	/**  IPs hidden from the server browser. */
	excluded_ips: string[],
	/**  Ping concurrency (5-100). */
	ping_concurrency: number,
	/**  Background ping timeout in ms (1000-5000). */
	ping_timeout_auto: number,
	/**  Manual ping timeout in ms (1000-30000). */
	ping_timeout_manual: number,
	/**  Consecutive timeouts before auto-retry stops (0-5). */
	ping_max_retries: number,
	/**  Include favorites in the background scan. */
	ping_scan_favorites: boolean,
	/**  Include history in the background scan. */
	ping_scan_history: boolean,
	/**  Include every other server in the background scan. */
	ping_scan_servers: boolean,
};

/**  The account and ping settings, as the settings dialog saves them. */
export type ProfileSettingsInput = {
	player: string | null,
	steamLogin: string | null,
	steamRoot: string | null,
	steamcmdEnabled: boolean,
	steamcmdPath: string | null,
	steamApiKey: string | null,
	steamId: string | null,
	battlemetricsApiKey: string | null,
	/**  (longitude, latitude). */
	userLocation: [number | null, number | null] | null,
	/**  Clamped to 5-100. */
	pingConcurrency: number,
	/**  Clamped to 1000-5000 ms. */
	pingTimeoutAuto: number,
	/**  Clamped to 1000-30000 ms. */
	pingTimeoutManual: number,
	/**  Clamped to 0-5. */
	pingMaxRetries: number,
	pingScanFavorites: boolean,
	pingScanHistory: boolean,
	pingScanServers: boolean,
};

/**  When the server restarts, as the site has measured it. */
export type RestartSchedule = {
	period_hours: number | null,
	/**  ISO 8601. */
	last_restart: string | null,
	/**  ISO 8601. */
	next_restart: string | null,
	/**  "high" | "medium" | "low", as the site rates its own guess. */
	confidence: string | null,
	/**  Restart times of day, "HH:MM" UTC. */
	slots_utc: string[],
};

/**  How far the scan of the whole list has got. */
export type ScanProgress = {
	done: number,
	total: number,
	paused: boolean,
	running: boolean,
};

/**  A server with its mod list, for the detail panel and the connect flow. */
export type ServerDto = {
	game_port: number,
	ip: string,
	query_port: number,
	name: string,
	map: string,
	players: number,
	max_players: number,
	environment: string,
	password: boolean,
	version: string,
	first_person_only: boolean,
	time: string,
	mods_count: number,
	mods: ModDto[],
	vac: boolean,
	battl_eye: boolean | null,
};

/**  What DayZ Metrics knows about a server, for the server panel's Stats tab. */
export type ServerMetrics = {
	/**  The site's id for the server. */
	id: number,
	/**  Its page on dayzmetrics.com. */
	url: string,
	name: string,
	map: string | null,
	version: string | null,
	/**  "online" | "offline" | … */
	status: string | null,
	/**  ISO 3166-1 alpha-2. */
	country: string | null,
	players: number | null,
	max_players: number | null,
	queue: number | null,
	/**  Position in the site's ranking (1 is the top). */
	rank_pos: number | null,
	rank_score: number | null,
	/**  How reliably it is up, 0–1, as the ranking weighs it. */
	rank_alive: number | null,
	/**  How sought after it is, 0–1, as the ranking weighs it. */
	rank_demand: number | null,
	avg_players_7d: number | null,
	peak_7d: number | null,
	/**  Percent of the last seven days it answered. */
	uptime_7d: number | null,
	/**  Players week over week, percent (+12 means 12 % more than last week). */
	wow_pct: number | null,
	/**  ISO 8601. */
	first_seen: string | null,
	/**  ISO 8601. */
	last_seen: string | null,
	/**  The site's own pings to it, milliseconds. */
	ping_lo: number | null,
	ping_hi: number | null,
	ping_jitter: number | null,
	ping_stability: number | null,
	/**  In-game time multiplier, by day and by night. */
	time_accel: number | null,
	night_time_accel: number | null,
	restart: RestartSchedule | null,
	wipe: WipeSchedule | null,
	/**  The site judges the player count to be padded (bots, fake slots). */
	is_fake: boolean,
	fake_reasons: string[],
	/**  "real" | "suspicious" | "fake" | …: how the count behaves over time. */
	behavior_verdict: string | null,
	behavior_score: number | null,
	/**  Reported by players and flagged by the site. */
	flagged: boolean,
	/**  Named to look like an official server without being one. */
	mimics_official: boolean,
	discord: string | null,
	website: string | null,
	links: MetricsLink[],
	notices: string[],
	playstyle: string | null,
	/**  "Vanilla" … "Heavily Modded", and the score behind it (0–100). */
	vanilla_band: string | null,
	vanilla_score: number | null,
	mod_count: number | null,
	/**  Bytes to download for every mod the server runs. */
	mod_total_bytes: number | null,
	/**  The last 24 hours: (unix seconds, players), every five minutes. */
	player_history: ([number, number | null])[],
	/**  The last 24 hours: (unix seconds, ms), where the site measured it. */
	ping_history: ([number, number | null])[],
};

/**  A window of the filtered, sorted list. */
export type ServerPage = {
	/**  Servers matching the filters. */
	total: number,
	/**  Rows `offset..offset + limit`. */
	rows: ServerRow[],
	stats: ServerStats,
	/**  The data generation these rows reflect. */
	generation: number,
};

/**  What the browser shows: filters, sort, and the window of rows wanted. */
export type ServerQuery = {
	/**  Case-insensitive, over name, IP and map. */
	search: string,
	map: string | null,
	firstPerson: Tri,
	password: Tri,
	battleye: Tri,
	modded: Tri,
	/**  Bohemia's own servers (only listed with a Steam API key). */
	official: Tri,
	hideEmpty: boolean,
	hideFull: boolean,
	/**  0 = any. Otherwise timeouts and slower servers go; unpinged ones stay. */
	maxPing: number,
	/**  Show servers on excluded IPs too. */
	showExcluded: boolean,
	sort: SortCol,
	asc: boolean,
	offset: number,
	limit: number,
};

/**  One row of the browser: the server with its freshest known state. */
export type ServerRow = {
	game_port: number,
	ip: string,
	query_port: number,
	name: string,
	map: string,
	/**  Freshest known: the last successful query, else the list. */
	players: number,
	max_players: number,
	environment: string,
	password: boolean,
	version: string,
	first_person_only: boolean,
	time: string,
	mods_count: number,
	vac: boolean,
	battl_eye: boolean | null,
	bots: number,
	/**  Null when never pinged. >= 5000 when it timed out. */
	ping_ms: number | null,
	ping_failed: boolean,
	favorite: boolean,
	excluded: boolean,
	/**  Full according to the list, but the last query failed. */
	unverified_full: boolean,
	/**  Bohemia's own server. */
	official: boolean,
	/**  A community server named like an official one ("1234 | EUROPE - DE"). */
	mimics_official: boolean,
};

/**  Totals over the filtered servers. */
export type ServerStats = {
	shown: number,
	players: number,
	full: number,
	empty: number,
	modded: number,
	official: number,
	pinged: number,
	best_ping: number | null,
};

/**  The list, or live data, changed: re-query what is on screen. */
export type ServersChanged = {
	generation: number,
};

/**  The column the browser sorts by. */
export type SortCol = "none" | "ping" | "players" | "name" | "map" | "mods" | 
/**  In-game time, "HH:MM" as minutes. */
"time";

/**  One Workshop item the Steam account is subscribed to, as Steam has it. */
export type SteamSubscriptionDto = {
	id: number,
	subscribed: boolean,
	installed: boolean,
	needs_update: boolean,
	downloading: boolean,
	pending: boolean,
	bytes_done: number,
	bytes_total: number,
};

/**  The account's subscriptions, or why they are not known. */
export type SteamSubscriptionsDto = {
	/**  Steam answered. */
	available: boolean,
	/**  Why it did not, when it did not. */
	reason: string | null,
	items: SteamSubscriptionDto[],
	/**
	 *  Title and requirements of the subscribed items, of the mods asked
	 *  about, and of what they require.
	 */
	details: WorkshopItemDto[],
};

/**  steamcmd appeared while `watch_steamcmd` was polling. */
export type SteamcmdDetected = SteamcmdStatusDto;

/**  Where SteamCMD keeps its things: the launcher's, never the Steam client's. */
export type SteamcmdDirsDto = {
	/**  Its install directory, where mods download. */
	content: string,
	/**
	 *  The `HOME` it runs with (Linux), where its login is cached; null on
	 *  Windows, where it keeps everything beside its executable.
	 */
	home: string | null,
};

export type SteamcmdStatusDto = {
	found: boolean,
	path: string | null,
	platform: string,
};

/**  Whether downloads through Steam can work on this machine. */
export type SteamworksStatusDto = {
	/**  Valve's library loaded. */
	library: boolean,
	/**  Why it did not, when it did not. */
	error: string | null,
	/**  The Steam client is running. */
	steam_running: boolean,
};

/**  Hardware specs used to recommend optimal DayZ launch options. */
export type SystemSpecsDto = {
	/**  Logical CPU count (threads). */
	logical_cores: number,
	/**  Physical CPU core count (falls back to logical when unknown). */
	physical_cores: number,
	/**  Total system RAM in megabytes. */
	total_memory_mb: number,
};

/**  A three-way filter: everything, only those with the flag, only those without. */
export type Tri = "all" | "only" | "none";

/**  A newer version than the one running. */
export type UpdateInfo = {
	version: string,
	currentVersion: string,
	/**  Release notes. */
	body: string | null,
	/**  Release date, ISO 8601. */
	date: string | null,
};

/**  What kind of copy this is, as far as updating goes. */
export type UpdateKind = "appimage" | "windows-zip" | "package-manager" | "dev";

/**  Whether this copy can install an update, and if not, why. */
export type UpdateSupport = {
	supported: boolean,
	kind: UpdateKind,
	reason: string | null,
};

/**  When the server wipes: the last one and the next, each announced or guessed. */
export type WipeSchedule = {
	/**  "YYYY-MM-DD". */
	last: string | null,
	/**  "announced" | "detected" | … */
	last_source: string | null,
	days_since: number | null,
	/**  "YYYY-MM-DD". */
	next: string | null,
	/**  "announced" | "predicted" | … */
	next_source: string | null,
	days_until: number | null,
	period_days: number | null,
};

/**  What the Workshop says about an item. */
export type WorkshopItemDto = {
	id: number,
	title: string,
	/**  The items it requires ("Required items" on its Workshop page). */
	requires: number[],
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

