import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "about",
  content: {
    updatesRestart: t({
      en: "Restart now",
      fr: "Redémarrer maintenant",
      de: "Jetzt neu starten",
      es: "Reiniciar ahora",
      ru: "Перезапустить",
    }),
    updatesDevBuild: t({
      en: "This is a development build: updates are not installed from here.",
      fr: "Ceci est une version de développement : les mises à jour ne s'installent pas d'ici.",
      de: "Dies ist ein Entwicklungs-Build: Updates werden hier nicht installiert.",
      es: "Esta es una versión de desarrollo: las actualizaciones no se instalan desde aquí.",
      ru: "Это сборка для разработки: обновления здесь не устанавливаются.",
    }),
    system: t({
      en: "This machine",
      fr: "Cette machine",
      de: "Dieser Rechner",
      es: "Este equipo",
      ru: "Этот компьютер",
    }),
    systemCpu: t({
      en: "Processor",
      fr: "Processeur",
      de: "Prozessor",
      es: "Procesador",
      ru: "Процессор",
    }),
    systemCores: insert(
      t({
        en: "{{physical}} cores · {{logical}} threads",
        fr: "{{physical}} cœurs · {{logical}} threads",
        de: "{{physical}} Kerne · {{logical}} Threads",
        es: "{{physical}} núcleos · {{logical}} hilos",
        ru: "{{physical}} ядер · {{logical}} потоков",
      }),
    ),
    systemMemory: t({
      en: "Memory",
      fr: "Mémoire",
      de: "Arbeitsspeicher",
      es: "Memoria",
      ru: "Память",
    }),
    systemHint: t({
      en: "Used to suggest -cpuCount, -exThreads and -maxMem in Launch options.",
      fr: "Sert à proposer -cpuCount, -exThreads et -maxMem dans les options de lancement.",
      de: "Dient für Vorschläge zu -cpuCount, -exThreads und -maxMem in den Startoptionen.",
      es: "Sirve para sugerir -cpuCount, -exThreads y -maxMem en las opciones de inicio.",
      ru: "Используется для подсказок -cpuCount, -exThreads и -maxMem.",
    }),
    version: t({ en: "Version", fr: "Version", de: "Version", es: "Versión", ru: "Версия" }),
    checkUpdates: t({
      en: "Check for updates",
      fr: "Rechercher des mises à jour",
      de: "Nach Updates suchen",
      es: "Buscar actualizaciones",
      ru: "Проверить обновления",
    }),
    updatesPackageManager: t({
      en: "On this system, updates come through your package manager or a new release download.",
      fr: "Sur ce système, les mises à jour passent par votre gestionnaire de paquets ou le téléchargement d'une nouvelle version.",
      de: "Auf diesem System kommen Updates über den Paketmanager oder einen neuen Download.",
      es: "En este sistema, las actualizaciones llegan por tu gestor de paquetes o una nueva descarga.",
      ru: "В этой системе обновления приходят через менеджер пакетов или новую загрузку.",
    }),
    licenseMit: t({
      en: "MIT licence",
      fr: "Licence MIT",
      de: "MIT-Lizenz",
      es: "Licencia MIT",
      ru: "Лицензия MIT",
    }),
    openSource: t({
      en: "Free and open source",
      fr: "Libre et open source",
      de: "Frei und quelloffen",
      es: "Libre y de código abierto",
      ru: "Свободное ПО с открытым кодом",
    }),
    heroTagline: t({
      en: "Server browser & mod manager for DayZ Standalone",
      fr: "Navigateur de serveurs et gestionnaire de mods pour DayZ Standalone",
      de: "Server-Browser & Mod-Manager für DayZ Standalone",
      es: "Navegador de servidores y gestor de mods para DayZ Standalone",
      ru: "Браузер серверов и менеджер модов для DayZ Standalone",
    }),
    sourceRepo: t({
      en: "Source repository",
      fr: "Dépôt source",
      de: "Quellcode-Repository",
      es: "Repositorio de código",
      ru: "Исходный код",
    }),
    featBrowser: t({
      en: "Server Browser",
      fr: "Navigateur de serveurs",
      de: "Server-Browser",
      es: "Navegador de servidores",
      ru: "Браузер серверов",
    }),
    featMods: t({
      en: "Mod Manager",
      fr: "Gestionnaire de mods",
      de: "Mod-Manager",
      es: "Gestor de mods",
      ru: "Менеджер модов",
    }),
    featStats: t({
      en: "Server stats",
      fr: "Stats des serveurs",
      de: "Serverstatistiken",
      es: "Estadísticas de servidores",
      ru: "Статистика серверов",
    }),
    featLaunch: t({
      en: "One-click Launch",
      fr: "Lancement en un clic",
      de: "Ein-Klick-Start",
      es: "Inicio con un clic",
      ru: "Запуск в один клик",
    }),
    updates: t({
      en: "Updates",
      fr: "Mises à jour",
      de: "Updates",
      es: "Actualizaciones",
      ru: "Обновления",
    }),
    updatesChecking: t({
      en: "Checking for updates…",
      fr: "Vérification des mises à jour…",
      de: "Suche nach Updates…",
      es: "Comprobando actualizaciones…",
      ru: "Проверка обновлений…",
    }),
    updatesUpToDate: t({
      en: "You're up to date",
      fr: "Vous êtes à jour",
      de: "Du bist auf dem neuesten Stand",
      es: "Estás actualizado",
      ru: "У вас актуальная версия",
    }),
    updatesLatest: insert(
      t({
        en: "v{{version}} is the latest version",
        fr: "v{{version}} est la dernière version",
        de: "v{{version}} ist die neueste Version",
        es: "v{{version}} es la última versión",
        ru: "v{{version}} — последняя версия",
      }),
    ),
    updatesRecheck: t({
      en: "Re-check",
      fr: "Revérifier",
      de: "Erneut prüfen",
      es: "Volver a comprobar",
      ru: "Проверить снова",
    }),
    updatesAvailable: t({
      en: "Update available —",
      fr: "Mise à jour disponible —",
      de: "Update verfügbar —",
      es: "Actualización disponible —",
      ru: "Доступно обновление —",
    }),
    updatesCurrent: t({
      en: "Current:",
      fr: "Actuelle :",
      de: "Aktuell:",
      es: "Actual:",
      ru: "Текущая:",
    }),
    updatesReleased: insert(
      t({
        en: "Released {{date}}",
        fr: "Publiée le {{date}}",
        de: "Veröffentlicht {{date}}",
        es: "Publicada {{date}}",
        ru: "Выпущено {{date}}",
      }),
    ),
    updatesInstall: t({
      en: "Install update",
      fr: "Installer la mise à jour",
      de: "Update installieren",
      es: "Instalar actualización",
      ru: "Установить обновление",
    }),
    updatesDownloading: insert(
      t({
        en: "Downloading v{{version}}…",
        fr: "Téléchargement de v{{version}}…",
        de: "Lade v{{version}} herunter…",
        es: "Descargando v{{version}}…",
        ru: "Скачивание v{{version}}…",
      }),
    ),
    updatesDone: t({
      en: "Download complete",
      fr: "Téléchargement terminé",
      de: "Download abgeschlossen",
      es: "Descarga completa",
      ru: "Скачивание завершено",
    }),
    updatesDoneHint: t({
      en: "The installer is launching — the app will restart automatically.",
      fr: "L'installateur se lance — l'application redémarrera automatiquement.",
      de: "Der Installer startet — die App wird automatisch neu gestartet.",
      es: "El instalador se está iniciando — la aplicación se reiniciará automáticamente.",
      ru: "Установщик запускается — приложение перезагрузится автоматически.",
    }),
    updatesRetry: t({
      en: "Retry",
      fr: "Réessayer",
      de: "Erneut versuchen",
      es: "Reintentar",
      ru: "Повторить",
    }),
    quickstart: t({
      en: "Quick Start",
      fr: "Démarrage rapide",
      de: "Schnellstart",
      es: "Inicio rápido",
      ru: "Быстрый старт",
    }),
    qsStep1Title: t({
      en: "Open account settings",
      fr: "Ouvrir les paramètres du compte",
      de: "Kontoeinstellungen öffnen",
      es: "Abre la configuración de cuenta",
      ru: "Откройте настройки аккаунта",
    }),
    qsStep1Body: t({
      en: 'Click your name (or "Set up account") in the title bar to configure your player name, Steam credentials, and API keys.',
      fr: "Cliquez sur votre nom (ou « Configurer le compte ») dans la barre de titre pour configurer votre nom de joueur, identifiants Steam et clés API.",
      de: 'Klicke auf deinen Namen (oder "Konto einrichten") in der Titelleiste um Spielername, Steam-Anmeldedaten und API-Schlüssel zu konfigurieren.',
      es: 'Haz clic en tu nombre (o "Configurar cuenta") en la barra de título para configurar tu nombre de jugador, credenciales de Steam y claves API.',
      ru: 'Нажмите на своё имя (или "Настроить аккаунт") в заголовке для настройки имени игрока, учётных данных Steam и API-ключей.',
    }),
    qsStep2Title: t({
      en: "Set your in-game name",
      fr: "Définir votre nom en jeu",
      de: "Spielername festlegen",
      es: "Establece tu nombre en el juego",
      ru: "Задайте имя в игре",
    }),
    qsStep2Body: t({
      en: "This is the character name passed as -name= when launching DayZ.",
      fr: "C'est le nom de personnage passé comme -name= au lancement de DayZ.",
      de: "Dies ist der Charaktername der als -name= beim DayZ-Start übergeben wird.",
      es: "Este es el nombre del personaje que se pasa como -name= al iniciar DayZ.",
      ru: "Это имя персонажа, передаваемое как -name= при запуске DayZ.",
    }),
    qsStep3Title: t({
      en: "Browse & connect",
      fr: "Parcourir et se connecter",
      de: "Durchsuchen & verbinden",
      es: "Explora y conecta",
      ru: "Ищите и подключайтесь",
    }),
    qsStep3Body: t({
      en: "Use the Servers tab to find a server. Double-click a row or click Connect to launch DayZ directly.",
      fr: "Utilisez l'onglet Serveurs pour trouver un serveur. Double-cliquez ou cliquez sur Connexion pour lancer DayZ.",
      de: "Benutze den Server-Tab um einen Server zu finden. Doppelklicke eine Zeile oder klicke Verbinden um DayZ direkt zu starten.",
      es: "Usa la pestaña Servidores para encontrar un servidor. Haz doble clic en una fila o clic en Conectar para iniciar DayZ directamente.",
      ru: "Используйте вкладку Серверы для поиска сервера. Дважды щёлкните по строке или нажмите Подключиться для запуска DayZ.",
    }),
    steamcmd: t({
      en: "SteamCMD & Mods",
      fr: "SteamCMD et Mods",
      de: "SteamCMD & Mods",
      es: "SteamCMD y mods",
      ru: "SteamCMD и моды",
    }),
    steamcmdWhat: t({
      en: "What is SteamCMD?",
      fr: "Qu'est-ce que SteamCMD ?",
      de: "Was ist SteamCMD?",
      es: "¿Qué es SteamCMD?",
      ru: "Что такое SteamCMD?",
    }),
    steamcmdDesc: insert(
      t({
        en: "A command-line tool from Valve used to download Steam Workshop content without the full Steam client. The app uses it to install and update DayZ mods in the background. If the title bar shows {{notFound}}, install it below or set the path manually in account settings.",
        fr: "Un outil en ligne de commande de Valve pour télécharger du contenu Steam Workshop. L'application l'utilise pour installer et mettre à jour les mods DayZ. Si la barre de titre affiche {{notFound}}, installez-le ci-dessous ou définissez le chemin dans les paramètres.",
        de: "Ein Befehlszeilen-Tool von Valve zum Herunterladen von Steam Workshop-Inhalten ohne den vollständigen Steam-Client. Die App verwendet es um DayZ-Mods im Hintergrund zu installieren und zu aktualisieren. Wenn in der Titelleiste {{notFound}} angezeigt wird, installiere es unten oder setze den Pfad manuell in den Kontoeinstellungen.",
        es: "Una herramienta de línea de comandos de Valve usada para descargar contenido de Steam Workshop sin el cliente completo de Steam. La aplicación la usa para instalar y actualizar mods de DayZ en segundo plano. Si la barra de título muestra {{notFound}}, instálalo abajo o establece la ruta manualmente en la configuración de cuenta.",
        ru: "Консольная утилита от Valve для скачивания контента Steam Workshop без полного клиента Steam. Приложение использует её для установки и обновления модов DayZ в фоне. Если в заголовке отображается {{notFound}}, установите её ниже или укажите путь вручную в настройках аккаунта.",
      }),
    ),
    steamcmdNotFound: t({
      en: "SteamCMD not found",
      fr: "SteamCMD non trouvé",
      de: "SteamCMD nicht gefunden",
      es: "SteamCMD no encontrado",
      ru: "SteamCMD не найден",
    }),
    steamcmdLinuxDebian: t({
      en: "Debian / Ubuntu",
      fr: "Debian / Ubuntu",
      de: "Debian / Ubuntu",
      es: "Debian / Ubuntu",
      ru: "Debian / Ubuntu",
    }),
    steamcmdLinuxArch: t({
      en: "Arch / Manjaro",
      fr: "Arch / Manjaro",
      de: "Arch / Manjaro",
      es: "Arch / Manjaro",
      ru: "Arch / Manjaro",
    }),
    steamcmdLinuxFedora: t({
      en: "Fedora / RHEL",
      fr: "Fedora / RHEL",
      de: "Fedora / RHEL",
      es: "Fedora / RHEL",
      ru: "Fedora / RHEL",
    }),
    steamcmdWinDesc: t({
      en: "SteamCMD will be downloaded from Valve and installed to",
      fr: "SteamCMD sera téléchargé depuis Valve et installé dans",
      de: "SteamCMD wird von Valve heruntergeladen und installiert in",
      es: "SteamCMD se descargará de Valve e instalará en",
      ru: "SteamCMD будет скачан от Valve и установлен в",
    }),
    steamcmdInstalled: t({
      en: "SteamCMD installed successfully.",
      fr: "SteamCMD installé avec succès.",
      de: "SteamCMD erfolgreich installiert.",
      es: "SteamCMD instalado correctamente.",
      ru: "SteamCMD успешно установлен.",
    }),
    steamcmdDownloading: t({
      en: "Downloading SteamCMD…",
      fr: "Téléchargement de SteamCMD…",
      de: "SteamCMD wird heruntergeladen…",
      es: "Descargando SteamCMD…",
      ru: "Скачивание SteamCMD…",
    }),
    steamcmdInstall: t({
      en: "Install SteamCMD",
      fr: "Installer SteamCMD",
      de: "SteamCMD installieren",
      es: "Instalar SteamCMD",
      ru: "Установить SteamCMD",
    }),
    modWorkflow: t({
      en: "Mod workflow",
      fr: "Workflow des mods",
      de: "Mod-Workflow",
      es: "Flujo de trabajo de mods",
      ru: "Работа с модами",
    }),
    modStep1: t({
      en: "Connect to a server — the app offers to install any missing mods automatically.",
      fr: "Connectez-vous à un serveur — l'application propose d'installer les mods manquants automatiquement.",
      de: "Mit einem Server verbinden — die App bietet an, fehlende Mods automatisch zu installieren.",
      es: "Conéctate a un servidor — la aplicación ofrece instalar los mods faltantes automáticamente.",
      ru: "Подключитесь к серверу — приложение предложит автоматически установить недостающие моды.",
    }),
    modStep2: t({
      en: "Go to the Mods tab and click Check updates to see which mods are outdated.",
      fr: "Allez dans l'onglet Mods et cliquez sur Vérifier les MAJ pour voir les mods obsolètes.",
      de: "Gehe zum Mods-Tab und klicke auf Updates prüfen um veraltete Mods zu sehen.",
      es: "Ve a la pestaña Mods y haz clic en Comprobar actualizaciones para ver qué mods están desactualizados.",
      ru: "Перейдите на вкладку Моды и нажмите Проверить обновления, чтобы увидеть устаревшие моды.",
    }),
    modStep3: t({
      en: "Click Update N to update all stale mods in one batch, or update them individually.",
      fr: "Cliquez sur Mettre à jour N pour tout mettre à jour en une fois, ou individuellement.",
      de: "Klicke auf N aktualisieren um alle veralteten Mods auf einmal zu aktualisieren, oder einzeln.",
      es: "Haz clic en Actualizar N para actualizar todos los mods obsoletos de una vez, o actualízalos individualmente.",
      ru: "Нажмите Обновить N для обновления всех устаревших модов одним пакетом или обновляйте их по отдельности.",
    }),
    shortcuts: t({
      en: "Keyboard Shortcuts",
      fr: "Raccourcis clavier",
      de: "Tastaturkürzel",
      es: "Atajos de teclado",
      ru: "Горячие клавиши",
    }),
    shortcutsGlobal: t({
      en: "Global",
      fr: "Global",
      de: "Global",
      es: "Globales",
      ru: "Глобальные",
    }),
    shortcutsServers: t({
      en: "Servers · Favorites · History",
      fr: "Serveurs · Favoris · Historique",
      de: "Server · Favoriten · Verlauf",
      es: "Servidores · Favoritos · Historial",
      ru: "Серверы · Избранное · История",
    }),
    shortcutsMods: t({ en: "Mods", fr: "Mods", de: "Mods", es: "Mods", ru: "Моды" }),
    shortcutTab: t({
      en: "Switch to tab 1–9",
      fr: "Aller à l'onglet 1–9",
      de: "Zu Tab 1–9 wechseln",
      es: "Cambiar a pestaña 1–9",
      ru: "Переключить на вкладку 1–9",
    }),
    shortcutRefresh: t({
      en: "Refresh server list",
      fr: "Actualiser la liste des serveurs",
      de: "Serverliste aktualisieren",
      es: "Actualizar lista de servidores",
      ru: "Обновить список серверов",
    }),
    shortcutUpdate: t({
      en: "Update stale mods",
      fr: "Mettre à jour les mods obsolètes",
      de: "Veraltete Mods aktualisieren",
      es: "Actualizar mods obsoletos",
      ru: "Обновить устаревшие моды",
    }),
    shortcutReconnect: t({
      en: "Reconnect to last server",
      fr: "Reconnecter au dernier serveur",
      de: "Mit letztem Server verbinden",
      es: "Reconectar al último servidor",
      ru: "Переподключиться к последнему серверу",
    }),
    shortcutNav: t({
      en: "Navigate the list",
      fr: "Naviguer dans la liste",
      de: "Liste navigieren",
      es: "Navegar por la lista",
      ru: "Навигация по списку",
    }),
    shortcutConnect: t({
      en: "Connect to server",
      fr: "Se connecter au serveur",
      de: "Mit Server verbinden",
      es: "Conectar al servidor",
      ru: "Подключиться к серверу",
    }),
    shortcutDirect: t({
      en: "Open in Direct Connect",
      fr: "Ouvrir dans Connexion directe",
      de: "In Direktverbindung öffnen",
      es: "Abrir en conexión directa",
      ru: "Открыть в прямом подключении",
    }),
    shortcutFav: t({
      en: "Toggle favorite",
      fr: "Basculer favori",
      de: "Favorit umschalten",
      es: "Alternar favorito",
      ru: "Переключить избранное",
    }),
    shortcutInfo: t({
      en: "Toggle info panel",
      fr: "Basculer panneau info",
      de: "Info-Panel umschalten",
      es: "Alternar panel de info",
      ru: "Переключить панель информации",
    }),
    shortcutPing: t({
      en: "Ping selected server",
      fr: "Ping du serveur sélectionné",
      de: "Ausgewählten Server pingen",
      es: "Hacer ping al servidor seleccionado",
      ru: "Пинг выбранного сервера",
    }),
    shortcutClose: t({
      en: "Close panel / deselect",
      fr: "Fermer panneau / désélectionner",
      de: "Panel schließen / Auswahl aufheben",
      es: "Cerrar panel / deseleccionar",
      ru: "Закрыть панель / снять выделение",
    }),
    shortcutDblclick: t({
      en: "Connect to server",
      fr: "Se connecter au serveur",
      de: "Mit Server verbinden",
      es: "Conectar al servidor",
      ru: "Подключиться к серверу",
    }),
    shortcutSpace: t({
      en: "Toggle checkbox",
      fr: "Basculer case à cocher",
      de: "Checkbox umschalten",
      es: "Alternar casilla",
      ru: "Переключить флажок",
    }),
    shortcutManaged: t({
      en: "Toggle managed",
      fr: "Basculer géré",
      de: "Verwaltet umschalten",
      es: "Alternar gestionado",
      ru: "Переключить управляемый",
    }),
    shortcutOpenfolder: t({
      en: "Open mod folder",
      fr: "Ouvrir le dossier du mod",
      de: "Mod-Ordner öffnen",
      es: "Abrir carpeta del mod",
      ru: "Открыть папку мода",
    }),
    sharing: t({
      en: "Sharing & Quick Connect",
      fr: "Partage et connexion rapide",
      de: "Teilen & Schnellverbindung",
      es: "Compartir y conexión rápida",
      ru: "Поделиться и быстрое подключение",
    }),
    sharingHow: t({
      en: "How it works",
      fr: "Comment ça marche",
      de: "So funktioniert es",
      es: "Cómo funciona",
      ru: "Как это работает",
    }),
    sharingDesc: insert(
      t({
        en: "Share a server with friends by copying a {{url}} URL or exporting a {{file}} file from the Direct Connect tab. When someone opens the link or file, the app automatically fills in the server address, queries for live info, and offers to install any missing mods before connecting.",
        fr: "Partagez un serveur avec vos amis en copiant une URL {{url}} ou en exportant un fichier {{file}} depuis l'onglet Connexion directe. Quand quelqu'un ouvre le lien ou fichier, l'application remplit automatiquement l'adresse et propose d'installer les mods manquants.",
        de: "Teile einen Server mit Freunden indem du eine {{url}}-URL kopierst oder eine {{file}}-Datei aus dem Direktverbindungs-Tab exportierst. Wenn jemand den Link oder die Datei öffnet, füllt die App automatisch die Serveradresse aus, fragt Live-Info ab und bietet an, fehlende Mods zu installieren.",
        es: "Comparte un servidor con amigos copiando una URL {{url}} o exportando un archivo {{file}} desde la pestaña Conexión directa. Cuando alguien abre el enlace o archivo, la aplicación rellena automáticamente la dirección del servidor, consulta info en vivo y ofrece instalar los mods faltantes antes de conectar.",
        ru: "Поделитесь сервером с друзьями, скопировав ссылку {{url}} или экспортировав файл {{file}} на вкладке Прямое подключение. Когда кто-то откроет ссылку или файл, приложение автоматически заполнит адрес сервера, запросит актуальную информацию и предложит установить недостающие моды перед подключением.",
      }),
    ),
    sharingUrls: t({
      en: "dzch:// URLs",
      fr: "URLs dzch://",
      de: "dzch://-URLs",
      es: "URLs dzch://",
      ru: "Ссылки dzch://",
    }),
    sharingUrlsDesc: t({
      en: "Compact links that encode a server address, mods, and optional password. Ideal for sharing in Discord, forums, or anywhere you can paste a link.",
      fr: "Liens compacts qui encodent une adresse serveur, mods et mot de passe optionnel. Idéal pour Discord, forums ou partout où vous pouvez coller un lien.",
      de: "Kompakte Links die Serveradresse, Mods und optionales Passwort enthalten. Ideal zum Teilen in Discord, Foren oder überall wo du einen Link einfügen kannst.",
      es: "Enlaces compactos que codifican la dirección del servidor, mods y contraseña opcional. Ideales para compartir en Discord, foros o cualquier lugar donde puedas pegar un enlace.",
      ru: "Компактные ссылки, кодирующие адрес сервера, моды и необязательный пароль. Идеально для публикации в Discord, на форумах или где угодно.",
    }),
    sharingBasic: t({
      en: "Basic:",
      fr: "Basique :",
      de: "Einfach:",
      es: "Básica:",
      ru: "Базовая:",
    }),
    sharingWithMods: t({
      en: "With mods:",
      fr: "Avec mods :",
      de: "Mit Mods:",
      es: "Con mods:",
      ru: "С модами:",
    }),
    sharingFull: t({
      en: "Full:",
      fr: "Complet :",
      de: "Vollständig:",
      es: "Completa:",
      ru: "Полная:",
    }),
    sharingParamQport: t({
      en: "Query port for A2S (falls back to heuristics if omitted)",
      fr: "Port de requête A2S (utilise l'heuristique si omis)",
      de: "Query-Port für A2S (Heuristiken wenn weggelassen)",
      es: "Puerto de consulta para A2S (usa heurísticas si se omite)",
      ru: "Порт запроса для A2S (по умолчанию определяется автоматически)",
    }),
    sharingParamName: t({
      en: "Server display name (informational, URL-encoded)",
      fr: "Nom d'affichage du serveur (informatif, encodé URL)",
      de: "Server-Anzeigename (informativ, URL-kodiert)",
      es: "Nombre del servidor (informativo, codificado en URL)",
      ru: "Отображаемое имя сервера (информационное, URL-кодированное)",
    }),
    sharingParamPassword: t({
      en: "Connection password (omit if none)",
      fr: "Mot de passe de connexion (omettre si aucun)",
      de: "Verbindungspasswort (weglassen wenn keins)",
      es: "Contraseña de conexión (omitir si no hay)",
      ru: "Пароль подключения (пропустить, если нет)",
    }),
    sharingParamMods: t({
      en: "Comma-separated Workshop IDs",
      fr: "IDs Workshop séparés par des virgules",
      de: "Kommagetrennte Workshop-IDs",
      es: "Workshop IDs separados por comas",
      ru: "Workshop ID через запятую",
    }),
    sharingFiles: t({
      en: ".dzch files",
      fr: "Fichiers .dzch",
      de: ".dzch-Dateien",
      es: "Archivos .dzch",
      ru: "Файлы .dzch",
    }),
    sharingFilesDesc: insert(
      t({
        en: "A small JSON file containing the full server config including mod names. Double-click one to open it in the app, or use the {{button}} button in the Direct Connect tab to create one.",
        fr: "Un petit fichier JSON contenant la config serveur complète avec les noms de mods. Double-cliquez pour l'ouvrir, ou utilisez le bouton {{button}} dans Connexion directe.",
        de: "Eine kleine JSON-Datei mit der vollständigen Serverkonfiguration inklusive Mod-Namen. Doppelklicke eine um sie in der App zu öffnen, oder benutze den {{button}}-Button im Direktverbindungs-Tab um eine zu erstellen.",
        es: "Un pequeño archivo JSON con la configuración completa del servidor incluyendo nombres de mods. Haz doble clic en uno para abrirlo en la aplicación, o usa el botón {{button}} en la pestaña Conexión directa para crear uno.",
        ru: "Небольшой JSON-файл с полной конфигурацией сервера, включая названия модов. Дважды щёлкните по нему для открытия в приложении, или используйте кнопку {{button}} на вкладке Прямое подключение для создания.",
      }),
    ),
    sharingFilesButton: t({
      en: "Export .dzch",
      fr: "Exporter .dzch",
      de: ".dzch exportieren",
      es: "Exportar .dzch",
      ru: "Экспорт .dzch",
    }),
    sharingFromDc: t({
      en: "Sharing from Direct Connect",
      fr: "Partager depuis Connexion directe",
      de: "Teilen aus Direktverbindung",
      es: "Compartir desde conexión directa",
      ru: "Поделиться из прямого подключения",
    }),
    sharingDcStep1: t({
      en: "Query a server in the Direct Connect tab (or press D on a server in the list).",
      fr: "Interrogez un serveur dans Connexion directe (ou appuyez sur D sur un serveur).",
      de: "Frage einen Server im Direktverbindungs-Tab ab (oder drücke D auf einem Server in der Liste).",
      es: "Consulta un servidor en la pestaña Conexión directa (o pulsa D en un servidor de la lista).",
      ru: "Запросите сервер на вкладке Прямое подключение (или нажмите D на сервере в списке).",
    }),
    sharingDcStep2: t({
      en: "Click Copy URL to copy a dzch:// link to the clipboard, or Export .dzch to save a file.",
      fr: "Cliquez sur Copier l'URL pour copier un lien dzch://, ou Exporter .dzch pour sauvegarder un fichier.",
      de: "Klicke URL kopieren um einen dzch://-Link in die Zwischenablage zu kopieren, oder .dzch exportieren um eine Datei zu speichern.",
      es: "Haz clic en Copiar URL para copiar un enlace dzch:// al portapapeles, o Exportar .dzch para guardar un archivo.",
      ru: "Нажмите Скопировать URL для копирования ссылки dzch:// или Экспорт .dzch для сохранения файла.",
    }),
    sharingDcStep3: t({
      en: "Send the link or file to friends — they open it and the app handles the rest.",
      fr: "Envoyez le lien ou fichier à vos amis — ils l'ouvrent et l'application fait le reste.",
      de: "Sende den Link oder die Datei an Freunde — sie öffnen ihn und die App erledigt den Rest.",
      es: "Envía el enlace o archivo a amigos — ellos lo abren y la aplicación se encarga del resto.",
      ru: "Отправьте ссылку или файл друзьям — они откроют его, и приложение сделает всё остальное.",
    }),
    profile: t({
      en: "Profile Management",
      fr: "Gestion du profil",
      de: "Profilverwaltung",
      es: "Gestión de perfil",
      ru: "Управление профилем",
    }),
    profileExport: t({
      en: "Export",
      fr: "Exporter",
      de: "Exportieren",
      es: "Exportar",
      ru: "Экспорт",
    }),
    profileExportDesc: insert(
      t({
        en: "Save settings, favorites, history to a {{file}} file (zstd-compressed, portable between machines).",
        fr: "Sauvegarder paramètres, favoris, historique dans un fichier {{file}} (compressé zstd, portable).",
        de: "Einstellungen, Favoriten, Verlauf in einer {{file}}-Datei speichern (zstd-komprimiert, zwischen Geräten übertragbar).",
        es: "Guardar configuración, favoritos, historial en un archivo {{file}} (comprimido con zstd, portable entre máquinas).",
        ru: "Сохранить настройки, избранное, историю в файл {{file}} (сжатый zstd, переносимый между машинами).",
      }),
    ),
    profileIncludeMods: t({
      en: "Include managed mod list",
      fr: "Inclure la liste des mods gérés",
      de: "Verwaltete Mod-Liste einschließen",
      es: "Incluir lista de mods gestionados",
      ru: "Включить список управляемых модов",
    }),
    profileImport: t({
      en: "Import",
      fr: "Importer",
      de: "Importieren",
      es: "Importar",
      ru: "Импорт",
    }),
    profileImportDesc: insert(
      t({
        en: "Restore a previously exported {{file}} file. Overwrites current profile and mod list.",
        fr: "Restaurer un fichier {{file}} exporté précédemment. Écrase le profil actuel et la liste des mods.",
        de: "Eine zuvor exportierte {{file}}-Datei wiederherstellen. Überschreibt aktuelles Profil und Mod-Liste.",
        es: "Restaurar un archivo {{file}} exportado previamente. Sobrescribe el perfil actual y la lista de mods.",
        ru: "Восстановить ранее экспортированный файл {{file}}. Перезаписывает текущий профиль и список модов.",
      }),
    ),
    profileReset: t({
      en: "Reset to defaults",
      fr: "Réinitialiser",
      de: "Auf Standard zurücksetzen",
      es: "Restablecer valores predeterminados",
      ru: "Сбросить к умолчаниям",
    }),
    profileResetDesc: t({
      en: "Wipe profile back to factory defaults — clears all settings, favorites, history and launch options. Installed mods on disk are not affected.",
      fr: "Réinitialiser le profil aux valeurs par défaut — efface tous les paramètres, favoris, historique et options de lancement. Les mods installés ne sont pas affectés.",
      de: "Profil auf Werkseinstellungen zurücksetzen — löscht alle Einstellungen, Favoriten, Verlauf und Startoptionen. Installierte Mods auf der Festplatte sind nicht betroffen.",
      es: "Restablecer el perfil a valores de fábrica — borra toda la configuración, favoritos, historial y opciones de inicio. Los mods instalados en disco no se afectan.",
      ru: "Вернуть профиль к заводским настройкам — удалить все настройки, избранное, историю и параметры запуска. Установленные моды на диске не затрагиваются.",
    }),
    tips: t({ en: "Tips", fr: "Astuces", de: "Tipps", es: "Consejos", ru: "Советы" }),
    tipAuthTitle: t({
      en: "AuthPlayerLoginState Error",
      fr: "Erreur AuthPlayerLoginState",
      de: "AuthPlayerLoginState-Fehler",
      es: "Error AuthPlayerLoginState",
      ru: "Ошибка AuthPlayerLoginState",
    }),
    tipAuthStep1: t({
      en: "Launch the game",
      fr: "Lancez le jeu",
      de: "Starte das Spiel",
      es: "Inicia el juego",
      ru: "Запустите игру",
    }),
    tipAuthStep2: t({
      en: "Rename your character and apply",
      fr: "Renommez votre personnage et appliquez",
      de: "Benenne deinen Charakter um und bestätige",
      es: "Cambia el nombre de tu personaje y aplica",
      ru: "Переименуйте своего персонажа и примените",
    }),
    tipAuthStep3: t({
      en: "Return to rename menu and rename back, apply",
      fr: "Retournez au menu de renommage, renommez à nouveau et appliquez",
      de: "Gehe zurück zum Umbenennen-Menü, benenne zurück und bestätige",
      es: "Vuelve al menú de renombrar, cambia el nombre de nuevo y aplica",
      ru: "Вернитесь в меню переименования, переименуйте обратно и примените",
    }),
    tipAuthStep4: t({
      en: "Click play",
      fr: "Cliquez sur jouer",
      de: "Klicke auf Spielen",
      es: "Haz clic en jugar",
      ru: "Нажмите играть",
    }),
    tipPerfTitle: t({
      en: "Performance",
      fr: "Performance",
      de: "Leistung",
      es: "Rendimiento",
      ru: "Производительность",
    }),
    tipPerfDesc: t({
      en: "The launcher may be slower while the progress bar on the Servers tab is visible (pinging servers in background).",
      fr: "Le lanceur peut être plus lent lorsque la barre de progression dans l'onglet Serveurs est visible (ping des serveurs en arrière-plan).",
      de: "Der Launcher kann langsamer sein, während die Fortschrittsanzeige im Server-Tab sichtbar ist (Server werden im Hintergrund angepingt).",
      es: "El lanzador puede ser más lento mientras la barra de progreso en la pestaña Servidores está visible (haciendo ping a servidores en segundo plano).",
      ru: "Лаунчер может работать медленнее, пока индикатор выполнения на вкладке Серверы виден (пинг серверов в фоновом режиме).",
    }),
    pingSettings: t({
      en: "Ping Settings",
      fr: "Paramètres de ping",
      de: "Ping-Einstellungen",
      es: "Configuración de ping",
      ru: "Настройки пинга",
    }),
    pingConcurrency: t({
      en: "Concurrency (parallel pings)",
      fr: "Concurrence (pings parallèles)",
      de: "Parallelität (gleichzeitige Pings)",
      es: "Concurrencia (pings paralelos)",
      ru: "Параллельность (одновременные пинги)",
    }),
    pingTimeoutAuto: t({
      en: "Auto ping timeout",
      fr: "Délai d'expiration auto",
      de: "Auto-Ping-Timeout",
      es: "Tiempo de espera automático",
      ru: "Авто-таймаут пинга",
    }),
    pingTimeoutManual: t({
      en: "Manual ping timeout",
      fr: "Délai d'expiration manuel",
      de: "Manueller Ping-Timeout",
      es: "Tiempo de espera manual",
      ru: "Ручной таймаут пинга",
    }),
    pingMaxRetries: t({
      en: "Max retries before stopping",
      fr: "Tentatives max",
      de: "Max. Wiederholungen",
      es: "Reintentos máximos",
      ru: "Макс. повторов",
    }),
    pingRetryDisabled: t({
      en: "Disabled",
      fr: "Désactivé",
      de: "Deaktiviert",
      es: "Desactivado",
      ru: "Отключено",
    }),
    pingScanScope: t({
      en: "Auto-ping scope",
      fr: "Portée du ping auto",
      de: "Auto-Ping-Bereich",
      es: "Alcance del ping auto",
      ru: "Область авто-пинга",
    }),
    pingScanFavorites: t({
      en: "Favorites",
      fr: "Favoris",
      de: "Favoriten",
      es: "Favoritos",
      ru: "Избранное",
    }),
    pingScanHistory: t({
      en: "History",
      fr: "Historique",
      de: "Verlauf",
      es: "Historial",
      ru: "История",
    }),
    pingScanServers: t({
      en: "Servers",
      fr: "Serveurs",
      de: "Server",
      es: "Servidores",
      ru: "Серверы",
    }),
    tabs: t({ en: "Tabs", fr: "Onglets", de: "Tabs", es: "Pestañas", ru: "Вкладки" }),
    tabServers: t({ en: "Servers", fr: "Serveurs", de: "Server", es: "Servidores", ru: "Серверы" }),
    tabServersDesc: t({
      en: "Live server list with search, filters and sortable table.",
      fr: "Liste des serveurs en direct avec recherche, filtres et tableau triable.",
      de: "Live-Serverliste mit Suche, Filtern und sortierbarer Tabelle.",
      es: "Lista de servidores en vivo con búsqueda, filtros y tabla ordenable.",
      ru: "Список серверов в реальном времени с поиском, фильтрами и сортировкой.",
    }),
    tabFavorites: t({
      en: "Favorites",
      fr: "Favoris",
      de: "Favoriten",
      es: "Favoritos",
      ru: "Избранное",
    }),
    tabFavoritesDesc: t({
      en: "Starred servers with live counts and ping.",
      fr: "Serveurs favoris avec comptage en direct et ping.",
      de: "Markierte Server mit Live-Anzahlen und Ping.",
      es: "Servidores marcados con recuentos en vivo y ping.",
      ru: "Отмеченные серверы с количеством игроков и пингом.",
    }),
    tabHistory: t({
      en: "History",
      fr: "Historique",
      de: "Verlauf",
      es: "Historial",
      ru: "История",
    }),
    tabHistoryDesc: t({
      en: "Previously joined servers with timestamps and live stats.",
      fr: "Serveurs déjà rejoints avec horodatage et stats en direct.",
      de: "Zuvor verbundene Server mit Zeitstempeln und Live-Statistiken.",
      es: "Servidores visitados previamente con marcas de tiempo y estadísticas en vivo.",
      ru: "Ранее посещённые серверы с метками времени и статистикой.",
    }),
    tabMods: t({ en: "Mods", fr: "Mods", de: "Mods", es: "Mods", ru: "Моды" }),
    tabModsDesc: t({
      en: "Manage Workshop mods — check, update, and clean up via SteamCMD.",
      fr: "Gérer les mods Workshop — vérifier, mettre à jour et nettoyer via SteamCMD.",
      de: "Workshop-Mods verwalten — prüfen, aktualisieren und aufräumen via SteamCMD.",
      es: "Gestionar mods del Workshop — comprobar, actualizar y limpiar vía SteamCMD.",
      ru: "Управление модами Workshop — проверка, обновление и очистка через SteamCMD.",
    }),
    tabNews: t({ en: "News", fr: "Actualités", de: "Neuigkeiten", es: "Noticias", ru: "Новости" }),
    tabNewsDesc: t({
      en: "Latest DayZ news from the official website.",
      fr: "Dernières actualités DayZ du site officiel.",
      de: "Aktuelle DayZ-Neuigkeiten von der offiziellen Website.",
      es: "Últimas noticias de DayZ del sitio web oficial.",
      ru: "Последние новости DayZ с официального сайта.",
    }),
    tabConnect: t({
      en: "Connect",
      fr: "Connexion",
      de: "Verbinden",
      es: "Conectar",
      ru: "Подключение",
    }),
    tabConnectDesc: t({
      en: "Direct connect by IP:port.",
      fr: "Connexion directe par IP:port.",
      de: "Direktverbindung per IP:Port.",
      es: "Conexión directa por IP:puerto.",
      ru: "Прямое подключение по IP:порт.",
    }),
    tabOptions: t({ en: "Options", fr: "Options", de: "Optionen", es: "Opciones", ru: "Опции" }),
    tabOptionsDesc: t({
      en: "Toggle DayZ launch options.",
      fr: "Activer/désactiver les options de lancement DayZ.",
      de: "DayZ-Startoptionen umschalten.",
      es: "Alternar opciones de inicio de DayZ.",
      ru: "Переключение параметров запуска DayZ.",
    }),
    tabOffline: t({
      en: "Offline",
      fr: "Hors ligne",
      de: "Offline",
      es: "Sin conexión",
      ru: "Оффлайн",
    }),
    tabOfflineDesc: t({
      en: "Community Offline Mode — solo missions without a server.",
      fr: "Mode hors ligne communautaire — missions solo sans serveur.",
      de: "Community Offline Mode — Solo-Missionen ohne Server.",
      es: "Community Offline Mode — misiones en solitario sin servidor.",
      ru: "Community Offline Mode — одиночные миссии без сервера.",
    }),
    apiKeys: t({
      en: "Optional API Keys",
      fr: "Clés API optionnelles",
      de: "Optionale API-Schlüssel",
      es: "Claves API opcionales",
      ru: "Опциональные API-ключи",
    }),
    apiSteam: t({
      en: "Steam API Key & Steam ID",
      fr: "Clé API Steam et Steam ID",
      de: "Steam API-Schlüssel & Steam-ID",
      es: "Steam API Key y Steam ID",
      ru: "Steam API Key и Steam ID",
    }),
    apiSteamHint: t({
      en: "Avatar in title bar · mod update checks",
      fr: "Avatar dans la barre de titre · vérification des mods",
      de: "Avatar in Titelleiste · Mod-Update-Prüfungen",
      es: "Avatar en barra de título · comprobaciones de actualización de mods",
      ru: "Аватар в заголовке · проверка обновлений модов",
    }),
    apiSteamAvatar: t({ en: "Avatar", fr: "Avatar", de: "Avatar", es: "Avatar", ru: "Аватар" }),
    apiSteamAvatarDesc: t({
      en: "Steam profile picture in the title bar.",
      fr: "Photo de profil Steam dans la barre de titre.",
      de: "Steam-Profilbild in der Titelleiste.",
      es: "Foto de perfil de Steam en la barra de título.",
      ru: "Фото профиля Steam в заголовке.",
    }),
    apiSteamMods: t({
      en: "Mod checks",
      fr: "Vérification des mods",
      de: "Mod-Prüfungen",
      es: "Comprobación de mods",
      ru: "Проверка модов",
    }),
    apiSteamModsDesc: t({
      en: "Workshop API queries at higher rate limits.",
      fr: "Requêtes API Workshop à limites plus élevées.",
      de: "Workshop-API-Abfragen mit höheren Rate-Limits.",
      es: "Consultas a la API del Workshop con límites más altos.",
      ru: "Запросы к Workshop API с повышенными лимитами.",
    }),
    apiSteamKey: t({
      en: "API key",
      fr: "Clé API",
      de: "API-Schlüssel",
      es: "Clave API",
      ru: "API ключ",
    }),
    apiSteamId: t({
      en: "Steam ID",
      fr: "Steam ID",
      de: "Steam-ID",
      es: "Steam ID",
      ru: "Steam ID",
    }),
    builtWith: t({
      en: "Built with",
      fr: "Construit avec",
      de: "Erstellt mit",
      es: "Construido con",
      ru: "Создано с",
    }),
    links: t({ en: "Links", fr: "Liens", de: "Links", es: "Enlaces", ru: "Ссылки" }),
    linkReleases: t({
      en: "Releases",
      fr: "Versions",
      de: "Releases",
      es: "Versiones",
      ru: "Релизы",
    }),
    linkBug: t({
      en: "Report a Bug",
      fr: "Signaler un bug",
      de: "Fehler melden",
      es: "Reportar un error",
      ru: "Сообщить об ошибке",
    }),
    linkWiki: t({ en: "Wiki", fr: "Wiki", de: "Wiki", es: "Wiki", ru: "Вики" }),
    linkLicense: t({ en: "License", fr: "Licence", de: "Lizenz", es: "Licencia", ru: "Лицензия" }),
    madeWith: t({
      en: "Made with",
      fr: "Fait avec",
      de: "Erstellt mit",
      es: "Hecho con",
      ru: "Сделано с",
    }),
    by: t({ en: "by", fr: "par", de: "von", es: "por", ru: "от" }),
    forgejo: t({ en: "Forgejo", fr: "Forgejo", de: "Forgejo", es: "Forgejo", ru: "Forgejo" }),
  },
} satisfies Dictionary;

export default content;
