import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "connect",
  content: {
    title: t({ en: "Direct Connect", fr: "Connexion directe", de: "Direktverbindung", es: "Conexión directa", ru: "Прямое подключение" }),
    connection: t({ en: "Connection", fr: "Connexion", de: "Verbindung", es: "Conexión", ru: "Подключение" }),
    ipHostname: t({ en: "IP / Hostname", fr: "IP / Nom d'hôte", de: "IP / Hostname", es: "IP / Hostname", ru: "IP / Хост" }),
    port: t({ en: "Port", fr: "Port", de: "Port", es: "Puerto", ru: "Порт" }),
    portGame: t({ en: "(game)", fr: "(jeu)", de: "(Spiel)", es: "(juego)", ru: "(игровой)" }),
    portQuery: t({ en: "(query)", fr: "(requête)", de: "(Query)", es: "(consulta)", ru: "(запрос)" }),
    password: t({ en: "Password", fr: "Mot de passe", de: "Passwort", es: "Contraseña", ru: "Пароль" }),
    optional: t({ en: "optional", fr: "optionnel", de: "optional", es: "opcional", ru: "необязательно" }),
    ipPlaceholder: t({ en: "e.g. 192.168.1.1", fr: "ex. 192.168.1.1", de: "z.B. 192.168.1.1", es: "ej. 192.168.1.1", ru: "напр. 192.168.1.1" }),
    passwordPlaceholder: t({ en: "Leave blank if none", fr: "Laisser vide si aucun", de: "Leer lassen wenn keins", es: "Dejar en blanco si no hay", ru: "Оставьте пустым, если нет" }),
    querying: t({ en: "Querying…", fr: "Interrogation…", de: "Abfrage…", es: "Consultando…", ru: "Запрос…" }),
    query: t({ en: "Query", fr: "Interroger", de: "Abfragen", es: "Consultar", ru: "Запросить" }),
    connect: t({ en: "Connect", fr: "Connexion", de: "Verbinden", es: "Conectar", ru: "Подключиться" }),
    alreadyFavorite: t({ en: "Already in favorites", fr: "Déjà dans les favoris", de: "Bereits in Favoriten", es: "Ya está en favoritos", ru: "Уже в избранном" }),
    addFavorite: t({ en: "Add to favorites", fr: "Ajouter aux favoris", de: "Zu Favoriten hinzufügen", es: "Añadir a favoritos", ru: "Добавить в избранное" }),
    copyUrlTitle: t({ en: "Copy a dzch:// URL to share this server", fr: "Copier une URL dzch:// pour partager ce serveur", de: "dzch://-URL zum Teilen kopieren", es: "Copiar URL dzch:// para compartir este servidor", ru: "Скопировать ссылку dzch:// для отправки сервера" }),
    copied: t({ en: "Copied!", fr: "Copié !", de: "Kopiert!", es: "¡Copiado!", ru: "Скопировано!" }),
    copyUrl: t({ en: "Copy URL", fr: "Copier l'URL", de: "URL kopieren", es: "Copiar URL", ru: "Скопировать URL" }),
    exportTitle: t({ en: "Save a .dzch file for one-click connect", fr: "Enregistrer un fichier .dzch pour connexion en un clic", de: ".dzch-Datei für Ein-Klick-Verbindung speichern", es: "Guardar archivo .dzch para conexión con un clic", ru: "Сохранить файл .dzch для подключения в один клик" }),
    export: t({ en: "Export .dzch", fr: "Exporter .dzch", de: ".dzch exportieren", es: "Exportar .dzch", ru: "Экспорт .dzch" }),
    extraMods: t({ en: "Extra Mods", fr: "Mods supplémentaires", de: "Zusätzliche Mods", es: "Mods adicionales", ru: "Дополнительные моды" }),
    extraModsHint: t({ en: "Add extra -mod entries not auto-detected by the server query.", fr: "Ajouter des entrées -mod non détectées automatiquement.", de: "Füge zusätzliche -mod Einträge hinzu, die nicht automatisch erkannt wurden.", es: "Añadir entradas -mod adicionales no detectadas automáticamente por la consulta del servidor.", ru: "Добавить дополнительные записи -mod, не определённые автоматически запросом сервера." }),
    mod: t({ en: "-mod", fr: "-mod", de: "-mod", es: "-mod", ru: "-mod" }),
    custom: t({ en: "custom", fr: "personnalisé", de: "custom", es: "personalizado", ru: "свой" }),
    detected: t({ en: "detected", fr: "détecté", de: "erkannt", es: "detectado", ru: "обнаружен" }),
    moveUp: t({ en: "Move up", fr: "Monter", de: "Nach oben", es: "Subir", ru: "Вверх" }),
    moveDown: t({ en: "Move down", fr: "Descendre", de: "Nach unten", es: "Bajar", ru: "Вниз" }),
    disable: t({ en: "Disable", fr: "Désactiver", de: "Deaktivieren", es: "Desactivar", ru: "Отключить" }),
    enable: t({ en: "Enable", fr: "Activer", de: "Aktivieren", es: "Activar", ru: "Включить" }),
    remove: t({ en: "Remove", fr: "Supprimer", de: "Entfernen", es: "Eliminar", ru: "Удалить" }),
    noModes: t({ en: "No modes configured. Query the server to auto-detect mods, or add manually.", fr: "Aucun mod configuré. Interrogez le serveur ou ajoutez manuellement.", de: "Keine Modi konfiguriert. Server abfragen um Mods automatisch zu erkennen, oder manuell hinzufügen.", es: "No hay mods configurados. Consulta el servidor para autodetectar mods, o añádelos manualmente.", ru: "Моды не настроены. Запросите сервер для автоопределения или добавьте вручную." }),
    pickMod: t({ en: "Pick installed mod…", fr: "Choisir un mod installé…", de: "Installierten Mod wählen…", es: "Seleccionar mod instalado…", ru: "Выбрать установленный мод…" }),
    addMod: t({ en: "Add mod", fr: "Ajouter mod", de: "Mod hinzufügen", es: "Añadir mod", ru: "Добавить мод" }),
    noInstalledMods: t({ en: "No installed mods found. Install mods from the Mods tab first.", fr: "Aucun mod installé. Installez des mods depuis l'onglet Mods.", de: "Keine installierten Mods gefunden. Installiere zuerst Mods im Mods-Tab.", es: "No se encontraron mods instalados. Instala mods desde la pestaña Mods primero.", ru: "Установленные моды не найдены. Сначала установите моды на вкладке Моды." }),
    allModsAdded: t({ en: "All installed mods have been added.", fr: "Tous les mods installés ont été ajoutés.", de: "Alle installierten Mods wurden hinzugefügt.", es: "Todos los mods instalados han sido añadidos.", ru: "Все установленные моды добавлены." }),
    launchPreview: t({ en: "Launch args preview", fr: "Aperçu des arguments de lancement", de: "Start-Argumente Vorschau", es: "Vista previa de argumentos de lanzamiento", ru: "Предпросмотр аргументов запуска" }),
    queryFailed: t({ en: "Query failed", fr: "Échec de la requête", de: "Abfrage fehlgeschlagen", es: "Consulta fallida", ru: "Запрос не удался" }),
    queryingServer: t({ en: "Querying server…", fr: "Interrogation du serveur…", de: "Server wird abgefragt…", es: "Consultando servidor…", ru: "Запрос сервера…" }),
    inServerList: t({ en: "In server list", fr: "Dans la liste des serveurs", de: "In Serverliste", es: "En la lista de servidores", ru: "В списке серверов" }),
    notInList: t({ en: "Not in list", fr: "Pas dans la liste", de: "Nicht in Liste", es: "No está en la lista", ru: "Нет в списке" }),
    queryPortBadge: t({ en: "Query port", fr: "Port requête", de: "Query-Port", es: "Puerto de consulta", ru: "Порт запроса" }),
    gamePortBadge: t({ en: "Game port", fr: "Port jeu", de: "Spiel-Port", es: "Puerto de juego", ru: "Игровой порт" }),
    players: t({ en: "Players", fr: "Joueurs", de: "Spieler", es: "Jugadores", ru: "Игроки" }),
    map: t({ en: "Map", fr: "Carte", de: "Karte", es: "Mapa", ru: "Карта" }),
    ip: t({ en: "IP", fr: "IP", de: "IP", es: "IP", ru: "IP" }),
    copyIp: t({ en: "Copy IP:port", fr: "Copier IP:port", de: "IP:Port kopieren", es: "Copiar IP:puerto", ru: "Скопировать IP:порт" }),
    gamePort: t({ en: "Game port", fr: "Port jeu", de: "Spiel-Port", es: "Puerto de juego", ru: "Игровой порт" }),
    queryPort: t({ en: "Query port", fr: "Port requête", de: "Query-Port", es: "Puerto de consulta", ru: "Порт запроса" }),
    serverTime: t({ en: "Server time", fr: "Heure serveur", de: "Serverzeit", es: "Hora del servidor", ru: "Время сервера" }),
    platform: t({ en: "Platform", fr: "Plateforme", de: "Plattform", es: "Plataforma", ru: "Платформа" }),
    version: t({ en: "Version", fr: "Version", de: "Version", es: "Versión", ru: "Версия" }),
    loadingMods: t({ en: "Loading mods…", fr: "Chargement des mods…", de: "Lade Mods…", es: "Cargando mods…", ru: "Загрузка модов…" }),
    modsCount: insert(t({ en: "Mods ({{count}})", fr: "Mods ({{count}})", de: "Mods ({{count}})", es: "Mods ({{count}})", ru: "Моды ({{count}})" })),
    openWorkshop: t({ en: "Open on Steam Workshop", fr: "Ouvrir sur Steam Workshop", de: "Im Steam Workshop öffnen", es: "Abrir en Steam Workshop", ru: "Открыть в Steam Workshop" }),
    modsNoIds: insert(t({ en: "{{count}} mod(s) — IDs not available", fr: "{{count}} mod(s) — IDs non disponibles", de: "{{count}} Mod(s) — IDs nicht verfügbar", es: "{{count}} mod(s) — IDs no disponibles", ru: "{{count}} мод(ов) — ID недоступны" })),
    noMods: t({ en: "No mods", fr: "Aucun mod", de: "Keine Mods", es: "Sin mods", ru: "Нет модов" }),
    onlinePlayers: t({ en: "Online Players", fr: "Joueurs en ligne", de: "Online-Spieler", es: "Jugadores en línea", ru: "Игроки онлайн" }),
    playersShown: insert(t({ en: "{{count}} shown", fr: "{{count}} affichés", de: "{{count}} angezeigt", es: "{{count}} mostrados", ru: "{{count}} показано" })),
    liveCountOnly: t({ en: "live count only", fr: "comptage en direct uniquement", de: "nur Live-Anzahl", es: "solo recuento en vivo", ru: "только счётчик" }),
    noPlayers: t({ en: "No players online", fr: "Aucun joueur en ligne", de: "Keine Spieler online", es: "No hay jugadores en línea", ru: "Нет игроков онлайн" }),
    playersNoNames: insert(t({ en: "{{count}} players online — names not reported by server", fr: "{{count}} joueurs en ligne — noms non fournis par le serveur", de: "{{count}} Spieler online — Namen werden vom Server nicht gemeldet", es: "{{count}} jugadores en línea — nombres no reportados por el servidor", ru: "{{count}} игроков онлайн — имена не сообщаются сервером" })),
    playersNoNamesOne: insert(t({ en: "{{count}} player online — names not reported by server", fr: "{{count}} joueur en ligne — nom non fourni par le serveur", de: "{{count}} Spieler online — Name wird vom Server nicht gemeldet", es: "{{count}} jugador en línea — nombres no reportados por el servidor", ru: "{{count}} игрок онлайн — имена не сообщаются сервером" })),
    refresh: t({ en: "Refresh", fr: "Actualiser", de: "Aktualisieren", es: "Actualizar", ru: "Обновить" }),
    noServer: t({ en: "No server queried", fr: "Aucun serveur interrogé", de: "Kein Server abgefragt", es: "Ningún servidor consultado", ru: "Сервер не запрошен" }),
    noServerHint: t({ en: "Enter an IP address and click Query to see server details, or press Enter to connect directly.", fr: "Entrez une adresse IP et cliquez sur Interroger, ou appuyez sur Entrée pour vous connecter.", de: "Gib eine IP-Adresse ein und klicke auf Abfragen um Serverdetails zu sehen, oder drücke Enter um direkt zu verbinden.", es: "Introduce una dirección IP y haz clic en Consultar para ver los detalles del servidor, o pulsa Enter para conectar directamente.", ru: "Введите IP-адрес и нажмите Запросить для просмотра деталей сервера, или нажмите Enter для прямого подключения." }),
    connectModalTitle: t({ en: "Connect to server", fr: "Connexion au serveur", de: "Mit Server verbinden", es: "Conectar al servidor", ru: "Подключение к серверу" }),
    connectModalInstallMods: t({ en: "Install missing mods", fr: "Installer les mods manquants", de: "Fehlende Mods installieren", es: "Instalar mods faltantes", ru: "Установить недостающие моды" }),
    connectModalUpdateMods: t({ en: "Update mods first", fr: "Mettre à jour les mods d'abord", de: "Mods zuerst aktualisieren", es: "Actualizar mods primero", ru: "Сначала обновить моды" }),
    connectModalModsNotInstalled: insert(t({ en: "{{count}} mod not installed", fr: "{{count}} mod non installé", de: "{{count}} Mod nicht installiert", es: "{{count}} mod no instalado", ru: "{{count}} мод не установлен" })),
    connectModalModsNotInstalledPlural: insert(t({ en: "{{count}} mods not installed", fr: "{{count}} mods non installés", de: "{{count}} Mods nicht installiert", es: "{{count}} mods no instalados", ru: "{{count}} модов не установлено" })),
    connectModalModsToCheck: insert(t({ en: "{{count}} mod to check", fr: "{{count}} mod à vérifier", de: "{{count}} Mod zu prüfen", es: "{{count}} mod para comprobar", ru: "{{count}} мод для проверки" })),
    connectModalModsToCheckPlural: insert(t({ en: "{{count}} mods to check", fr: "{{count}} mods à vérifier", de: "{{count}} Mods zu prüfen", es: "{{count}} mods para comprobar", ru: "{{count}} модов для проверки" })),
    connectModalWarning: t({ en: "Missing mods may cause connection issues or a crash.", fr: "Les mods manquants peuvent causer des problèmes de connexion ou un crash.", de: "Fehlende Mods können Verbindungsprobleme oder Abstürze verursachen.", es: "Los mods faltantes pueden causar problemas de conexión o un cierre inesperado.", ru: "Недостающие моды могут вызвать проблемы с подключением или вылет." }),
    connectModalCancel: t({ en: "Cancel", fr: "Annuler", de: "Abbrechen", es: "Cancelar", ru: "Отмена" }),
    connectModalInstallConnect: t({ en: "Install & connect", fr: "Installer et connecter", de: "Installieren & verbinden", es: "Instalar y conectar", ru: "Установить и подключиться" }),
    connectModalUpdateConnect: t({ en: "Update & connect", fr: "Mettre à jour et connecter", de: "Aktualisieren & verbinden", es: "Actualizar y conectar", ru: "Обновить и подключиться" }),
    connectModalConnect: t({ en: "Connect", fr: "Connexion", de: "Verbinden", es: "Conectar", ru: "Подключиться" }),
    badgeQueryPort: t({ en: "You entered the query (A2S) port", fr: "Vous avez entré le port de requête (A2S)", de: "Du hast den Query (A2S) Port eingegeben", es: "Has introducido el puerto de consulta (A2S)", ru: "Вы ввели порт запроса (A2S)" }),
    badgeGamePort: t({ en: "You entered the game port, query port auto-detected", fr: "Vous avez entré le port de jeu, port de requête détecté auto", de: "Du hast den Spiel-Port eingegeben, Query-Port automatisch erkannt", es: "Has introducido el puerto de juego, puerto de consulta autodetectado", ru: "Вы ввели игровой порт, порт запроса определён автоматически" }),
    battleye: t({ en: "BattlEye", fr: "BattlEye", de: "BattlEye", es: "BattlEye", ru: "BattlEye" }),
    _1pp: t({ en: "1PP", fr: "1PP", de: "1PP", es: "1PP", ru: "1PP" }),
    vac: t({ en: "VAC", fr: "VAC", de: "VAC", es: "VAC", ru: "VAC" }),
    platformWindows: t({ en: "Windows", fr: "Windows", de: "Windows", es: "Windows", ru: "Windows" }),
    platformLinux: t({ en: "Linux", fr: "Linux", de: "Linux", es: "Linux", ru: "Linux" }),
    connectLaunchingServer: insert(t({ en: "Launching {{name}}…", fr: "Lancement de {{name}}…", de: "{{name}} wird gestartet…", es: "Iniciando {{name}}…", ru: "Запуск {{name}}…" })),
    connectLaunchingAddress: insert(t({ en: "Launching {{address}}…", fr: "Lancement de {{address}}…", de: "{{address}} wird gestartet…", es: "Iniciando {{address}}…", ru: "Запуск {{address}}…" })),
    connectWaitingSteam: t({ en: "Waiting for Steam to open DayZ…", fr: "En attente de Steam pour ouvrir DayZ…", de: "Warten auf Steam, um DayZ zu öffnen…", es: "Esperando a que Steam abra DayZ…", ru: "Ожидание открытия DayZ через Steam…" }),
    connectLaunchFailed: insert(t({ en: "Launch failed: {{error}}", fr: "Échec du lancement : {{error}}", de: "Start fehlgeschlagen: {{error}}", es: "Error de inicio: {{error}}", ru: "Ошибка запуска: {{error}}" })),
    cliNoHistory: t({ en: "No history entry to reconnect to", fr: "Aucune entrée d'historique pour se reconnecter", de: "Kein Verlaufseintrag zum Wiederverbinden vorhanden", es: "No hay entrada de historial para reconectar", ru: "Нет записи истории для переподключения" }),
    cliDzchOpenFailed: insert(t({ en: "Failed to open .dzch config: {{error}}", fr: "Échec de l'ouverture de la configuration .dzch : {{error}}", de: "Fehler beim Öffnen der .dzch-Konfiguration: {{error}}", es: "Error al abrir configuración .dzch: {{error}}", ru: "Не удалось открыть .dzch конфигурацию: {{error}}" })),
  },
} satisfies Dictionary;

export default content;
