import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "connect",
  content: {
    title: t({
      en: "Direct Connect",
      fr: "Connexion directe",
      de: "Direktverbindung",
      es: "Conexión directa",
      ru: "Прямое подключение",
    }),
    connection: t({
      en: "Connection",
      fr: "Connexion",
      de: "Verbindung",
      es: "Conexión",
      ru: "Подключение",
    }),
    ipHostname: t({
      en: "IP / Hostname",
      fr: "IP / Nom d'hôte",
      de: "IP / Hostname",
      es: "IP / Hostname",
      ru: "IP / Хост",
    }),
    port: t({ en: "Port", fr: "Port", de: "Port", es: "Puerto", ru: "Порт" }),
    portGame: t({ en: "(game)", fr: "(jeu)", de: "(Spiel)", es: "(juego)", ru: "(игровой)" }),
    portQuery: t({
      en: "(query)",
      fr: "(requête)",
      de: "(Query)",
      es: "(consulta)",
      ru: "(запрос)",
    }),
    password: t({
      en: "Password",
      fr: "Mot de passe",
      de: "Passwort",
      es: "Contraseña",
      ru: "Пароль",
    }),
    passwordAskTitle: t({
      en: "Password required",
      fr: "Mot de passe requis",
      de: "Passwort erforderlich",
      es: "Contraseña requerida",
      ru: "Нужен пароль",
    }),
    passwordAskMessage: insert(
      t({
        en: "{{name}} is protected by a password.",
        fr: "{{name}} est protégé par un mot de passe.",
        de: "{{name}} ist passwortgeschützt.",
        es: "{{name}} está protegido con contraseña.",
        ru: "{{name}} защищён паролем.",
      }),
    ),
    passwordAskSave: t({
      en: "Save it with the server in my favourites",
      fr: "L'enregistrer avec le serveur dans mes favoris",
      de: "Mit dem Server in meinen Favoriten speichern",
      es: "Guardarla con el servidor en mis favoritos",
      ru: "Сохранить вместе с сервером в избранном",
    }),
    passwordAskJoin: t({
      en: "Join",
      fr: "Rejoindre",
      de: "Beitreten",
      es: "Unirse",
      ru: "Войти",
    }),
    modsUnknownTitle: t({
      en: "Mods unknown",
      fr: "Mods inconnus",
      de: "Mods unbekannt",
      es: "Mods desconocidos",
      ru: "Моды неизвестны",
    }),
    modsUnknownMessage: insert(
      t({
        en: "The mods {{name}} needs could not be read ({{error}}). Joining without them will probably fail.",
        fr: "Impossible de lire les mods requis par {{name}} ({{error}}). Rejoindre sans eux échouera probablement.",
        de: "Die von {{name}} benötigten Mods konnten nicht gelesen werden ({{error}}). Ohne sie scheitert der Beitritt wahrscheinlich.",
        es: "No se pudieron leer los mods que necesita {{name}} ({{error}}). Unirse sin ellos probablemente fallará.",
        ru: "Не удалось получить моды для {{name}} ({{error}}). Без них вход, скорее всего, не удастся.",
      }),
    ),
    modsUnknownGo: t({
      en: "Join anyway",
      fr: "Rejoindre quand même",
      de: "Trotzdem beitreten",
      es: "Unirse de todos modos",
      ru: "Всё равно войти",
    }),
    portsSummary: insert(
      t({
        en: "Ports: {{ports}}",
        fr: "Ports : {{ports}}",
        de: "Ports: {{ports}}",
        es: "Puertos: {{ports}}",
        ru: "Порты: {{ports}}",
      }),
    ),
    optional: t({
      en: "optional",
      fr: "optionnel",
      de: "optional",
      es: "opcional",
      ru: "необязательно",
    }),
    ipPlaceholder: t({
      en: "e.g. 192.168.1.1",
      fr: "ex. 192.168.1.1",
      de: "z.B. 192.168.1.1",
      es: "ej. 192.168.1.1",
      ru: "напр. 192.168.1.1",
    }),
    passwordPlaceholder: t({
      en: "Leave blank if none",
      fr: "Laisser vide si aucun",
      de: "Leer lassen wenn keins",
      es: "Dejar en blanco si no hay",
      ru: "Оставьте пустым, если нет",
    }),
    querying: t({
      en: "Querying…",
      fr: "Interrogation…",
      de: "Abfrage…",
      es: "Consultando…",
      ru: "Запрос…",
    }),
    query: t({ en: "Query", fr: "Interroger", de: "Abfragen", es: "Consultar", ru: "Запросить" }),
    connect: t({
      en: "Connect",
      fr: "Connexion",
      de: "Verbinden",
      es: "Conectar",
      ru: "Подключиться",
    }),
    alreadyFavorite: t({
      en: "Already in favorites",
      fr: "Déjà dans les favoris",
      de: "Bereits in Favoriten",
      es: "Ya está en favoritos",
      ru: "Уже в избранном",
    }),
    addFavorite: t({
      en: "Add to favorites",
      fr: "Ajouter aux favoris",
      de: "Zu Favoriten hinzufügen",
      es: "Añadir a favoritos",
      ru: "Добавить в избранное",
    }),
    copyUrlTitle: t({
      en: "Copy a dzch:// URL to share this server",
      fr: "Copier une URL dzch:// pour partager ce serveur",
      de: "dzch://-URL zum Teilen kopieren",
      es: "Copiar URL dzch:// para compartir este servidor",
      ru: "Скопировать ссылку dzch:// для отправки сервера",
    }),
    copied: t({
      en: "Copied!",
      fr: "Copié !",
      de: "Kopiert!",
      es: "¡Copiado!",
      ru: "Скопировано!",
    }),
    copyUrl: t({
      en: "Copy URL",
      fr: "Copier l'URL",
      de: "URL kopieren",
      es: "Copiar URL",
      ru: "Скопировать URL",
    }),
    exportTitle: t({
      en: "Save a .dzch file for one-click connect",
      fr: "Enregistrer un fichier .dzch pour connexion en un clic",
      de: ".dzch-Datei für Ein-Klick-Verbindung speichern",
      es: "Guardar archivo .dzch para conexión con un clic",
      ru: "Сохранить файл .dzch для подключения в один клик",
    }),
    export: t({
      en: "Export .dzch",
      fr: "Exporter .dzch",
      de: ".dzch exportieren",
      es: "Exportar .dzch",
      ru: "Экспорт .dzch",
    }),
    extraMods: t({
      en: "Extra Mods",
      fr: "Mods supplémentaires",
      de: "Zusätzliche Mods",
      es: "Mods adicionales",
      ru: "Дополнительные моды",
    }),
    extraModsHint: t({
      en: "Add extra -mod entries not auto-detected by the server query.",
      fr: "Ajouter des entrées -mod non détectées automatiquement.",
      de: "Füge zusätzliche -mod Einträge hinzu, die nicht automatisch erkannt wurden.",
      es: "Añadir entradas -mod adicionales no detectadas automáticamente por la consulta del servidor.",
      ru: "Добавить дополнительные записи -mod, не определённые автоматически запросом сервера.",
    }),
    mod: t({ en: "-mod", fr: "-mod", de: "-mod", es: "-mod", ru: "-mod" }),
    custom: t({ en: "custom", fr: "personnalisé", de: "custom", es: "personalizado", ru: "свой" }),
    detected: t({ en: "detected", fr: "détecté", de: "erkannt", es: "detectado", ru: "обнаружен" }),
    moveUp: t({ en: "Move up", fr: "Monter", de: "Nach oben", es: "Subir", ru: "Вверх" }),
    moveDown: t({ en: "Move down", fr: "Descendre", de: "Nach unten", es: "Bajar", ru: "Вниз" }),
    disable: t({
      en: "Disable",
      fr: "Désactiver",
      de: "Deaktivieren",
      es: "Desactivar",
      ru: "Отключить",
    }),
    enable: t({ en: "Enable", fr: "Activer", de: "Aktivieren", es: "Activar", ru: "Включить" }),
    remove: t({ en: "Remove", fr: "Supprimer", de: "Entfernen", es: "Eliminar", ru: "Удалить" }),
    noModes: t({
      en: "No modes configured. Query the server to auto-detect mods, or add manually.",
      fr: "Aucun mod configuré. Interrogez le serveur ou ajoutez manuellement.",
      de: "Keine Modi konfiguriert. Server abfragen um Mods automatisch zu erkennen, oder manuell hinzufügen.",
      es: "No hay mods configurados. Consulta el servidor para autodetectar mods, o añádelos manualmente.",
      ru: "Моды не настроены. Запросите сервер для автоопределения или добавьте вручную.",
    }),
    pickMod: t({
      en: "Pick installed mod…",
      fr: "Choisir un mod installé…",
      de: "Installierten Mod wählen…",
      es: "Seleccionar mod instalado…",
      ru: "Выбрать установленный мод…",
    }),
    addMod: t({
      en: "Add mod",
      fr: "Ajouter mod",
      de: "Mod hinzufügen",
      es: "Añadir mod",
      ru: "Добавить мод",
    }),
    noInstalledMods: t({
      en: "No installed mods found. Install mods from the Mods tab first.",
      fr: "Aucun mod installé. Installez des mods depuis l'onglet Mods.",
      de: "Keine installierten Mods gefunden. Installiere zuerst Mods im Mods-Tab.",
      es: "No se encontraron mods instalados. Instala mods desde la pestaña Mods primero.",
      ru: "Установленные моды не найдены. Сначала установите моды на вкладке Моды.",
    }),
    allModsAdded: t({
      en: "All installed mods have been added.",
      fr: "Tous les mods installés ont été ajoutés.",
      de: "Alle installierten Mods wurden hinzugefügt.",
      es: "Todos los mods instalados han sido añadidos.",
      ru: "Все установленные моды добавлены.",
    }),
    launchPreview: t({
      en: "Launch args preview",
      fr: "Aperçu des arguments de lancement",
      de: "Start-Argumente Vorschau",
      es: "Vista previa de argumentos de lanzamiento",
      ru: "Предпросмотр аргументов запуска",
    }),
    queryFailed: t({
      en: "Query failed",
      fr: "Échec de la requête",
      de: "Abfrage fehlgeschlagen",
      es: "Consulta fallida",
      ru: "Запрос не удался",
    }),
    queryingServer: t({
      en: "Querying server…",
      fr: "Interrogation du serveur…",
      de: "Server wird abgefragt…",
      es: "Consultando servidor…",
      ru: "Запрос сервера…",
    }),
    inServerList: t({
      en: "In server list",
      fr: "Dans la liste des serveurs",
      de: "In Serverliste",
      es: "En la lista de servidores",
      ru: "В списке серверов",
    }),
    notInList: t({
      en: "Not in list",
      fr: "Pas dans la liste",
      de: "Nicht in Liste",
      es: "No está en la lista",
      ru: "Нет в списке",
    }),
    queryPortBadge: t({
      en: "Query port",
      fr: "Port requête",
      de: "Query-Port",
      es: "Puerto de consulta",
      ru: "Порт запроса",
    }),
    gamePortBadge: t({
      en: "Game port",
      fr: "Port jeu",
      de: "Spiel-Port",
      es: "Puerto de juego",
      ru: "Игровой порт",
    }),
    players: t({ en: "Players", fr: "Joueurs", de: "Spieler", es: "Jugadores", ru: "Игроки" }),
    map: t({ en: "Map", fr: "Carte", de: "Karte", es: "Mapa", ru: "Карта" }),
    ip: t({ en: "IP", fr: "IP", de: "IP", es: "IP", ru: "IP" }),
    copyIp: t({
      en: "Copy IP:port",
      fr: "Copier IP:port",
      de: "IP:Port kopieren",
      es: "Copiar IP:puerto",
      ru: "Скопировать IP:порт",
    }),
    gamePort: t({
      en: "Game port",
      fr: "Port jeu",
      de: "Spiel-Port",
      es: "Puerto de juego",
      ru: "Игровой порт",
    }),
    queryPort: t({
      en: "Query port",
      fr: "Port requête",
      de: "Query-Port",
      es: "Puerto de consulta",
      ru: "Порт запроса",
    }),
    serverTime: t({
      en: "Server time",
      fr: "Heure serveur",
      de: "Serverzeit",
      es: "Hora del servidor",
      ru: "Время сервера",
    }),
    platform: t({
      en: "Platform",
      fr: "Plateforme",
      de: "Plattform",
      es: "Plataforma",
      ru: "Платформа",
    }),
    version: t({ en: "Version", fr: "Version", de: "Version", es: "Versión", ru: "Версия" }),
    loadingMods: t({
      en: "Loading mods…",
      fr: "Chargement des mods…",
      de: "Lade Mods…",
      es: "Cargando mods…",
      ru: "Загрузка модов…",
    }),
    modsCount: insert(
      t({
        en: "Mods ({{count}})",
        fr: "Mods ({{count}})",
        de: "Mods ({{count}})",
        es: "Mods ({{count}})",
        ru: "Моды ({{count}})",
      }),
    ),
    openWorkshop: t({
      en: "Open on Steam Workshop",
      fr: "Ouvrir sur Steam Workshop",
      de: "Im Steam Workshop öffnen",
      es: "Abrir en Steam Workshop",
      ru: "Открыть в Steam Workshop",
    }),
    modsNoIds: insert(
      t({
        en: "{{count}} mod(s) — IDs not available",
        fr: "{{count}} mod(s) — IDs non disponibles",
        de: "{{count}} Mod(s) — IDs nicht verfügbar",
        es: "{{count}} mod(s) — IDs no disponibles",
        ru: "{{count}} мод(ов) — ID недоступны",
      }),
    ),
    noMods: t({
      en: "No mods",
      fr: "Aucun mod",
      de: "Keine Mods",
      es: "Sin mods",
      ru: "Нет модов",
    }),
    onlinePlayers: t({
      en: "Online Players",
      fr: "Joueurs en ligne",
      de: "Online-Spieler",
      es: "Jugadores en línea",
      ru: "Игроки онлайн",
    }),
    playersShown: insert(
      t({
        en: "{{count}} shown",
        fr: "{{count}} affichés",
        de: "{{count}} angezeigt",
        es: "{{count}} mostrados",
        ru: "{{count}} показано",
      }),
    ),
    liveCountOnly: t({
      en: "live count only",
      fr: "comptage en direct uniquement",
      de: "nur Live-Anzahl",
      es: "solo recuento en vivo",
      ru: "только счётчик",
    }),
    noPlayers: t({
      en: "No players online",
      fr: "Aucun joueur en ligne",
      de: "Keine Spieler online",
      es: "No hay jugadores en línea",
      ru: "Нет игроков онлайн",
    }),
    playersNoNames: insert(
      t({
        en: "{{count}} players online — names not reported by server",
        fr: "{{count}} joueurs en ligne — noms non fournis par le serveur",
        de: "{{count}} Spieler online — Namen werden vom Server nicht gemeldet",
        es: "{{count}} jugadores en línea — nombres no reportados por el servidor",
        ru: "{{count}} игроков онлайн — имена не сообщаются сервером",
      }),
    ),
    playersNoNamesOne: insert(
      t({
        en: "{{count}} player online — names not reported by server",
        fr: "{{count}} joueur en ligne — nom non fourni par le serveur",
        de: "{{count}} Spieler online — Name wird vom Server nicht gemeldet",
        es: "{{count}} jugador en línea — nombres no reportados por el servidor",
        ru: "{{count}} игрок онлайн — имена не сообщаются сервером",
      }),
    ),
    refresh: t({
      en: "Refresh",
      fr: "Actualiser",
      de: "Aktualisieren",
      es: "Actualizar",
      ru: "Обновить",
    }),
    noServer: t({
      en: "No server queried",
      fr: "Aucun serveur interrogé",
      de: "Kein Server abgefragt",
      es: "Ningún servidor consultado",
      ru: "Сервер не запрошен",
    }),
    noServerHint: t({
      en: "Enter an IP address and click Query to see server details, or press Enter to connect directly.",
      fr: "Entrez une adresse IP et cliquez sur Interroger, ou appuyez sur Entrée pour vous connecter.",
      de: "Gib eine IP-Adresse ein und klicke auf Abfragen um Serverdetails zu sehen, oder drücke Enter um direkt zu verbinden.",
      es: "Introduce una dirección IP y haz clic en Consultar para ver los detalles del servidor, o pulsa Enter para conectar directamente.",
      ru: "Введите IP-адрес и нажмите Запросить для просмотра деталей сервера, или нажмите Enter для прямого подключения.",
    }),
    connectModalTitle: t({
      en: "Connect to server",
      fr: "Connexion au serveur",
      de: "Mit Server verbinden",
      es: "Conectar al servidor",
      ru: "Подключение к серверу",
    }),
    connectModalInstallMods: t({
      en: "Install missing mods",
      fr: "Installer les mods manquants",
      de: "Fehlende Mods installieren",
      es: "Instalar mods faltantes",
      ru: "Установить недостающие моды",
    }),
    connectModalUpdateMods: t({
      en: "Update mods first",
      fr: "Mettre à jour les mods d'abord",
      de: "Mods zuerst aktualisieren",
      es: "Actualizar mods primero",
      ru: "Сначала обновить моды",
    }),
    connectModalModsNotInstalled: insert(
      t({
        en: "{{count}} mod not installed",
        fr: "{{count}} mod non installé",
        de: "{{count}} Mod nicht installiert",
        es: "{{count}} mod no instalado",
        ru: "{{count}} мод не установлен",
      }),
    ),
    connectModalModsNotInstalledPlural: insert(
      t({
        en: "{{count}} mods not installed",
        fr: "{{count}} mods non installés",
        de: "{{count}} Mods nicht installiert",
        es: "{{count}} mods no instalados",
        ru: "{{count}} модов не установлено",
      }),
    ),
    connectModalModsToCheck: insert(
      t({
        en: "{{count}} mod to check",
        fr: "{{count}} mod à vérifier",
        de: "{{count}} Mod zu prüfen",
        es: "{{count}} mod para comprobar",
        ru: "{{count}} мод для проверки",
      }),
    ),
    connectModalModsToCheckPlural: insert(
      t({
        en: "{{count}} mods to check",
        fr: "{{count}} mods à vérifier",
        de: "{{count}} Mods zu prüfen",
        es: "{{count}} mods para comprobar",
        ru: "{{count}} модов для проверки",
      }),
    ),
    connectModalWarning: t({
      en: "Missing mods may cause connection issues or a crash.",
      fr: "Les mods manquants peuvent causer des problèmes de connexion ou un crash.",
      de: "Fehlende Mods können Verbindungsprobleme oder Abstürze verursachen.",
      es: "Los mods faltantes pueden causar problemas de conexión o un cierre inesperado.",
      ru: "Недостающие моды могут вызвать проблемы с подключением или вылет.",
    }),
    connectModalCancel: t({
      en: "Cancel",
      fr: "Annuler",
      de: "Abbrechen",
      es: "Cancelar",
      ru: "Отмена",
    }),
    connectModalInstallConnect: t({
      en: "Install & connect",
      fr: "Installer et connecter",
      de: "Installieren & verbinden",
      es: "Instalar y conectar",
      ru: "Установить и подключиться",
    }),
    connectModalUpdateConnect: t({
      en: "Update & connect",
      fr: "Mettre à jour et connecter",
      de: "Aktualisieren & verbinden",
      es: "Actualizar y conectar",
      ru: "Обновить и подключиться",
    }),
    connectModalConnect: t({
      en: "Connect",
      fr: "Connexion",
      de: "Verbinden",
      es: "Conectar",
      ru: "Подключиться",
    }),
    badgeQueryPort: t({
      en: "You entered the query (A2S) port",
      fr: "Vous avez entré le port de requête (A2S)",
      de: "Du hast den Query (A2S) Port eingegeben",
      es: "Has introducido el puerto de consulta (A2S)",
      ru: "Вы ввели порт запроса (A2S)",
    }),
    badgeGamePort: t({
      en: "You entered the game port, query port auto-detected",
      fr: "Vous avez entré le port de jeu, port de requête détecté auto",
      de: "Du hast den Spiel-Port eingegeben, Query-Port automatisch erkannt",
      es: "Has introducido el puerto de juego, puerto de consulta autodetectado",
      ru: "Вы ввели игровой порт, порт запроса определён автоматически",
    }),
    battleye: t({ en: "BattlEye", fr: "BattlEye", de: "BattlEye", es: "BattlEye", ru: "BattlEye" }),
    _1pp: t({ en: "1PP", fr: "1PP", de: "1PP", es: "1PP", ru: "1PP" }),
    vac: t({ en: "VAC", fr: "VAC", de: "VAC", es: "VAC", ru: "VAC" }),
    platformWindows: t({
      en: "Windows",
      fr: "Windows",
      de: "Windows",
      es: "Windows",
      ru: "Windows",
    }),
    platformLinux: t({ en: "Linux", fr: "Linux", de: "Linux", es: "Linux", ru: "Linux" }),
    connectLaunchingServer: insert(
      t({
        en: "Launching {{name}}…",
        fr: "Lancement de {{name}}…",
        de: "{{name}} wird gestartet…",
        es: "Iniciando {{name}}…",
        ru: "Запуск {{name}}…",
      }),
    ),
    connectLaunchingAddress: insert(
      t({
        en: "Launching {{address}}…",
        fr: "Lancement de {{address}}…",
        de: "{{address}} wird gestartet…",
        es: "Iniciando {{address}}…",
        ru: "Запуск {{address}}…",
      }),
    ),
    connectWaitingSteam: t({
      en: "Waiting for Steam to open DayZ…",
      fr: "En attente de Steam pour ouvrir DayZ…",
      de: "Warten auf Steam, um DayZ zu öffnen…",
      es: "Esperando a que Steam abra DayZ…",
      ru: "Ожидание открытия DayZ через Steam…",
    }),
    connectLaunchFailed: insert(
      t({
        en: "Launch failed: {{error}}",
        fr: "Échec du lancement : {{error}}",
        de: "Start fehlgeschlagen: {{error}}",
        es: "Error de inicio: {{error}}",
        ru: "Ошибка запуска: {{error}}",
      }),
    ),
    cliNoHistory: t({
      en: "No history entry to reconnect to",
      fr: "Aucune entrée d'historique pour se reconnecter",
      de: "Kein Verlaufseintrag zum Wiederverbinden vorhanden",
      es: "No hay entrada de historial para reconectar",
      ru: "Нет записи истории для переподключения",
    }),
    cliDzchOpenFailed: insert(
      t({
        en: "Failed to open .dzch config: {{error}}",
        fr: "Échec de l'ouverture de la configuration .dzch : {{error}}",
        de: "Fehler beim Öffnen der .dzch-Konfiguration: {{error}}",
        es: "Error al abrir configuración .dzch: {{error}}",
        ru: "Не удалось открыть .dzch конфигурацию: {{error}}",
      }),
    ),
    intro: t({
      en: "Join any server by its address, even one missing from the public list. Query it first to see who is on and which mods it runs.",
      fr: "Rejoignez n'importe quel serveur par son adresse, même absent de la liste publique. Interrogez-le d'abord pour voir qui joue et quels mods il utilise.",
      de: "Tritt jedem Server über seine Adresse bei, auch wenn er nicht in der öffentlichen Liste steht. Frage ihn zuerst ab, um Spieler und Mods zu sehen.",
      es: "Únete a cualquier servidor por su dirección, incluso si no está en la lista pública. Consúltalo antes para ver quién juega y qué mods usa.",
      ru: "Подключайтесь к любому серверу по адресу, даже если его нет в общем списке. Сначала запросите его, чтобы увидеть игроков и моды.",
    }),
    queryPortOptional: t({
      en: "Query port (optional)",
      fr: "Port de requête (facultatif)",
      de: "Abfrageport (optional)",
      es: "Puerto de consulta (opcional)",
      ru: "Порт запроса (необязательно)",
    }),
    queryPortHint: t({
      en: "Only when the server answers queries on a port of its own. Usually found by itself.",
      fr: "Seulement si le serveur répond aux requêtes sur un port à part. Généralement trouvé tout seul.",
      de: "Nur wenn der Server Abfragen auf einem eigenen Port beantwortet. Wird meist selbst gefunden.",
      es: "Solo si el servidor responde consultas en un puerto propio. Normalmente se detecta solo.",
      ru: "Только если сервер отвечает на запросы на отдельном порту. Обычно определяется сам.",
    }),
    addressHint: t({
      en: "Paste ip:port and the port is split off by itself.",
      fr: "Collez ip:port, le port est séparé tout seul.",
      de: "Füge ip:port ein, der Port wird automatisch getrennt.",
      es: "Pega ip:puerto y el puerto se separa solo.",
      ru: "Вставьте ip:порт — порт отделится сам.",
    }),
    addressMissing: t({
      en: "Enter an IP address or a host name.",
      fr: "Saisissez une adresse IP ou un nom d'hôte.",
      de: "Gib eine IP-Adresse oder einen Hostnamen ein.",
      es: "Introduce una dirección IP o un nombre de host.",
      ru: "Введите IP-адрес или имя хоста.",
    }),
    portInvalid: t({
      en: "A port is a number between 1 and 65535.",
      fr: "Un port est un nombre entre 1 et 65535.",
      de: "Ein Port ist eine Zahl zwischen 1 und 65535.",
      es: "Un puerto es un número entre 1 y 65535.",
      ru: "Порт — число от 1 до 65535.",
    }),
    savedPassword: t({
      en: "Filled in from your favourites",
      fr: "Repris de vos favoris",
      de: "Aus deinen Favoriten übernommen",
      es: "Tomada de tus favoritos",
      ru: "Взято из избранного",
    }),
    showPassword: t({
      en: "Show the password",
      fr: "Afficher le mot de passe",
      de: "Passwort anzeigen",
      es: "Mostrar la contraseña",
      ru: "Показать пароль",
    }),
    hidePassword: t({
      en: "Hide the password",
      fr: "Masquer le mot de passe",
      de: "Passwort verbergen",
      es: "Ocultar la contraseña",
      ru: "Скрыть пароль",
    }),
    openDzch: t({
      en: "Open .dzch",
      fr: "Ouvrir un .dzch",
      de: ".dzch öffnen",
      es: "Abrir .dzch",
      ru: "Открыть .dzch",
    }),
    openDzchTitle: t({
      en: "Open a server config file someone shared",
      fr: "Ouvrir un fichier de serveur partagé",
      de: "Eine geteilte Server-Konfigurationsdatei öffnen",
      es: "Abrir un archivo de servidor compartido",
      ru: "Открыть файл сервера, которым с вами поделились",
    }),
    dzchFilter: t({
      en: "DayZ Community Hub server",
      fr: "Serveur DayZ Community Hub",
      de: "DayZ-Community-Hub-Server",
      es: "Servidor de DayZ Community Hub",
      ru: "Сервер DayZ Community Hub",
    }),
    exported: insert(
      t({
        en: "Saved {{file}}",
        fr: "{{file}} enregistré",
        de: "{{file}} gespeichert",
        es: "{{file}} guardado",
        ru: "Сохранено: {{file}}",
      }),
    ),
    exportFailed: insert(
      t({
        en: "Could not save the file: {{error}}",
        fr: "Impossible d'enregistrer le fichier : {{error}}",
        de: "Datei konnte nicht gespeichert werden: {{error}}",
        es: "No se pudo guardar el archivo: {{error}}",
        ru: "Не удалось сохранить файл: {{error}}",
      }),
    ),
    linkCopied: t({
      en: "Link copied",
      fr: "Lien copié",
      de: "Link kopiert",
      es: "Enlace copiado",
      ru: "Ссылка скопирована",
    }),
    share: t({ en: "Share", fr: "Partager", de: "Teilen", es: "Compartir", ru: "Поделиться" }),
    recent: t({
      en: "Recent servers",
      fr: "Serveurs récents",
      de: "Letzte Server",
      es: "Servidores recientes",
      ru: "Недавние серверы",
    }),
    noRecent: t({
      en: "Servers you join appear here.",
      fr: "Les serveurs rejoints apparaissent ici.",
      de: "Server, denen du beitrittst, erscheinen hier.",
      es: "Los servidores a los que te unes aparecen aquí.",
      ru: "Здесь появятся серверы, к которым вы подключались.",
    }),
    fromFavorites: t({
      en: "Favourite",
      fr: "Favori",
      de: "Favorit",
      es: "Favorito",
      ru: "Избранное",
    }),
    customArg: t({
      en: "Custom argument",
      fr: "Argument personnalisé",
      de: "Eigenes Argument",
      es: "Argumento personalizado",
      ru: "Свой аргумент",
    }),
    customArgPlaceholder: t({
      en: "-doLogs",
      fr: "-doLogs",
      de: "-doLogs",
      es: "-doLogs",
      ru: "-doLogs",
    }),
    addArg: t({
      en: "Add argument",
      fr: "Ajouter l'argument",
      de: "Argument hinzufügen",
      es: "Añadir argumento",
      ru: "Добавить аргумент",
    }),
    modInstalled: t({
      en: "Installed",
      fr: "Installé",
      de: "Installiert",
      es: "Instalado",
      ru: "Установлен",
    }),
    modMissing: t({ en: "Missing", fr: "Manquant", de: "Fehlt", es: "Falta", ru: "Нет" }),
    modStale: t({ en: "Update", fr: "À jour ?", de: "Update", es: "Actualizar", ru: "Обновить" }),
    modsSummary: insert(
      t({
        en: "{{installed}} installed · {{missing}} missing",
        fr: "{{installed}} installés · {{missing}} manquants",
        de: "{{installed}} installiert · {{missing}} fehlen",
        es: "{{installed}} instalados · {{missing}} faltan",
        ru: "{{installed}} установлено · {{missing}} нет",
      }),
    ),
    rules: t({
      en: "Server rules",
      fr: "Règles du serveur",
      de: "Serverregeln",
      es: "Reglas del servidor",
      ru: "Параметры сервера",
    }),
    bots: insert(
      t({
        en: "{{count}} bots",
        fr: "{{count}} bots",
        de: "{{count}} Bots",
        es: "{{count}} bots",
        ru: "Ботов: {{count}}",
      }),
    ),
    ping: t({ en: "Ping", fr: "Ping", de: "Ping", es: "Ping", ru: "Пинг" }),
    pingAgain: t({
      en: "Ping again",
      fr: "Relancer le ping",
      de: "Erneut pingen",
      es: "Hacer ping otra vez",
      ru: "Пинговать снова",
    }),
    score: t({ en: "Score", fr: "Score", de: "Punkte", es: "Puntos", ru: "Счёт" }),
    timePlayed: t({
      en: "Time on",
      fr: "Temps de jeu",
      de: "Spielzeit",
      es: "Tiempo jugado",
      ru: "Время в игре",
    }),
    name: t({ en: "Name", fr: "Nom", de: "Name", es: "Nombre", ru: "Имя" }),
    firstPerson: t({
      en: "1st person only",
      fr: "1re personne seulement",
      de: "Nur Ego-Perspektive",
      es: "Solo 1.ª persona",
      ru: "Только от 1-го лица",
    }),
    passwordProtected: t({
      en: "Password protected",
      fr: "Protégé par mot de passe",
      de: "Passwortgeschützt",
      es: "Protegido con contraseña",
      ru: "Защищён паролем",
    }),
    openInBrowser: t({
      en: "Open in the server list",
      fr: "Ouvrir dans la liste",
      de: "In der Serverliste öffnen",
      es: "Abrir en la lista",
      ru: "Открыть в списке",
    }),
    enterToConnect: t({
      en: "Enter connects",
      fr: "Entrée pour se connecter",
      de: "Enter verbindet",
      es: "Intro conecta",
      ru: "Enter — подключиться",
    }),
    argsCount: insert(
      t({
        en: "{{count}} active",
        fr: "{{count}} actifs",
        de: "{{count}} aktiv",
        es: "{{count}} activos",
        ru: "Активно: {{count}}",
      }),
    ),
  },
} satisfies Dictionary;

export default content;
