import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "detail",
  content: {
    dmTitle: t({
      en: "DayZ Metrics",
      fr: "DayZ Metrics",
      de: "DayZ Metrics",
      es: "DayZ Metrics",
      ru: "DayZ Metrics",
    }),
    dmSource: t({
      en: "Source: dayzmetrics.com",
      fr: "Source : dayzmetrics.com",
      de: "Quelle: dayzmetrics.com",
      es: "Fuente: dayzmetrics.com",
      ru: "Источник: dayzmetrics.com",
    }),
    openDm: t({
      en: "Open on DayZ Metrics",
      fr: "Ouvrir sur DayZ Metrics",
      de: "Auf DayZ Metrics öffnen",
      es: "Abrir en DayZ Metrics",
      ru: "Открыть на DayZ Metrics",
    }),
    dmRefresh: t({
      en: "Refresh the stats",
      fr: "Actualiser les stats",
      de: "Statistiken aktualisieren",
      es: "Actualizar estadísticas",
      ru: "Обновить статистику",
    }),
    dmNotListed: t({
      en: "This server is not listed on DayZ Metrics",
      fr: "Ce serveur n'est pas référencé sur DayZ Metrics",
      de: "Dieser Server ist nicht auf DayZ Metrics gelistet",
      es: "Este servidor no figura en DayZ Metrics",
      ru: "Этого сервера нет на DayZ Metrics",
    }),
    dmPeak7d: t({
      en: "Peak · 7 days",
      fr: "Pic · 7 jours",
      de: "Spitze · 7 Tage",
      es: "Pico · 7 días",
      ru: "Пик · 7 дней",
    }),
    dmAvg7d: t({
      en: "Average · 7 days",
      fr: "Moyenne · 7 jours",
      de: "Durchschnitt · 7 Tage",
      es: "Media · 7 días",
      ru: "Среднее · 7 дней",
    }),
    dmUptime7d: t({
      en: "Uptime · 7 days",
      fr: "Disponibilité · 7 jours",
      de: "Verfügbarkeit · 7 Tage",
      es: "Disponibilidad · 7 días",
      ru: "Аптайм · 7 дней",
    }),
    dmTrend: t({
      en: "Week over week",
      fr: "Sur une semaine",
      de: "Zur Vorwoche",
      es: "Semana a semana",
      ru: "За неделю",
    }),
    dmPingRange: t({
      en: "Ping measured by the site",
      fr: "Ping mesuré par le site",
      de: "Vom Dienst gemessener Ping",
      es: "Ping medido por el sitio",
      ru: "Пинг, измеренный сайтом",
    }),
    dmSchedule: t({
      en: "Restarts and wipes",
      fr: "Redémarrages et wipes",
      de: "Neustarts und Wipes",
      es: "Reinicios y wipes",
      ru: "Рестарты и вайпы",
    }),
    dmNextRestart: t({
      en: "Next restart",
      fr: "Prochain redémarrage",
      de: "Nächster Neustart",
      es: "Próximo reinicio",
      ru: "Следующий рестарт",
    }),
    dmEvery: insert(
      t({
        en: "every {{hours}} h",
        fr: "toutes les {{hours}} h",
        de: "alle {{hours}} Std.",
        es: "cada {{hours}} h",
        ru: "каждые {{hours}} ч",
      }),
    ),
    dmIn: insert(
      t({
        en: "in {{time}}",
        fr: "dans {{time}}",
        de: "in {{time}}",
        es: "en {{time}}",
        ru: "через {{time}}",
      }),
    ),
    dmNextWipe: t({
      en: "Next wipe",
      fr: "Prochain wipe",
      de: "Nächster Wipe",
      es: "Próximo wipe",
      ru: "Следующий вайп",
    }),
    dmLastWipe: t({
      en: "Last wipe",
      fr: "Dernier wipe",
      de: "Letzter Wipe",
      es: "Último wipe",
      ru: "Последний вайп",
    }),
    dmInDays: insert(
      t({
        en: "in {{days}} d",
        fr: "dans {{days}} j",
        de: "in {{days}} T.",
        es: "en {{days}} d",
        ru: "через {{days}} дн.",
      }),
    ),
    dmDaysAgo: insert(
      t({
        en: "{{days}} d ago",
        fr: "il y a {{days}} j",
        de: "vor {{days}} T.",
        es: "hace {{days}} d",
        ru: "{{days}} дн. назад",
      }),
    ),
    dmAnnounced: t({
      en: "announced",
      fr: "annoncé",
      de: "angekündigt",
      es: "anunciado",
      ru: "объявлен",
    }),
    dmPredicted: t({
      en: "predicted",
      fr: "prévu",
      de: "vorhergesagt",
      es: "previsto",
      ru: "прогноз",
    }),
    dmTimeSpeed: t({
      en: "Time speed",
      fr: "Vitesse du temps",
      de: "Zeitgeschwindigkeit",
      es: "Velocidad del tiempo",
      ru: "Скорость времени",
    }),
    dmTimeSpeedValue: insert(
      t({
        en: "×{{day}} day · ×{{night}} night",
        fr: "×{{day}} jour · ×{{night}} nuit",
        de: "×{{day}} Tag · ×{{night}} Nacht",
        es: "×{{day}} día · ×{{night}} noche",
        ru: "×{{day}} день · ×{{night}} ночь",
      }),
    ),
    dmStyle: t({ en: "Style", fr: "Style", de: "Stil", es: "Estilo", ru: "Стиль" }),
    dmModsSize: t({
      en: "Mods to download",
      fr: "Mods à télécharger",
      de: "Herunterzuladende Mods",
      es: "Mods a descargar",
      ru: "Моды для загрузки",
    }),
    dmTrackedSince: t({
      en: "Tracked since",
      fr: "Suivi depuis",
      de: "Erfasst seit",
      es: "Registrado desde",
      ru: "Отслеживается с",
    }),
    dmFake: t({
      en: "The player count looks fake",
      fr: "Le nombre de joueurs semble truqué",
      de: "Die Spielerzahl wirkt gefälscht",
      es: "El número de jugadores parece falso",
      ru: "Число игроков похоже на накрутку",
    }),
    dmFakeHint: t({
      en: "DayZ Metrics sees padded slots or bots: there are probably far fewer real players.",
      fr: "DayZ Metrics détecte des places gonflées ou des bots : il y a sans doute bien moins de vrais joueurs.",
      de: "DayZ Metrics erkennt aufgeblähte Plätze oder Bots: vermutlich gibt es weit weniger echte Spieler.",
      es: "DayZ Metrics detecta plazas infladas o bots: probablemente hay muchos menos jugadores reales.",
      ru: "DayZ Metrics видит накрутку или ботов: реальных игроков, скорее всего, гораздо меньше.",
    }),
    dmSuspect: t({
      en: "The player count looks suspicious",
      fr: "Le nombre de joueurs semble suspect",
      de: "Die Spielerzahl wirkt verdächtig",
      es: "El número de jugadores parece sospechoso",
      ru: "Число игроков выглядит подозрительно",
    }),
    dmFlagged: t({
      en: "Reported by players",
      fr: "Signalé par des joueurs",
      de: "Von Spielern gemeldet",
      es: "Denunciado por jugadores",
      ru: "Жалобы игроков",
    }),
    dmMimics: t({
      en: "Named like an official server",
      fr: "Nommé comme un serveur officiel",
      de: "Wie ein offizieller Server benannt",
      es: "Nombrado como un servidor oficial",
      ru: "Назван как официальный сервер",
    }),
    dmLinks: t({ en: "Links", fr: "Liens", de: "Links", es: "Enlaces", ru: "Ссылки" }),
    dmDiscord: t({ en: "Discord", fr: "Discord", de: "Discord", es: "Discord", ru: "Discord" }),
    dmWebsite: t({ en: "Website", fr: "Site web", de: "Webseite", es: "Sitio web", ru: "Сайт" }),
    dmNotices: t({ en: "Notices", fr: "Annonces", de: "Hinweise", es: "Avisos", ru: "Объявления" }),
    tabOverview: t({ en: "Overview", fr: "Aperçu", de: "Übersicht", es: "Resumen", ru: "Обзор" }),
    tabPlayers: t({ en: "Players", fr: "Joueurs", de: "Spieler", es: "Jugadores", ru: "Игроки" }),
    tabMods: t({ en: "Mods", fr: "Mods", de: "Mods", es: "Mods", ru: "Моды" }),
    tabRules: t({ en: "Rules", fr: "Règles", de: "Regeln", es: "Reglas", ru: "Правила" }),
    tabStats: t({
      en: "Stats",
      fr: "Stats",
      de: "Statistik",
      es: "Estadísticas",
      ru: "Статистика",
    }),
    sections: t({
      en: "Server information",
      fr: "Informations du serveur",
      de: "Serverinformationen",
      es: "Información del servidor",
      ru: "Информация о сервере",
    }),
    connection: t({
      en: "Connection",
      fr: "Connexion",
      de: "Verbindung",
      es: "Conexión",
      ru: "Подключение",
    }),
    shareLink: t({
      en: "Share link",
      fr: "Lien de partage",
      de: "Teilen-Link",
      es: "Enlace para compartir",
      ru: "Ссылка",
    }),
    shareLinkHint: t({
      en: "Opens this server in DayZ Community Hub",
      fr: "Ouvre ce serveur dans DayZ Community Hub",
      de: "Öffnet diesen Server in DayZ Community Hub",
      es: "Abre este servidor en DayZ Community Hub",
      ru: "Открывает этот сервер в DayZ Community Hub",
    }),
    passwordRequired: t({
      en: "Password required",
      fr: "Mot de passe requis",
      de: "Passwort erforderlich",
      es: "Contraseña requerida",
      ru: "Нужен пароль",
    }),
    maxPlayers: t({ en: "Slots", fr: "Places", de: "Plätze", es: "Plazas", ru: "Слоты" }),
    rank: t({ en: "Rank", fr: "Rang", de: "Rang", es: "Rango", ru: "Рейтинг" }),
    uptime: t({
      en: "Uptime",
      fr: "Disponibilité",
      de: "Verfügbarkeit",
      es: "Disponibilidad",
      ru: "Аптайм",
    }),
    country: t({ en: "Country", fr: "Pays", de: "Land", es: "País", ru: "Страна" }),
    details: t({ en: "Details", fr: "Détails", de: "Details", es: "Detalles", ru: "Подробности" }),
    modsState: t({ en: "Mods", fr: "Mods", de: "Mods", es: "Mods", ru: "Моды" }),
    allInstalled: t({
      en: "Everything this server runs is installed",
      fr: "Tout ce que ce serveur utilise est installé",
      de: "Alles, was dieser Server nutzt, ist installiert",
      es: "Todo lo que usa este servidor está instalado",
      ru: "Всё, что нужно серверу, установлено",
    }),
    downloadAndJoin: insert(
      t({
        en: "Download {{count}} missing & join",
        fr: "Télécharger {{count}} manquant(s) et rejoindre",
        de: "{{count}} fehlende laden & beitreten",
        es: "Descargar {{count}} y unirse",
        ru: "Скачать {{count}} и войти",
      }),
    ),
    updateAndJoin: insert(
      t({
        en: "Update {{count}} & join",
        fr: "Mettre à jour {{count}} et rejoindre",
        de: "{{count}} aktualisieren & beitreten",
        es: "Actualizar {{count}} y unirse",
        ru: "Обновить {{count}} и войти",
      }),
    ),
    installMissing: insert(
      t({
        en: "Install {{count}} missing",
        fr: "Installer {{count}} manquant(s)",
        de: "{{count}} fehlende installieren",
        es: "Instalar {{count}} que faltan",
        ru: "Установить {{count}}",
      }),
    ),
    updateStale: insert(
      t({
        en: "Update {{count}}",
        fr: "Mettre à jour {{count}}",
        de: "{{count}} aktualisieren",
        es: "Actualizar {{count}}",
        ru: "Обновить {{count}}",
      }),
    ),
    filterAll: t({ en: "All", fr: "Tous", de: "Alle", es: "Todos", ru: "Все" }),
    filterMissing: t({ en: "Missing", fr: "Manquants", de: "Fehlend", es: "Faltan", ru: "Нет" }),
    filterStale: t({
      en: "To update",
      fr: "À mettre à jour",
      de: "Zu aktualisieren",
      es: "Por actualizar",
      ru: "Обновить",
    }),
    noneInFilter: t({
      en: "Nothing in this filter",
      fr: "Rien dans ce filtre",
      de: "Nichts in diesem Filter",
      es: "Nada en este filtro",
      ru: "В этом фильтре пусто",
    }),
    playersNow: t({
      en: "On the server now",
      fr: "Sur le serveur maintenant",
      de: "Gerade auf dem Server",
      es: "En el servidor ahora",
      ru: "Сейчас на сервере",
    }),
    longestHere: t({
      en: "Longest here",
      fr: "Les plus présents",
      de: "Am längsten da",
      es: "Más tiempo aquí",
      ru: "Дольше всех",
    }),
    seeAll: insert(
      t({
        en: "See all {{count}}",
        fr: "Voir les {{count}}",
        de: "Alle {{count}} anzeigen",
        es: "Ver los {{count}}",
        ru: "Показать все {{count}}",
      }),
    ),
    searchPlayers: t({
      en: "Search players",
      fr: "Rechercher un joueur",
      de: "Spieler suchen",
      es: "Buscar jugadores",
      ru: "Поиск игроков",
    }),
    searchRules: t({
      en: "Search rules",
      fr: "Rechercher une règle",
      de: "Regeln suchen",
      es: "Buscar reglas",
      ru: "Поиск правил",
    }),
    timeHere: t({
      en: "Time here",
      fr: "Temps ici",
      de: "Zeit hier",
      es: "Tiempo aquí",
      ru: "Время",
    }),
    score: t({ en: "Score", fr: "Score", de: "Punkte", es: "Puntos", ru: "Очки" }),
    noMatch: t({
      en: "No match",
      fr: "Aucun résultat",
      de: "Kein Treffer",
      es: "Sin resultados",
      ru: "Ничего не найдено",
    }),
    noRules: t({
      en: "The server reported no rules",
      fr: "Le serveur n’a indiqué aucune règle",
      de: "Der Server meldet keine Regeln",
      es: "El servidor no informó reglas",
      ru: "Сервер не сообщил правил",
    }),
    you: t({
      en: "You and this server",
      fr: "Vous et ce serveur",
      de: "Du und dieser Server",
      es: "Tú y este servidor",
      ru: "Вы и этот сервер",
    }),
    lastPlayedHere: insert(
      t({
        en: "Last played {{when}}",
        fr: "Dernière partie {{when}}",
        de: "Zuletzt gespielt {{when}}",
        es: "Última partida {{when}}",
        ru: "Последняя игра {{when}}",
      }),
    ),
    sessions: insert(
      t({
        en: "{{count}} sessions in your history",
        fr: "{{count}} sessions dans l’historique",
        de: "{{count}} Sitzungen im Verlauf",
        es: "{{count}} sesiones en tu historial",
        ru: "{{count}} сессий в истории",
      }),
    ),
    sessionsOne: t({
      en: "1 session in your history",
      fr: "1 session dans l’historique",
      de: "1 Sitzung im Verlauf",
      es: "1 sesión en tu historial",
      ru: "1 сессия в истории",
    }),
    neverPlayed: t({
      en: "Never played here yet",
      fr: "Jamais joué ici",
      de: "Hier noch nie gespielt",
      es: "Nunca has jugado aquí",
      ru: "Ещё не играли здесь",
    }),
    inFavorites: t({
      en: "In your favourites",
      fr: "Dans vos favoris",
      de: "In deinen Favoriten",
      es: "En tus favoritos",
      ru: "В избранном",
    }),
    notInFavorites: t({
      en: "Not in your favourites",
      fr: "Pas dans vos favoris",
      de: "Nicht in deinen Favoriten",
      es: "No está en tus favoritos",
      ru: "Не в избранном",
    }),
    openSettings: t({
      en: "Open settings",
      fr: "Ouvrir les réglages",
      de: "Einstellungen öffnen",
      es: "Abrir ajustes",
      ru: "Открыть настройки",
    }),
    copyValue: t({
      en: "Copy the value",
      fr: "Copier la valeur",
      de: "Wert kopieren",
      es: "Copiar el valor",
      ru: "Скопировать значение",
    }),
    // ── added by the new detail panel ──
    title: t({
      en: "Server details",
      fr: "Détails du serveur",
      de: "Serverdetails",
      es: "Detalles del servidor",
      ru: "Сведения о сервере",
    }),
    close: t({
      en: "Close the details",
      fr: "Fermer les détails",
      de: "Details schließen",
      es: "Cerrar los detalles",
      ru: "Закрыть сведения",
    }),
    play: t({ en: "Play", fr: "Jouer", de: "Spielen", es: "Jugar", ru: "Играть" }),
    playTitle: t({
      en: "Launch DayZ and join this server",
      fr: "Lancer DayZ et rejoindre ce serveur",
      de: "DayZ starten und diesem Server beitreten",
      es: "Iniciar DayZ y unirse a este servidor",
      ru: "Запустить DayZ и подключиться к серверу",
    }),
    addFavorite: t({
      en: "Add to favorites",
      fr: "Ajouter aux favoris",
      de: "Zu Favoriten hinzufügen",
      es: "Añadir a favoritos",
      ru: "Добавить в избранное",
    }),
    removeFavorite: t({
      en: "Remove from favorites",
      fr: "Retirer des favoris",
      de: "Aus Favoriten entfernen",
      es: "Quitar de favoritos",
      ru: "Убрать из избранного",
    }),
    openDirect: t({
      en: "Open in Direct connect",
      fr: "Ouvrir dans Connexion directe",
      de: "In Direktverbindung öffnen",
      es: "Abrir en Conexión directa",
      ru: "Открыть в прямом подключении",
    }),
    exclude: t({
      en: "Hide this IP from the list",
      fr: "Masquer cette IP de la liste",
      de: "Diese IP aus der Liste ausblenden",
      es: "Ocultar esta IP de la lista",
      ru: "Скрыть этот IP из списка",
    }),
    unexclude: t({
      en: "Show this IP in the list again",
      fr: "Réafficher cette IP dans la liste",
      de: "Diese IP wieder in der Liste zeigen",
      es: "Volver a mostrar esta IP en la lista",
      ru: "Снова показывать этот IP",
    }),
    excluded: t({
      en: "Excluded",
      fr: "Exclu",
      de: "Ausgeschlossen",
      es: "Excluido",
      ru: "Исключён",
    }),
    rePing: t({
      en: "Ping again",
      fr: "Relancer le ping",
      de: "Erneut pingen",
      es: "Hacer ping de nuevo",
      ru: "Пинговать снова",
    }),
    refreshLive: t({
      en: "Ask the server again",
      fr: "Interroger à nouveau le serveur",
      de: "Server erneut abfragen",
      es: "Consultar el servidor de nuevo",
      ru: "Опросить сервер снова",
    }),
    notListed: t({
      en: "Not in the public server list: only what the server answers directly is shown.",
      fr: "Absent de la liste publique : seules les réponses directes du serveur sont affichées.",
      de: "Nicht in der öffentlichen Serverliste: nur die direkten Antworten des Servers werden gezeigt.",
      es: "No está en la lista pública: solo se muestra lo que el servidor responde directamente.",
      ru: "Сервера нет в публичном списке: показано только то, что он отвечает напрямую.",
    }),
    gamePort: t({
      en: "Game port",
      fr: "Port de jeu",
      de: "Spielport",
      es: "Puerto de juego",
      ru: "Игровой порт",
    }),
    address: t({ en: "Address", fr: "Adresse", de: "Adresse", es: "Dirección", ru: "Адрес" }),
    windows: t({ en: "Windows", fr: "Windows", de: "Windows", es: "Windows", ru: "Windows" }),
    linux: t({ en: "Linux", fr: "Linux", de: "Linux", es: "Linux", ru: "Linux" }),
    day: t({ en: "Day", fr: "Jour", de: "Tag", es: "Día", ru: "День" }),
    night: t({ en: "Night", fr: "Nuit", de: "Nacht", es: "Noche", ru: "Ночь" }),
    dawn: t({
      en: "Dawn or dusk",
      fr: "Aube ou crépuscule",
      de: "Dämmerung",
      es: "Amanecer o anochecer",
      ru: "Сумерки",
    }),
    general: t({ en: "Server", fr: "Serveur", de: "Server", es: "Servidor", ru: "Сервер" }),
    location: t({
      en: "Location",
      fr: "Emplacement",
      de: "Standort",
      es: "Ubicación",
      ru: "Расположение",
    }),
    modInstalled: t({
      en: "Installed",
      fr: "Installé",
      de: "Installiert",
      es: "Instalado",
      ru: "Установлен",
    }),
    modMissing: t({ en: "Missing", fr: "Manquant", de: "Fehlt", es: "Falta", ru: "Нет" }),
    modStale: t({
      en: "Update",
      fr: "Mise à jour",
      de: "Update",
      es: "Actualizar",
      ru: "Обновить",
    }),
    modsSummary: insert(
      t({
        en: "{{installed}} installed · {{missing}} missing · {{stale}} to update",
        fr: "{{installed}} installés · {{missing}} manquants · {{stale}} à mettre à jour",
        de: "{{installed}} installiert · {{missing}} fehlen · {{stale}} zu aktualisieren",
        es: "{{installed}} instalados · {{missing}} faltan · {{stale}} por actualizar",
        ru: "{{installed}} установлено · {{missing}} нет · {{stale}} обновить",
      }),
    ),
    modsLocalSize: insert(
      t({
        en: "{{size}} on disk",
        fr: "{{size}} sur le disque",
        de: "{{size}} auf der Festplatte",
        es: "{{size}} en disco",
        ru: "{{size}} на диске",
      }),
    ),
    modsFromA2s: t({
      en: "Reported by the server itself, without Workshop ids",
      fr: "Annoncés par le serveur lui-même, sans identifiant Workshop",
      de: "Vom Server selbst gemeldet, ohne Workshop-IDs",
      es: "Informados por el propio servidor, sin id de Workshop",
      ru: "Сообщены самим сервером, без ID Workshop",
    }),
    copyId: t({
      en: "Copy the Workshop id",
      fr: "Copier l'identifiant Workshop",
      de: "Workshop-ID kopieren",
      es: "Copiar el id de Workshop",
      ru: "Скопировать ID Workshop",
    }),
    playersOnline: insert(
      t({
        en: "Online now ({{count}})",
        fr: "En ligne ({{count}})",
        de: "Jetzt online ({{count}})",
        es: "En línea ({{count}})",
        ru: "Сейчас в игре ({{count}})",
      }),
    ),
    rules: insert(
      t({
        en: "Server rules ({{count}})",
        fr: "Règles du serveur ({{count}})",
        de: "Serverregeln ({{count}})",
        es: "Reglas del servidor ({{count}})",
        ru: "Правила сервера ({{count}})",
      }),
    ),
    liveFailed: t({
      en: "The server did not answer the query.",
      fr: "Le serveur n'a pas répondu à la requête.",
      de: "Der Server hat auf die Abfrage nicht geantwortet.",
      es: "El servidor no respondió a la consulta.",
      ru: "Сервер не ответил на запрос.",
    }),
    queryingLive: t({
      en: "Asking the server…",
      fr: "Interrogation du serveur…",
      de: "Server wird abgefragt…",
      es: "Consultando el servidor…",
      ru: "Опрос сервера…",
    }),
    queue: t({ en: "Queue", fr: "File d'attente", de: "Warteschlange", es: "Cola", ru: "Очередь" }),
    fill: t({
      en: "Fill",
      fr: "Remplissage",
      de: "Auslastung",
      es: "Ocupación",
      ru: "Заполненность",
    }),
    realPlayers: t({
      en: "Real players",
      fr: "Joueurs réels",
      de: "Echte Spieler",
      es: "Jugadores reales",
      ru: "Живые игроки",
    }),
    hive: t({ en: "Hive", fr: "Hive", de: "Hive", es: "Hive", ru: "Хайв" }),
    hiveOfficial: t({
      en: "Official",
      fr: "Officiel",
      de: "Offiziell",
      es: "Oficial",
      ru: "Официальный",
    }),
    hivePrivate: t({ en: "Private", fr: "Privé", de: "Privat", es: "Privado", ru: "Частный" }),
    hivePublic: t({
      en: "Public (community)",
      fr: "Public (communautaire)",
      de: "Öffentlich (Community)",
      es: "Público (comunidad)",
      ru: "Общий (сообщество)",
    }),
    hiveHint: t({
      en: "Official and public-hive servers share your character; a private hive keeps its own.",
      fr: "Les serveurs officiels et du hive public partagent votre personnage ; un hive privé garde le sien.",
      de: "Offizielle und Public-Hive-Server teilen deinen Charakter; ein privater Hive hat seinen eigenen.",
      es: "Los servidores oficiales y del hive público comparten tu personaje; un hive privado tiene el suyo.",
      ru: "Официальные серверы и общий хайв делят вашего персонажа; у частного хайва свой.",
    }),
    loginQueue: t({
      en: "Login queue",
      fr: "File d'attente",
      de: "Warteschlange",
      es: "Cola de acceso",
      ru: "Очередь входа",
    }),
    queueWaiting: insert(
      t({
        en: "{{count}} waiting",
        fr: "{{count}} en attente",
        de: "{{count}} wartend",
        es: "{{count}} esperando",
        ru: "ждут: {{count}}",
      }),
    ),
    queueEmpty: t({ en: "None", fr: "Aucune", de: "Keine", es: "Ninguna", ru: "Нет" }),
    whitelist: t({
      en: "Whitelist",
      fr: "Liste blanche",
      de: "Whitelist",
      es: "Lista blanca",
      ru: "Белый список",
    }),
    modsFromServer: t({
      en: "Announced by the server itself: it is not in the public list",
      fr: "Annoncés par le serveur lui-même : il n'est pas dans la liste publique",
      de: "Vom Server selbst gemeldet: er ist nicht in der öffentlichen Liste",
      es: "Anunciados por el propio servidor: no está en la lista pública",
      ru: "Сообщены самим сервером: его нет в публичном списке",
    }),
    bmPeak: t({ en: "Peak", fr: "Pic", de: "Spitze", es: "Pico", ru: "Пик" }),
    bmOffline: t({
      en: "offline",
      fr: "hors ligne",
      de: "offline",
      es: "desconectado",
      ru: "офлайн",
    }),
    copyIp: t({
      en: "Copy IP:port",
      fr: "Copier IP:port",
      de: "IP:Port kopieren",
      es: "Copiar IP:puerto",
      ru: "Скопировать IP:порт",
    }),
    copyAll: t({
      en: "Copy server details",
      fr: "Copier les détails du serveur",
      de: "Serverdetails kopieren",
      es: "Copiar detalles del servidor",
      ru: "Скопировать информацию о сервере",
    }),
    queryPort: t({
      en: "Query port",
      fr: "Port requête",
      de: "Query-Port",
      es: "Puerto de consulta",
      ru: "Порт запроса",
    }),
    players: t({ en: "Players", fr: "Joueurs", de: "Spieler", es: "Jugadores", ru: "Игроки" }),
    map: t({ en: "Map", fr: "Carte", de: "Karte", es: "Mapa", ru: "Карта" }),
    version: t({ en: "Version", fr: "Version", de: "Version", es: "Versión", ru: "Версия" }),
    time: t({ en: "Time", fr: "Heure", de: "Zeit", es: "Hora", ru: "Время" }),
    ping: t({ en: "Ping", fr: "Ping", de: "Ping", es: "Ping", ru: "Пинг" }),
    platform: t({
      en: "Platform",
      fr: "Plateforme",
      de: "Plattform",
      es: "Plataforma",
      ru: "Платформа",
    }),
    firstPerson: t({
      en: "1st-person",
      fr: "1ère personne",
      de: "Ego-Perspektive",
      es: "1ª persona",
      ru: "От 1-го лица",
    }),
    password: t({
      en: "Password",
      fr: "Mot de passe",
      de: "Passwort",
      es: "Contraseña",
      ru: "Пароль",
    }),
    vac: t({ en: "VAC", fr: "VAC", de: "VAC", es: "VAC", ru: "VAC" }),
    battleye: t({ en: "BattlEye", fr: "BattlEye", de: "BattlEye", es: "BattlEye", ru: "BattlEye" }),
    yes: t({ en: "Yes", fr: "Oui", de: "Ja", es: "Sí", ru: "Да" }),
    no: t({ en: "No", fr: "Non", de: "Nein", es: "No", ru: "Нет" }),
    loadingMods: insert(
      t({
        en: "Loading mods ({{count}})…",
        fr: "Chargement des mods ({{count}})…",
        de: "Lade Mods ({{count}})…",
        es: "Cargando mods ({{count}})…",
        ru: "Загрузка модов ({{count}})…",
      }),
    ),
    modsCount: insert(
      t({
        en: "Mods ({{count}})",
        fr: "Mods ({{count}})",
        de: "Mods ({{count}})",
        es: "Mods ({{count}})",
        ru: "Моды ({{count}})",
      }),
    ),
    openWorkshop: t({
      en: "Open on Steam Workshop",
      fr: "Ouvrir sur Steam Workshop",
      de: "Im Steam Workshop öffnen",
      es: "Abrir en Steam Workshop",
      ru: "Открыть в Steam Workshop",
    }),
    modsFailed: insert(
      t({
        en: "{{count}} mod(s) — fetch failed",
        fr: "{{count}} mod(s) — échec de récupération",
        de: "{{count}} Mod(s) — Abruf fehlgeschlagen",
        es: "{{count}} mod(s) — error al obtener",
        ru: "{{count}} мод(ов) — ошибка загрузки",
      }),
    ),
    retry: t({
      en: "Retry",
      fr: "Réessayer",
      de: "Erneut versuchen",
      es: "Reintentar",
      ru: "Повторить",
    }),
    modsNotReported: insert(
      t({
        en: "{{count}} mod(s) — not reported by server",
        fr: "{{count}} mod(s) — non fournis par le serveur",
        de: "{{count}} Mod(s) — nicht vom Server gemeldet",
        es: "{{count}} mod(s) — no reportados por el servidor",
        ru: "{{count}} мод(ов) — не сообщается сервером",
      }),
    ),
    queryMods: t({
      en: "Query live server for mod list",
      fr: "Interroger le serveur pour la liste des mods",
      de: "Live-Server nach Mod-Liste abfragen",
      es: "Consultar servidor en vivo para lista de mods",
      ru: "Запросить список модов с сервера",
    }),
    queryA2s: t({
      en: "Query A2S",
      fr: "Interroger A2S",
      de: "A2S abfragen",
      es: "Consultar A2S",
      ru: "Запрос A2S",
    }),
    noMods: t({
      en: "No mods",
      fr: "Aucun mod",
      de: "Keine Mods",
      es: "Sin mods",
      ru: "Нет модов",
    }),
    bmOnline: t({ en: "online", fr: "en ligne", de: "online", es: "en línea", ru: "онлайн" }),
    bmRank: t({ en: "Rank", fr: "Rang", de: "Rang", es: "Ranking", ru: "Рейтинг" }),
    bmPlayerHistory: t({
      en: "Player count (24 h)",
      fr: "Joueurs (24 h)",
      de: "Spieleranzahl (24 h)",
      es: "Jugadores (24 h)",
      ru: "Игроки (24 ч)",
    }),
    bmMin: t({ en: "Min", fr: "Min", de: "Min", es: "Mín", ru: "Мин" }),
    bm24hAgo: t({
      en: "24h ago",
      fr: "il y a 24h",
      de: "vor 24h",
      es: "hace 24h",
      ru: "24ч назад",
    }),
    bmAvg: insert(
      t({
        en: "avg: {{count}}",
        fr: "moy : {{count}}",
        de: "Ø: {{count}}",
        es: "prom: {{count}}",
        ru: "сред: {{count}}",
      }),
    ),
    bmNow: t({ en: "now", fr: "maintenant", de: "jetzt", es: "ahora", ru: "сейчас" }),
    a2sTitle: t({
      en: "Live A2S Info",
      fr: "Infos A2S en direct",
      de: "Live A2S-Info",
      es: "Info A2S en vivo",
      ru: "A2S информация",
    }),
    a2sLivePlayers: t({
      en: "Live players",
      fr: "Joueurs en direct",
      de: "Live-Spieler",
      es: "Jugadores en vivo",
      ru: "Игроки онлайн",
    }),
    bots: t({ en: "Bots", fr: "Bots", de: "Bots", es: "Bots", ru: "Боты" }),
    a2sGame: t({ en: "Game", fr: "Jeu", de: "Spiel", es: "Juego", ru: "Игра" }),
    a2sOnlinePlayers: t({
      en: "Online players",
      fr: "Joueurs en ligne",
      de: "Online-Spieler",
      es: "Jugadores en línea",
      ru: "Игроки онлайн",
    }),
    a2sNoPlayers: t({
      en: "No players online",
      fr: "Aucun joueur en ligne",
      de: "Keine Spieler online",
      es: "No hay jugadores en línea",
      ru: "Нет игроков онлайн",
    }),
    a2sNamesNotReported: t({
      en: "Player names not reported by server",
      fr: "Noms des joueurs non fournis par le serveur",
      de: "Spielernamen nicht vom Server gemeldet",
      es: "Nombres de jugadores no reportados por el servidor",
      ru: "Имена игроков не сообщаются сервером",
    }),
    a2sClickRefresh: t({
      en: "Click Refresh to query live data",
      fr: "Cliquez sur Actualiser pour interroger les données",
      de: "Klicke Aktualisieren für Live-Daten",
      es: "Clic en Actualizar para consultar datos en vivo",
      ru: "Нажмите Обновить для запроса данных",
    }),
    ageToday: t({ en: "today", fr: "aujourd'hui", de: "heute", es: "hoy", ru: "сегодня" }),
    ageDay: t({ en: "1 day", fr: "1 jour", de: "1 Tag", es: "1 día", ru: "1 день" }),
    ageDays: insert(
      t({
        en: "{{count}} days",
        fr: "{{count}} jours",
        de: "{{count}} Tage",
        es: "{{count}} días",
        ru: "{{count}} дней",
      }),
    ),
    ageMonth: t({ en: "1 month", fr: "1 mois", de: "1 Monat", es: "1 mes", ru: "1 месяц" }),
    ageMonths: insert(
      t({
        en: "{{count}} months",
        fr: "{{count}} mois",
        de: "{{count}} Monate",
        es: "{{count}} meses",
        ru: "{{count}} месяцев",
      }),
    ),
    ageYear: t({ en: "1 year", fr: "1 an", de: "1 Jahr", es: "1 año", ru: "1 год" }),
    ageYears: insert(
      t({
        en: "{{count}} years",
        fr: "{{count}} ans",
        de: "{{count}} Jahre",
        es: "{{count}} años",
        ru: "{{count}} лет",
      }),
    ),
    ago: insert(
      t({
        en: "{{time}} ago",
        fr: "il y a {{time}}",
        de: "vor {{time}}",
        es: "hace {{time}}",
        ru: "{{time}} назад",
      }),
    ),
  },
} satisfies Dictionary;

export default content;
