import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "detail",
  content: {
    copyIp: t({ en: "Copy IP:port", fr: "Copier IP:port", de: "IP:Port kopieren", es: "Copiar IP:puerto", ru: "Скопировать IP:порт" }),
    copyAll: t({ en: "Copy server details", fr: "Copier les détails du serveur", de: "Serverdetails kopieren", es: "Copiar detalles del servidor", ru: "Скопировать информацию о сервере" }),
    queryPort: t({ en: "Query port", fr: "Port requête", de: "Query-Port", es: "Puerto de consulta", ru: "Порт запроса" }),
    players: t({ en: "Players", fr: "Joueurs", de: "Spieler", es: "Jugadores", ru: "Игроки" }),
    map: t({ en: "Map", fr: "Carte", de: "Karte", es: "Mapa", ru: "Карта" }),
    version: t({ en: "Version", fr: "Version", de: "Version", es: "Versión", ru: "Версия" }),
    time: t({ en: "Time", fr: "Heure", de: "Zeit", es: "Hora", ru: "Время" }),
    ping: t({ en: "Ping", fr: "Ping", de: "Ping", es: "Ping", ru: "Пинг" }),
    platform: t({ en: "Platform", fr: "Plateforme", de: "Plattform", es: "Plataforma", ru: "Платформа" }),
    firstPerson: t({ en: "1st-person", fr: "1ère personne", de: "Ego-Perspektive", es: "1ª persona", ru: "От 1-го лица" }),
    password: t({ en: "Password", fr: "Mot de passe", de: "Passwort", es: "Contraseña", ru: "Пароль" }),
    vac: t({ en: "VAC", fr: "VAC", de: "VAC", es: "VAC", ru: "VAC" }),
    battleye: t({ en: "BattlEye", fr: "BattlEye", de: "BattlEye", es: "BattlEye", ru: "BattlEye" }),
    yes: t({ en: "Yes", fr: "Oui", de: "Ja", es: "Sí", ru: "Да" }),
    no: t({ en: "No", fr: "Non", de: "Nein", es: "No", ru: "Нет" }),
    loadingMods: insert(t({ en: "Loading mods ({{count}})…", fr: "Chargement des mods ({{count}})…", de: "Lade Mods ({{count}})…", es: "Cargando mods ({{count}})…", ru: "Загрузка модов ({{count}})…" })),
    modsCount: insert(t({ en: "Mods ({{count}})", fr: "Mods ({{count}})", de: "Mods ({{count}})", es: "Mods ({{count}})", ru: "Моды ({{count}})" })),
    openWorkshop: t({ en: "Open on Steam Workshop", fr: "Ouvrir sur Steam Workshop", de: "Im Steam Workshop öffnen", es: "Abrir en Steam Workshop", ru: "Открыть в Steam Workshop" }),
    modsFailed: insert(t({ en: "{{count}} mod(s) — fetch failed", fr: "{{count}} mod(s) — échec de récupération", de: "{{count}} Mod(s) — Abruf fehlgeschlagen", es: "{{count}} mod(s) — error al obtener", ru: "{{count}} мод(ов) — ошибка загрузки" })),
    retry: t({ en: "Retry", fr: "Réessayer", de: "Erneut versuchen", es: "Reintentar", ru: "Повторить" }),
    modsNotReported: insert(t({ en: "{{count}} mod(s) — not reported by server", fr: "{{count}} mod(s) — non fournis par le serveur", de: "{{count}} Mod(s) — nicht vom Server gemeldet", es: "{{count}} mod(s) — no reportados por el servidor", ru: "{{count}} мод(ов) — не сообщается сервером" })),
    queryMods: t({ en: "Query live server for mod list", fr: "Interroger le serveur pour la liste des mods", de: "Live-Server nach Mod-Liste abfragen", es: "Consultar servidor en vivo para lista de mods", ru: "Запросить список модов с сервера" }),
    queryA2s: t({ en: "Query A2S", fr: "Interroger A2S", de: "A2S abfragen", es: "Consultar A2S", ru: "Запрос A2S" }),
    noMods: t({ en: "No mods", fr: "Aucun mod", de: "Keine Mods", es: "Sin mods", ru: "Нет модов" }),
    bmTitle: t({ en: "BattleMetrics", fr: "BattleMetrics", de: "BattleMetrics", es: "BattleMetrics", ru: "BattleMetrics" }),
    bmRefreshTitle: t({ en: "Refresh BattleMetrics data", fr: "Actualiser les données BattleMetrics", de: "BattleMetrics-Daten aktualisieren", es: "Actualizar datos de BattleMetrics", ru: "Обновить данные BattleMetrics" }),
    bmConfigure: t({ en: "Configure a BattleMetrics API token in settings to see server rankings & history.", fr: "Configurez un jeton API BattleMetrics dans les paramètres pour voir les classements et l'historique.", de: "Konfiguriere einen BattleMetrics API-Token in den Einstellungen für Server-Rankings & Verlauf.", es: "Configura un token de API de BattleMetrics en ajustes para ver rankings e historial del servidor.", ru: "Настройте токен BattleMetrics API в настройках для просмотра рейтингов и истории сервера." }),
    bmLoading: t({ en: "Loading BattleMetrics data…", fr: "Chargement des données BattleMetrics…", de: "Lade BattleMetrics-Daten…", es: "Cargando datos de BattleMetrics…", ru: "Загрузка данных BattleMetrics…" }),
    bmOfficial: t({ en: "official", fr: "officiel", de: "offiziell", es: "oficial", ru: "официальный" }),
    bmPrivate: t({ en: "private", fr: "privé", de: "privat", es: "privado", ru: "приватный" }),
    bm3pp: t({ en: "3PP", fr: "3PP", de: "3PP", es: "3PP", ru: "3PP" }),
    bm1pp: t({ en: "1PP", fr: "1PP", de: "1PP", es: "1PP", ru: "1PP" }),
    bmModded: t({ en: "modded", fr: "moddé", de: "gemoddet", es: "con mods", ru: "с модами" }),
    bmOnline: t({ en: "online", fr: "en ligne", de: "online", es: "en línea", ru: "онлайн" }),
    bmName: t({ en: "BM Server", fr: "Serveur BM", de: "BM Server", es: "Servidor BM", ru: "Сервер BM" }),
    bmRank: t({ en: "Rank", fr: "Rang", de: "Rang", es: "Ranking", ru: "Рейтинг" }),
    bmPlayers: t({ en: "Players", fr: "Joueurs", de: "Spieler", es: "Jugadores", ru: "Игроки" }),
    bmStatus: t({ en: "Status", fr: "Statut", de: "Status", es: "Estado", ru: "Статус" }),
    bmCountry: t({ en: "Country", fr: "Pays", de: "Land", es: "País", ru: "Страна" }),
    bmDistance: t({ en: "Distance", fr: "Distance", de: "Entfernung", es: "Distancia", ru: "Расстояние" }),
    bmUptime: t({ en: "Uptime", fr: "Disponibilité", de: "Verfügbarkeit", es: "Tiempo activo", ru: "Аптайм" }),
    bmFirstSeen: t({ en: "First seen", fr: "Première vue", de: "Erstmals gesehen", es: "Primera vez visto", ru: "Первое появление" }),
    bmSteamId: t({ en: "Steam ID", fr: "Steam ID", de: "Steam-ID", es: "Steam ID", ru: "Steam ID" }),
    bmOpenSteam: t({ en: "Open Steam profile", fr: "Ouvrir le profil Steam", de: "Steam-Profil öffnen", es: "Abrir perfil de Steam", ru: "Открыть профиль Steam" }),
    bmPlayerHistory: t({ en: "Player count (24 h)", fr: "Joueurs (24 h)", de: "Spieleranzahl (24 h)", es: "Jugadores (24 h)", ru: "Игроки (24 ч)" }),
    bmMin: t({ en: "Min", fr: "Min", de: "Min", es: "Mín", ru: "Мин" }),
    bmCurrent: t({ en: "Current", fr: "Actuel", de: "Aktuell", es: "Actual", ru: "Текущий" }),
    bmMax: t({ en: "Max", fr: "Max", de: "Max", es: "Máx", ru: "Макс" }),
    bm24hAgo: t({ en: "24h ago", fr: "il y a 24h", de: "vor 24h", es: "hace 24h", ru: "24ч назад" }),
    bmAvg: insert(t({ en: "avg: {{count}}", fr: "moy : {{count}}", de: "Ø: {{count}}", es: "prom: {{count}}", ru: "сред: {{count}}" })),
    bmNow: t({ en: "now", fr: "maintenant", de: "jetzt", es: "ahora", ru: "сейчас" }),
    bmView: t({ en: "View on BattleMetrics", fr: "Voir sur BattleMetrics", de: "Auf BattleMetrics ansehen", es: "Ver en BattleMetrics", ru: "Смотреть на BattleMetrics" }),
    a2sTitle: t({ en: "Live A2S Info", fr: "Infos A2S en direct", de: "Live A2S-Info", es: "Info A2S en vivo", ru: "A2S информация" }),
    a2sLivePlayers: t({ en: "Live players", fr: "Joueurs en direct", de: "Live-Spieler", es: "Jugadores en vivo", ru: "Игроки онлайн" }),
    bots: t({ en: "Bots", fr: "Bots", de: "Bots", es: "Bots", ru: "Боты" }),
    a2sGame: t({ en: "Game", fr: "Jeu", de: "Spiel", es: "Juego", ru: "Игра" }),
    a2sOnlinePlayers: t({ en: "Online players", fr: "Joueurs en ligne", de: "Online-Spieler", es: "Jugadores en línea", ru: "Игроки онлайн" }),
    a2sNoPlayers: t({ en: "No players online", fr: "Aucun joueur en ligne", de: "Keine Spieler online", es: "No hay jugadores en línea", ru: "Нет игроков онлайн" }),
    a2sNamesNotReported: t({ en: "Player names not reported by server", fr: "Noms des joueurs non fournis par le serveur", de: "Spielernamen nicht vom Server gemeldet", es: "Nombres de jugadores no reportados por el servidor", ru: "Имена игроков не сообщаются сервером" }),
    a2sClickRefresh: t({ en: "Click Refresh to query live data", fr: "Cliquez sur Actualiser pour interroger les données", de: "Klicke Aktualisieren für Live-Daten", es: "Clic en Actualizar para consultar datos en vivo", ru: "Нажмите Обновить для запроса данных" }),
    ageToday: t({ en: "today", fr: "aujourd'hui", de: "heute", es: "hoy", ru: "сегодня" }),
    ageDay: t({ en: "1 day", fr: "1 jour", de: "1 Tag", es: "1 día", ru: "1 день" }),
    ageDays: insert(t({ en: "{{count}} days", fr: "{{count}} jours", de: "{{count}} Tage", es: "{{count}} días", ru: "{{count}} дней" })),
    ageMonth: t({ en: "1 month", fr: "1 mois", de: "1 Monat", es: "1 mes", ru: "1 месяц" }),
    ageMonths: insert(t({ en: "{{count}} months", fr: "{{count}} mois", de: "{{count}} Monate", es: "{{count}} meses", ru: "{{count}} месяцев" })),
    ageYear: t({ en: "1 year", fr: "1 an", de: "1 Jahr", es: "1 año", ru: "1 год" }),
    ageYears: insert(t({ en: "{{count}} years", fr: "{{count}} ans", de: "{{count}} Jahre", es: "{{count}} años", ru: "{{count}} лет" })),
    ago: insert(t({ en: "{{time}} ago", fr: "il y a {{time}}", de: "vor {{time}}", es: "hace {{time}}", ru: "{{time}} назад" })),
  },
} satisfies Dictionary;

export default content;
