import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "mods",
  content: {
    // ── the new view ──
    title: t({ en: "Mods", fr: "Mods", de: "Mods", es: "Mods", ru: "Моды" }),
    searchPlaceholder: t({ en: "Search name or Workshop ID…", fr: "Rechercher un nom ou un ID Workshop…", de: "Name oder Workshop-ID suchen…", es: "Buscar nombre o ID de Workshop…", ru: "Поиск по имени или ID Workshop…" }),
    filterAll: t({ en: "All", fr: "Tous", de: "Alle", es: "Todos", ru: "Все" }),
    filterUpdates: t({ en: "Updates", fr: "Mises à jour", de: "Updates", es: "Actualizaciones", ru: "Обновления" }),
    filterUnmanaged: t({ en: "Unlinked", fr: "Non liés", de: "Nicht verknüpft", es: "Sin enlazar", ru: "Не связаны" }),
    filterLabel: t({ en: "Show", fr: "Afficher", de: "Anzeigen", es: "Mostrar", ru: "Показать" }),
    statInstalled: t({ en: "Installed", fr: "Installés", de: "Installiert", es: "Instalados", ru: "Установлено" }),
    statSize: t({ en: "On disk", fr: "Sur le disque", de: "Auf der Festplatte", es: "En disco", ru: "На диске" }),
    statStale: t({ en: "Behind", fr: "En retard", de: "Veraltet", es: "Desactualizados", ru: "Устарели" }),
    statLinked: t({ en: "Linked", fr: "Liés", de: "Verknüpft", es: "Enlazados", ru: "Связаны" }),
    statUnlinked: t({ en: "Unlinked", fr: "Non liés", de: "Nicht verknüpft", es: "Sin enlazar", ru: "Не связаны" }),
    statChecked: t({ en: "Last checked", fr: "Dernière vérification", de: "Zuletzt geprüft", es: "Última comprobación", ru: "Последняя проверка" }),
    statLargest: t({ en: "Largest", fr: "Le plus lourd", de: "Größter", es: "El más grande", ru: "Самый большой" }),
    neverChecked: t({ en: "never", fr: "jamais", de: "nie", es: "nunca", ru: "никогда" }),
    apiKeyMissingTitle: t({ en: "Update checks are off", fr: "La vérification des mises à jour est désactivée", de: "Update-Prüfung ist aus", es: "La comprobación de actualizaciones está desactivada", ru: "Проверка обновлений отключена" }),
    apiKeyMissingBody: t({ en: "Add a Steam Web API key to see which mods are behind the Workshop.", fr: "Ajoutez une clé Steam Web API pour voir quels mods sont en retard sur le Workshop.", de: "Füge einen Steam-Web-API-Schlüssel hinzu, um zu sehen, welche Mods hinter dem Workshop liegen.", es: "Añade una clave de Steam Web API para ver qué mods están por detrás del Workshop.", ru: "Добавьте ключ Steam Web API, чтобы видеть, какие моды отстают от Workshop." }),
    openSettings: t({ en: "Add a key", fr: "Ajouter une clé", de: "Schlüssel hinzufügen", es: "Añadir una clave", ru: "Добавить ключ" }),
    daysBehind: insert(t({ en: "{{days}} d behind", fr: "{{days}} j de retard", de: "{{days}} T zurück", es: "{{days}} d de retraso", ru: "отстаёт на {{days}} д" })),
    behindToday: t({ en: "behind", fr: "en retard", de: "veraltet", es: "desactualizado", ru: "устарел" }),
    noMatch: t({ en: "No mod matches these filters.", fr: "Aucun mod ne correspond à ces filtres.", de: "Kein Mod passt zu diesen Filtern.", es: "Ningún mod coincide con estos filtros.", ru: "Нет модов, подходящих под фильтры." }),
    clearFilters: t({ en: "Clear filters", fr: "Effacer les filtres", de: "Filter zurücksetzen", es: "Borrar filtros", ru: "Сбросить фильтры" }),
    moreActions: t({ en: "More actions", fr: "Plus d'actions", de: "Weitere Aktionen", es: "Más acciones", ru: "Другие действия" }),
    cleanup: t({ en: "Remove managed mods and links", fr: "Supprimer les mods gérés et leurs liens", de: "Verwaltete Mods und Links entfernen", es: "Quitar mods gestionados y enlaces", ru: "Удалить управляемые моды и ссылки" }),
    update: t({ en: "Update", fr: "Mettre à jour", de: "Aktualisieren", es: "Actualizar", ru: "Обновить" }),
    openModFolder: t({ en: "Open its folder", fr: "Ouvrir son dossier", de: "Ordner öffnen", es: "Abrir su carpeta", ru: "Открыть папку" }),
    rowActions: t({ en: "Actions", fr: "Actions", de: "Aktionen", es: "Acciones", ru: "Действия" }),
    detailsEmpty: t({ en: "Select a mod to see its details.", fr: "Sélectionnez un mod pour voir ses détails.", de: "Wähle einen Mod, um Details zu sehen.", es: "Selecciona un mod para ver sus detalles.", ru: "Выберите мод, чтобы увидеть подробности." }),
    detailsStatus: t({ en: "Status", fr: "État", de: "Status", es: "Estado", ru: "Статус" }),
    detailsLink: t({ en: "Loaded in game", fr: "Chargé en jeu", de: "Im Spiel geladen", es: "Cargado en el juego", ru: "Загружается в игре" }),
    detailsLinkHint: t({ en: "A link in the game folder makes DayZ load this mod when it joins a server that runs it.", fr: "Un lien dans le dossier du jeu permet à DayZ de charger ce mod sur les serveurs qui l'utilisent.", de: "Ein Link im Spielordner lässt DayZ diesen Mod laden, wenn ein Server ihn nutzt.", es: "Un enlace en la carpeta del juego hace que DayZ cargue este mod en los servidores que lo usan.", ru: "Ссылка в папке игры позволяет DayZ загружать этот мод на серверах, где он используется." }),
    detailsUpToDate: t({ en: "Up to date", fr: "À jour", de: "Aktuell", es: "Al día", ru: "Актуален" }),
    detailsUnknown: t({ en: "Not checked", fr: "Non vérifié", de: "Nicht geprüft", es: "Sin comprobar", ru: "Не проверен" }),
    detailsShare: t({ en: "Share of all mods", fr: "Part de tous les mods", de: "Anteil aller Mods", es: "Parte del total", ru: "Доля от всех модов" }),
    detailsLaunchParam: t({ en: "Launch parameter", fr: "Paramètre de lancement", de: "Startparameter", es: "Parámetro de inicio", ru: "Параметр запуска" }),
    bulkUpdate: insert(t({ en: "Update {{count}}", fr: "Mettre à jour {{count}}", de: "{{count}} aktualisieren", es: "Actualizar {{count}}", ru: "Обновить {{count}}" })),
    reviewUpdateAll: t({ en: "Re-validate every mod", fr: "Revalider tous les mods", de: "Alle Mods neu prüfen", es: "Revalidar todos los mods", ru: "Перепроверить все моды" }),
    reviewSize: insert(t({ en: "{{size}} to check", fr: "{{size}} à vérifier", de: "{{size}} zu prüfen", es: "{{size}} por comprobar", ru: "{{size}} к проверке" })),
    reviewUnknownSize: t({ en: "Size known after download", fr: "Taille connue après le téléchargement", de: "Größe nach dem Download bekannt", es: "Tamaño conocido tras la descarga", ru: "Размер станет известен после загрузки" }),
    installParsed: insert(t({ en: "{{count}} IDs found", fr: "{{count}} ID trouvés", de: "{{count}} IDs gefunden", es: "{{count}} ID encontrados", ru: "Найдено ID: {{count}}" })),
    installAlready: t({ en: "already installed", fr: "déjà installé", de: "bereits installiert", es: "ya instalado", ru: "уже установлен" }),
    count: insert(t({ en: "{{count}} mods", fr: "{{count}} mods", de: "{{count}} Mods", es: "{{count}} mods", ru: "{{count}} модов" })),
    countOne: insert(t({ en: "{{count}} mod", fr: "{{count}} mod", de: "{{count}} Mod", es: "{{count}} mod", ru: "{{count}} мод" })),
    updatesAvailable: insert(t({ en: "{{count}} updates available", fr: "{{count}} mises à jour disponibles", de: "{{count}} Updates verfügbar", es: "{{count}} actualizaciones disponibles", ru: "{{count}} обновлений доступно" })),
    updateAvailableOne: insert(t({ en: "{{count}} update available", fr: "{{count}} mise à jour disponible", de: "{{count}} Update verfügbar", es: "{{count}} actualización disponible", ru: "{{count}} обновление доступно" })),
    allUpToDate: t({ en: "All up to date", fr: "Tout est à jour", de: "Alle aktuell", es: "Todo actualizado", ru: "Все моды актуальны" }),
    install: t({ en: "Install mod", fr: "Installer un mod", de: "Mod installieren", es: "Instalar mod", ru: "Установить мод" }),
    installTitle: t({ en: "Install a mod manually by Workshop ID or URL", fr: "Installer un mod manuellement par ID Workshop ou URL", de: "Mod manuell per Workshop-ID oder URL installieren", es: "Instalar un mod manualmente por Workshop ID o URL", ru: "Установить мод вручную по Workshop ID или URL" }),
    openFolder: t({ en: "Open folder", fr: "Ouvrir le dossier", de: "Ordner öffnen", es: "Abrir carpeta", ru: "Открыть папку" }),
    openFolderTitle: t({ en: "Open Workshop mods directory in file manager", fr: "Ouvrir le dossier des mods Workshop", de: "Workshop-Mods-Verzeichnis im Dateimanager öffnen", es: "Abrir carpeta de mods del Workshop en el gestor de archivos", ru: "Открыть папку модов Workshop в файловом менеджере" }),
    checking: t({ en: "Checking…", fr: "Vérification…", de: "Prüfe…", es: "Comprobando…", ru: "Проверка…" }),
    checkUpdates: t({ en: "Check updates", fr: "Vérifier les MAJ", de: "Updates prüfen", es: "Comprobar actualizaciones", ru: "Проверить обновления" }),
    checkUpdatesTitle: t({ en: "Check Steam Workshop for updates", fr: "Vérifier les mises à jour sur Steam Workshop", de: "Steam Workshop auf Updates prüfen", es: "Comprobar actualizaciones en Steam Workshop", ru: "Проверить обновления в Steam Workshop" }),
    updateCount: insert(t({ en: "Update {{count}}", fr: "Mettre à jour {{count}}", de: "{{count}} aktualisieren", es: "Actualizar {{count}}", ru: "Обновить {{count}}" })),
    updateCountTitle: insert(t({ en: "Update only the {{count}} mods with available updates", fr: "Mettre à jour les {{count}} mods avec des MAJ disponibles", de: "Nur die {{count}} Mods mit verfügbaren Updates aktualisieren", es: "Actualizar solo los {{count}} mods con actualizaciones disponibles", ru: "Обновить только {{count}} модов с доступными обновлениями" })),
    all: t({ en: "All", fr: "Tous", de: "Alle", es: "Todos", ru: "Все" }),
    updateAll: t({ en: "Update all", fr: "Tout mettre à jour", de: "Alle aktualisieren", es: "Actualizar todos", ru: "Обновить все" }),
    updateAllTitle: t({ en: "Force re-validate all mods via steamcmd", fr: "Forcer la re-validation de tous les mods via steamcmd", de: "Alle Mods per steamcmd neu validieren", es: "Forzar revalidación de todos los mods vía steamcmd", ru: "Принудительная переустановка всех модов через steamcmd" }),
    refreshTitle: t({ en: "Refresh mod list", fr: "Actualiser la liste des mods", de: "Mod-Liste aktualisieren", es: "Actualizar lista de mods", ru: "Обновить список модов" }),
    cleanupTitle: t({ en: "Remove all managed mods and symlinks", fr: "Supprimer tous les mods gérés et les liens symboliques", de: "Alle verwalteten Mods und Symlinks entfernen", es: "Eliminar todos los mods gestionados y enlaces simbólicos", ru: "Удалить все управляемые моды и симлинки" }),
    loading: t({ en: "Loading mods…", fr: "Chargement des mods…", de: "Lade Mods…", es: "Cargando mods…", ru: "Загрузка модов…" }),
    noMods: t({ en: "No mods installed", fr: "Aucun mod installé", de: "Keine Mods installiert", es: "No hay mods instalados", ru: "Моды не установлены" }),
    noModsHint: t({ en: "Connect to a modded server to install mods", fr: "Connectez-vous à un serveur moddé pour installer des mods", de: "Mit einem Server mit Mods verbinden um Mods zu installieren", es: "Conéctate a un servidor con mods para instalarlos", ru: "Подключитесь к серверу с модами для их установки" }),
    selectAll: t({ en: "Select all", fr: "Tout sélectionner", de: "Alle auswählen", es: "Seleccionar todos", ru: "Выбрать все" }),
    deselectAll: t({ en: "Deselect all", fr: "Tout désélectionner", de: "Auswahl aufheben", es: "Deseleccionar todos", ru: "Снять выделение" }),
    colName: t({ en: "Name", fr: "Nom", de: "Name", es: "Nombre", ru: "Название" }),
    colWorkshopId: t({ en: "Workshop ID", fr: "ID Workshop", de: "Workshop-ID", es: "Workshop ID", ru: "Workshop ID" }),
    colSize: t({ en: "Size", fr: "Taille", de: "Größe", es: "Tamaño", ru: "Размер" }),
    colLocal: t({ en: "Local", fr: "Local", de: "Lokal", es: "Local", ru: "Локальный" }),
    colRemote: t({ en: "Remote", fr: "Distant", de: "Remote", es: "Remoto", ru: "Удалённый" }),
    colStatus: t({ en: "Status", fr: "Statut", de: "Status", es: "Estado", ru: "Статус" }),
    colStatusTitle: t({ en: "UPDATE = new version on Workshop; OK = up to date; LINKED = symlink active; UNLINKED = no symlink", fr: "UPDATE = nouvelle version ; OK = à jour ; LINKED = lien actif ; UNLINKED = pas de lien", de: "UPDATE = neue Version im Workshop; OK = aktuell; LINKED = Symlink aktiv; UNLINKED = kein Symlink", es: "UPDATE = nueva versión en Workshop; OK = actualizado; LINKED = enlace activo; UNLINKED = sin enlace", ru: "UPDATE = новая версия в Workshop; OK = актуальный; LINKED = симлинк активен; UNLINKED = нет симлинка" }),
    updateAvailable: t({ en: "Update available", fr: "Mise à jour disponible", de: "Update verfügbar", es: "Actualización disponible", ru: "Доступно обновление" }),
    managed: t({ en: "Managed", fr: "Géré", de: "Verwaltet", es: "Gestionado", ru: "Управляемый" }),
    copyName: t({ en: "Copy mod name", fr: "Copier le nom du mod", de: "Mod-Name kopieren", es: "Copiar nombre del mod", ru: "Скопировать название мода" }),
    copied: t({ en: "Copied!", fr: "Copié !", de: "Kopiert!", es: "¡Copiado!", ru: "Скопировано!" }),
    openWorkshop: t({ en: "Open on Steam Workshop", fr: "Ouvrir sur Steam Workshop", de: "Im Steam Workshop öffnen", es: "Abrir en Steam Workshop", ru: "Открыть в Steam Workshop" }),
    copyWorkshopId: t({ en: "Copy workshop ID", fr: "Copier l'ID workshop", de: "Workshop-ID kopieren", es: "Copiar workshop ID", ru: "Скопировать workshop ID" }),
    statusUpdate: t({ en: "UPDATE", fr: "MAJ", de: "UPDATE", es: "ACTUALIZAR", ru: "ОБНОВИТЬ" }),
    statusOk: t({ en: "OK", fr: "OK", de: "OK", es: "OK", ru: "OK" }),
    statusLinked: t({ en: "LINKED", fr: "LIÉ", de: "LINKED", es: "ENLAZADO", ru: "СВЯЗАН" }),
    statusUnlinked: t({ en: "UNLINKED", fr: "NON LIÉ", de: "UNLINKED", es: "SIN ENLACE", ru: "НЕ СВЯЗАН" }),
    updateClick: t({ en: "Update available — click to update", fr: "Mise à jour disponible — cliquez pour mettre à jour", de: "Update verfügbar — klicken zum Aktualisieren", es: "Actualización disponible — clic para actualizar", ru: "Доступно обновление — нажмите для обновления" }),
    revalidate: t({ en: "Force re-validate via steamcmd", fr: "Forcer la re-validation via steamcmd", de: "Per steamcmd neu validieren", es: "Forzar revalidación vía steamcmd", ru: "Принудительная переустановка через steamcmd" }),
    updating: t({ en: "Updating…", fr: "Mise à jour…", de: "Aktualisiere…", es: "Actualizando…", ru: "Обновление…" }),
    linkedHint: t({ en: "Linked: symlink active — this mod is loaded when connecting to modded servers. Click to remove the symlink.", fr: "Lié : lien symbolique actif — ce mod est chargé lors de la connexion. Cliquez pour supprimer le lien.", de: "Verknüpft: Symlink aktiv — dieser Mod wird beim Verbinden mit Mod-Servern geladen. Klicken um Symlink zu entfernen.", es: "Enlazado: enlace simbólico activo — este mod se carga al conectar a servidores con mods. Clic para eliminar el enlace.", ru: "Связан: симлинк активен — этот мод загружается при подключении к серверам с модами. Нажмите, чтобы удалить симлинк." }),
    unlinkedHint: t({ en: "Unlinked: no symlink — this mod is installed but won't be loaded. Click to create a symlink so it is included in server connections.", fr: "Non lié : pas de lien symbolique — ce mod ne sera pas chargé. Cliquez pour créer un lien.", de: "Nicht verknüpft: kein Symlink — dieser Mod ist installiert, wird aber nicht geladen. Klicken um Symlink zu erstellen.", es: "Sin enlace: sin enlace simbólico — este mod está instalado pero no se cargará. Clic para crear un enlace y que se incluya en las conexiones.", ru: "Не связан: нет симлинка — мод установлен, но не загружается. Нажмите, чтобы создать симлинк для использования при подключении." }),
    delete: t({ en: "Delete mod", fr: "Supprimer le mod", de: "Mod löschen", es: "Eliminar mod", ru: "Удалить мод" }),
    installModalTitle: t({ en: "Install Mod", fr: "Installer un mod", de: "Mod installieren", es: "Instalar mod", ru: "Установка мода" }),
    installModalDesc: t({ en: "Download via Steam Workshop ID or URL", fr: "Télécharger via ID ou URL Steam Workshop", de: "Per Steam Workshop-ID oder URL herunterladen", es: "Descargar vía Steam Workshop ID o URL", ru: "Скачать по Steam Workshop ID или URL" }),
    close: t({ en: "Close", fr: "Fermer", de: "Schließen", es: "Cerrar", ru: "Закрыть" }),
    workshopIdsLabel: t({ en: "Workshop IDs or URLs", fr: "IDs ou URLs Workshop", de: "Workshop-IDs oder URLs", es: "Workshop IDs o URLs", ru: "Workshop ID или URL" }),
    workshopIdsHint: t({ en: "one per line, or comma-separated", fr: "un par ligne, ou séparés par des virgules", de: "eine pro Zeile oder kommagetrennt", es: "uno por línea, o separados por comas", ru: "по одному на строку или через запятую" }),
    noValidIds: t({ en: "No valid Workshop IDs found.", fr: "Aucun ID Workshop valide trouvé.", de: "Keine gültigen Workshop-IDs gefunden.", es: "No se encontraron Workshop IDs válidos.", ru: "Не найдено допустимых Workshop ID." }),
    queued: insert(t({ en: "{{count}} mods queued", fr: "{{count}} mods en file d'attente", de: "{{count}} Mods in Warteschlange", es: "{{count}} mods en cola", ru: "{{count}} модов в очереди" })),
    queuedOne: insert(t({ en: "{{count}} mod queued", fr: "{{count}} mod en file d'attente", de: "{{count}} Mod in Warteschlange", es: "{{count}} mod en cola", ru: "{{count}} мод в очереди" })),
    noValidDetected: t({ en: "No valid IDs detected.", fr: "Aucun ID valide détecté.", de: "Keine gültigen IDs erkannt.", es: "No se detectaron IDs válidos.", ru: "Не обнаружено допустимых ID." }),
    cancel: t({ en: "Cancel", fr: "Annuler", de: "Abbrechen", es: "Cancelar", ru: "Отмена" }),
    installMods: insert(t({ en: "Install {{count}} mods", fr: "Installer {{count}} mods", de: "{{count}} Mods installieren", es: "Instalar {{count}} mods", ru: "Установить {{count}} модов" })),
    installMod: t({ en: "Install mod", fr: "Installer le mod", de: "Mod installieren", es: "Instalar mod", ru: "Установить мод" }),
    selected: insert(t({ en: "{{count}} mods selected", fr: "{{count}} mods sélectionnés", de: "{{count}} Mods ausgewählt", es: "{{count}} mods seleccionados", ru: "{{count}} модов выбрано" })),
    selectedOne: insert(t({ en: "{{count}} mod selected", fr: "{{count}} mod sélectionné", de: "{{count}} Mod ausgewählt", es: "{{count}} mod seleccionado", ru: "{{count}} мод выбран" })),
    selectAllUpdates: t({ en: "Select all with updates", fr: "Sélectionner tous avec MAJ", de: "Alle mit Updates auswählen", es: "Seleccionar todos con actualizaciones", ru: "Выбрать все с обновлениями" }),
    selectAllUpdatesTitle: t({ en: "Select all mods that have available updates", fr: "Sélectionner tous les mods avec des mises à jour disponibles", de: "Alle Mods mit verfügbaren Updates auswählen", es: "Seleccionar todos los mods con actualizaciones disponibles", ru: "Выбрать все моды с доступными обновлениями" }),
    updateStale: insert(t({ en: "Update {{count}} stale", fr: "MAJ {{count}} obsolètes", de: "{{count}} veraltete aktualisieren", es: "Actualizar {{count}} obsoletos", ru: "Обновить {{count}} устаревших" })),
    updateStaleTitle: insert(t({ en: "Update {{count}} selected mods with available updates", fr: "Mettre à jour les {{count}} mods sélectionnés avec des MAJ", de: "{{count}} ausgewählte Mods mit verfügbaren Updates aktualisieren", es: "Actualizar {{count}} mods seleccionados con actualizaciones disponibles", ru: "Обновить {{count}} выбранных модов с доступными обновлениями" })),
    revalidateCount: insert(t({ en: "Re-validate {{count}}", fr: "Re-valider {{count}}", de: "{{count}} neu validieren", es: "Revalidar {{count}}", ru: "Переустановить {{count}}" })),
    revalidateTitle: insert(t({ en: "Force re-validate {{count}} selected mods via steamcmd", fr: "Forcer la re-validation de {{count}} mods via steamcmd", de: "{{count}} ausgewählte Mods per steamcmd neu validieren", es: "Forzar revalidación de {{count}} mods seleccionados vía steamcmd", ru: "Принудительная переустановка {{count}} выбранных модов через steamcmd" })),
    link: insert(t({ en: "Link {{count}}", fr: "Lier {{count}}", de: "{{count}} verknüpfen", es: "Enlazar {{count}}", ru: "Связать {{count}}" })),
    linkTitle: insert(t({ en: "Link {{count}} mods — create symlinks so they are loaded when connecting to servers", fr: "Lier {{count}} mods — créer des liens symboliques", de: "{{count}} Mods verknüpfen — Symlinks erstellen damit sie bei Serververbindungen geladen werden", es: "Enlazar {{count}} mods — crear enlaces simbólicos para que se carguen al conectar a servidores", ru: "Связать {{count}} модов — создать симлинки для загрузки при подключении к серверам" })),
    unlink: insert(t({ en: "Unlink {{count}}", fr: "Délier {{count}}", de: "{{count}} trennen", es: "Desenlazar {{count}}", ru: "Отвязать {{count}}" })),
    unlinkTitle: insert(t({ en: "Unlink {{count}} mods — remove symlinks so they won't be loaded", fr: "Délier {{count}} mods — supprimer les liens symboliques", de: "{{count}} Mods trennen — Symlinks entfernen damit sie nicht geladen werden", es: "Desenlazar {{count}} mods — eliminar enlaces simbólicos para que no se carguen", ru: "Отвязать {{count}} модов — удалить симлинки, чтобы они не загружались" })),
    deleteCount: insert(t({ en: "Delete {{count}}", fr: "Supprimer {{count}}", de: "{{count}} löschen", es: "Eliminar {{count}}", ru: "Удалить {{count}}" })),
    deleteTitle: insert(t({ en: "Delete {{count}} selected mods", fr: "Supprimer {{count}} mods sélectionnés", de: "{{count}} ausgewählte Mods löschen", es: "Eliminar {{count}} mods seleccionados", ru: "Удалить {{count}} выбранных модов" })),
    clearSelection: t({ en: "Clear", fr: "Effacer", de: "Leeren", es: "Limpiar", ru: "Очистить" }),
    clearSelectionTitle: t({ en: "Clear selection", fr: "Effacer la sélection", de: "Auswahl aufheben", es: "Limpiar selección", ru: "Снять выделение" }),
    confirmTitleUpdate: insert(t({ en: "Update {{count}} mods", fr: "Mettre à jour {{count}} mods", de: "{{count}} Mods aktualisieren", es: "Actualizar {{count}} mods", ru: "Обновить {{count}} модов" })),
    confirmTitleInstall: insert(t({ en: "Install {{count}} mods", fr: "Installer {{count}} mods", de: "{{count}} Mods installieren", es: "Instalar {{count}} mods", ru: "Установить {{count}} модов" })),
    confirmLocalDate: t({ en: "Local", fr: "Local", de: "Lokal", es: "Local", ru: "Локально" }),
    confirmRemoteDate: t({ en: "Remote", fr: "Distant", de: "Remote", es: "Remoto", ru: "Удалённо" }),
    confirmNewer: insert(t({ en: "{{days}} days newer", fr: "{{days}} jours plus récent", de: "{{days}} Tage neuer", es: "{{days}} días más nuevo", ru: "на {{days}} дней новее" })),
    confirmWarning: t({ en: "Steam will be closed during this operation", fr: "Steam sera fermé pendant cette opération", de: "Steam wird während dieses Vorgangs geschlossen", es: "Steam se cerrará durante esta operación", ru: "Steam будет закрыт во время этой операции" }),
    confirmUpdate: insert(t({ en: "Update {{count}} mods", fr: "Mettre à jour {{count}} mods", de: "{{count}} Mods aktualisieren", es: "Actualizar {{count}} mods", ru: "Обновить {{count}} модов" })),
    confirmInstall: insert(t({ en: "Install {{count}} mods", fr: "Installer {{count}} mods", de: "{{count}} Mods installieren", es: "Instalar {{count}} mods", ru: "Установить {{count}} модов" })),
    confirmCancel: t({ en: "Cancel", fr: "Annuler", de: "Abbrechen", es: "Cancelar", ru: "Отмена" }),
    confirmOpenWorkshop: t({ en: "Open Steam Workshop page", fr: "Ouvrir la page Steam Workshop", de: "Steam Workshop-Seite öffnen", es: "Abrir página de Steam Workshop", ru: "Открыть страницу Steam Workshop" }),
    loadFailed: insert(t({ en: "Failed to load mods: {{error}}", fr: "Échec du chargement des mods : {{error}}", de: "Fehler beim Laden der Mods: {{error}}", es: "Error al cargar mods: {{error}}", ru: "Не удалось загрузить моды: {{error}}" })),
    updateCheckFailed: insert(t({ en: "Update check failed: {{error}}", fr: "Échec de la vérification des mises à jour : {{error}}", de: "Update-Prüfung fehlgeschlagen: {{error}}", es: "Error en comprobación de actualizaciones: {{error}}", ru: "Ошибка проверки обновлений: {{error}}" })),
    deleteSingleTitle: t({ en: "Delete Mod", fr: "Supprimer le mod", de: "Mod löschen", es: "Eliminar mod", ru: "Удаление мода" }),
    deleteSingleMessage: insert(t({ en: "Delete '{{name}}' ({{id}})?\nSize: {{size}}", fr: "Supprimer '{{name}}' ({{id}}) ?\nTaille : {{size}}", de: "'{{name}}' ({{id}}) löschen?\nGröße: {{size}}", es: "¿Eliminar '{{name}}' ({{id}})?\nTamaño: {{size}}", ru: "Удалить '{{name}}' ({{id}})?\nРазмер: {{size}}" })),
    deletedSingle: insert(t({ en: "Deleted {{name}}", fr: "{{name}} supprimé", de: "{{name}} gelöscht", es: "Eliminado {{name}}", ru: "Удалён {{name}}" })),
    linked: insert(t({ en: "{{name}} linked (symlink created)", fr: "{{name}} lié (symlink créé)", de: "{{name}} verknüpft (Symlink erstellt)", es: "{{name}} enlazado (enlace simbólico creado)", ru: "{{name}} связан (симлинк создан)" })),
    unlinked: insert(t({ en: "{{name}} unlinked (symlink removed)", fr: "{{name}} délié (symlink supprimé)", de: "{{name}} nicht verknüpft (Symlink entfernt)", es: "{{name}} desenlazado (enlace simbólico eliminado)", ru: "{{name}} отвязан (симлинк удалён)" })),
    toggleFailed: insert(t({ en: "Failed: {{error}}", fr: "Échec : {{error}}", de: "Fehlgeschlagen: {{error}}", es: "Error: {{error}}", ru: "Ошибка: {{error}}" })),
    cleanupMessage: t({ en: "Remove all managed mods and symlinks?", fr: "Supprimer tous les mods gérés et les symlinks ?", de: "Alle verwalteten Mods und Symlinks entfernen?", es: "¿Eliminar todos los mods gestionados y enlaces simbólicos?", ru: "Удалить все управляемые моды и симлинки?" }),
    cleanupFailed: t({ en: "Cleanup failed", fr: "Échec du nettoyage", de: "Aufräumen fehlgeschlagen", es: "Error en limpieza", ru: "Ошибка очистки" }),
    deleteSelectedTitle: t({ en: "Delete Mods", fr: "Supprimer les mods", de: "Mods löschen", es: "Eliminar mods", ru: "Удаление модов" }),
    deleteSelectedMessage: insert(t({ en: "Delete {{count}} mod?\nTotal size: {{size}}", fr: "Supprimer {{count}} mod ?\nTaille totale : {{size}}", de: "{{count}} Mod löschen?\nGesamtgröße: {{size}}", es: "¿Eliminar {{count}} mod?\nTamaño total: {{size}}", ru: "Удалить {{count}} мод?\nОбщий размер: {{size}}" })),
    deleteSelectedMessagePlural: insert(t({ en: "Delete {{count}} mods?\nTotal size: {{size}}", fr: "Supprimer {{count}} mods ?\nTaille totale : {{size}}", de: "{{count}} Mods löschen?\nGesamtgröße: {{size}}", es: "¿Eliminar {{count}} mods?\nTamaño total: {{size}}", ru: "Удалить {{count}} модов?\nОбщий размер: {{size}}" })),
    deletedSelected: insert(t({ en: "Deleted {{count}} mod", fr: "{{count}} mod supprimé", de: "{{count}} Mod gelöscht", es: "Eliminado {{count}} mod", ru: "Удалён {{count}} мод" })),
    deletedSelectedPlural: insert(t({ en: "Deleted {{count}} mods", fr: "{{count}} mods supprimés", de: "{{count}} Mods gelöscht", es: "Eliminados {{count}} mods", ru: "Удалено {{count}} модов" })),
    deleteFailed: t({ en: "Delete failed", fr: "Échec de la suppression", de: "Löschen fehlgeschlagen", es: "Error al eliminar", ru: "Ошибка удаления" }),
    deleteButton: insert(t({ en: "Delete {{count}}", fr: "Supprimer {{count}}", de: "{{count}} löschen", es: "Eliminar {{count}}", ru: "Удалить {{count}}" })),
    preparing: t({ en: "Preparing…", fr: "Préparation…", de: "Vorbereitung…", es: "Preparando…", ru: "Подготовка…" }),
    closingSteam: t({ en: "Closing Steam…", fr: "Fermeture de Steam…", de: "Steam wird geschlossen…", es: "Cerrando Steam…", ru: "Закрытие Steam…" }),
    updatedSuccessfully: insert(t({ en: "Mods: {{count}} updated successfully", fr: "Mods : {{count}} mis à jour avec succès", de: "Mods: {{count}} erfolgreich aktualisiert", es: "Mods: {{count}} actualizados correctamente", ru: "Моды: {{count}} успешно обновлено" })),
    updateResults: insert(t({ en: "Mods: {{ok}} OK, {{failed}} failed", fr: "Mods : {{ok}} OK, {{failed}} échoué(s)", de: "Mods: {{ok}} OK, {{failed}} fehlgeschlagen", es: "Mods: {{ok}} OK, {{failed}} fallidos", ru: "Моды: {{ok}} OK, {{failed}} с ошибками" })),
    operationFailed: insert(t({ en: "Mod operation failed: {{error}}", fr: "Échec de l'opération mod : {{error}}", de: "Mod-Operation fehlgeschlagen: {{error}}", es: "Error en operación de mods: {{error}}", ru: "Ошибка операции с модами: {{error}}" })),
    passwordSendFailed: insert(t({ en: "Failed to send password: {{error}}", fr: "Échec de l'envoi du mot de passe : {{error}}", de: "Fehler beim Senden des Passworts: {{error}}", es: "Error al enviar contraseña: {{error}}", ru: "Не удалось отправить пароль: {{error}}" })),
    upToDate: t({ en: "All mods are up to date", fr: "Tous les mods sont à jour", de: "Alle Mods sind aktuell", es: "Todos los mods están actualizados", ru: "Все моды актуальны" }),
    installAria: t({ en: "Install mod", fr: "Installer le mod", de: "Mod installieren", es: "Instalar mod", ru: "Установить мод" }),
  },
} satisfies Dictionary;

export default content;
