import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "mods",
  content: {
    closeDetail: t({
      en: "Close the details",
      fr: "Fermer le détail",
      de: "Details schließen",
      es: "Cerrar el detalle",
      ru: "Закрыть подробности",
    }),
    // ── the new view ──
    title: t({ en: "Mods", fr: "Mods", de: "Mods", es: "Mods", ru: "Моды" }),
    searchPlaceholder: t({
      en: "Search name or Workshop ID…",
      fr: "Rechercher un nom ou un ID Workshop…",
      de: "Name oder Workshop-ID suchen…",
      es: "Buscar nombre o ID de Workshop…",
      ru: "Поиск по имени или ID Workshop…",
    }),
    filterAll: t({ en: "All", fr: "Tous", de: "Alle", es: "Todos", ru: "Все" }),
    filterUpdates: t({
      en: "Updates",
      fr: "Mises à jour",
      de: "Updates",
      es: "Actualizaciones",
      ru: "Обновления",
    }),
    filterUnmanaged: t({
      en: "Unlinked",
      fr: "Non liés",
      de: "Nicht verknüpft",
      es: "Sin enlazar",
      ru: "Не связаны",
    }),
    filterLabel: t({ en: "Show", fr: "Afficher", de: "Anzeigen", es: "Mostrar", ru: "Показать" }),
    statInstalled: t({
      en: "Installed",
      fr: "Installés",
      de: "Installiert",
      es: "Instalados",
      ru: "Установлено",
    }),
    statSize: t({
      en: "On disk",
      fr: "Sur le disque",
      de: "Auf der Festplatte",
      es: "En disco",
      ru: "На диске",
    }),
    statChecked: t({
      en: "Last checked",
      fr: "Dernière vérification",
      de: "Zuletzt geprüft",
      es: "Última comprobación",
      ru: "Последняя проверка",
    }),
    neverChecked: t({ en: "never", fr: "jamais", de: "nie", es: "nunca", ru: "никогда" }),
    apiKeyMissingTitle: t({
      en: "Update checks are off",
      fr: "La vérification des mises à jour est désactivée",
      de: "Update-Prüfung ist aus",
      es: "La comprobación de actualizaciones está desactivada",
      ru: "Проверка обновлений отключена",
    }),
    apiKeyMissingBody: t({
      en: "Add a Steam Web API key to see which mods are behind the Workshop.",
      fr: "Ajoutez une clé Steam Web API pour voir quels mods sont en retard sur le Workshop.",
      de: "Füge einen Steam-Web-API-Schlüssel hinzu, um zu sehen, welche Mods hinter dem Workshop liegen.",
      es: "Añade una clave de Steam Web API para ver qué mods están por detrás del Workshop.",
      ru: "Добавьте ключ Steam Web API, чтобы видеть, какие моды отстают от Workshop.",
    }),
    openSettings: t({
      en: "Add a key",
      fr: "Ajouter une clé",
      de: "Schlüssel hinzufügen",
      es: "Añadir una clave",
      ru: "Добавить ключ",
    }),
    daysBehind: insert(
      t({
        en: "{{days}} d behind",
        fr: "{{days}} j de retard",
        de: "{{days}} T zurück",
        es: "{{days}} d de retraso",
        ru: "отстаёт на {{days}} д",
      }),
    ),
    behindToday: t({
      en: "behind",
      fr: "en retard",
      de: "veraltet",
      es: "desactualizado",
      ru: "устарел",
    }),
    noMatch: t({
      en: "No mod matches these filters.",
      fr: "Aucun mod ne correspond à ces filtres.",
      de: "Kein Mod passt zu diesen Filtern.",
      es: "Ningún mod coincide con estos filtros.",
      ru: "Нет модов, подходящих под фильтры.",
    }),
    clearFilters: t({
      en: "Clear filters",
      fr: "Effacer les filtres",
      de: "Filter zurücksetzen",
      es: "Borrar filtros",
      ru: "Сбросить фильтры",
    }),
    moreActions: t({
      en: "More actions",
      fr: "Plus d'actions",
      de: "Weitere Aktionen",
      es: "Más acciones",
      ru: "Другие действия",
    }),
    cleanup: t({
      en: "Delete the launcher's downloads and game links",
      fr: "Supprimer les téléchargements du lanceur et les liens du jeu",
      de: "Downloads des Launchers und Spiel-Verknüpfungen löschen",
      es: "Eliminar las descargas del lanzador y los enlaces del juego",
      ru: "Удалить загрузки лаунчера и ссылки в игре",
    }),
    update: t({
      en: "Update",
      fr: "Mettre à jour",
      de: "Aktualisieren",
      es: "Actualizar",
      ru: "Обновить",
    }),
    openModFolder: t({
      en: "Open its folder",
      fr: "Ouvrir son dossier",
      de: "Ordner öffnen",
      es: "Abrir su carpeta",
      ru: "Открыть папку",
    }),
    detailsStatus: t({ en: "Status", fr: "État", de: "Status", es: "Estado", ru: "Статус" }),
    detailsLink: t({
      en: "Loaded in game",
      fr: "Chargé en jeu",
      de: "Im Spiel geladen",
      es: "Cargado en el juego",
      ru: "Загружается в игре",
    }),
    detailsLinkHint: t({
      en: "A link in the game folder makes DayZ load this mod. Joining a server that uses it creates the link, so leaving it off is fine.",
      fr: "Un lien dans le dossier du jeu permet à DayZ de charger ce mod. Rejoindre un serveur qui l'utilise crée le lien : le laisser désactivé ne pose pas de problème.",
      de: "Ein Link im Spielordner lässt DayZ diesen Mod laden. Beim Beitritt zu einem Server, der ihn nutzt, wird er angelegt: aus zu lassen ist unbedenklich.",
      es: "Un enlace en la carpeta del juego hace que DayZ cargue este mod. Unirse a un servidor que lo usa crea el enlace, así que dejarlo desactivado no es un problema.",
      ru: "Ссылка в папке игры позволяет DayZ загружать этот мод. Подключение к серверу, который его использует, создаёт ссылку, так что её отсутствие не проблема.",
    }),
    detailsUpToDate: t({
      en: "Up to date",
      fr: "À jour",
      de: "Aktuell",
      es: "Al día",
      ru: "Актуален",
    }),
    detailsUnknown: t({
      en: "Not checked",
      fr: "Non vérifié",
      de: "Nicht geprüft",
      es: "Sin comprobar",
      ru: "Не проверен",
    }),
    detailsShare: t({
      en: "Share of all mods",
      fr: "Part de tous les mods",
      de: "Anteil aller Mods",
      es: "Parte del total",
      ru: "Доля от всех модов",
    }),
    detailsLaunchParam: t({
      en: "Launch parameter",
      fr: "Paramètre de lancement",
      de: "Startparameter",
      es: "Parámetro de inicio",
      ru: "Параметр запуска",
    }),
    bulkUpdate: insert(
      t({
        en: "Update {{count}}",
        fr: "Mettre à jour {{count}}",
        de: "{{count}} aktualisieren",
        es: "Actualizar {{count}}",
        ru: "Обновить {{count}}",
      }),
    ),
    reviewUpdateAll: t({
      en: "Re-validate every mod",
      fr: "Revalider tous les mods",
      de: "Alle Mods neu prüfen",
      es: "Revalidar todos los mods",
      ru: "Перепроверить все моды",
    }),
    reviewSize: insert(
      t({
        en: "{{size}} to check",
        fr: "{{size}} à vérifier",
        de: "{{size}} zu prüfen",
        es: "{{size}} por comprobar",
        ru: "{{size}} к проверке",
      }),
    ),
    reviewUnknownSize: t({
      en: "Size known after download",
      fr: "Taille connue après le téléchargement",
      de: "Größe nach dem Download bekannt",
      es: "Tamaño conocido tras la descarga",
      ru: "Размер станет известен после загрузки",
    }),
    installParsed: insert(
      t({
        en: "{{count}} IDs found",
        fr: "{{count}} ID trouvés",
        de: "{{count}} IDs gefunden",
        es: "{{count}} ID encontrados",
        ru: "Найдено ID: {{count}}",
      }),
    ),
    installAlready: t({
      en: "already installed",
      fr: "déjà installé",
      de: "bereits installiert",
      es: "ya instalado",
      ru: "уже установлен",
    }),
    count: insert(
      t({
        en: "{{count}} mods",
        fr: "{{count}} mods",
        de: "{{count}} Mods",
        es: "{{count}} mods",
        ru: "{{count}} модов",
      }),
    ),
    countOne: insert(
      t({
        en: "{{count}} mod",
        fr: "{{count}} mod",
        de: "{{count}} Mod",
        es: "{{count}} mod",
        ru: "{{count}} мод",
      }),
    ),
    updatesAvailable: insert(
      t({
        en: "{{count}} updates available",
        fr: "{{count}} mises à jour disponibles",
        de: "{{count}} Updates verfügbar",
        es: "{{count}} actualizaciones disponibles",
        ru: "{{count}} обновлений доступно",
      }),
    ),
    updateAvailableOne: insert(
      t({
        en: "{{count}} update available",
        fr: "{{count}} mise à jour disponible",
        de: "{{count}} Update verfügbar",
        es: "{{count}} actualización disponible",
        ru: "{{count}} обновление доступно",
      }),
    ),
    allUpToDate: t({
      en: "All up to date",
      fr: "Tout est à jour",
      de: "Alle aktuell",
      es: "Todo actualizado",
      ru: "Все моды актуальны",
    }),
    install: t({
      en: "Install mod",
      fr: "Installer un mod",
      de: "Mod installieren",
      es: "Instalar mod",
      ru: "Установить мод",
    }),
    installTitle: t({
      en: "Install a mod manually by Workshop ID or URL",
      fr: "Installer un mod manuellement par ID Workshop ou URL",
      de: "Mod manuell per Workshop-ID oder URL installieren",
      es: "Instalar un mod manualmente por Workshop ID o URL",
      ru: "Установить мод вручную по Workshop ID или URL",
    }),
    openFolder: t({
      en: "Open folder",
      fr: "Ouvrir le dossier",
      de: "Ordner öffnen",
      es: "Abrir carpeta",
      ru: "Открыть папку",
    }),
    openFolderTitle: t({
      en: "Open Workshop mods directory in file manager",
      fr: "Ouvrir le dossier des mods Workshop",
      de: "Workshop-Mods-Verzeichnis im Dateimanager öffnen",
      es: "Abrir carpeta de mods del Workshop en el gestor de archivos",
      ru: "Открыть папку модов Workshop в файловом менеджере",
    }),
    checking: t({
      en: "Checking…",
      fr: "Vérification…",
      de: "Prüfe…",
      es: "Comprobando…",
      ru: "Проверка…",
    }),
    checkUpdates: t({
      en: "Check updates",
      fr: "Vérifier les MAJ",
      de: "Updates prüfen",
      es: "Comprobar actualizaciones",
      ru: "Проверить обновления",
    }),
    checkUpdatesTitle: t({
      en: "Check Steam Workshop for updates",
      fr: "Vérifier les mises à jour sur Steam Workshop",
      de: "Steam Workshop auf Updates prüfen",
      es: "Comprobar actualizaciones en Steam Workshop",
      ru: "Проверить обновления в Steam Workshop",
    }),
    updateCount: insert(
      t({
        en: "Update {{count}}",
        fr: "Mettre à jour {{count}}",
        de: "{{count}} aktualisieren",
        es: "Actualizar {{count}}",
        ru: "Обновить {{count}}",
      }),
    ),
    updateCountTitle: insert(
      t({
        en: "Update only the {{count}} mods with available updates",
        fr: "Mettre à jour les {{count}} mods avec des MAJ disponibles",
        de: "Nur die {{count}} Mods mit verfügbaren Updates aktualisieren",
        es: "Actualizar solo los {{count}} mods con actualizaciones disponibles",
        ru: "Обновить только {{count}} модов с доступными обновлениями",
      }),
    ),
    all: t({ en: "All", fr: "Tous", de: "Alle", es: "Todos", ru: "Все" }),
    updateAll: t({
      en: "Update all",
      fr: "Tout mettre à jour",
      de: "Alle aktualisieren",
      es: "Actualizar todos",
      ru: "Обновить все",
    }),
    refreshTitle: t({
      en: "Refresh mod list",
      fr: "Actualiser la liste des mods",
      de: "Mod-Liste aktualisieren",
      es: "Actualizar lista de mods",
      ru: "Обновить список модов",
    }),
    cleanupTitle: t({
      en: "Remove all managed mods and symlinks",
      fr: "Supprimer tous les mods gérés et les liens symboliques",
      de: "Alle verwalteten Mods und Symlinks entfernen",
      es: "Eliminar todos los mods gestionados y enlaces simbólicos",
      ru: "Удалить все управляемые моды и симлинки",
    }),
    loading: t({
      en: "Loading mods…",
      fr: "Chargement des mods…",
      de: "Lade Mods…",
      es: "Cargando mods…",
      ru: "Загрузка модов…",
    }),
    noMods: t({
      en: "No mods installed",
      fr: "Aucun mod installé",
      de: "Keine Mods installiert",
      es: "No hay mods instalados",
      ru: "Моды не установлены",
    }),
    noModsHint: t({
      en: "Connect to a modded server to install mods",
      fr: "Connectez-vous à un serveur moddé pour installer des mods",
      de: "Mit einem Server mit Mods verbinden um Mods zu installieren",
      es: "Conéctate a un servidor con mods para instalarlos",
      ru: "Подключитесь к серверу с модами для их установки",
    }),
    selectAll: t({
      en: "Select all",
      fr: "Tout sélectionner",
      de: "Alle auswählen",
      es: "Seleccionar todos",
      ru: "Выбрать все",
    }),
    deselectAll: t({
      en: "Deselect all",
      fr: "Tout désélectionner",
      de: "Auswahl aufheben",
      es: "Deseleccionar todos",
      ru: "Снять выделение",
    }),
    colName: t({ en: "Name", fr: "Nom", de: "Name", es: "Nombre", ru: "Название" }),
    colWorkshopId: t({
      en: "Workshop ID",
      fr: "ID Workshop",
      de: "Workshop-ID",
      es: "Workshop ID",
      ru: "Workshop ID",
    }),
    colSize: t({ en: "Size", fr: "Taille", de: "Größe", es: "Tamaño", ru: "Размер" }),
    colStatus: t({ en: "Status", fr: "Statut", de: "Status", es: "Estado", ru: "Статус" }),
    updateAvailable: t({
      en: "Update available",
      fr: "Mise à jour disponible",
      de: "Update verfügbar",
      es: "Actualización disponible",
      ru: "Доступно обновление",
    }),
    managed: t({ en: "Managed", fr: "Géré", de: "Verwaltet", es: "Gestionado", ru: "Управляемый" }),
    copyName: t({
      en: "Copy mod name",
      fr: "Copier le nom du mod",
      de: "Mod-Name kopieren",
      es: "Copiar nombre del mod",
      ru: "Скопировать название мода",
    }),
    copied: t({
      en: "Copied!",
      fr: "Copié !",
      de: "Kopiert!",
      es: "¡Copiado!",
      ru: "Скопировано!",
    }),
    openWorkshop: t({
      en: "Open on Steam Workshop",
      fr: "Ouvrir sur Steam Workshop",
      de: "Im Steam Workshop öffnen",
      es: "Abrir en Steam Workshop",
      ru: "Открыть в Steam Workshop",
    }),
    statusUpdate: t({ en: "UPDATE", fr: "MAJ", de: "UPDATE", es: "ACTUALIZAR", ru: "ОБНОВИТЬ" }),
    updating: t({
      en: "Updating…",
      fr: "Mise à jour…",
      de: "Aktualisiere…",
      es: "Actualizando…",
      ru: "Обновление…",
    }),
    delete: t({
      en: "Delete mod",
      fr: "Supprimer le mod",
      de: "Mod löschen",
      es: "Eliminar mod",
      ru: "Удалить мод",
    }),
    installModalTitle: t({
      en: "Install Mod",
      fr: "Installer un mod",
      de: "Mod installieren",
      es: "Instalar mod",
      ru: "Установка мода",
    }),
    installModalDesc: t({
      en: "Download via Steam Workshop ID or URL",
      fr: "Télécharger via ID ou URL Steam Workshop",
      de: "Per Steam Workshop-ID oder URL herunterladen",
      es: "Descargar vía Steam Workshop ID o URL",
      ru: "Скачать по Steam Workshop ID или URL",
    }),
    close: t({ en: "Close", fr: "Fermer", de: "Schließen", es: "Cerrar", ru: "Закрыть" }),
    workshopIdsLabel: t({
      en: "Workshop IDs or URLs",
      fr: "IDs ou URLs Workshop",
      de: "Workshop-IDs oder URLs",
      es: "Workshop IDs o URLs",
      ru: "Workshop ID или URL",
    }),
    workshopIdsHint: t({
      en: "one per line, or comma-separated",
      fr: "un par ligne, ou séparés par des virgules",
      de: "eine pro Zeile oder kommagetrennt",
      es: "uno por línea, o separados por comas",
      ru: "по одному на строку или через запятую",
    }),
    noValidIds: t({
      en: "No valid Workshop IDs found.",
      fr: "Aucun ID Workshop valide trouvé.",
      de: "Keine gültigen Workshop-IDs gefunden.",
      es: "No se encontraron Workshop IDs válidos.",
      ru: "Не найдено допустимых Workshop ID.",
    }),
    queued: insert(
      t({
        en: "{{count}} mods queued",
        fr: "{{count}} mods en file d'attente",
        de: "{{count}} Mods in Warteschlange",
        es: "{{count}} mods en cola",
        ru: "{{count}} модов в очереди",
      }),
    ),
    queuedOne: insert(
      t({
        en: "{{count}} mod queued",
        fr: "{{count}} mod en file d'attente",
        de: "{{count}} Mod in Warteschlange",
        es: "{{count}} mod en cola",
        ru: "{{count}} мод в очереди",
      }),
    ),
    noValidDetected: t({
      en: "No valid IDs detected.",
      fr: "Aucun ID valide détecté.",
      de: "Keine gültigen IDs erkannt.",
      es: "No se detectaron IDs válidos.",
      ru: "Не обнаружено допустимых ID.",
    }),
    cancel: t({ en: "Cancel", fr: "Annuler", de: "Abbrechen", es: "Cancelar", ru: "Отмена" }),
    installMods: insert(
      t({
        en: "Install {{count}} mods",
        fr: "Installer {{count}} mods",
        de: "{{count}} Mods installieren",
        es: "Instalar {{count}} mods",
        ru: "Установить {{count}} модов",
      }),
    ),
    installMod: t({
      en: "Install mod",
      fr: "Installer le mod",
      de: "Mod installieren",
      es: "Instalar mod",
      ru: "Установить мод",
    }),
    selected: insert(
      t({
        en: "{{count}} mods selected",
        fr: "{{count}} mods sélectionnés",
        de: "{{count}} Mods ausgewählt",
        es: "{{count}} mods seleccionados",
        ru: "{{count}} модов выбрано",
      }),
    ),
    selectedOne: insert(
      t({
        en: "{{count}} mod selected",
        fr: "{{count}} mod sélectionné",
        de: "{{count}} Mod ausgewählt",
        es: "{{count}} mod seleccionado",
        ru: "{{count}} мод выбран",
      }),
    ),
    selectAllUpdates: t({
      en: "Select all with updates",
      fr: "Sélectionner ceux à mettre à jour",
      de: "Alle mit Updates auswählen",
      es: "Seleccionar los que tienen actualización",
      ru: "Выбрать все с обновлениями",
    }),
    selectAllUpdatesTitle: t({
      en: "Select all mods that have available updates",
      fr: "Sélectionner tous les mods avec des mises à jour disponibles",
      de: "Alle Mods mit verfügbaren Updates auswählen",
      es: "Seleccionar todos los mods con actualizaciones disponibles",
      ru: "Выбрать все моды с доступными обновлениями",
    }),
    updateStale: insert(
      t({
        en: "Update {{count}}",
        fr: "Mettre à jour {{count}}",
        de: "{{count}} aktualisieren",
        es: "Actualizar {{count}}",
        ru: "Обновить {{count}}",
      }),
    ),
    updateStaleTitle: insert(
      t({
        en: "Update {{count}} selected mods with available updates",
        fr: "Mettre à jour les {{count}} mods sélectionnés avec des MAJ",
        de: "{{count}} ausgewählte Mods mit verfügbaren Updates aktualisieren",
        es: "Actualizar {{count}} mods seleccionados con actualizaciones disponibles",
        ru: "Обновить {{count}} выбранных модов с доступными обновлениями",
      }),
    ),
    revalidateCount: insert(
      t({
        en: "Download {{count}} again",
        fr: "Retélécharger {{count}}",
        de: "{{count}} erneut laden",
        es: "Volver a descargar {{count}}",
        ru: "Скачать заново {{count}}",
      }),
    ),
    revalidateTitle: insert(
      t({
        en: "Download the {{count}} selected mods again, even those that are up to date",
        fr: "Retélécharger les {{count}} mods sélectionnés, même ceux qui sont à jour",
        de: "Die {{count}} ausgewählten Mods erneut laden, auch aktuelle",
        es: "Volver a descargar los {{count}} mods seleccionados, incluso los que están al día",
        ru: "Скачать заново {{count}} выбранных модов, даже актуальные",
      }),
    ),
    link: insert(
      t({
        en: "Link {{count}}",
        fr: "Lier {{count}}",
        de: "{{count}} verknüpfen",
        es: "Enlazar {{count}}",
        ru: "Связать {{count}}",
      }),
    ),
    linkTitle: insert(
      t({
        en: "Link {{count}} mods into the game folder",
        fr: "Lier {{count}} mods dans le dossier du jeu",
        de: "{{count}} Mods im Spielordner verknüpfen",
        es: "Enlazar {{count}} mods en la carpeta del juego",
        ru: "Связать {{count}} модов в папке игры",
      }),
    ),
    unlink: insert(
      t({
        en: "Unlink {{count}}",
        fr: "Retirer le lien de {{count}}",
        de: "{{count}} Verknüpfungen entfernen",
        es: "Quitar enlace de {{count}}",
        ru: "Отвязать {{count}}",
      }),
    ),
    unlinkTitle: insert(
      t({
        en: "Remove the game-folder link of {{count}} mods; joining a server that uses them links them again",
        fr: "Retirer le lien de {{count}} mods du dossier du jeu ; rejoindre un serveur qui les utilise les relie",
        de: "Die Verknüpfung von {{count}} Mods im Spielordner entfernen; beim Beitritt zu einem Server, der sie nutzt, werden sie neu verknüpft",
        es: "Quitar el enlace de {{count}} mods de la carpeta del juego; unirse a un servidor que los usa los vuelve a enlazar",
        ru: "Убрать ссылки {{count}} модов из папки игры; подключение к серверу, который их использует, создаст их снова",
      }),
    ),
    deleteCount: insert(
      t({
        en: "Delete {{count}}",
        fr: "Supprimer {{count}}",
        de: "{{count}} löschen",
        es: "Eliminar {{count}}",
        ru: "Удалить {{count}}",
      }),
    ),
    deleteTitle: insert(
      t({
        en: "Delete {{count}} selected mods",
        fr: "Supprimer {{count}} mods sélectionnés",
        de: "{{count}} ausgewählte Mods löschen",
        es: "Eliminar {{count}} mods seleccionados",
        ru: "Удалить {{count}} выбранных модов",
      }),
    ),
    clearSelectionTitle: t({
      en: "Clear selection",
      fr: "Effacer la sélection",
      de: "Auswahl aufheben",
      es: "Limpiar selección",
      ru: "Снять выделение",
    }),
    confirmTitleUpdate: insert(
      t({
        en: "Update {{count}} mods",
        fr: "Mettre à jour {{count}} mods",
        de: "{{count}} Mods aktualisieren",
        es: "Actualizar {{count}} mods",
        ru: "Обновить {{count}} модов",
      }),
    ),
    confirmTitleInstall: insert(
      t({
        en: "Install {{count}} mods",
        fr: "Installer {{count}} mods",
        de: "{{count}} Mods installieren",
        es: "Instalar {{count}} mods",
        ru: "Установить {{count}} модов",
      }),
    ),
    confirmLocalDate: t({ en: "Local", fr: "Local", de: "Lokal", es: "Local", ru: "Локально" }),
    confirmRemoteDate: t({
      en: "Remote",
      fr: "Distant",
      de: "Remote",
      es: "Remoto",
      ru: "Удалённо",
    }),
    confirmNewer: insert(
      t({
        en: "{{days}} days newer",
        fr: "{{days}} jours plus récent",
        de: "{{days}} Tage neuer",
        es: "{{days}} días más nuevo",
        ru: "на {{days}} дней новее",
      }),
    ),
    confirmWarning: t({
      en: "SteamCMD logs in with your account, which disconnects the Steam client: go back online in Steam afterwards. The Steam client mode in Settings avoids this.",
      fr: "SteamCMD se connecte avec votre compte, ce qui déconnecte le client Steam : repassez en ligne dans Steam ensuite. Le mode « Client Steam » des paramètres évite cela.",
      de: "SteamCMD meldet sich mit Ihrem Konto an, wodurch der Steam-Client getrennt wird: Gehen Sie danach in Steam wieder online. Der Modus „Steam-Client“ in den Einstellungen vermeidet das.",
      es: "SteamCMD inicia sesión con tu cuenta, lo que desconecta el cliente de Steam: vuelve a conectarte en Steam después. El modo «Cliente de Steam» de los ajustes lo evita.",
      ru: "SteamCMD входит в ваш аккаунт, из-за чего клиент Steam отключается: после этого снова выйдите в сеть в Steam. Режим «Клиент Steam» в настройках этого избегает.",
    }),
    confirmWarningSteam: t({
      en: "Steam downloads the mods and shows you as playing DayZ meanwhile. Launch the game once the download has finished.",
      fr: "Steam télécharge les mods et vous montre en train de jouer à DayZ pendant ce temps. Lancez le jeu une fois le téléchargement terminé.",
      de: "Steam lädt die Mods herunter und zeigt Sie währenddessen als DayZ spielend an. Starten Sie das Spiel, wenn der Download abgeschlossen ist.",
      es: "Steam descarga los mods y mientras tanto te muestra jugando a DayZ. Inicia el juego cuando termine la descarga.",
      ru: "Steam загружает моды и в это время показывает, что вы играете в DayZ. Запускайте игру после завершения загрузки.",
    }),
    confirmUpdate: insert(
      t({
        en: "Update {{count}} mods",
        fr: "Mettre à jour {{count}} mods",
        de: "{{count}} Mods aktualisieren",
        es: "Actualizar {{count}} mods",
        ru: "Обновить {{count}} модов",
      }),
    ),
    confirmInstall: insert(
      t({
        en: "Install {{count}} mods",
        fr: "Installer {{count}} mods",
        de: "{{count}} Mods installieren",
        es: "Instalar {{count}} mods",
        ru: "Установить {{count}} модов",
      }),
    ),
    confirmCancel: t({
      en: "Cancel",
      fr: "Annuler",
      de: "Abbrechen",
      es: "Cancelar",
      ru: "Отмена",
    }),
    confirmOpenWorkshop: t({
      en: "Open Steam Workshop page",
      fr: "Ouvrir la page Steam Workshop",
      de: "Steam Workshop-Seite öffnen",
      es: "Abrir página de Steam Workshop",
      ru: "Открыть страницу Steam Workshop",
    }),
    loadFailed: insert(
      t({
        en: "Failed to load mods: {{error}}",
        fr: "Échec du chargement des mods : {{error}}",
        de: "Fehler beim Laden der Mods: {{error}}",
        es: "Error al cargar mods: {{error}}",
        ru: "Не удалось загрузить моды: {{error}}",
      }),
    ),
    updateCheckFailed: insert(
      t({
        en: "Update check failed: {{error}}",
        fr: "Échec de la vérification des mises à jour : {{error}}",
        de: "Update-Prüfung fehlgeschlagen: {{error}}",
        es: "Error en comprobación de actualizaciones: {{error}}",
        ru: "Ошибка проверки обновлений: {{error}}",
      }),
    ),
    deleteSingleTitle: t({
      en: "Delete Mod",
      fr: "Supprimer le mod",
      de: "Mod löschen",
      es: "Eliminar mod",
      ru: "Удаление мода",
    }),
    deleteSingleMessage: insert(
      t({
        en: "Delete '{{name}}' ({{id}})?\nSize: {{size}}\nYour Steam account is unsubscribed from it.",
        fr: "Supprimer '{{name}}' ({{id}}) ?\nTaille : {{size}}\nVotre compte Steam s'en désabonne.",
        de: "'{{name}}' ({{id}}) löschen?\nGröße: {{size}}\nIhr Steam-Konto beendet das Abonnement.",
        es: "¿Eliminar '{{name}}' ({{id}})?\nTamaño: {{size}}\nTu cuenta de Steam cancela la suscripción.",
        ru: "Удалить '{{name}}' ({{id}})?\nРазмер: {{size}}\nВаш аккаунт Steam отпишется от него.",
      }),
    ),
    deletedSingle: insert(
      t({
        en: "Deleted {{name}}",
        fr: "{{name}} supprimé",
        de: "{{name}} gelöscht",
        es: "Eliminado {{name}}",
        ru: "Удалён {{name}}",
      }),
    ),
    linked: insert(
      t({
        en: "{{name}} linked (symlink created)",
        fr: "{{name}} lié (symlink créé)",
        de: "{{name}} verknüpft (Symlink erstellt)",
        es: "{{name}} enlazado (enlace simbólico creado)",
        ru: "{{name}} связан (симлинк создан)",
      }),
    ),
    unlinked: insert(
      t({
        en: "{{name}} unlinked (symlink removed)",
        fr: "{{name}} délié (symlink supprimé)",
        de: "{{name}} nicht verknüpft (Symlink entfernt)",
        es: "{{name}} desenlazado (enlace simbólico eliminado)",
        ru: "{{name}} отвязан (симлинк удалён)",
      }),
    ),
    toggleFailed: insert(
      t({
        en: "Failed: {{error}}",
        fr: "Échec : {{error}}",
        de: "Fehlgeschlagen: {{error}}",
        es: "Error: {{error}}",
        ru: "Ошибка: {{error}}",
      }),
    ),
    cleanupMessage: t({
      en: "Delete every mod the launcher downloaded and every link in the game folder? Mods in your Steam library stay.",
      fr: "Supprimer tous les mods téléchargés par le lanceur et tous les liens du dossier du jeu ? Les mods de votre bibliothèque Steam restent.",
      de: "Alle vom Launcher geladenen Mods und alle Verknüpfungen im Spielordner löschen? Mods in deiner Steam-Bibliothek bleiben.",
      es: "¿Eliminar todos los mods descargados por el lanzador y todos los enlaces de la carpeta del juego? Los mods de tu biblioteca de Steam se quedan.",
      ru: "Удалить все моды, скачанные лаунчером, и все ссылки в папке игры? Моды в библиотеке Steam останутся.",
    }),
    cleanupFailed: t({
      en: "Cleanup failed",
      fr: "Échec du nettoyage",
      de: "Aufräumen fehlgeschlagen",
      es: "Error en limpieza",
      ru: "Ошибка очистки",
    }),
    deleteSelectedTitle: t({
      en: "Delete Mods",
      fr: "Supprimer les mods",
      de: "Mods löschen",
      es: "Eliminar mods",
      ru: "Удаление модов",
    }),
    deleteSelectedMessage: insert(
      t({
        en: "Delete {{count}} mod?\nTotal size: {{size}}\nYour Steam account is unsubscribed from them.",
        fr: "Supprimer {{count}} mod ?\nTaille totale : {{size}}\nVotre compte Steam s'en désabonne.",
        de: "{{count}} Mod löschen?\nGesamtgröße: {{size}}\nIhr Steam-Konto beendet die Abonnements.",
        es: "¿Eliminar {{count}} mod?\nTamaño total: {{size}}\nTu cuenta de Steam cancela las suscripciones.",
        ru: "Удалить {{count}} мод?\nОбщий размер: {{size}}\nВаш аккаунт Steam отпишется от них.",
      }),
    ),
    deleteSelectedMessagePlural: insert(
      t({
        en: "Delete {{count}} mods?\nTotal size: {{size}}\nYour Steam account is unsubscribed from them.",
        fr: "Supprimer {{count}} mods ?\nTaille totale : {{size}}\nVotre compte Steam s'en désabonne.",
        de: "{{count}} Mods löschen?\nGesamtgröße: {{size}}\nIhr Steam-Konto beendet die Abonnements.",
        es: "¿Eliminar {{count}} mods?\nTamaño total: {{size}}\nTu cuenta de Steam cancela las suscripciones.",
        ru: "Удалить {{count}} модов?\nОбщий размер: {{size}}\nВаш аккаунт Steam отпишется от них.",
      }),
    ),
    deletedSelected: insert(
      t({
        en: "Deleted {{count}} mod",
        fr: "{{count}} mod supprimé",
        de: "{{count}} Mod gelöscht",
        es: "Eliminado {{count}} mod",
        ru: "Удалён {{count}} мод",
      }),
    ),
    deletedSelectedPlural: insert(
      t({
        en: "Deleted {{count}} mods",
        fr: "{{count}} mods supprimés",
        de: "{{count}} Mods gelöscht",
        es: "Eliminados {{count}} mods",
        ru: "Удалено {{count}} модов",
      }),
    ),
    deleteFailed: t({
      en: "Delete failed",
      fr: "Échec de la suppression",
      de: "Löschen fehlgeschlagen",
      es: "Error al eliminar",
      ru: "Ошибка удаления",
    }),
    deleteButton: insert(
      t({
        en: "Delete {{count}}",
        fr: "Supprimer {{count}}",
        de: "{{count}} löschen",
        es: "Eliminar {{count}}",
        ru: "Удалить {{count}}",
      }),
    ),
    preparing: t({
      en: "Preparing…",
      fr: "Préparation…",
      de: "Vorbereitung…",
      es: "Preparando…",
      ru: "Подготовка…",
    }),
    updatedSuccessfully: insert(
      t({
        en: "Mods: {{count}} updated successfully",
        fr: "Mods : {{count}} mis à jour avec succès",
        de: "Mods: {{count}} erfolgreich aktualisiert",
        es: "Mods: {{count}} actualizados correctamente",
        ru: "Моды: {{count}} успешно обновлено",
      }),
    ),
    updateResults: insert(
      t({
        en: "Mods: {{ok}} OK, {{failed}} failed",
        fr: "Mods : {{ok}} OK, {{failed}} échoué(s)",
        de: "Mods: {{ok}} OK, {{failed}} fehlgeschlagen",
        es: "Mods: {{ok}} OK, {{failed}} fallidos",
        ru: "Моды: {{ok}} OK, {{failed}} с ошибками",
      }),
    ),
    operationFailed: insert(
      t({
        en: "Mod operation failed: {{error}}",
        fr: "Échec de l'opération mod : {{error}}",
        de: "Mod-Operation fehlgeschlagen: {{error}}",
        es: "Error en operación de mods: {{error}}",
        ru: "Ошибка операции с модами: {{error}}",
      }),
    ),
    keptInSteam: insert(
      t({
        en: "{{name}} is unlinked, but its files stay in your Steam library: Steam could not unsubscribe from it (is Steam running and online?). Unsubscribe in Steam to remove them.",
        fr: "{{name}} n'est plus lié, mais ses fichiers restent dans votre bibliothèque Steam : Steam n'a pas pu s'en désabonner (Steam est-il lancé et en ligne ?). Désabonnez-vous dans Steam pour les retirer.",
        de: "{{name}} ist nicht mehr verknüpft, aber die Dateien bleiben in Ihrer Steam-Bibliothek: Steam konnte das Abonnement nicht beenden (läuft Steam und ist online?). Beenden Sie das Abonnement in Steam, um sie zu entfernen.",
        es: "{{name}} ya no está vinculado, pero sus archivos siguen en tu biblioteca de Steam: Steam no pudo cancelar la suscripción (¿Steam está abierto y en línea?). Cancélala en Steam para quitarlos.",
        ru: "{{name}} отвязан, но его файлы остаются в вашей библиотеке Steam: Steam не смог отписаться (Steam запущен и в сети?). Отпишитесь в Steam, чтобы удалить их.",
      }),
    ),
    keptInSteamMany: insert(
      t({
        en: "{{count}} of them stay in your Steam library: Steam could not unsubscribe from them (is Steam running and online?). Unsubscribe in Steam to remove their files.",
        fr: "{{count}} d'entre eux restent dans votre bibliothèque Steam : Steam n'a pas pu s'en désabonner (Steam est-il lancé et en ligne ?). Désabonnez-vous dans Steam pour retirer leurs fichiers.",
        de: "{{count}} davon bleiben in Ihrer Steam-Bibliothek: Steam konnte die Abonnements nicht beenden (läuft Steam und ist online?). Beenden Sie sie in Steam, um die Dateien zu entfernen.",
        es: "{{count}} siguen en tu biblioteca de Steam: Steam no pudo cancelar las suscripciones (¿Steam está abierto y en línea?). Cancélalas en Steam para quitar sus archivos.",
        ru: "{{count}} из них остаются в вашей библиотеке Steam: Steam не смог отписаться (Steam запущен и в сети?). Отпишитесь в Steam, чтобы удалить файлы.",
      }),
    ),
    sourceLauncher: t({
      en: "Launcher",
      fr: "Lanceur",
      de: "Launcher",
      es: "Lanzador",
      ru: "Лаунчер",
    }),
    sourceSteam: t({ en: "Steam", fr: "Steam", de: "Steam", es: "Steam", ru: "Steam" }),
    sourceLauncherHint: t({
      en: "Downloaded by the launcher's SteamCMD, into its own folder",
      fr: "Téléchargé par le SteamCMD du lanceur, dans son propre dossier",
      de: "Vom SteamCMD des Launchers in dessen eigenen Ordner geladen",
      es: "Descargado por el SteamCMD del lanzador, en su propia carpeta",
      ru: "Загружен SteamCMD лаунчера в его собственную папку",
    }),
    sourceSteamHint: t({
      en: "In a Steam library: read only, Steam keeps subscribed mods up to date",
      fr: "Dans une bibliothèque Steam : lecture seule, Steam met à jour les mods auxquels vous êtes abonné",
      de: "In einer Steam-Bibliothek: nur lesend, Steam aktualisiert abonnierte Mods selbst",
      es: "En una biblioteca de Steam: solo lectura, Steam actualiza los mods suscritos",
      ru: "В библиотеке Steam: только чтение, Steam сам обновляет подписанные моды",
    }),
    otherCopy: t({
      en: "An older copy is also in the other folder",
      fr: "Une copie plus ancienne est aussi dans l'autre dossier",
      de: "Eine ältere Kopie liegt auch im anderen Ordner",
      es: "También hay una copia más antigua en la otra carpeta",
      ru: "Более старая копия есть и в другой папке",
    }),
    repairHint: t({
      en: "Downloads it again into the launcher's folder and checks every file: slow, for a mod that does not load.",
      fr: "Le retélécharge dans le dossier du lanceur en vérifiant chaque fichier : lent, pour un mod qui ne se charge pas.",
      de: "Lädt ihn erneut in den Ordner des Launchers und prüft jede Datei: langsam, für einen Mod, der nicht lädt.",
      es: "Lo vuelve a descargar en la carpeta del lanzador y comprueba cada archivo: lento, para un mod que no carga.",
      ru: "Скачивает заново в папку лаунчера с проверкой каждого файла: медленно, для мода, который не загружается.",
    }),
    repair: t({
      en: "Repair (check every file)",
      fr: "Réparer (vérifier chaque fichier)",
      de: "Reparieren (jede Datei prüfen)",
      es: "Reparar (comprobar cada archivo)",
      ru: "Восстановить (проверить все файлы)",
    }),
    loginOk: t({
      en: "SteamCMD is logged in",
      fr: "SteamCMD est connecté",
      de: "SteamCMD ist angemeldet",
      es: "SteamCMD tiene la sesión iniciada",
      ru: "SteamCMD выполнил вход",
    }),
    loginFailed: t({
      en: "SteamCMD did not log in",
      fr: "SteamCMD ne s'est pas connecté",
      de: "SteamCMD hat sich nicht angemeldet",
      es: "SteamCMD no inició sesión",
      ru: "SteamCMD не выполнил вход",
    }),
    passwordSendFailed: insert(
      t({
        en: "Failed to send password: {{error}}",
        fr: "Échec de l'envoi du mot de passe : {{error}}",
        de: "Fehler beim Senden des Passworts: {{error}}",
        es: "Error al enviar contraseña: {{error}}",
        ru: "Не удалось отправить пароль: {{error}}",
      }),
    ),
    upToDate: t({
      en: "All mods are up to date",
      fr: "Tous les mods sont à jour",
      de: "Alle Mods sind aktuell",
      es: "Todos los mods están actualizados",
      ru: "Все моды актуальны",
    }),
    installAria: t({
      en: "Install mod",
      fr: "Installer le mod",
      de: "Mod installieren",
      es: "Instalar mod",
      ru: "Установить мод",
    }),
    // ── the list and its details, said plainly ──
    stateDownloading: t({
      en: "Downloading…",
      fr: "Téléchargement…",
      de: "Wird geladen…",
      es: "Descargando…",
      ru: "Загрузка…",
    }),
    stateQueued: t({
      en: "Waiting",
      fr: "En attente",
      de: "Wartet",
      es: "En espera",
      ru: "В очереди",
    }),
    whereLauncher: t({
      en: "Launcher's folder",
      fr: "Dossier du lanceur",
      de: "Ordner des Launchers",
      es: "Carpeta del lanzador",
      ru: "Папка лаунчера",
    }),
    whereSteam: t({
      en: "Steam library",
      fr: "Bibliothèque Steam",
      de: "Steam-Bibliothek",
      es: "Biblioteca de Steam",
      ru: "Библиотека Steam",
    }),
    colInGame: t({
      en: "In game",
      fr: "En jeu",
      de: "Im Spiel",
      es: "En el juego",
      ru: "В игре",
    }),
    colDownloaded: t({
      en: "Your version",
      fr: "Votre version",
      de: "Deine Version",
      es: "Tu versión",
      ru: "Ваша версия",
    }),
    inGameLinked: t({
      en: "Linked",
      fr: "Lié",
      de: "Verknüpft",
      es: "Enlazado",
      ru: "Связан",
    }),
    inGameNotLinked: t({
      en: "Not linked",
      fr: "Non lié",
      de: "Nicht verknüpft",
      es: "Sin enlazar",
      ru: "Не связан",
    }),
    inGameLinkedTitle: t({
      en: "Linked in the game folder: DayZ loads it on the servers that use it.",
      fr: "Lié dans le dossier du jeu : DayZ le charge sur les serveurs qui l'utilisent.",
      de: "Im Spielordner verknüpft: DayZ lädt ihn auf den Servern, die ihn nutzen.",
      es: "Enlazado en la carpeta del juego: DayZ lo carga en los servidores que lo usan.",
      ru: "Связан в папке игры: DayZ загружает его на серверах, которые его используют.",
    }),
    inGameNotLinkedTitle: t({
      en: "Not linked in the game folder yet: joining a server that uses it links it.",
      fr: "Pas encore lié dans le dossier du jeu : rejoindre un serveur qui l'utilise le lie.",
      de: "Noch nicht im Spielordner verknüpft: Beim Beitritt zu einem Server, der ihn nutzt, wird er verknüpft.",
      es: "Aún sin enlazar en la carpeta del juego: unirse a un servidor que lo usa lo enlaza.",
      ru: "Ещё не связан в папке игры: подключение к серверу, который его использует, создаст ссылку.",
    }),
    linkAction: t({
      en: "Link into the game",
      fr: "Lier au jeu",
      de: "Mit dem Spiel verknüpfen",
      es: "Enlazar al juego",
      ru: "Связать с игрой",
    }),
    unlinkAction: t({
      en: "Remove the game link",
      fr: "Retirer le lien du jeu",
      de: "Spiel-Verknüpfung entfernen",
      es: "Quitar el enlace del juego",
      ru: "Убрать ссылку из игры",
    }),
    redownload: t({
      en: "Download again",
      fr: "Retélécharger",
      de: "Erneut herunterladen",
      es: "Volver a descargar",
      ru: "Скачать заново",
    }),
    redownloadAll: t({
      en: "Download all again",
      fr: "Tout retélécharger",
      de: "Alle erneut herunterladen",
      es: "Volver a descargar todos",
      ru: "Скачать все заново",
    }),
    rescan: t({
      en: "Read the folders again",
      fr: "Relire les dossiers",
      de: "Ordner neu einlesen",
      es: "Volver a leer las carpetas",
      ru: "Перечитать папки",
    }),
    copyId: t({
      en: "Copy the Workshop ID",
      fr: "Copier l'ID Workshop",
      de: "Workshop-ID kopieren",
      es: "Copiar el ID de Workshop",
      ru: "Скопировать ID Workshop",
    }),
    sectionVersion: t({
      en: "Version",
      fr: "Version",
      de: "Version",
      es: "Versión",
      ru: "Версия",
    }),
    sectionWhere: t({
      en: "Where it is",
      fr: "Emplacement",
      de: "Speicherort",
      es: "Ubicación",
      ru: "Расположение",
    }),
    sectionCare: t({
      en: "Repair or remove",
      fr: "Réparer ou supprimer",
      de: "Reparieren oder entfernen",
      es: "Reparar o quitar",
      ru: "Восстановить или удалить",
    }),
    sectionIds: t({
      en: "Identifiers",
      fr: "Identifiants",
      de: "Kennungen",
      es: "Identificadores",
      ru: "Идентификаторы",
    }),
    yourCopy: t({
      en: "Your copy",
      fr: "Votre copie",
      de: "Deine Kopie",
      es: "Tu copia",
      ru: "Ваша копия",
    }),
    workshopCopy: t({
      en: "On the Workshop",
      fr: "Sur le Workshop",
      de: "Im Workshop",
      es: "En el Workshop",
      ru: "В Workshop",
    }),
    steamKeepsUpToDate: t({
      en: "Steam updates this copy itself while you are subscribed; updating here downloads a copy into the launcher's folder.",
      fr: "Steam met cette copie à jour lui-même tant que vous êtes abonné ; mettre à jour ici télécharge une copie dans le dossier du lanceur.",
      de: "Steam aktualisiert diese Kopie selbst, solange du abonniert bist; ein Update hier lädt eine Kopie in den Ordner des Launchers.",
      es: "Steam actualiza esta copia mientras estés suscrito; actualizar aquí descarga una copia en la carpeta del lanzador.",
      ru: "Steam сам обновляет эту копию, пока вы подписаны; обновление здесь скачает копию в папку лаунчера.",
    }),
    deleteHint: t({
      en: "Deletes its files and the game link, and unsubscribes your Steam account from it.",
      fr: "Supprime ses fichiers et le lien du jeu, et désabonne votre compte Steam.",
      de: "Löscht seine Dateien und die Spiel-Verknüpfung und beendet das Steam-Abo.",
      es: "Elimina sus archivos y el enlace del juego, y cancela la suscripción de tu cuenta de Steam.",
      ru: "Удаляет его файлы и ссылку в игре и отписывает ваш аккаунт Steam.",
    }),
    selectedSize: insert(
      t({
        en: "{{size}} on disk",
        fr: "{{size}} sur le disque",
        de: "{{size}} auf der Festplatte",
        es: "{{size}} en disco",
        ru: "{{size}} на диске",
      }),
    ),
    toDownload: insert(
      t({
        en: "{{count}} to update",
        fr: "{{count}} à mettre à jour",
        de: "{{count}} zu aktualisieren",
        es: "{{count}} por actualizar",
        ru: "{{count}} к обновлению",
      }),
    ),
    // ── what Steam says: subscriptions and its own downloads ──
    whereSubscribed: t({
      en: "Subscribed on Steam",
      fr: "Abonné sur Steam",
      de: "Auf Steam abonniert",
      es: "Suscrito en Steam",
      ru: "Подписка в Steam",
    }),
    whereNotSubscribed: t({
      en: "Steam library, not subscribed",
      fr: "Bibliothèque Steam, sans abonnement",
      de: "Steam-Bibliothek, nicht abonniert",
      es: "Biblioteca de Steam, sin suscripción",
      ru: "Библиотека Steam, без подписки",
    }),
    alsoSubscribed: t({
      en: "also subscribed on Steam",
      fr: "aussi abonné sur Steam",
      de: "auch auf Steam abonniert",
      es: "también suscrito en Steam",
      ru: "также подписка в Steam",
    }),
    sourceSubscribed: t({
      en: "Subscribed",
      fr: "Abonné",
      de: "Abonniert",
      es: "Suscrito",
      ru: "Подписка",
    }),
    subscribedHint: t({
      en: "Your Steam account is subscribed to it: Steam downloads it and keeps it up to date.",
      fr: "Votre compte Steam y est abonné : Steam le télécharge et le tient à jour.",
      de: "Dein Steam-Konto hat ihn abonniert: Steam lädt ihn herunter und hält ihn aktuell.",
      es: "Tu cuenta de Steam está suscrita: Steam lo descarga y lo mantiene al día.",
      ru: "Ваш аккаунт Steam подписан на него: Steam сам скачивает и обновляет его.",
    }),
    notSubscribedHint: t({
      en: "In a Steam library, but your Steam account is not subscribed to it: Steam will not update it.",
      fr: "Dans une bibliothèque Steam, mais votre compte n'y est pas abonné : Steam ne le mettra pas à jour.",
      de: "In einer Steam-Bibliothek, aber dein Konto hat ihn nicht abonniert: Steam aktualisiert ihn nicht.",
      es: "En una biblioteca de Steam, pero tu cuenta no está suscrita: Steam no lo actualizará.",
      ru: "В библиотеке Steam, но ваш аккаунт не подписан: Steam не будет его обновлять.",
    }),
    steamUnknown: t({
      en: "Whether your Steam account is subscribed is unknown while Steam is not running.",
      fr: "On ne sait pas si votre compte Steam y est abonné tant que Steam n'est pas lancé.",
      de: "Ob dein Steam-Konto ihn abonniert hat, ist unbekannt, solange Steam nicht läuft.",
      es: "No se sabe si tu cuenta de Steam está suscrita mientras Steam no esté abierto.",
      ru: "Пока Steam не запущен, неизвестно, подписан ли ваш аккаунт.",
    }),
    steamDownloading: t({
      en: "Steam downloading",
      fr: "Steam télécharge",
      de: "Steam lädt",
      es: "Steam descarga",
      ru: "Steam загружает",
    }),
    steamQueued: t({
      en: "Waiting for Steam",
      fr: "En attente de Steam",
      de: "Wartet auf Steam",
      es: "Esperando a Steam",
      ru: "Ожидает Steam",
    }),
    steamDownloads: insert(
      t({
        en: "Steam: {{count}} downloading",
        fr: "Steam : {{count}} en téléchargement",
        de: "Steam: {{count}} im Download",
        es: "Steam: {{count}} descargando",
        ru: "Steam: загрузок {{count}}",
      }),
    ),
    steamDownloadsTitle: t({
      en: "Downloads the Steam client is making for your subscriptions; the list updates when they finish.",
      fr: "Téléchargements que le client Steam fait pour vos abonnements ; la liste se met à jour quand ils se terminent.",
      de: "Downloads, die der Steam-Client für deine Abos macht; die Liste aktualisiert sich, wenn sie fertig sind.",
      es: "Descargas que el cliente de Steam hace para tus suscripciones; la lista se actualiza cuando terminan.",
      ru: "Загрузки клиента Steam по вашим подпискам; список обновится, когда они завершатся.",
    }),
  },
} satisfies Dictionary;

export default content;
