import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "offline",
  content: {
    title: t({ en: "Offline Missions", fr: "Missions hors ligne", de: "Offline-Missionen", es: "Misiones sin conexión", ru: "Оффлайн миссии" }),
    refreshTitle: t({ en: "Refresh mission list", fr: "Actualiser la liste des missions", de: "Missionsliste aktualisieren", es: "Actualizar lista de misiones", ru: "Обновить список миссий" }),
    noMissions: t({ en: "No missions installed", fr: "Aucune mission installée", de: "Keine Missionen installiert", es: "No hay misiones instaladas", ru: "Миссии не установлены" }),
    noMissionsHint: insert(t({ en: "Click {{installButton}} to download DayZ Community Offline Mode", fr: "Cliquez sur {{installButton}} pour télécharger DayZ Community Offline Mode", de: "Klicke {{installButton}} um DayZ Community Offline Mode herunterzuladen", es: "Haz clic en {{installButton}} para descargar DayZ Community Offline Mode", ru: "Нажмите {{installButton}} для скачивания DayZ Community Offline Mode" })),
    installButton: t({ en: "Install", fr: "Installer", de: "Installieren", es: "Instalar", ru: "Установить" }),
    openFolder: t({ en: "Open mission folder", fr: "Ouvrir le dossier des missions", de: "Missionsordner öffnen", es: "Abrir carpeta de misiones", ru: "Открыть папку миссий" }),
    removeMission: t({ en: "Remove this mission", fr: "Supprimer cette mission", de: "Diese Mission entfernen", es: "Eliminar esta misión", ru: "Удалить эту миссию" }),
    installing: t({ en: "Installing…", fr: "Installation…", de: "Installiere…", es: "Instalando…", ru: "Установка…" }),
    installUpdate: t({ en: "Install / Update", fr: "Installer / Mettre à jour", de: "Installieren / Aktualisieren", es: "Instalar / Actualizar", ru: "Установить / Обновить" }),
    exploreTitle: t({ en: "Open the Missions folder in file manager", fr: "Ouvrir le dossier Missions dans l'explorateur", de: "Missionsordner im Dateimanager öffnen", es: "Abrir carpeta de misiones en el gestor de archivos", ru: "Открыть папку миссий в файловом менеджере" }),
    explore: t({ en: "Explore", fr: "Explorer", de: "Erkunden", es: "Explorar", ru: "Обзор" }),
    clearSavesTitle: t({ en: "Delete storage_-1/ save data inside each mission folder (loot, player state, world state). Missions are kept.", fr: "Supprimer les sauvegardes storage_-1/ dans chaque dossier mission.", de: "Speicherdaten storage_-1/ in jedem Missionsordner löschen (Loot, Spielerstand, Weltzustand). Missionen bleiben erhalten.", es: "Eliminar datos de guardado storage_-1/ dentro de cada carpeta de misión (botín, estado del jugador, estado del mundo). Las misiones se conservan.", ru: "Удалить сохранения storage_-1/ в каждой папке миссии (лут, состояние игрока, состояние мира). Миссии сохраняются." }),
    clearSaves: t({ en: "Clear saves", fr: "Effacer les sauvegardes", de: "Speicher leeren", es: "Limpiar guardados", ru: "Очистить сохранения" }),
    removeAllTitle: t({ en: "Remove all DayZCommunityOfflineMode mission folders. Use Install / Update to reinstall.", fr: "Supprimer tous les dossiers mission DayZCommunityOfflineMode.", de: "Alle DayZCommunityOfflineMode Missionsordner entfernen. Zur Neuinstallation Installieren / Aktualisieren verwenden.", es: "Eliminar todas las carpetas de misión de DayZCommunityOfflineMode. Usa Instalar / Actualizar para reinstalar.", ru: "Удалить все папки миссий DayZCommunityOfflineMode. Используйте Установить / Обновить для переустановки." }),
    removeAll: t({ en: "Remove all", fr: "Tout supprimer", de: "Alle entfernen", es: "Eliminar todo", ru: "Удалить все" }),
    launch: t({ en: "Launch", fr: "Lancer", de: "Starten", es: "Iniciar", ru: "Запустить" }),
    doubleclickHint: t({ en: "Double-click to launch directly", fr: "Double-cliquez pour lancer directement", de: "Doppelklick zum direkten Starten", es: "Doble clic para iniciar directamente", ru: "Дважды щёлкните для запуска" }),
    selectMission: t({ en: "Select a mission", fr: "Sélectionnez une mission", de: "Mission auswählen", es: "Selecciona una misión", ru: "Выберите миссию" }),
    selectHint: t({ en: "or double-click to launch", fr: "ou double-cliquez pour lancer", de: "oder Doppelklick zum Starten", es: "o doble clic para iniciar", ru: "или дважды щёлкните для запуска" }),
    statusNoMissions: t({ en: "No missions found. Click 'Install / Update' to download.", fr: "Aucune mission trouvée. Cliquez sur 'Installer / Mettre à jour'.", de: "Keine Missionen gefunden. Klicke auf 'Installieren / Aktualisieren' zum Herunterladen.", es: "No se encontraron misiones. Haz clic en 'Instalar / Actualizar' para descargar.", ru: "Миссии не найдены. Нажмите 'Установить / Обновить' для скачивания." }),
    statusAvailable: insert(t({ en: "{{count}} missions available", fr: "{{count}} missions disponibles", de: "{{count}} Missionen verfügbar", es: "{{count}} misiones disponibles", ru: "{{count}} миссий доступно" })),
    statusAvailableOne: insert(t({ en: "{{count}} mission available", fr: "{{count}} mission disponible", de: "{{count}} Mission verfügbar", es: "{{count}} misión disponible", ru: "{{count}} миссия доступна" })),
    statusDownloading: t({ en: "Downloading DayZCommunityOfflineMode…", fr: "Téléchargement de DayZCommunityOfflineMode…", de: "DayZCommunityOfflineMode wird heruntergeladen…", es: "Descargando DayZCommunityOfflineMode…", ru: "Скачивание DayZCommunityOfflineMode…" }),
    statusLaunching: insert(t({ en: "Launching offline: {{mission}}", fr: "Lancement hors ligne : {{mission}}", de: "Starte Offline: {{mission}}", es: "Iniciando sin conexión: {{mission}}", ru: "Запуск оффлайн: {{mission}}" })),
    statusLaunchFailed: insert(t({ en: "Launch failed: {{error}}", fr: "Échec du lancement : {{error}}", de: "Start fehlgeschlagen: {{error}}", es: "Error al iniciar: {{error}}", ru: "Ошибка запуска: {{error}}" })),
    statusRemovingAll: t({ en: "Removing offline mode…", fr: "Suppression du mode hors ligne…", de: "Offline-Modus wird entfernt…", es: "Eliminando modo sin conexión…", ru: "Удаление оффлайн режима…" }),
    statusRemovedFolders: insert(t({ en: "Removed {{count}} mission folders", fr: "{{count}} dossiers mission supprimés", de: "{{count}} Missionsordner entfernt", es: "Eliminadas {{count}} carpetas de misión", ru: "Удалено {{count}} папок миссий" })),
    statusRemovedFoldersOne: insert(t({ en: "Removed {{count}} mission folder", fr: "{{count}} dossier mission supprimé", de: "{{count}} Missionsordner entfernt", es: "Eliminada {{count}} carpeta de misión", ru: "Удалена {{count}} папка миссии" })),
    statusNothingToRemove: t({ en: "Nothing to remove", fr: "Rien à supprimer", de: "Nichts zu entfernen", es: "Nada que eliminar", ru: "Нечего удалять" }),
    statusRemoveFailed: insert(t({ en: "Remove failed: {{error}}", fr: "Échec de la suppression : {{error}}", de: "Entfernen fehlgeschlagen: {{error}}", es: "Error al eliminar: {{error}}", ru: "Ошибка удаления: {{error}}" })),
    statusClearedSaves: insert(t({ en: "Cleared saves for {{count}} missions", fr: "Sauvegardes effacées pour {{count}} missions", de: "Spielstände für {{count}} Missionen gelöscht", es: "Guardados limpiados para {{count}} misiones", ru: "Очищены сохранения для {{count}} миссий" })),
    statusClearedSavesOne: insert(t({ en: "Cleared saves for {{count}} mission", fr: "Sauvegardes effacées pour {{count}} mission", de: "Spielstände für {{count}} Mission gelöscht", es: "Guardados limpiados para {{count}} misión", ru: "Очищены сохранения для {{count}} миссии" })),
    statusNoSaves: t({ en: "No saves found", fr: "Aucune sauvegarde trouvée", de: "Keine Spielstände gefunden", es: "No se encontraron guardados", ru: "Сохранения не найдены" }),
    statusClearFailed: insert(t({ en: "Clear failed: {{error}}", fr: "Échec de l'effacement : {{error}}", de: "Löschen fehlgeschlagen: {{error}}", es: "Error al limpiar: {{error}}", ru: "Ошибка очистки: {{error}}" })),
    statusRemovingMission: insert(t({ en: "Removing {{mission}}…", fr: "Suppression de {{mission}}…", de: "{{mission}} wird entfernt…", es: "Eliminando {{mission}}…", ru: "Удаление {{mission}}…" })),
    statusRemovedMission: insert(t({ en: "Removed {{mission}}", fr: "{{mission}} supprimée", de: "{{mission}} entfernt", es: "Eliminada {{mission}}", ru: "Удалена {{mission}}" })),
    dialogRemoveTitle: t({ en: "Remove Offline Mode", fr: "Supprimer le mode hors ligne", de: "Offline-Modus entfernen", es: "Eliminar modo sin conexión", ru: "Удаление оффлайн режима" }),
    dialogRemoveMessage: t({ en: "Delete all DayZCommunityOfflineMode mission folders?\nThis cannot be undone. You can reinstall with \"Install / Update\".", fr: "Supprimer tous les dossiers mission DayZCommunityOfflineMode ?\nCette action est irréversible.", de: "Alle DayZCommunityOfflineMode Missionsordner löschen?\nDies kann nicht rückgängig gemacht werden. Mit \"Installieren / Aktualisieren\" neu installieren.", es: "¿Eliminar todas las carpetas de misión de DayZCommunityOfflineMode?\nEsto no se puede deshacer. Puedes reinstalar con \"Instalar / Actualizar\".", ru: "Удалить все папки миссий DayZCommunityOfflineMode?\nЭто действие нельзя отменить. Вы можете переустановить через \"Установить / Обновить\"." }),
    dialogRemoveConfirm: t({ en: "Remove all", fr: "Tout supprimer", de: "Alle entfernen", es: "Eliminar todo", ru: "Удалить все" }),
    dialogClearTitle: t({ en: "Clear Saves", fr: "Effacer les sauvegardes", de: "Spielstände löschen", es: "Limpiar guardados", ru: "Очистка сохранений" }),
    dialogClearMessage: t({ en: "Delete all offline save data (storage_-1/) for every mission?\nThis wipes loot, player state and world state. The missions themselves are kept.", fr: "Supprimer toutes les données de sauvegarde (storage_-1/) pour chaque mission ?\nCela efface le loot, l'état du joueur et du monde.", de: "Alle Offline-Spielstände (storage_-1/) für jede Mission löschen?\nDies löscht Beute, Spielerstand und Weltzustand. Die Missionen selbst bleiben erhalten.", es: "¿Eliminar todos los datos de guardado sin conexión (storage_-1/) para todas las misiones?\nEsto borra botín, estado del jugador y estado del mundo. Las misiones se conservan.", ru: "Удалить все оффлайн сохранения (storage_-1/) для всех миссий?\nЭто удалит лут, состояние игрока и состояние мира. Сами миссии сохранятся." }),
    dialogClearConfirm: t({ en: "Clear saves", fr: "Effacer les sauvegardes", de: "Spielstände löschen", es: "Limpiar guardados", ru: "Очистить сохранения" }),
    dialogRemoveMissionTitle: t({ en: "Remove Mission", fr: "Supprimer la mission", de: "Mission entfernen", es: "Eliminar misión", ru: "Удаление миссии" }),
    dialogRemoveMissionMessage: insert(t({ en: "Delete the mission \"{{mission}}\"?\nThis cannot be undone.", fr: "Supprimer la mission « {{mission}} » ?\nCette action est irréversible.", de: "Mission \"{{mission}}\" löschen?\nDies kann nicht rückgängig gemacht werden.", es: "¿Eliminar la misión \"{{mission}}\"?\nEsto no se puede deshacer.", ru: "Удалить миссию \"{{mission}}\"?\nЭто действие нельзя отменить." })),
    dialogRemoveMissionConfirm: t({ en: "Remove", fr: "Supprimer", de: "Entfernen", es: "Eliminar", ru: "Удалить" }),
    missionTag: t({ en: "MISSION", fr: "MISSION", de: "MISSION", es: "MISIÓN", ru: "МИССИЯ" }),
    missionOffline: t({ en: "OFFLINE", fr: "HORS LIGNE", de: "OFFLINE", es: "SIN CONEXIÓN", ru: "ОФФЛАЙН" }),
    missionCoop: t({ en: "COOP", fr: "COOP", de: "KOOP", es: "COOP", ru: "КООП" }),
    missionPvp: t({ en: "PVP", fr: "PVP", de: "PVP", es: "PVP", ru: "PVP" }),
    missionSurvival: t({ en: "SURVIVAL", fr: "SURVIE", de: "ÜBERLEBEN", es: "SUPERVIVENCIA", ru: "ВЫЖИВАНИЕ" }),
  },
} satisfies Dictionary;

export default content;
