import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "options",
  content: {
    searchPlaceholder: t({ en: "Search options…", fr: "Rechercher des options…", de: "Optionen suchen…", es: "Buscar opciones…", ru: "Поиск опций…" }),
    recommendTitle: t({ en: "Recommended for your PC", fr: "Recommandé pour votre PC", de: "Empfohlen für deinen PC", es: "Recomendado para tu PC", ru: "Рекомендовано для вашего ПК" }),
    recommendDesc: insert(t({ en: "Detected {{cores}} cores · {{ram}} GB RAM — apply tuned performance flags.", fr: "Détecté : {{cores}} cœurs · {{ram}} Go RAM — appliquer des options de performance optimisées.", de: "Erkannt: {{cores}} Kerne · {{ram}} GB RAM — optimierte Performance-Flags anwenden.", es: "Detectado: {{cores}} núcleos · {{ram}} GB RAM — aplicar opciones de rendimiento optimizadas.", ru: "Обнаружено: {{cores}} ядер · {{ram}} ГБ ОЗУ — применить оптимальные флаги производительности." })),
    recommendApply: t({ en: "Apply", fr: "Appliquer", de: "Anwenden", es: "Aplicar", ru: "Применить" }),
    recommendApplied: t({ en: "Applied", fr: "Appliqué", de: "Angewendet", es: "Aplicado", ru: "Применено" }),
    recommendDetecting: t({ en: "Detecting hardware…", fr: "Détection du matériel…", de: "Hardware wird erkannt…", es: "Detectando hardware…", ru: "Определение оборудования…" }),
    active: insert(t({ en: "{{count}} active", fr: "{{count}} actives", de: "{{count}} aktiv", es: "{{count}} activas", ru: "{{count}} активно" })),
    activeOne: insert(t({ en: "{{count}} active", fr: "{{count}} active", de: "{{count}} aktiv", es: "{{count}} activa", ru: "{{count}} активна" })),
    flagsHint: t({ en: "Flags passed to DayZ at launch", fr: "Options passées à DayZ au lancement", de: "Flags die beim DayZ-Start übergeben werden", es: "Parámetros pasados a DayZ al iniciar", ru: "Флаги, передаваемые DayZ при запуске" }),
    enabledCount: insert(t({ en: "{{enabled}}/{{total}} enabled", fr: "{{enabled}}/{{total}} activées", de: "{{enabled}}/{{total}} aktiviert", es: "{{enabled}}/{{total}} activadas", ru: "{{enabled}}/{{total}} включено" })),
    apply: t({ en: "Apply", fr: "Appliquer", de: "Anwenden", es: "Aplicar", ru: "Применить" }),
    cancel: t({ en: "Cancel", fr: "Annuler", de: "Abbrechen", es: "Cancelar", ru: "Отмена" }),
    editValue: t({ en: "Edit value", fr: "Modifier la valeur", de: "Wert bearbeiten", es: "Editar valor", ru: "Изменить значение" }),
    setValue: t({ en: "set value", fr: "définir la valeur", de: "Wert setzen", es: "establecer valor", ru: "задать значение" }),
    edit: t({ en: "Edit", fr: "Modifier", de: "Bearbeiten", es: "Editar", ru: "Изменить" }),
    noMatch: insert(t({ en: "No options match \"{{search}}\"", fr: "Aucune option ne correspond à « {{search}} »", de: "Keine Optionen für \"{{search}}\" gefunden", es: "Ninguna opción coincide con \"{{search}}\"", ru: "Нет опций, соответствующих \"{{search}}\"" })),
    groupWindow: t({ en: "Window", fr: "Fenêtre", de: "Fenster", es: "Ventana", ru: "Окно" }),
    groupStartup: t({ en: "Startup", fr: "Démarrage", de: "Startoptionen", es: "Inicio", ru: "Запуск" }),
    groupPerformance: t({ en: "Performance", fr: "Performance", de: "Leistung", es: "Rendimiento", ru: "Производительность" }),
    groupWorld: t({ en: "World", fr: "Monde", de: "Welt", es: "Mundo", ru: "Мир" }),
    groupDeveloper: t({ en: "Developer", fr: "Développeur", de: "Entwickler", es: "Desarrollador", ru: "Разработчик" }),
    groupOther: t({ en: "Other", fr: "Autre", de: "Sonstige", es: "Otros", ru: "Прочее" }),
    labelWindowed: t({ en: "Windowed", fr: "Fenêtré", de: "Fenstermodus", es: "Ventana", ru: "Оконный режим" }),
    labelBorderless: t({ en: "Borderless", fr: "Sans bordure", de: "Rahmenlos", es: "Sin bordes", ru: "Без рамки" }),
    labelNosplash: t({ en: "No Splash", fr: "Sans splash", de: "Kein Splash", es: "Sin splash", ru: "Без заставки" }),
    labelSkipintro: t({ en: "Skip Intro", fr: "Passer l'intro", de: "Intro überspringen", es: "Saltar intro", ru: "Пропуск интро" }),
    labelNolauncher: t({ en: "No Launcher", fr: "Sans lanceur", de: "Kein Launcher", es: "Sin launcher", ru: "Без лаунчера" }),
    labelHigh: t({ en: "High Priority", fr: "Priorité haute", de: "Hohe Priorität", es: "Alta prioridad", ru: "Высокий приоритет" }),
    labelMaxMem: t({ en: "Max RAM", fr: "RAM max", de: "Max RAM", es: "RAM máxima", ru: "Макс. ОЗУ" }),
    labelMaxVram: t({ en: "Max VRAM", fr: "VRAM max", de: "Max VRAM", es: "VRAM máxima", ru: "Макс. VRAM" }),
    labelCpuCount: t({ en: "CPU Cores", fr: "Cœurs CPU", de: "CPU-Kerne", es: "Núcleos CPU", ru: "Ядер ЦП" }),
    labelExThreads: t({ en: "Threads", fr: "Threads", de: "Threads", es: "Hilos", ru: "Потоков" }),
    labelNoBenchmark: t({ en: "No Benchmark", fr: "Sans benchmark", de: "Kein Benchmark", es: "Sin benchmark", ru: "Без бенчмарка" }),
    labelWorld: t({ en: "World", fr: "Monde", de: "Welt", es: "Mundo", ru: "Мир" }),
    labelNoPause: t({ en: "No Pause", fr: "Sans pause", de: "Keine Pause", es: "Sin pausa", ru: "Без паузы" }),
    labelFilePatching: t({ en: "File Patching", fr: "File Patching", de: "File Patching", es: "Parcheo de archivos", ru: "Патчинг файлов" }),
    labelDoLogs: t({ en: "Logging", fr: "Journalisation", de: "Protokollierung", es: "Registro", ru: "Логирование" }),
    labelScriptDebug: t({ en: "Script Debug", fr: "Débogage script", de: "Script Debug", es: "Depurar scripts", ru: "Отладка скриптов" }),
    labelBuldozer: t({ en: "Buldozer", fr: "Buldozer", de: "Buldozer", es: "Buldozer", ru: "Бульдозер" }),
    labelWinxp: t({ en: "DirectX 9", fr: "DirectX 9", de: "DirectX 9", es: "DirectX 9", ru: "DirectX 9" }),
    labelProfiles: t({ en: "Profiles Dir", fr: "Dossier profils", de: "Profilordner", es: "Carpeta perfiles", ru: "Папка профилей" }),
    descWindow: t({ en: "Run in windowed mode", fr: "Lancer en mode fenêtré", de: "Im Fenstermodus starten", es: "Ejecutar en modo ventana", ru: "Запуск в оконном режиме" }),
    descNoborder: t({ en: "Borderless window", fr: "Fenêtre sans bordure", de: "Rahmenloses Fenster", es: "Ventana sin bordes", ru: "Окно без рамки" }),
    descNosplash: t({ en: "Skip splash screen", fr: "Passer l'écran de démarrage", de: "Splash-Screen überspringen", es: "Omitir pantalla de splash", ru: "Пропустить заставку" }),
    descSkipintro: t({ en: "Skip intro video", fr: "Passer la vidéo d'intro", de: "Intro-Video überspringen", es: "Omitir video de introducción", ru: "Пропустить интро-видео" }),
    descNolauncher: t({ en: "Skip launcher", fr: "Passer le lanceur", de: "Launcher überspringen", es: "Omitir launcher", ru: "Пропустить лаунчер" }),
    descHigh: t({ en: "High process priority", fr: "Priorité de processus élevée", de: "Hohe Prozesspriorität", es: "Prioridad alta del proceso", ru: "Высокий приоритет процесса" }),
    descMaxMem: t({ en: "Max memory in MB", fr: "Mémoire max en Mo", de: "Max Arbeitsspeicher in MB", es: "Memoria máxima en MB", ru: "Макс. память в МБ" }),
    descMaxVram: t({ en: "Max VRAM in MB", fr: "VRAM max en Mo", de: "Max VRAM in MB", es: "VRAM máxima en MB", ru: "Макс. VRAM в МБ" }),
    descCpuCount: t({ en: "Number of CPU cores", fr: "Nombre de cœurs CPU", de: "Anzahl der CPU-Kerne", es: "Número de núcleos de CPU", ru: "Количество ядер ЦП" }),
    descExThreads: t({ en: "Number of threads", fr: "Nombre de threads", de: "Anzahl der Threads", es: "Número de hilos", ru: "Количество потоков" }),
    descNoBenchmark: t({ en: "Disable benchmark", fr: "Désactiver le benchmark", de: "Benchmark deaktivieren", es: "Desactivar benchmark", ru: "Отключить бенчмарк" }),
    descWorld: t({ en: "World to load", fr: "Monde à charger", de: "Zu ladende Welt", es: "Mundo a cargar", ru: "Загружаемый мир" }),
    descNoPause: t({ en: "Don't pause when unfocused", fr: "Ne pas mettre en pause sans focus", de: "Nicht pausieren wenn unfokussiert", es: "No pausar al perder el foco", ru: "Не ставить на паузу при потере фокуса" }),
    descFilePatching: t({ en: "Enable file patching", fr: "Activer le file patching", de: "File Patching aktivieren", es: "Habilitar parcheo de archivos", ru: "Включить патчинг файлов" }),
    descDoLogs: t({ en: "Enable logging", fr: "Activer la journalisation", de: "Protokollierung aktivieren", es: "Habilitar registro", ru: "Включить логирование" }),
    descScriptDebug: t({ en: "Script debug mode", fr: "Mode débogage script", de: "Script-Debug-Modus", es: "Modo depuración de scripts", ru: "Режим отладки скриптов" }),
    descBuldozer: t({ en: "Buldozer mode", fr: "Mode Buldozer", de: "Buldozer-Modus", es: "Modo buldozer", ru: "Режим бульдозер" }),
    descWinxp: t({ en: "DirectX 9 compatibility", fr: "Compatibilité DirectX 9", de: "DirectX 9 Kompatibilität", es: "Compatibilidad con DirectX 9", ru: "Совместимость с DirectX 9" }),
    descProfiles: t({ en: "Custom profiles directory", fr: "Dossier de profils personnalisé", de: "Benutzerdefinierter Profilordner", es: "Carpeta de perfiles personalizada", ru: "Пользовательская папка профилей" }),
  },
} satisfies Dictionary;

export default content;
