import { t, type Dictionary } from "intlayer";

// A controller driving the window: the hint bar and the settings' Controller section.
const content = {
  key: "pad",
  content: {
    // ── hint bar ────────────────────────────────────────────────────────
    hints: t({
      en: "Controller buttons",
      fr: "Boutons de la manette",
      de: "Controller-Tasten",
      es: "Botones del mando",
      ru: "Кнопки геймпада",
    }),
    select: t({ en: "Select", fr: "Valider", de: "Auswählen", es: "Elegir", ru: "Выбрать" }),
    back: t({ en: "Back", fr: "Retour", de: "Zurück", es: "Atrás", ru: "Назад" }),
    type: t({ en: "Type", fr: "Saisir", de: "Tippen", es: "Escribir", ru: "Ввод" }),
    views: t({ en: "Views", fr: "Vues", de: "Ansichten", es: "Vistas", ru: "Разделы" }),
    page: t({ en: "Page", fr: "Page", de: "Seite", es: "Página", ru: "Страница" }),
    move: t({ en: "Move", fr: "Déplacer", de: "Bewegen", es: "Mover", ru: "Перемещение" }),
    settings: t({
      en: "Settings",
      fr: "Paramètres",
      de: "Einstellungen",
      es: "Ajustes",
      ru: "Настройки",
    }),
    search: t({ en: "Search", fr: "Rechercher", de: "Suchen", es: "Buscar", ru: "Поиск" }),
    refresh: t({
      en: "Refresh",
      fr: "Actualiser",
      de: "Aktualisieren",
      es: "Actualizar",
      ru: "Обновить",
    }),
    favorite: t({ en: "Favourite", fr: "Favori", de: "Favorit", es: "Favorito", ru: "Избранное" }),
    join: t({ en: "Join", fr: "Rejoindre", de: "Beitreten", es: "Unirse", ru: "Войти" }),

    // ── settings ────────────────────────────────────────────────────────
    section: t({
      en: "Controller",
      fr: "Manette",
      de: "Controller",
      es: "Mando",
      ru: "Геймпад",
    }),
    sectionHint: t({
      en: "Drive the launcher with a gamepad: a Steam Deck, an Xbox or a PlayStation controller.",
      fr: "Piloter le lanceur à la manette : Steam Deck, manette Xbox ou PlayStation.",
      de: "Den Launcher mit einem Gamepad bedienen: Steam Deck, Xbox- oder PlayStation-Controller.",
      es: "Maneja el lanzador con un mando: Steam Deck, mando de Xbox o de PlayStation.",
      ru: "Управление лаунчером с геймпада: Steam Deck, контроллер Xbox или PlayStation.",
    }),
    mode: t({
      en: "Controller mode",
      fr: "Mode manette",
      de: "Controller-Modus",
      es: "Modo mando",
      ru: "Режим геймпада",
    }),
    modeHint: t({
      en: "Auto switches to it when a controller is used and back when the mouse moves. Never ignores controllers.",
      fr: "Auto passe en mode manette dès qu'une manette sert et revient quand la souris bouge. Jamais ignore les manettes.",
      de: "Auto wechselt dorthin, sobald ein Controller benutzt wird, und zurück, wenn sich die Maus bewegt. Nie ignoriert Controller.",
      es: "Auto cambia a él al usar un mando y vuelve cuando se mueve el ratón. Nunca ignora los mandos.",
      ru: "«Авто» включает его при нажатии на геймпаде и выключает при движении мыши. «Никогда» игнорирует геймпады.",
    }),
    modeAuto: t({ en: "Auto", fr: "Auto", de: "Auto", es: "Auto", ru: "Авто" }),
    modeAlways: t({ en: "Always", fr: "Toujours", de: "Immer", es: "Siempre", ru: "Всегда" }),
    modeNever: t({ en: "Never", fr: "Jamais", de: "Nie", es: "Nunca", ru: "Никогда" }),
    scale: t({
      en: "Interface size with a controller",
      fr: "Taille de l'interface à la manette",
      de: "Oberflächengröße mit Controller",
      es: "Tamaño de la interfaz con mando",
      ru: "Размер интерфейса с геймпадом",
    }),
    connected: t({
      en: "Connected",
      fr: "Connectée",
      de: "Verbunden",
      es: "Conectado",
      ru: "Подключено",
    }),
    noPad: t({
      en: "No controller connected",
      fr: "Aucune manette connectée",
      de: "Kein Controller verbunden",
      es: "Ningún mando conectado",
      ru: "Геймпад не подключён",
    }),
    unavailable: t({
      en: "Controllers cannot be read on this system (on Linux, check access to /dev/input).",
      fr: "Les manettes ne peuvent pas être lues sur ce système (sous Linux, vérifier l'accès à /dev/input).",
      de: "Controller können auf diesem System nicht gelesen werden (unter Linux den Zugriff auf /dev/input prüfen).",
      es: "No se pueden leer mandos en este sistema (en Linux, comprueba el acceso a /dev/input).",
      ru: "Геймпады недоступны в этой системе (в Linux проверьте доступ к /dev/input).",
    }),
    steamKeyboard: t({
      en: "Steam's on-screen keyboard opens on text fields",
      fr: "Le clavier à l'écran de Steam s'ouvre sur les champs de texte",
      de: "Steams Bildschirmtastatur öffnet sich in Textfeldern",
      es: "El teclado en pantalla de Steam se abre en los campos de texto",
      ru: "Экранная клавиатура Steam открывается в текстовых полях",
    }),
    details: t({
      en: "Details",
      fr: "Détails",
      de: "Details",
      es: "Detalles",
      ru: "Детали",
    }),
    update: t({
      en: "Update",
      fr: "Mettre à jour",
      de: "Aktualisieren",
      es: "Actualizar",
      ru: "Обновить",
    }),
    tickMod: t({
      en: "Tick",
      fr: "Cocher",
      de: "Markieren",
      es: "Marcar",
      ru: "Отметить",
    }),
    query: t({
      en: "Query",
      fr: "Interroger",
      de: "Abfragen",
      es: "Consultar",
      ru: "Опросить",
    }),
    launch: t({
      en: "Launch",
      fr: "Lancer",
      de: "Starten",
      es: "Lanzar",
      ru: "Запустить",
    }),
    installMode: t({
      en: "Install / update",
      fr: "Installer / mettre à jour",
      de: "Installieren / aktualisieren",
      es: "Instalar / actualizar",
      ru: "Установить / обновить",
    }),
    openArticle: t({
      en: "Open the article",
      fr: "Ouvrir l'article",
      de: "Artikel öffnen",
      es: "Abrir el artículo",
      ru: "Открыть статью",
    }),
    applyRecommended: t({
      en: "Apply recommended",
      fr: "Appliquer les recommandations",
      de: "Empfehlungen anwenden",
      es: "Aplicar recomendaciones",
      ru: "Применить рекомендации",
    }),
    activeOnly: t({
      en: "Active only",
      fr: "Actives seulement",
      de: "Nur aktive",
      es: "Solo activas",
      ru: "Только активные",
    }),
    legendSticks: t({
      en: "Right stick: scroll · L3: rejoin the last server · R3: the server's details",
      fr: "Stick droit : défiler · L3 : rejoindre la dernière partie · R3 : détails du serveur",
      de: "Rechter Stick: scrollen · L3: letzten Server erneut betreten · R3: Serverdetails",
      es: "Stick derecho: desplazar · L3: volver al último servidor · R3: detalles del servidor",
      ru: "Правый стик: прокрутка · L3: вернуться на последний сервер · R3: детали сервера",
    }),
    legend: t({ en: "Buttons", fr: "Boutons", de: "Tasten", es: "Botones", ru: "Кнопки" }),
    legendMove: t({
      en: "Move between items; through every row of a list",
      fr: "Aller d'un élément à l'autre ; ligne par ligne dans une liste",
      de: "Zwischen Elementen wechseln; Zeile für Zeile in einer Liste",
      es: "Moverse entre elementos; fila a fila en una lista",
      ru: "Переход между элементами; по строкам в списке",
    }),
    legendSelect: t({
      en: "Press the button, open the menu, toggle the switch",
      fr: "Appuyer sur le bouton, ouvrir le menu, basculer l'interrupteur",
      de: "Taste drücken, Menü öffnen, Schalter umlegen",
      es: "Pulsar el botón, abrir el menú, activar el interruptor",
      ru: "Нажать кнопку, открыть меню, переключить",
    }),
    legendBack: t({
      en: "Close the dialog or menu, clear the selection",
      fr: "Fermer la fenêtre ou le menu, effacer la sélection",
      de: "Dialog oder Menü schließen, Auswahl aufheben",
      es: "Cerrar el diálogo o menú, quitar la selección",
      ru: "Закрыть окно или меню, снять выделение",
    }),
    legendXY: t({
      en: "The view's own actions, shown in the bar at the bottom",
      fr: "Les actions propres à la vue, affichées dans la barre du bas",
      de: "Die Aktionen der Ansicht, unten in der Leiste angezeigt",
      es: "Las acciones de la vista, mostradas en la barra inferior",
      ru: "Действия раздела, показаны в нижней панели",
    }),
    legendTabs: t({
      en: "Previous / next view",
      fr: "Vue précédente / suivante",
      de: "Vorherige / nächste Ansicht",
      es: "Vista anterior / siguiente",
      ru: "Предыдущий / следующий раздел",
    }),
    legendPage: t({
      en: "Page up / down",
      fr: "Page précédente / suivante",
      de: "Seite hoch / runter",
      es: "Página arriba / abajo",
      ru: "Страница вверх / вниз",
    }),
    legendMenu: t({
      en: "Settings; View: the search field",
      fr: "Paramètres ; Affichage : le champ de recherche",
      de: "Einstellungen; Ansicht: das Suchfeld",
      es: "Ajustes; Vista: el campo de búsqueda",
      ru: "Настройки; View: поле поиска",
    }),
  },
} satisfies Dictionary;

export default content;
