import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "progress",
  content: {
    minimise: t({ en: "Keep running in the background", fr: "Continuer en arrière-plan", de: "Im Hintergrund fortsetzen", es: "Seguir en segundo plano", ru: "Продолжить в фоне" }),
    elapsed: t({ en: "Elapsed", fr: "Écoulé", de: "Vergangen", es: "Transcurrido", ru: "Прошло" }),
    speed: t({ en: "Speed", fr: "Débit", de: "Geschwindigkeit", es: "Velocidad", ru: "Скорость" }),
    itemProgress: t({ en: "Current mod", fr: "Mod en cours", de: "Aktueller Mod", es: "Mod actual", ru: "Текущий мод" }),
    overall: t({ en: "Overall", fr: "Global", de: "Gesamt", es: "Total", ru: "Всего" }),
    succeeded: t({ en: "Succeeded", fr: "Réussis", de: "Erfolgreich", es: "Correctos", ru: "Успешно" }),
    failedLabel: t({ en: "Failed", fr: "Échecs", de: "Fehlgeschlagen", es: "Fallidos", ru: "Ошибки" }),
    queue: t({ en: "Done so far", fr: "Terminés", de: "Bisher erledigt", es: "Completados", ru: "Готово" }),
    noneYet: t({ en: "Nothing finished yet.", fr: "Rien de terminé pour l'instant.", de: "Noch nichts fertig.", es: "Nada terminado todavía.", ru: "Пока ничего не завершено." }),
    showPassword: t({ en: "Show the password", fr: "Afficher le mot de passe", de: "Passwort anzeigen", es: "Mostrar la contraseña", ru: "Показать пароль" }),
    copyLog: t({ en: "Copy the log", fr: "Copier le journal", de: "Protokoll kopieren", es: "Copiar el registro", ru: "Скопировать журнал" }),
    followLog: t({ en: "Follow", fr: "Suivre", de: "Folgen", es: "Seguir", ru: "Следить" }),
    steamguardTitle: t({ en: "Steam Guard Authorization Required", fr: "Autorisation Steam Guard requise", de: "Steam Guard Autorisierung erforderlich", es: "Se requiere autorización de Steam Guard", ru: "Требуется авторизация Steam Guard" }),
    steamguardDesc: insert(t({ en: "Open the {{app}} on your phone and approve the sign-in to continue.", fr: "Ouvrez l'{{app}} sur votre téléphone et approuvez la connexion pour continuer.", de: "Öffne die {{app}} auf deinem Handy und bestätige die Anmeldung um fortzufahren.", es: "Abre la {{app}} en tu teléfono y aprueba el inicio de sesión para continuar.", ru: "Откройте {{app}} на телефоне и подтвердите вход для продолжения." })),
    steamguardApp: t({ en: "Steam Mobile app", fr: "application Steam Mobile", de: "Steam Mobile App", es: "aplicación Steam Mobile", ru: "приложение Steam Mobile" }),
    steamguardStep1: t({ en: "Open Steam app on phone", fr: "Ouvrir l'app Steam sur téléphone", de: "Steam App auf Handy öffnen", es: "Abre la app de Steam en el teléfono", ru: "Откройте Steam на телефоне" }),
    steamguardStep2: t({ en: "Tap the approval notification", fr: "Appuyer sur la notification d'approbation", de: "Bestätigungsbenachrichtigung antippen", es: "Toca la notificación de aprobación", ru: "Подтвердите уведомление" }),
    steamguardStep3: t({ en: "Download resumes", fr: "Le téléchargement reprend", de: "Download wird fortgesetzt", es: "La descarga continúa", ru: "Скачивание продолжится" }),
    steamguardWaiting: t({ en: "Waiting for confirmation…", fr: "En attente de confirmation…", de: "Warte auf Bestätigung…", es: "Esperando confirmación…", ru: "Ожидание подтверждения…" }),
    steamguardHurry: t({ en: "Hurry — SteamCMD will time out soon!", fr: "Dépêchez-vous — SteamCMD va expirer !", de: "Beeil dich — SteamCMD wird bald abbrechen!", es: "¡Date prisa — SteamCMD expirará pronto!", ru: "Поспешите — SteamCMD скоро завершится по таймауту!" }),
    steamguardTimeout: t({ en: "SteamCMD may have timed out. Check the log below.", fr: "SteamCMD a peut-être expiré. Vérifiez le journal ci-dessous.", de: "SteamCMD ist möglicherweise abgelaufen. Überprüfe das Log unten.", es: "SteamCMD puede haber expirado. Revisa el log abajo.", ru: "Возможно, SteamCMD завершился по таймауту. Проверьте лог ниже." }),
    cancel: t({ en: "Cancel", fr: "Annuler", de: "Abbrechen", es: "Cancelar", ru: "Отмена" }),
    modOperation: t({ en: "Mod Operation", fr: "Opération sur les mods", de: "Mod-Vorgang", es: "Operación de mods", ru: "Операция с модами" }),
    statusShuttingDown: t({ en: "Closing Steam before SteamCMD can run…", fr: "Fermeture de Steam avant que SteamCMD puisse s'exécuter…", de: "Steam wird geschlossen bevor SteamCMD starten kann…", es: "Cerrando Steam antes de que SteamCMD pueda ejecutarse…", ru: "Закрытие Steam перед запуском SteamCMD…" }),
    statusSteamGuard: t({ en: "Waiting for Steam Guard…", fr: "En attente de Steam Guard…", de: "Warte auf Steam Guard…", es: "Esperando Steam Guard…", ru: "Ожидание Steam Guard…" }),
    statusPassword: t({ en: "Waiting for password…", fr: "En attente du mot de passe…", de: "Warte auf Passwort…", es: "Esperando contraseña…", ru: "Ожидание пароля…" }),
    statusLoginFailed: t({ en: "Login failed or credentials expired", fr: "Échec de connexion ou identifiants expirés", de: "Anmeldung fehlgeschlagen oder Anmeldedaten abgelaufen", es: "Inicio de sesión fallido o credenciales expiradas", ru: "Ошибка входа или просроченные учётные данные" }),
    statusDone: insert(t({ en: "Done — {{ok}} mod completed", fr: "Terminé — {{ok}} mod complété", de: "Fertig — {{ok}} Mod abgeschlossen", es: "Listo — {{ok}} mod completado", ru: "Готово — {{ok}} мод завершён" })),
    statusDonePlural: insert(t({ en: "Done — {{ok}} mods completed", fr: "Terminé — {{ok}} mods complétés", de: "Fertig — {{ok}} Mods abgeschlossen", es: "Listo — {{ok}} mods completados", ru: "Готово — {{ok}} модов завершено" })),
    statusDoneFailed: insert(t({ en: "Done — {{ok}} OK, {{failed}} failed", fr: "Terminé — {{ok}} OK, {{failed}} échoué(s)", de: "Fertig — {{ok}} OK, {{failed}} fehlgeschlagen", es: "Listo — {{ok}} OK, {{failed}} fallidos", ru: "Готово — {{ok}} OK, {{failed}} с ошибками" })),
    statusDownloading: insert(t({ en: "Downloading: {{name}}", fr: "Téléchargement : {{name}}", de: "Lade herunter: {{name}}", es: "Descargando: {{name}}", ru: "Скачивание: {{name}}" })),
    statusPreparing: t({ en: "Preparing…", fr: "Préparation…", de: "Vorbereitung…", es: "Preparando…", ru: "Подготовка…" }),
    passwordTitle: t({ en: "Steam Password Required", fr: "Mot de passe Steam requis", de: "Steam Passwort erforderlich", es: "Se requiere contraseña de Steam", ru: "Требуется пароль Steam" }),
    passwordDesc: t({ en: "SteamCMD needs your password to log in. It will not be stored.", fr: "SteamCMD a besoin de votre mot de passe pour se connecter. Il ne sera pas stocké.", de: "SteamCMD benötigt dein Passwort zum Anmelden. Es wird nicht gespeichert.", es: "SteamCMD necesita tu contraseña para iniciar sesión. No se almacenará.", ru: "SteamCMD требует пароль для входа. Он не будет сохранён." }),
    passwordPlaceholder: t({ en: "Enter Steam password", fr: "Entrez le mot de passe Steam", de: "Steam Passwort eingeben", es: "Introduce la contraseña de Steam", ru: "Введите пароль Steam" }),
    passwordSend: t({ en: "Send", fr: "Envoyer", de: "Senden", es: "Enviar", ru: "Отправить" }),
    dontTrust: t({ en: "I don't trust this", fr: "Je ne fais pas confiance", de: "Ich vertraue dem nicht", es: "No confío en esto", ru: "Я не доверяю этому" }),
    copied: t({ en: "Copied!", fr: "Copié !", de: "Kopiert!", es: "¡Copiado!", ru: "Скопировано!" }),
    manualTitle: t({ en: "Login Manually via Terminal", fr: "Connexion manuelle via terminal", de: "Manuell über Terminal anmelden", es: "Iniciar sesión manualmente vía terminal", ru: "Ручной вход через терминал" }),
    manualCopied: t({ en: "The following command has been copied to your clipboard:", fr: "La commande suivante a été copiée dans votre presse-papiers :", de: "Der folgende Befehl wurde in die Zwischenablage kopiert:", es: "El siguiente comando se ha copiado al portapapeles:", ru: "Следующая команда скопирована в буфер обмена:" }),
    manualStep1: t({ en: "Open a terminal and paste the command", fr: "Ouvrez un terminal et collez la commande", de: "Öffne ein Terminal und füge den Befehl ein", es: "Abre una terminal y pega el comando", ru: "Откройте терминал и вставьте команду" }),
    manualStep2: t({ en: "Enter your password and complete Steam Guard if prompted", fr: "Entrez votre mot de passe et complétez Steam Guard si demandé", de: "Gib dein Passwort ein und bestätige Steam Guard falls nötig", es: "Introduce tu contraseña y completa Steam Guard si se solicita", ru: "Введите пароль и пройдите Steam Guard при необходимости" }),
    manualStep3: t({ en: "SteamCMD will cache your credentials locally", fr: "SteamCMD mettra vos identifiants en cache localement", de: "SteamCMD speichert deine Anmeldedaten lokal", es: "SteamCMD guardará tus credenciales localmente", ru: "SteamCMD сохранит учётные данные локально" }),
    manualStep4: t({ en: "Come back here and retry — no password will be needed", fr: "Revenez ici et réessayez — plus de mot de passe nécessaire", de: "Komm hierher zurück und versuche es erneut — kein Passwort wird benötigt", es: "Vuelve aquí y reintenta — no se necesitará contraseña", ru: "Вернитесь сюда и повторите — пароль не потребуется" }),
    manualNote: t({ en: "This app never sees your password. SteamCMD stores an encrypted credential token on your machine that it reuses for future logins.", fr: "Cette application ne voit jamais votre mot de passe. SteamCMD stocke un jeton chiffré sur votre machine qu'il réutilise pour les connexions futures.", de: "Diese App sieht dein Passwort nie. SteamCMD speichert ein verschlüsseltes Anmelde-Token auf deinem Computer das für zukünftige Anmeldungen wiederverwendet wird.", es: "Esta aplicación nunca ve tu contraseña. SteamCMD almacena un token de credencial cifrado en tu máquina que reutiliza para futuros inicios de sesión.", ru: "Это приложение никогда не видит ваш пароль. SteamCMD хранит зашифрованный токен на вашем компьютере для последующих входов." }),
    manualConfirm: t({ en: "Got it, cancel operation", fr: "Compris, annuler l'opération", de: "Verstanden, Vorgang abbrechen", es: "Entendido, cancelar operación", ru: "Понял, отменить операцию" }),
    dismiss: t({ en: "Dismiss", fr: "Fermer", de: "Schließen", es: "Descartar", ru: "Закрыть" }),
    working: t({ en: "Working…", fr: "En cours…", de: "Arbeite…", es: "Trabajando…", ru: "Работаю…" }),
    lines: insert(t({ en: "{{count}} lines", fr: "{{count}} lignes", de: "{{count}} Zeilen", es: "{{count}} líneas", ru: "{{count}} строк" })),
  },
} satisfies Dictionary;

export default content;
