import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "servers",
  content: {
    listUnavailable: t({
      en: "The server list could not be loaded",
      fr: "La liste des serveurs n'a pas pu être chargée",
      de: "Die Serverliste konnte nicht geladen werden",
      es: "No se pudo cargar la lista de servidores",
      ru: "Не удалось загрузить список серверов",
    }),
    savedPassword: t({
      en: "Password saved with this favourite",
      fr: "Mot de passe enregistré avec ce favori",
      de: "Passwort mit diesem Favoriten gespeichert",
      es: "Contraseña guardada con este favorito",
      ru: "Пароль сохранён в избранном",
    }),
    moreFilters: t({
      en: "More filters",
      fr: "Plus de filtres",
      de: "Weitere Filter",
      es: "Más filtros",
      ru: "Ещё фильтры",
    }),
    activeFilters: insert(
      t({
        en: "{{count}} active",
        fr: "{{count}} actif(s)",
        de: "{{count}} aktiv",
        es: "{{count}} activo(s)",
        ru: "активно: {{count}}",
      }),
    ),
    ping: t({ en: "Ping", fr: "Ping", de: "Ping", es: "Ping", ru: "Пинг" }),
    occupancy: t({
      en: "Occupancy",
      fr: "Occupation",
      de: "Belegung",
      es: "Ocupación",
      ru: "Заполненность",
    }),
    statShown: t({ en: "Shown", fr: "Affichés", de: "Angezeigt", es: "Mostrados", ru: "Показано" }),
    statPlayers: t({ en: "Players", fr: "Joueurs", de: "Spieler", es: "Jugadores", ru: "Игроки" }),
    statFull: t({ en: "Full", fr: "Pleins", de: "Voll", es: "Llenos", ru: "Заполнены" }),
    statEmpty: t({ en: "Empty", fr: "Vides", de: "Leer", es: "Vacíos", ru: "Пустые" }),
    statModded: t({ en: "Modded", fr: "Moddés", de: "Gemoddet", es: "Con mods", ru: "С модами" }),
    statBestPing: t({
      en: "Best ping",
      fr: "Meilleur ping",
      de: "Bester Ping",
      es: "Mejor ping",
      ru: "Лучший пинг",
    }),
    statPinged: t({ en: "Pinged", fr: "Pingés", de: "Angepingt", es: "Con ping", ru: "Опрошено" }),
    hideEmpty: t({
      en: "Hide empty",
      fr: "Masquer les vides",
      de: "Leere ausblenden",
      es: "Ocultar vacíos",
      ru: "Скрыть пустые",
    }),
    hideFull: t({
      en: "Hide full",
      fr: "Masquer les pleins",
      de: "Volle ausblenden",
      es: "Ocultar llenos",
      ru: "Скрыть заполненные",
    }),
    maxPing: t({
      en: "Max ping",
      fr: "Ping max",
      de: "Max. Ping",
      es: "Ping máx.",
      ru: "Макс. пинг",
    }),
    anyPing: t({
      en: "Any ping",
      fr: "Tout ping",
      de: "Jeder Ping",
      es: "Cualquier ping",
      ru: "Любой пинг",
    }),
    filters: t({ en: "Filters", fr: "Filtres", de: "Filter", es: "Filtros", ru: "Фильтры" }),
    serverList: t({
      en: "Server list",
      fr: "Liste des serveurs",
      de: "Serverliste",
      es: "Lista de servidores",
      ru: "Список серверов",
    }),
    selectServer: t({
      en: "Select a server to see its players, mods and rules",
      fr: "Sélectionnez un serveur pour voir ses joueurs, mods et règles",
      de: "Wähle einen Server, um Spieler, Mods und Regeln zu sehen",
      es: "Selecciona un servidor para ver sus jugadores, mods y reglas",
      ru: "Выберите сервер, чтобы увидеть игроков, моды и правила",
    }),
    directConnect: t({
      en: "Open in Direct Connect",
      fr: "Ouvrir dans Connexion directe",
      de: "In Direktverbindung öffnen",
      es: "Abrir en Conexión directa",
      ru: "Открыть в прямом подключении",
    }),
    pingNow: t({
      en: "Ping this server",
      fr: "Pinger ce serveur",
      de: "Diesen Server anpingen",
      es: "Hacer ping a este servidor",
      ru: "Пинговать сервер",
    }),
    copyLinkShort: t({
      en: "Copy dzch:// link",
      fr: "Copier le lien dzch://",
      de: "dzch://-Link kopieren",
      es: "Copiar enlace dzch://",
      ru: "Скопировать ссылку dzch://",
    }),
    includeIp: insert(
      t({
        en: "Stop excluding {{ip}}",
        fr: "Ne plus exclure {{ip}}",
        de: "{{ip}} nicht mehr ausschließen",
        es: "Dejar de excluir {{ip}}",
        ru: "Больше не исключать {{ip}}",
      }),
    ),
    copyLink: t({
      en: "Copy a dzch:// link to send to a friend",
      fr: "Copier un lien dzch:// à envoyer à un ami",
      de: "dzch://-Link zum Senden an einen Freund kopieren",
      es: "Copiar un enlace dzch:// para enviar a un amigo",
      ru: "Скопировать ссылку dzch:// для друга",
    }),
    lastPlayed: t({
      en: "Last played",
      fr: "Dernière partie",
      de: "Zuletzt gespielt",
      es: "Última partida",
      ru: "Последняя игра",
    }),
    lastPlayedRefresh: t({
      en: "Click to refresh player count",
      fr: "Cliquez pour actualiser le nombre de joueurs",
      de: "Klicken um Spieleranzahl zu aktualisieren",
      es: "Clic para actualizar recuento de jugadores",
      ru: "Нажмите для обновления количества игроков",
    }),
    lastPlayedPing: t({
      en: "Click to ping",
      fr: "Cliquez pour ping",
      de: "Klicken um Ping zu messen",
      es: "Clic para hacer ping",
      ru: "Нажмите для пинга",
    }),
    lastPlayedOffline: t({
      en: "OFFLINE",
      fr: "HORS LIGNE",
      de: "OFFLINE",
      es: "DESCONECTADO",
      ru: "ОФФЛАЙН",
    }),
    lastPlayedOfflineHint: t({
      en: "Server not found in current list — may be offline",
      fr: "Serveur non trouvé — peut être hors ligne",
      de: "Server nicht in aktueller Liste gefunden — möglicherweise offline",
      es: "Servidor no encontrado en la lista actual — puede estar desconectado",
      ru: "Сервер не найден в текущем списке — возможно, не в сети",
    }),
    lastPlayedReconnect: t({
      en: "Reconnect",
      fr: "Reconnecter",
      de: "Erneut verbinden",
      es: "Reconectar",
      ru: "Переподключиться",
    }),
    lastPlayedDismiss: t({
      en: "Dismiss",
      fr: "Ignorer",
      de: "Ausblenden",
      es: "Descartar",
      ru: "Скрыть",
    }),
    searchPlaceholder: t({
      en: "Search name, IP, map…",
      fr: "Rechercher nom, IP, carte…",
      de: "Name, IP, Karte suchen…",
      es: "Buscar nombre, IP, mapa…",
      ru: "Поиск по имени, IP, карте…",
    }),
    clearSearch: t({
      en: "Clear search",
      fr: "Effacer la recherche",
      de: "Suche löschen",
      es: "Limpiar búsqueda",
      ru: "Очистить поиск",
    }),
    allMaps: t({
      en: "All maps",
      fr: "Toutes les cartes",
      de: "Alle Karten",
      es: "Todos los mapas",
      ru: "Все карты",
    }),
    clearMapFilter: t({
      en: "Clear map filter",
      fr: "Effacer le filtre de carte",
      de: "Kartenfilter löschen",
      es: "Limpiar filtro de mapa",
      ru: "Сбросить фильтр карты",
    }),
    filterModsAll: t({
      en: "Mods: all",
      fr: "Mods : tous",
      de: "Mods: alle",
      es: "Mods: todos",
      ru: "Моды: все",
    }),
    filterModsOnly: t({
      en: "Mods only",
      fr: "Avec mods",
      de: "Nur Mods",
      es: "Solo con mods",
      ru: "Только с модами",
    }),
    filterModsNone: t({
      en: "No mods",
      fr: "Sans mods",
      de: "Keine Mods",
      es: "Sin mods",
      ru: "Без модов",
    }),
    figSortPlayers: t({
      en: "Busiest servers first",
      fr: "Les serveurs les plus peuplés d'abord",
      de: "Vollste Server zuerst",
      es: "Los servidores más poblados primero",
      ru: "Сначала самые заполненные",
    }),
    figSortPing: t({
      en: "Closest servers first",
      fr: "Les serveurs les plus proches d'abord",
      de: "Nächste Server zuerst",
      es: "Los servidores más cercanos primero",
      ru: "Сначала ближайшие серверы",
    }),
    figHideFull: t({
      en: "Hide the full servers",
      fr: "Masquer les serveurs pleins",
      de: "Volle Server ausblenden",
      es: "Ocultar los servidores llenos",
      ru: "Скрыть заполненные серверы",
    }),
    figShowFull: t({
      en: "Show the full servers again",
      fr: "Réafficher les serveurs pleins",
      de: "Volle Server wieder zeigen",
      es: "Volver a mostrar los servidores llenos",
      ru: "Снова показать заполненные серверы",
    }),
    figHideEmpty: t({
      en: "Hide the empty servers",
      fr: "Masquer les serveurs vides",
      de: "Leere Server ausblenden",
      es: "Ocultar los servidores vacíos",
      ru: "Скрыть пустые серверы",
    }),
    figShowEmpty: t({
      en: "Show the empty servers again",
      fr: "Réafficher les serveurs vides",
      de: "Leere Server wieder zeigen",
      es: "Volver a mostrar los servidores vacíos",
      ru: "Снова показать пустые серверы",
    }),
    figAllMods: t({
      en: "Show servers with and without mods",
      fr: "Afficher les serveurs avec et sans mods",
      de: "Server mit und ohne Mods zeigen",
      es: "Mostrar servidores con y sin mods",
      ru: "Показать серверы с модами и без",
    }),
    filterModsTitleAll: t({
      en: "Click to show only modded servers",
      fr: "Cliquez pour afficher uniquement les serveurs moddés",
      de: "Klicken für nur Server mit Mods",
      es: "Clic para mostrar solo servidores con mods",
      ru: "Нажмите, чтобы показать только серверы с модами",
    }),
    filterModsTitleOnly: t({
      en: "Click to hide modded servers",
      fr: "Cliquez pour masquer les serveurs moddés",
      de: "Klicken um Server mit Mods auszublenden",
      es: "Clic para ocultar servidores con mods",
      ru: "Нажмите, чтобы скрыть серверы с модами",
    }),
    filterModsTitleNone: t({
      en: "Click to show all servers",
      fr: "Cliquez pour afficher tous les serveurs",
      de: "Klicken für alle Server",
      es: "Clic para mostrar todos los servidores",
      ru: "Нажмите, чтобы показать все серверы",
    }),
    filterFpAll: t({
      en: "1P: all",
      fr: "1P : tous",
      de: "1P: alle",
      es: "1P: todos",
      ru: "1P: все",
    }),
    filterFpOnly: t({
      en: "1P only",
      fr: "1P seulement",
      de: "Nur 1P",
      es: "Solo 1P",
      ru: "Только 1P",
    }),
    filterFpNone: t({ en: "No 1P", fr: "Sans 1P", de: "Kein 1P", es: "Sin 1P", ru: "Без 1P" }),
    filterFpTitleAll: t({
      en: "1P = First-Person Only servers (no third-person camera). Click to show only 1P servers.",
      fr: "1P = Serveurs première personne uniquement. Cliquez pour n'afficher que les serveurs 1P.",
      de: "1P = Nur Ego-Perspektive (keine dritte Person). Klicken für nur 1P Server.",
      es: "1P = servidores solo en primera persona (sin cámara en tercera persona). Clic para mostrar solo servidores 1P.",
      ru: "1P = серверы только от первого лица (без камеры от третьего лица). Нажмите, чтобы показать только 1P серверы.",
    }),
    filterFpTitleOnly: t({
      en: "Showing first-person only servers. Click to exclude first-person servers.",
      fr: "Affichage des serveurs première personne. Cliquez pour les exclure.",
      de: "Zeige nur Ego-Perspektive Server. Klicken um diese auszuschließen.",
      es: "Mostrando servidores solo en primera persona. Clic para excluir servidores en primera persona.",
      ru: "Показаны серверы только от первого лица. Нажмите, чтобы исключить серверы от первого лица.",
    }),
    filterFpTitleNone: t({
      en: "Hiding first-person only servers. Click to show all servers.",
      fr: "Masquage des serveurs première personne. Cliquez pour tout afficher.",
      de: "Ego-Perspektive Server ausgeblendet. Klicken für alle Server.",
      es: "Ocultando servidores solo en primera persona. Clic para mostrar todos los servidores.",
      ru: "Серверы от первого лица скрыты. Нажмите, чтобы показать все серверы.",
    }),
    filterPwdAll: t({
      en: "Pwd: all",
      fr: "Mdp : tous",
      de: "Pwd: alle",
      es: "Pwd: todos",
      ru: "Пароль: все",
    }),
    filterPwdNone: t({
      en: "No pwd",
      fr: "Sans mdp",
      de: "Kein Pwd",
      es: "Sin pwd",
      ru: "Без пароля",
    }),
    filterPwdOnly: t({
      en: "Pwd only",
      fr: "Avec mdp",
      de: "Nur Pwd",
      es: "Solo pwd",
      ru: "С паролем",
    }),
    filterPwdTitleAll: t({
      en: "Click to hide password servers",
      fr: "Cliquez pour masquer les serveurs protégés",
      de: "Klicken um passwortgeschützte Server auszublenden",
      es: "Clic para ocultar servidores con contraseña",
      ru: "Нажмите, чтобы скрыть серверы с паролем",
    }),
    filterPwdTitleNone: t({
      en: "Click to show only password servers",
      fr: "Cliquez pour n'afficher que les serveurs protégés",
      de: "Klicken für nur passwortgeschützte Server",
      es: "Clic para mostrar solo servidores con contraseña",
      ru: "Нажмите, чтобы показать только серверы с паролем",
    }),
    filterPwdTitleOnly: t({
      en: "Click to show all servers",
      fr: "Cliquez pour afficher tous les serveurs",
      de: "Klicken für alle Server",
      es: "Clic para mostrar todos los servidores",
      ru: "Нажмите, чтобы показать все серверы",
    }),
    filterBeAll: t({
      en: "BE: all",
      fr: "BE : tous",
      de: "BE: alle",
      es: "BE: todos",
      ru: "BE: все",
    }),
    filterBeOnly: t({
      en: "BE only",
      fr: "BE seulement",
      de: "Nur BE",
      es: "Solo BE",
      ru: "Только BE",
    }),
    filterBeNone: t({ en: "No BE", fr: "Sans BE", de: "Kein BE", es: "Sin BE", ru: "Без BE" }),
    filterBeTitleAll: t({
      en: "Click to show only BattlEye servers",
      fr: "Cliquez pour n'afficher que les serveurs BattlEye",
      de: "Klicken für nur BattlEye Server",
      es: "Clic para mostrar solo servidores con BattlEye",
      ru: "Нажмите, чтобы показать только серверы с BattlEye",
    }),
    filterBeTitleOnly: t({
      en: "Click to hide BattlEye servers",
      fr: "Cliquez pour masquer les serveurs BattlEye",
      de: "Klicken um BattlEye Server auszublenden",
      es: "Clic para ocultar servidores con BattlEye",
      ru: "Нажмите, чтобы скрыть серверы с BattlEye",
    }),
    filterBeTitleNone: t({
      en: "Click to show all servers",
      fr: "Cliquez pour afficher tous les serveurs",
      de: "Klicken für alle Server",
      es: "Clic para mostrar todos los servidores",
      ru: "Нажмите, чтобы показать все серверы",
    }),
    official: t({
      en: "Official",
      fr: "Officiel",
      de: "Offiziell",
      es: "Oficial",
      ru: "Официальный",
    }),
    officialBadge: t({
      en: "OFFICIAL",
      fr: "OFFICIEL",
      de: "OFFIZIELL",
      es: "OFICIAL",
      ru: "ОФИЦ.",
    }),
    officialTitle: t({
      en: "Official server, run by Bohemia Interactive on the public hive",
      fr: "Serveur officiel, géré par Bohemia Interactive sur la hive publique",
      de: "Offizieller Server von Bohemia Interactive im öffentlichen Hive",
      es: "Servidor oficial, gestionado por Bohemia Interactive en la hive pública",
      ru: "Официальный сервер Bohemia Interactive на общем хайве",
    }),
    mimicsOfficial: t({
      en: "Looks official",
      fr: "Imite l'officiel",
      de: "Wirkt offiziell",
      es: "Imita al oficial",
      ru: "Похож на офиц.",
    }),
    mimicsOfficialTitle: t({
      en: "A community server named like an official one: it has its own hive and its own rules",
      fr: "Serveur communautaire nommé comme un officiel : il a sa propre hive et ses propres règles",
      de: "Community-Server, der wie ein offizieller heißt: eigener Hive, eigene Regeln",
      es: "Servidor comunitario con nombre de oficial: tiene su propia hive y sus propias reglas",
      ru: "Сервер сообщества с названием как у официального: свой хайв и свои правила",
    }),
    filterOfficialTitleAll: t({
      en: "Click to show only official servers",
      fr: "Cliquez pour n'afficher que les serveurs officiels",
      de: "Klicken für nur offizielle Server",
      es: "Clic para mostrar solo servidores oficiales",
      ru: "Нажмите, чтобы показать только официальные серверы",
    }),
    filterOfficialNoKey: t({
      en: "Official servers are listed once a Steam API key is set in Settings",
      fr: "Les serveurs officiels s'affichent une fois une clé API Steam renseignée dans les paramètres",
      de: "Offizielle Server erscheinen, sobald in den Einstellungen ein Steam-API-Schlüssel hinterlegt ist",
      es: "Los servidores oficiales aparecen al configurar una clave de API de Steam en Ajustes",
      ru: "Официальные серверы появятся после ввода ключа Steam API в настройках",
    }),
    excludedReveal: t({
      en: "Click to reveal excluded · hold 1.5s to manage",
      fr: "Cliquez pour révéler les exclus · maintenez 1,5s pour gérer",
      de: "Klicken zum Anzeigen · 1,5s halten zum Verwalten",
      es: "Clic para mostrar excluidos · mantén 1.5s para gestionar",
      ru: "Нажмите, чтобы показать исключённые · удерживайте 1.5 сек для управления",
    }),
    excludedHide: t({
      en: "Click to hide excluded · hold 1.5s to manage",
      fr: "Cliquez pour masquer les exclus · maintenez 1,5s pour gérer",
      de: "Klicken zum Ausblenden · 1,5s halten zum Verwalten",
      es: "Clic para ocultar excluidos · mantén 1.5s para gestionar",
      ru: "Нажмите, чтобы скрыть исключённые · удерживайте 1.5 сек для управления",
    }),
    excludedCount: insert(
      t({
        en: "Excluded: {{count}}",
        fr: "Exclus : {{count}}",
        de: "Ausgeschlossen: {{count}}",
        es: "Excluidos: {{count}}",
        ru: "Исключено: {{count}}",
      }),
    ),
    showAll: t({
      en: "Show all",
      fr: "Tout afficher",
      de: "Alle anzeigen",
      es: "Mostrar todos",
      ru: "Показать все",
    }),
    toggleDetails: t({
      en: "Toggle details panel",
      fr: "Basculer le panneau de détails",
      de: "Details ein-/ausblenden",
      es: "Alternar panel de detalles",
      ru: "Переключить панель деталей",
    }),
    details: t({ en: "Details", fr: "Détails", de: "Details", es: "Detalles", ru: "Детали" }),
    refreshTitle: t({
      en: "Refresh server list",
      fr: "Actualiser la liste des serveurs",
      de: "Serverliste aktualisieren",
      es: "Actualizar lista de servidores",
      ru: "Обновить список серверов",
    }),
    refresh: t({
      en: "Refresh",
      fr: "Actualiser",
      de: "Aktualisieren",
      es: "Actualizar",
      ru: "Обновить",
    }),
    pausePing: t({
      en: "Pause ping scan",
      fr: "Suspendre le scan ping",
      de: "Ping-Scan pausieren",
      es: "Pausar escaneo de ping",
      ru: "Приостановить сканирование",
    }),
    resumePing: t({
      en: "Resume ping scan",
      fr: "Reprendre le scan ping",
      de: "Ping-Scan fortsetzen",
      es: "Reanudar escaneo de ping",
      ru: "Возобновить сканирование",
    }),
    refreshing: t({
      en: "Refreshing server list…",
      fr: "Actualisation de la liste des serveurs…",
      de: "Serverliste wird aktualisiert…",
      es: "Actualizando lista de servidores…",
      ru: "Обновление списка серверов…",
    }),
    loaded: insert(
      t({
        en: "Loaded {{count}} servers",
        fr: "{{count}} serveurs chargés",
        de: "{{count}} Server geladen",
        es: "Cargados {{count}} servidores",
        ru: "Загружено {{count}} серверов",
      }),
    ),
    loadFailed: insert(
      t({
        en: "Failed to load servers: {{error}}",
        fr: "Échec du chargement des serveurs : {{error}}",
        de: "Serverliste konnte nicht geladen werden: {{error}}",
        es: "Error al cargar servidores: {{error}}",
        ru: "Не удалось загрузить серверы: {{error}}",
      }),
    ),
    refreshFailed: insert(
      t({
        en: "Refresh failed: {{error}}",
        fr: "Échec de l'actualisation : {{error}}",
        de: "Aktualisierung fehlgeschlagen: {{error}}",
        es: "Error al actualizar: {{error}}",
        ru: "Ошибка обновления: {{error}}",
      }),
    ),
    loading: t({
      en: "Loading servers…",
      fr: "Chargement des serveurs…",
      de: "Server werden geladen…",
      es: "Cargando servidores…",
      ru: "Загрузка серверов…",
    }),
    noMatch: t({
      en: "No servers match your search",
      fr: "Aucun serveur ne correspond à votre recherche",
      de: "Keine Server entsprechen der Suche",
      es: "Ningún servidor coincide con tu búsqueda",
      ru: "Нет серверов, соответствующих поиску",
    }),
    filterYes: insert(
      t({
        en: "{{label}}: yes",
        fr: "{{label}} : oui",
        de: "{{label}}: ja",
        es: "{{label}}: sí",
        ru: "{{label}}: да",
      }),
    ),
    filterNo: insert(
      t({
        en: "{{label}}: no",
        fr: "{{label}} : non",
        de: "{{label}}: nein",
        es: "{{label}}: no",
        ru: "{{label}}: нет",
      }),
    ),
    filterValue: insert(
      t({
        en: "{{label}}: {{value}}",
        fr: "{{label}} : {{value}}",
        de: "{{label}}: {{value}}",
        es: "{{label}}: {{value}}",
        ru: "{{label}}: {{value}}",
      }),
    ),
    filterSearch: insert(
      t({
        en: "Search: “{{query}}”",
        fr: "Recherche : « {{query}} »",
        de: "Suche: „{{query}}“",
        es: "Búsqueda: «{{query}}»",
        ru: "Поиск: «{{query}}»",
      }),
    ),
    filterRemove: insert(
      t({
        en: "Remove the filter {{label}}",
        fr: "Retirer le filtre {{label}}",
        de: "Filter {{label}} entfernen",
        es: "Quitar el filtro {{label}}",
        ru: "Убрать фильтр {{label}}",
      }),
    ),
    clearFilters: t({
      en: "Clear filters",
      fr: "Effacer les filtres",
      de: "Filter löschen",
      es: "Borrar filtros",
      ru: "Сбросить фильтры",
    }),
    staleData: insert(
      t({
        en: "Server data is {{minutes}} minutes old",
        fr: "Les données serveur datent de {{minutes}} minutes",
        de: "Serverdaten sind {{minutes}} Minuten alt",
        es: "Los datos del servidor tienen {{minutes}} minutos",
        ru: "Данные серверов устарели на {{minutes}} минут",
      }),
    ),
    colPing: t({ en: "Ping", fr: "Ping", de: "Ping", es: "Ping", ru: "Пинг" }),
    colPlayers: t({ en: "Players", fr: "Joueurs", de: "Spieler", es: "Jugadores", ru: "Игроки" }),
    colServer: t({ en: "Server", fr: "Serveur", de: "Server", es: "Servidor", ru: "Сервер" }),
    colMap: t({ en: "Map", fr: "Carte", de: "Karte", es: "Mapa", ru: "Карта" }),
    colTime: t({ en: "Time", fr: "Heure", de: "Zeit", es: "Hora", ru: "Время" }),
    colTimeTitle: t({
      en: "In-game server time",
      fr: "Heure en jeu du serveur",
      de: "Serverzeit im Spiel",
      es: "Hora del servidor en el juego",
      ru: "Игровое время на сервере",
    }),
    colMods: t({ en: "Mods", fr: "Mods", de: "Mods", es: "Mods", ru: "Моды" }),
    colOs: t({ en: "OS", fr: "OS", de: "OS", es: "SO", ru: "ОС" }),
    removeFavorite: t({
      en: "Remove from favorites",
      fr: "Retirer des favoris",
      de: "Aus Favoriten entfernen",
      es: "Quitar de favoritos",
      ru: "Убрать из избранного",
    }),
    addFavorite: t({
      en: "Add to favorites",
      fr: "Ajouter aux favoris",
      de: "Zu Favoriten hinzufügen",
      es: "Añadir a favoritos",
      ru: "Добавить в избранное",
    }),
    ipExcludedClick: insert(
      t({
        en: "{{ip}} is excluded — click to remove",
        fr: "{{ip}} est exclue — cliquez pour retirer",
        de: "{{ip}} ist ausgeschlossen — klicken zum Entfernen",
        es: "{{ip}} está excluida — clic para quitar",
        ru: "{{ip}} исключён — нажмите для удаления",
      }),
    ),
    excludeIp: insert(
      t({
        en: "Exclude {{ip}} from list",
        fr: "Exclure {{ip}} de la liste",
        de: "{{ip}} von Liste ausschließen",
        es: "Excluir {{ip}} de la lista",
        ru: "Исключить {{ip}} из списка",
      }),
    ),
    clickPing: t({
      en: "Click to ping",
      fr: "Cliquez pour ping",
      de: "Klicken zum Pingen",
      es: "Clic para hacer ping",
      ru: "Нажмите для пинга",
    }),
    clickRefreshPlayers: t({
      en: "Click to refresh player count",
      fr: "Cliquez pour actualiser le nombre de joueurs",
      de: "Klicken um Spieleranzahl zu aktualisieren",
      es: "Clic para actualizar recuento de jugadores",
      ru: "Нажмите для обновления количества игроков",
    }),
    copyIp: insert(
      t({
        en: "Copy {{address}} to clipboard",
        fr: "Copier {{address}} dans le presse-papiers",
        de: "{{address}} in Zwischenablage kopieren",
        es: "Copiar {{address}} al portapapeles",
        ru: "Скопировать {{address}} в буфер обмена",
      }),
    ),
    passwordProtected: t({
      en: "Password protected",
      fr: "Protégé par mot de passe",
      de: "Passwortgeschützt",
      es: "Protegido con contraseña",
      ru: "Защищён паролем",
    }),
    firstPerson: t({
      en: "First person only",
      fr: "Première personne uniquement",
      de: "Nur Ego-Perspektive",
      es: "Solo primera persona",
      ru: "Только от первого лица",
    }),
    battleye: t({ en: "BattlEye", fr: "BattlEye", de: "BattlEye", es: "BattlEye", ru: "BattlEye" }),
    modsAllReady: insert(
      t({
        en: "Its {{count}} mods are installed and current: joins at once",
        fr: "Ses {{count}} mods sont installés et à jour : connexion immédiate",
        de: "Seine {{count}} Mods sind installiert und aktuell: sofort beitreten",
        es: "Sus {{count}} mods están instalados y al día: entra al instante",
        ru: "Все {{count}} модов установлены и актуальны: вход сразу",
      }),
    ),
    modsMissingTip: insert(
      t({
        en: "{{missing}} of its {{count}} mods are not installed: downloaded when you join",
        fr: "{{missing}} de ses {{count}} mods ne sont pas installés : téléchargés en rejoignant",
        de: "{{missing}} seiner {{count}} Mods fehlen: werden beim Beitreten geladen",
        es: "{{missing}} de sus {{count}} mods no están instalados: se descargan al entrar",
        ru: "{{missing}} из {{count}} модов не установлены: скачаются при входе",
      }),
    ),
    modsStaleTip: insert(
      t({
        en: "{{stale}} of your copies need an update",
        fr: "{{stale}} de vos copies doivent être mises à jour",
        de: "{{stale}} deiner Kopien brauchen ein Update",
        es: "{{stale}} de tus copias necesitan actualizarse",
        ru: "{{stale}} ваших копий нужно обновить",
      }),
    ),
    showMods: t({
      en: "Show mod list",
      fr: "Afficher la liste des mods",
      de: "Mod-Liste anzeigen",
      es: "Mostrar lista de mods",
      ru: "Показать список модов",
    }),
    osWindows: t({ en: "Windows", fr: "Windows", de: "Windows", es: "Windows", ru: "Windows" }),
    osLinux: t({ en: "Linux", fr: "Linux", de: "Linux", es: "Linux", ru: "Linux" }),
    bots: insert(
      t({
        en: "{{count}} bots reported (often fake players)",
        fr: "{{count}} bots signalés (souvent de faux joueurs)",
        de: "{{count}} Bots gemeldet (oft Fake-Spieler)",
        es: "{{count}} bots reportados (a menudo jugadores falsos)",
        ru: "Ботов: {{count}} (часто фейковые игроки)",
      }),
    ),
    jumpTop: t({
      en: "Jump to top",
      fr: "Aller en haut",
      de: "Nach oben springen",
      es: "Ir arriba",
      ru: "Наверх",
    }),
    favorite: t({
      en: "Favorite",
      fr: "Favoris",
      de: "Favorit",
      es: "Favorito",
      ru: "В избранное",
    }),
    unfavorite: t({
      en: "Unfavorite",
      fr: "Retirer",
      de: "Entfernen",
      es: "Quitar favorito",
      ru: "Из избранного",
    }),
    info: t({ en: "Info", fr: "Info", de: "Info", es: "Info", ru: "Инфо" }),
    queryA2s: t({
      en: "Query live A2S info",
      fr: "Interroger les infos A2S",
      de: "Live A2S-Info abfragen",
      es: "Consultar info A2S en vivo",
      ru: "Запросить A2S информацию",
    }),
    connect: t({
      en: "Connect",
      fr: "Connexion",
      de: "Verbinden",
      es: "Conectar",
      ru: "Подключиться",
    }),
    connectTitle: t({
      en: "Launch DayZ and connect to this server",
      fr: "Lancer DayZ et se connecter à ce serveur",
      de: "DayZ starten und mit Server verbinden",
      es: "Iniciar DayZ y conectar a este servidor",
      ru: "Запустить DayZ и подключиться к серверу",
    }),
    copyIpPort: t({
      en: "Copy IP:port",
      fr: "Copier IP:port",
      de: "IP:Port kopieren",
      es: "Copiar IP:puerto",
      ru: "Скопировать IP:порт",
    }),
    copied: t({
      en: "Copied!",
      fr: "Copié !",
      de: "Kopiert!",
      es: "¡Copiado!",
      ru: "Скопировано!",
    }),
    modOne: insert(
      t({
        en: "{{count}} mod",
        fr: "{{count}} mod",
        de: "{{count}} Mod",
        es: "{{count}} mod",
        ru: "{{count}} мод",
      }),
    ),
    modOther: insert(
      t({
        en: "{{count}} mods",
        fr: "{{count}} mods",
        de: "{{count}} Mods",
        es: "{{count}} mods",
        ru: "{{count}} модов",
      }),
    ),
    a2sFailed: t({
      en: "A2S query failed",
      fr: "Requête A2S échouée",
      de: "A2S-Abfrage fehlgeschlagen",
      es: "Consulta A2S falló",
      ru: "Ошибка запроса A2S",
    }),
    pingTimeout: t({
      en: "Ping timed out - player count may be stale",
      fr: "Ping expiré - le nombre de joueurs peut être obsolète",
      de: "Ping-Timeout - Spielerzahl möglicherweise veraltet",
      es: "Ping agotado - el número de jugadores puede estar desactualizado",
      ru: "Таймаут пинга - количество игроков может быть устаревшим",
    }),
    playerCountUnverified: t({
      en: "Player count could not be verified - may be stale",
      fr: "Le nombre de joueurs n'a pas pu être vérifié - peut être obsolète",
      de: "Spielerzahl konnte nicht verifiziert werden - möglicherweise veraltet",
      es: "No se pudo verificar el número de jugadores - puede estar desactualizado",
      ru: "Не удалось проверить количество игроков - данные могут быть устаревшими",
    }),
  },
} satisfies Dictionary;

export default content;
