import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "settings",
  content: {
    account: t({ en: "Account settings", fr: "Paramètres du compte", de: "Kontoeinstellungen", es: "Configuración de cuenta", ru: "Настройки аккаунта" }),
    unnamedPlayer: t({ en: "Unnamed player", fr: "Joueur sans nom", de: "Unbenannter Spieler", es: "Jugador sin nombre", ru: "Безымянный игрок" }),
    noSteamLinked: t({ en: "No Steam account linked", fr: "Aucun compte Steam lié", de: "Kein Steam-Konto verknüpft", es: "No hay cuenta de Steam vinculada", ru: "Аккаунт Steam не привязан" }),
    steamLinked: insert(t({ en: "Steam: {{login}}", fr: "Steam : {{login}}", de: "Steam: {{login}}", es: "Steam: {{login}}", ru: "Steam: {{login}}" })),
    close: t({ en: "Close", fr: "Fermer", de: "Schließen", es: "Cerrar", ru: "Закрыть" }),
    identity: t({ en: "Identity", fr: "Identité", de: "Identität", es: "Identidad", ru: "Личность" }),
    ingameName: t({ en: "In-game name", fr: "Nom en jeu", de: "Spielername", es: "Nombre en el juego", ru: "Имя в игре" }),
    ingameNamePlaceholder: t({ en: "Your DayZ player name", fr: "Votre nom de joueur DayZ", de: "Dein DayZ Spielername", es: "Tu nombre de jugador en DayZ", ru: "Ваше имя игрока в DayZ" }),
    steamLogin: t({ en: "Steam Login", fr: "Connexion Steam", de: "Steam-Anmeldung", es: "Inicio de sesión en Steam", ru: "Вход в Steam" }),
    steamLoginDesc: t({ en: "for SteamCMD mod updates", fr: "pour les mises à jour de mods SteamCMD", de: "für SteamCMD Mod-Updates", es: "para actualizaciones de mods con SteamCMD", ru: "для обновления модов через SteamCMD" }),
    username: t({ en: "Username", fr: "Nom d'utilisateur", de: "Benutzername", es: "Usuario", ru: "Имя пользователя" }),
    password: t({ en: "Password", fr: "Mot de passe", de: "Passwort", es: "Contraseña", ru: "Пароль" }),
    passwordPlaceholder: t({ en: "Leave blank for cached credentials", fr: "Laisser vide pour les identifiants en cache", de: "Leer lassen für gespeicherte Anmeldedaten", es: "Dejar en blanco para credenciales en caché", ru: "Оставьте пустым для кешированных данных" }),
    steamRoot: t({ en: "Steam root", fr: "Dossier Steam", de: "Steam-Pfad", es: "Carpeta raíz de Steam", ru: "Корневая папка Steam" }),
    steamcmdPath: t({ en: "SteamCMD path", fr: "Chemin SteamCMD", de: "SteamCMD-Pfad", es: "Ruta de SteamCMD", ru: "Путь к SteamCMD" }),
    browse: t({ en: "Browse…", fr: "Parcourir…", de: "Durchsuchen…", es: "Examinar…", ru: "Обзор…" }),
    selectSteamRoot: t({ en: "Select Steam root (steamapps folder)", fr: "Sélectionner le dossier Steam (steamapps)", de: "Steam-Verzeichnis auswählen (steamapps Ordner)", es: "Seleccionar carpeta raíz de Steam (steamapps)", ru: "Выберите корневую папку Steam (steamapps)" }),
    selectSteamcmd: t({ en: "Select steamcmd binary", fr: "Sélectionner l'exécutable steamcmd", de: "steamcmd-Programm auswählen", es: "Seleccionar ejecutable de steamcmd", ru: "Выберите исполняемый файл steamcmd" }),
    passwordWarning: t({ en: "Password is stored in plaintext in profile.json", fr: "Le mot de passe est stocké en clair dans profile.json", de: "Passwort wird unverschlüsselt in profile.json gespeichert", es: "La contraseña se almacena en texto plano en profile.json", ru: "Пароль хранится в открытом виде в profile.json" }),
    clearPassword: t({ en: "Clear password from profile", fr: "Effacer le mot de passe du profil", de: "Passwort aus Profil entfernen", es: "Borrar contraseña del perfil", ru: "Удалить пароль из профиля" }),
    hide: t({ en: "Hide", fr: "Masquer", de: "Ausblenden", es: "Ocultar", ru: "Скрыть" }),
    show: t({ en: "Show", fr: "Afficher", de: "Anzeigen", es: "Mostrar", ru: "Показать" }),
    steamApi: t({ en: "Steam API", fr: "API Steam", de: "Steam API", es: "Steam API", ru: "Steam API" }),
    steamApiDesc: t({ en: "avatar in titlebar & mod update checks", fr: "avatar dans la barre de titre et vérification des mods", de: "Avatar in Titelleiste & Mod-Update-Prüfung", es: "avatar en la barra de título y comprobación de actualizaciones de mods", ru: "аватар в заголовке и проверка обновлений модов" }),
    apiKey: t({ en: "API key", fr: "Clé API", de: "API-Schlüssel", es: "Clave API", ru: "API ключ" }),
    steamId: t({ en: "Steam ID", fr: "Steam ID", de: "Steam-ID", es: "Steam ID", ru: "Steam ID" }),
    battlemetrics: t({ en: "BattleMetrics", fr: "BattleMetrics", de: "BattleMetrics", es: "BattleMetrics", ru: "BattleMetrics" }),
    battlemetricsDesc: t({ en: "rankings, uptime & distance", fr: "classements, disponibilité et distance", de: "Rankings, Verfügbarkeit & Entfernung", es: "rankings, tiempo activo y distancia", ru: "рейтинги, аптайм и расстояние" }),
    apiToken: t({ en: "API token", fr: "Jeton API", de: "API-Token", es: "Token API", ru: "API токен" }),
    yourLocation: t({ en: "Your Location", fr: "Votre position", de: "Dein Standort", es: "Tu ubicación", ru: "Ваше местоположение" }),
    locationDesc: t({ en: "for distance calculation", fr: "pour le calcul de distance", de: "für Entfernungsberechnung", es: "para cálculo de distancia", ru: "для расчёта расстояния" }),
    locationSet: t({ en: "Location set", fr: "Position définie", de: "Standort festgelegt", es: "Ubicación establecida", ru: "Местоположение задано" }),
    openMaps: t({ en: "Open in Google Maps", fr: "Ouvrir dans Google Maps", de: "In Google Maps öffnen", es: "Abrir en Google Maps", ru: "Открыть в Google Maps" }),
    clearLocation: t({ en: "Clear location", fr: "Effacer la position", de: "Standort löschen", es: "Borrar ubicación", ru: "Очистить местоположение" }),
    detecting: t({ en: "Detecting…", fr: "Détection…", de: "Wird erkannt…", es: "Detectando…", ru: "Определение…" }),
    autodetectIp: t({ en: "Auto-detect via IP", fr: "Détection auto via IP", de: "Automatisch per IP erkennen", es: "Autodetectar por IP", ru: "Автоопределение по IP" }),
    manual: t({ en: "Manual:", fr: "Manuel :", de: "Manuell:", es: "Manual:", ru: "Вручную:" }),
    lat: t({ en: "Lat", fr: "Lat", de: "Lat", es: "Lat", ru: "Шир." }),
    lon: t({ en: "Lon", fr: "Lon", de: "Lon", es: "Lon", ru: "Долг." }),
    getTokenAt: t({ en: "Get a token at", fr: "Obtenir un jeton sur", de: "Token erhältlich unter", es: "Obtener token en", ru: "Получить токен на" }),
    locationHelp: t({ en: "Location is used to calculate distance to servers.", fr: "La position est utilisée pour calculer la distance aux serveurs.", de: "Standort wird zur Entfernungsberechnung verwendet.", es: "La ubicación se usa para calcular la distancia a los servidores.", ru: "Местоположение используется для расчёта расстояния до серверов." }),
    cancel: t({ en: "Cancel", fr: "Annuler", de: "Abbrechen", es: "Cancelar", ru: "Отмена" }),
    excludedIps: t({ en: "Excluded IPs", fr: "IPs exclues", de: "Ausgeschlossene IPs", es: "IPs excluidas", ru: "Исключённые IP" }),
    manageExcluded: t({ en: "Manage excluded IPs", fr: "Gérer les IPs exclues", de: "Ausgeschlossene IPs verwalten", es: "Gestionar IPs excluidas", ru: "Управление исключёнными IP" }),
    save: t({ en: "Save changes", fr: "Enregistrer", de: "Speichern", es: "Guardar cambios", ru: "Сохранить изменения" }),
    profileLoadFailed: insert(t({ en: "Failed to load profile: {{error}}", fr: "Échec du chargement du profil : {{error}}", de: "Fehler beim Laden des Profils: {{error}}", es: "Error al cargar perfil: {{error}}", ru: "Не удалось загрузить профиль: {{error}}" })),
    profileSettingsSaved: t({ en: "Settings saved", fr: "Paramètres enregistrés", de: "Einstellungen gespeichert", es: "Configuración guardada", ru: "Настройки сохранены" }),
    profileSettingsSaveFailed: insert(t({ en: "Failed to save settings: {{error}}", fr: "Échec de l'enregistrement des paramètres : {{error}}", de: "Fehler beim Speichern der Einstellungen: {{error}}", es: "Error al guardar configuración: {{error}}", ru: "Не удалось сохранить настройки: {{error}}" })),
    profileOptionToggleFailed: insert(t({ en: "Failed: {{error}}", fr: "Échec : {{error}}", de: "Fehlgeschlagen: {{error}}", es: "Error: {{error}}", ru: "Ошибка: {{error}}" })),
    profileOptionSetFailed: insert(t({ en: "Failed: {{error}}", fr: "Échec : {{error}}", de: "Fehlgeschlagen: {{error}}", es: "Error: {{error}}", ru: "Ошибка: {{error}}" })),
    excludedIpsTitle: t({ en: "Excluded IPs", fr: "IPs exclues", de: "Ausgeschlossene IPs", es: "IPs excluidas", ru: "Исключённые IP" }),
    excludedIpsDesc: t({ en: "Servers from these IPs are hidden from the browser", fr: "Les serveurs de ces IPs sont masqués du navigateur", de: "Server mit diesen IPs werden im Browser ausgeblendet", es: "Los servidores de estas IPs están ocultos del navegador", ru: "Серверы с этих IP скрыты из браузера" }),
    excludedIpsNone: t({ en: "No excluded IPs", fr: "Aucune IP exclue", de: "Keine ausgeschlossenen IPs", es: "No hay IPs excluidas", ru: "Нет исключённых IP" }),
    excludedIpsRemove: insert(t({ en: "Remove exclusion for {{ip}}", fr: "Retirer l'exclusion pour {{ip}}", de: "Ausschluss für {{ip}} entfernen", es: "Quitar exclusión para {{ip}}", ru: "Убрать исключение для {{ip}}" })),
    excludedIpsCountOne: insert(t({ en: "{{count}} IP excluded", fr: "{{count}} IP exclue", de: "{{count}} IP ausgeschlossen", es: "{{count}} IP excluida", ru: "{{count}} IP исключён" })),
    excludedIpsCountOther: insert(t({ en: "{{count}} IPs excluded", fr: "{{count}} IPs exclues", de: "{{count}} IPs ausgeschlossen", es: "{{count}} IPs excluidas", ru: "{{count}} IP исключено" })),
    profileExportTitle: t({ en: "Export profile", fr: "Exporter le profil", de: "Profil exportieren", es: "Exportar perfil", ru: "Экспорт профиля" }),
    profileFilterName: t({ en: "DayZ Community Hub profile", fr: "Profil DayZ Community Hub", de: "DayZ Community Hub-Profil", es: "Perfil de DayZ Community Hub", ru: "Профиль DayZ Community Hub" }),
    profileExported: t({ en: "Profile exported successfully", fr: "Profil exporté avec succès", de: "Profil erfolgreich exportiert", es: "Perfil exportado correctamente", ru: "Профиль успешно экспортирован" }),
    profileExportFailed: insert(t({ en: "Export failed: {{error}}", fr: "Échec de l'export : {{error}}", de: "Export fehlgeschlagen: {{error}}", es: "Error en exportación: {{error}}", ru: "Ошибка экспорта: {{error}}" })),
    profileImportTitle: t({ en: "Import profile", fr: "Importer le profil", de: "Profil importieren", es: "Importar perfil", ru: "Импорт профиля" }),
    profileImportConfirmTitle: t({ en: "Import Profile", fr: "Importer le profil", de: "Profil importieren", es: "Importar perfil", ru: "Импорт профиля" }),
    profileImportConfirmMessage: t({ en: "This will overwrite your current profile, favorites, history and launch options. The app will restart to apply the changes. Continue?", fr: "Cela écrasera votre profil actuel, vos favoris, votre historique et vos options de lancement. L'application redémarrera pour appliquer les modifications. Continuer ?", de: "Dies überschreibt Ihr aktuelles Profil, Favoriten, Verlauf und Startoptionen. Die App wird neu gestartet, um die Änderungen anzuwenden. Fortfahren?", es: "Esto sobrescribirá tu perfil actual, favoritos, historial y opciones de inicio. La aplicación se reiniciará para aplicar los cambios. ¿Continuar?", ru: "Это перезапишет ваш текущий профиль, избранное, историю и параметры запуска. Приложение перезапустится для применения изменений. Продолжить?" }),
    profileImportFailed: t({ en: "Import failed", fr: "Échec de l'import", de: "Import fehlgeschlagen", es: "Error en importación", ru: "Ошибка импорта" }),
    profileResetTitle: t({ en: "Reset to Factory Defaults", fr: "Réinitialiser aux valeurs d'usine", de: "Auf Werkseinstellungen zurücksetzen", es: "Restablecer valores de fábrica", ru: "Сброс к заводским настройкам" }),
    profileResetMessage: t({ en: "This will delete all settings, favorites, history, cached server lists, and launch options — as if the app was never launched. Mods downloaded to your Steam workshop folder are not affected. The app will restart and the setup wizard will reappear.", fr: "Cela supprimera tous les paramètres, favoris, historique, listes de serveurs en cache et options de lancement — comme si l'application n'avait jamais été lancée. Les mods téléchargés dans votre dossier Steam Workshop ne sont pas affectés. L'application redémarrera et l'assistant de configuration réapparaîtra.", de: "Dies löscht alle Einstellungen, Favoriten, Verlauf, zwischengespeicherte Serverlisten und Startoptionen — als wäre die App nie gestartet worden. Heruntergeladene Mods im Steam-Workshop-Ordner sind nicht betroffen. Die App wird neu gestartet und der Einrichtungsassistent erscheint erneut.", es: "Esto eliminará toda la configuración, favoritos, historial, listas de servidores en caché y opciones de inicio — como si la aplicación nunca se hubiera iniciado. Los mods descargados en tu carpeta de workshop de Steam no se afectan. La aplicación se reiniciará y aparecerá el asistente de configuración.", ru: "Это удалит все настройки, избранное, историю, кешированные списки серверов и параметры запуска — как будто приложение никогда не запускалось. Моды, скачанные в папку Steam workshop, не затрагиваются. Приложение перезапустится и снова появится мастер настройки." }),
    profileResetFailed: t({ en: "Reset failed", fr: "Échec de la réinitialisation", de: "Zurücksetzen fehlgeschlagen", es: "Error al restablecer", ru: "Ошибка сброса" }),
  },
} satisfies Dictionary;

export default content;
