import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "settings",
  content: {
    sectionAccount: t({ en: "Account", fr: "Compte", de: "Konto", es: "Cuenta", ru: "Аккаунт" }),
    sectionSteam: t({ en: "Steam & SteamCMD", fr: "Steam et SteamCMD", de: "Steam & SteamCMD", es: "Steam y SteamCMD", ru: "Steam и SteamCMD" }),
    sectionApis: t({ en: "API keys", fr: "Clés d'API", de: "API-Schlüssel", es: "Claves de API", ru: "API-ключи" }),
    sectionLocation: t({ en: "Location", fr: "Position", de: "Standort", es: "Ubicación", ru: "Местоположение" }),
    sectionPing: t({ en: "Ping", fr: "Ping", de: "Ping", es: "Ping", ru: "Пинг" }),
    sectionExcluded: t({ en: "Excluded IPs", fr: "IP exclues", de: "Ausgeschlossene IPs", es: "IP excluidas", ru: "Исключённые IP" }),
    sectionAppearance: t({ en: "Appearance", fr: "Apparence", de: "Darstellung", es: "Apariencia", ru: "Оформление" }),
    sectionLanguage: t({ en: "Language", fr: "Langue", de: "Sprache", es: "Idioma", ru: "Язык" }),
    sectionWindow: t({ en: "Window", fr: "Fenêtre", de: "Fenster", es: "Ventana", ru: "Окно" }),
    sectionData: t({ en: "Profile data", fr: "Données du profil", de: "Profildaten", es: "Datos del perfil", ru: "Данные профиля" }),
    onThisPage: t({ en: "On this page", fr: "Sur cette page", de: "Auf dieser Seite", es: "En esta página", ru: "На этой странице" }),
    unsaved: t({ en: "Unsaved changes to your account", fr: "Modifications du compte non enregistrées", de: "Ungespeicherte Kontoänderungen", es: "Cambios de la cuenta sin guardar", ru: "Несохранённые изменения аккаунта" }),
    discard: t({ en: "Discard", fr: "Annuler les modifications", de: "Verwerfen", es: "Descartar", ru: "Отменить" }),
    ingameNameHint: t({ en: "Passed to DayZ as -name= when you join a server.", fr: "Transmis à DayZ via -name= quand vous rejoignez un serveur.", de: "Wird DayZ beim Beitritt als -name= übergeben.", es: "Se pasa a DayZ como -name= al unirte a un servidor.", ru: "Передаётся в DayZ как -name= при подключении." }),
    usernameHint: t({ en: "Leave empty to download mods anonymously where possible.", fr: "Laissez vide pour télécharger les mods anonymement quand c'est possible.", de: "Leer lassen, um Mods wenn möglich anonym zu laden.", es: "Déjalo vacío para descargar mods de forma anónima cuando sea posible.", ru: "Оставьте пустым для анонимной загрузки модов, где возможно." }),
    passwordHint: t({ en: "Only needed if SteamCMD has no cached login.", fr: "Utile seulement si SteamCMD n'a pas de session en cache.", de: "Nur nötig, wenn SteamCMD keine gespeicherte Anmeldung hat.", es: "Solo si SteamCMD no tiene una sesión guardada.", ru: "Нужен, только если у SteamCMD нет сохранённого входа." }),
    steamRootHint: t({ en: "The folder that contains steamapps. Detected automatically when empty.", fr: "Le dossier qui contient steamapps. Détecté automatiquement s'il est vide.", de: "Der Ordner mit steamapps. Wird automatisch erkannt, wenn leer.", es: "La carpeta que contiene steamapps. Se detecta sola si está vacía.", ru: "Папка, содержащая steamapps. Определяется автоматически, если пусто." }),
    steamcmdPathHint: t({ en: "Leave empty to use the one found on this machine.", fr: "Laissez vide pour utiliser celui trouvé sur cette machine.", de: "Leer lassen, um das gefundene zu verwenden.", es: "Déjalo vacío para usar el que se encuentre en este equipo.", ru: "Оставьте пустым, чтобы использовать найденный." }),
    steamcmdStatus: t({ en: "SteamCMD", fr: "SteamCMD", de: "SteamCMD", es: "SteamCMD", ru: "SteamCMD" }),
    steamcmdFound: t({ en: "Found", fr: "Trouvé", de: "Gefunden", es: "Encontrado", ru: "Найден" }),
    steamcmdMissing: t({ en: "Not found: mods cannot be downloaded", fr: "Introuvable : les mods ne peuvent pas être téléchargés", de: "Nicht gefunden: Mods können nicht geladen werden", es: "No encontrado: no se pueden descargar mods", ru: "Не найден: моды не загрузить" }),
    steamcmdDetect: t({ en: "Detect again", fr: "Détecter à nouveau", de: "Erneut suchen", es: "Detectar de nuevo", ru: "Найти снова" }),
    steamcmdInstallWin: t({ en: "Install SteamCMD", fr: "Installer SteamCMD", de: "SteamCMD installieren", es: "Instalar SteamCMD", ru: "Установить SteamCMD" }),
    steamcmdInstalling: t({ en: "Installing SteamCMD…", fr: "Installation de SteamCMD…", de: "SteamCMD wird installiert…", es: "Instalando SteamCMD…", ru: "Установка SteamCMD…" }),
    steamcmdInstallLinux: t({ en: "Install it with your package manager:", fr: "Installez-le avec votre gestionnaire de paquets :", de: "Installieren Sie es mit Ihrem Paketmanager:", es: "Instálalo con tu gestor de paquetes:", ru: "Установите его через менеджер пакетов:" }),
    steamApiHint: t({ en: "Shows your avatar and checks the Workshop for mod updates.", fr: "Affiche votre avatar et vérifie les mises à jour des mods sur le Workshop.", de: "Zeigt Ihren Avatar und prüft den Workshop auf Mod-Updates.", es: "Muestra tu avatar y busca actualizaciones de mods en el Workshop.", ru: "Показывает аватар и проверяет обновления модов в Workshop." }),
    steamIdHint: t({ en: "Your 17-digit SteamID64.", fr: "Votre SteamID64 à 17 chiffres.", de: "Ihre 17-stellige SteamID64.", es: "Tu SteamID64 de 17 dígitos.", ru: "Ваш 17-значный SteamID64." }),
    getKey: t({ en: "Get a key", fr: "Obtenir une clé", de: "Schlüssel holen", es: "Obtener una clave", ru: "Получить ключ" }),
    findSteamId: t({ en: "Find your ID", fr: "Trouver votre ID", de: "ID finden", es: "Buscar tu ID", ru: "Найти ID" }),
    bmHint: t({
      en: "Only useful with a paid BattleMetrics subscription: its API no longer answers free tokens. Server stats come from DayZ Metrics without any key.",
      fr: "Utile seulement avec un abonnement BattleMetrics payant : leur API ne répond plus aux jetons gratuits. Les stats des serveurs viennent de DayZ Metrics, sans clé.",
      de: "Nur mit einem kostenpflichtigen BattleMetrics-Abo nützlich: die API beantwortet keine kostenlosen Tokens mehr. Serverstatistiken kommen ohne Schlüssel von DayZ Metrics.",
      es: "Solo útil con una suscripción de pago a BattleMetrics: su API ya no responde a tokens gratuitos. Las estadísticas de servidores vienen de DayZ Metrics, sin clave.",
      ru: "Нужен только при платной подписке BattleMetrics: их API больше не отвечает на бесплатные токены. Статистика серверов берётся с DayZ Metrics без ключа.",
    }),
    locationDetected: t({ en: "Detected from your IP address", fr: "Détectée depuis votre adresse IP", de: "Aus Ihrer IP-Adresse ermittelt", es: "Detectada a partir de tu IP", ru: "Определено по IP-адресу" }),
    locationNone: t({ en: "No location set: distances to servers are hidden.", fr: "Aucune position : les distances aux serveurs sont masquées.", de: "Kein Standort: Entfernungen werden ausgeblendet.", es: "Sin ubicación: se ocultan las distancias.", ru: "Местоположение не задано: расстояния скрыты." }),
    locationInvalid: t({ en: "Latitude is −90 to 90, longitude −180 to 180.", fr: "La latitude va de −90 à 90, la longitude de −180 à 180.", de: "Breite −90 bis 90, Länge −180 bis 180.", es: "Latitud de −90 a 90, longitud de −180 a 180.", ru: "Широта от −90 до 90, долгота от −180 до 180." }),
    apply: t({ en: "Apply", fr: "Appliquer", de: "Übernehmen", es: "Aplicar", ru: "Применить" }),
    pingIntro: t({ en: "How the app measures the line to each server. Changes apply to the next scan.", fr: "Comment l'application mesure la ligne vers chaque serveur. Appliqué au prochain balayage.", de: "Wie die App die Verbindung zu jedem Server misst. Gilt ab dem nächsten Scan.", es: "Cómo mide la app la conexión a cada servidor. Se aplica en el próximo escaneo.", ru: "Как приложение измеряет связь с сервером. Применяется при следующем сканировании." }),
    pingConcurrencyHint: t({ en: "Servers asked at once. Higher is faster but can flood a weak connection.", fr: "Serveurs interrogés en même temps. Plus haut = plus rapide, mais peut saturer une connexion faible.", de: "Gleichzeitig abgefragte Server. Höher ist schneller, kann aber schwache Leitungen überlasten.", es: "Servidores consultados a la vez. Más es más rápido pero puede saturar una conexión débil.", ru: "Одновременные запросы. Больше — быстрее, но может перегрузить слабый канал." }),
    pingTimeoutAutoHint: t({ en: "How long the background scan waits for an answer.", fr: "Temps d'attente d'une réponse pendant le balayage.", de: "Wartezeit auf eine Antwort beim Hintergrund-Scan.", es: "Espera de respuesta del escaneo en segundo plano.", ru: "Ожидание ответа при фоновом сканировании." }),
    pingTimeoutManualHint: t({ en: "How long a ping you ask for waits.", fr: "Temps d'attente d'un ping demandé à la main.", de: "Wartezeit eines manuellen Pings.", es: "Espera de un ping manual.", ru: "Ожидание ручного пинга." }),
    pingMaxRetriesHint: t({ en: "Timeouts in a row before a server is no longer asked while scrolling.", fr: "Délais dépassés d'affilée avant de ne plus interroger un serveur au défilement.", de: "Zeitüberschreitungen in Folge, bevor ein Server beim Scrollen nicht mehr gefragt wird.", es: "Tiempos agotados seguidos antes de dejar de consultar un servidor al desplazarse.", ru: "Таймаутов подряд, после которых сервер не опрашивается при прокрутке." }),
    pingScopeHint: t({ en: "Which servers the startup scan pings, in this order.", fr: "Serveurs pingés au démarrage, dans cet ordre.", de: "Welche Server der Start-Scan anpingt, in dieser Reihenfolge.", es: "Servidores que el escaneo inicial consulta, en este orden.", ru: "Какие серверы пингуются при запуске, по порядку." }),
    excludedHint: t({ en: "Servers from these addresses are hidden from the list. Exclude one from its row's menu.", fr: "Les serveurs de ces adresses sont masqués. Excluez-en un depuis le menu de sa ligne.", de: "Server dieser Adressen werden ausgeblendet. Über das Zeilenmenü ausschließen.", es: "Los servidores de estas direcciones se ocultan. Exclúyelos desde el menú de su fila.", ru: "Серверы с этих адресов скрыты. Исключайте через меню строки." }),
    followSystem: t({ en: "Follow the system", fr: "Suivre le système", de: "System folgen", es: "Seguir al sistema", ru: "Как в системе" }),
    followSystemHint: t({ en: "Chernarus when the desktop is dark, survey map when it is light.", fr: "Tchernarus quand le bureau est sombre, carte d'état-major quand il est clair.", de: "Tschernarus bei dunklem, Messtischblatt bei hellem Desktop.", es: "Chernarus con escritorio oscuro, mapa topográfico con claro.", ru: "Чернарусь для тёмной темы системы, топокарта — для светлой." }),
    yourTheme: t({ en: "Your theme", fr: "Votre thème", de: "Ihr Design", es: "Tu tema", ru: "Ваша тема" }),
    yourThemeHint: t({ en: "Twelve colours; every border, tint and muted text is worked out from them.", fr: "Douze couleurs ; bordures, teintes et textes atténués en sont déduits.", de: "Zwölf Farben; Rahmen, Tönungen und gedämpfter Text werden daraus abgeleitet.", es: "Doce colores; bordes, tintes y texto atenuado se derivan de ellos.", ru: "Двенадцать цветов; рамки, оттенки и приглушённый текст выводятся из них." }),
    customize: t({ en: "Customize", fr: "Personnaliser", de: "Anpassen", es: "Personalizar", ru: "Настроить" }),
    startFrom: t({ en: "Start from", fr: "Partir de", de: "Ausgehen von", es: "Partir de", ru: "На основе" }),
    tokenBg: t({ en: "Window floor", fr: "Fond de la fenêtre", de: "Fenstergrund", es: "Fondo de la ventana", ru: "Фон окна" }),
    tokenPanel: t({ en: "Panels", fr: "Panneaux", de: "Flächen", es: "Paneles", ru: "Панели" }),
    tokenRaised: t({ en: "Controls & hover", fr: "Contrôles et survol", de: "Bedienelemente & Hover", es: "Controles y hover", ru: "Элементы и наведение" }),
    tokenFg: t({ en: "Text", fr: "Texte", de: "Text", es: "Texto", ru: "Текст" }),
    tokenAccent: t({ en: "Accent", fr: "Accent", de: "Akzent", es: "Acento", ru: "Акцент" }),
    tokenAccentFg: t({ en: "Text on accent", fr: "Texte sur accent", de: "Text auf Akzent", es: "Texto sobre acento", ru: "Текст на акценте" }),
    tokenOk: t({ en: "Good", fr: "Bon", de: "Gut", es: "Bien", ru: "Хорошо" }),
    tokenWarn: t({ en: "Warning", fr: "Avertissement", de: "Warnung", es: "Aviso", ru: "Предупреждение" }),
    tokenErr: t({ en: "Error", fr: "Erreur", de: "Fehler", es: "Error", ru: "Ошибка" }),
    tokenInfo: t({ en: "Information", fr: "Information", de: "Information", es: "Información", ru: "Информация" }),
    tokenMap: t({ en: "Map names", fr: "Noms de carte", de: "Kartennamen", es: "Nombres de mapa", ru: "Названия карт" }),
    tokenMods: t({ en: "Mods", fr: "Mods", de: "Mods", es: "Mods", ru: "Моды" }),
    themeCopied: t({ en: "Theme copied to the clipboard", fr: "Thème copié dans le presse-papiers", de: "Design in die Zwischenablage kopiert", es: "Tema copiado al portapapeles", ru: "Тема скопирована" }),
    windowHint: t({ en: "How the frameless window is drawn. Rounded corners need a compositor that supports them.", fr: "Rendu de la fenêtre sans bordure. Les coins arrondis demandent un compositeur compatible.", de: "Darstellung des rahmenlosen Fensters. Runde Ecken brauchen einen passenden Compositor.", es: "Cómo se dibuja la ventana sin marco. Las esquinas redondeadas requieren un compositor compatible.", ru: "Как рисуется окно без рамки. Скругление требует поддержки композитора." }),
    windowRadius: t({ en: "Corner radius", fr: "Rayon des coins", de: "Eckenradius", es: "Radio de esquinas", ru: "Радиус углов" }),
    windowBorder: t({ en: "Border", fr: "Bordure", de: "Rahmen", es: "Borde", ru: "Рамка" }),
    windowBorderFocus: t({ en: "When focused", fr: "Fenêtre active", de: "Aktiv", es: "Con foco", ru: "Активно" }),
    windowBorderBlur: t({ en: "When unfocused", fr: "Fenêtre inactive", de: "Inaktiv", es: "Sin foco", ru: "Неактивно" }),
    languageHint: t({ en: "The interface language. Server names and mod names stay as their authors wrote them.", fr: "La langue de l'interface. Les noms de serveurs et de mods restent tels que leurs auteurs les ont écrits.", de: "Sprache der Oberfläche. Server- und Modnamen bleiben wie von ihren Autoren geschrieben.", es: "Idioma de la interfaz. Los nombres de servidores y mods no cambian.", ru: "Язык интерфейса. Названия серверов и модов не переводятся." }),
    dataHint: t({ en: "Your profile holds settings, favourites, history and launch options. Installed mods are never touched.", fr: "Le profil contient réglages, favoris, historique et options de lancement. Les mods installés ne sont jamais touchés.", de: "Das Profil enthält Einstellungen, Favoriten, Verlauf und Startoptionen. Installierte Mods bleiben unberührt.", es: "El perfil guarda ajustes, favoritos, historial y opciones de inicio. Los mods instalados nunca se tocan.", ru: "Профиль хранит настройки, избранное, историю и параметры запуска. Моды не затрагиваются." }),
    dangerZone: t({ en: "Danger zone", fr: "Zone sensible", de: "Gefahrenbereich", es: "Zona peligrosa", ru: "Опасная зона" }),
    account: t({ en: "Account settings", fr: "Paramètres du compte", de: "Kontoeinstellungen", es: "Configuración de cuenta", ru: "Настройки аккаунта" }),
    unnamedPlayer: t({ en: "Unnamed player", fr: "Joueur sans nom", de: "Unbenannter Spieler", es: "Jugador sin nombre", ru: "Безымянный игрок" }),
    noSteamLinked: t({ en: "No Steam account linked", fr: "Aucun compte Steam lié", de: "Kein Steam-Konto verknüpft", es: "No hay cuenta de Steam vinculada", ru: "Аккаунт Steam не привязан" }),
    steamLinked: insert(t({ en: "Steam: {{login}}", fr: "Steam : {{login}}", de: "Steam: {{login}}", es: "Steam: {{login}}", ru: "Steam: {{login}}" })),
    close: t({ en: "Close", fr: "Fermer", de: "Schließen", es: "Cerrar", ru: "Закрыть" }),
    identity: t({ en: "Identity", fr: "Identité", de: "Identität", es: "Identidad", ru: "Личность" }),
    ingameName: t({ en: "In-game name", fr: "Nom en jeu", de: "Spielername", es: "Nombre en el juego", ru: "Имя в игре" }),
    ingameNamePlaceholder: t({ en: "Your DayZ player name", fr: "Votre nom de joueur DayZ", de: "Dein DayZ Spielername", es: "Tu nombre de jugador en DayZ", ru: "Ваше имя игрока в DayZ" }),
    steamLogin: t({ en: "Steam Login", fr: "Connexion Steam", de: "Steam-Anmeldung", es: "Inicio de sesión en Steam", ru: "Вход в Steam" }),
    steamLoginDesc: t({ en: "for SteamCMD mod updates", fr: "pour les mises à jour de mods SteamCMD", de: "für SteamCMD Mod-Updates", es: "para actualizaciones de mods con SteamCMD", ru: "для обновления модов через SteamCMD" }),
    username: t({ en: "Username", fr: "Nom d'utilisateur", de: "Benutzername", es: "Usuario", ru: "Имя пользователя" }),
    password: t({ en: "Password", fr: "Mot de passe", de: "Passwort", es: "Contraseña", ru: "Пароль" }),
    passwordPlaceholder: t({ en: "Leave blank for cached credentials", fr: "Laisser vide pour les identifiants en cache", de: "Leer lassen für gespeicherte Anmeldedaten", es: "Dejar en blanco para credenciales en caché", ru: "Оставьте пустым для кешированных данных" }),
    steamRoot: t({ en: "Steam root", fr: "Dossier Steam", de: "Steam-Pfad", es: "Carpeta raíz de Steam", ru: "Корневая папка Steam" }),
    steamcmdPath: t({ en: "SteamCMD path", fr: "Chemin SteamCMD", de: "SteamCMD-Pfad", es: "Ruta de SteamCMD", ru: "Путь к SteamCMD" }),
    browse: t({ en: "Browse…", fr: "Parcourir…", de: "Durchsuchen…", es: "Examinar…", ru: "Обзор…" }),
    selectSteamRoot: t({ en: "Select Steam root (steamapps folder)", fr: "Sélectionner le dossier Steam (steamapps)", de: "Steam-Verzeichnis auswählen (steamapps Ordner)", es: "Seleccionar carpeta raíz de Steam (steamapps)", ru: "Выберите корневую папку Steam (steamapps)" }),
    selectSteamcmd: t({ en: "Select steamcmd binary", fr: "Sélectionner l'exécutable steamcmd", de: "steamcmd-Programm auswählen", es: "Seleccionar ejecutable de steamcmd", ru: "Выберите исполняемый файл steamcmd" }),
    passwordWarning: t({ en: "Password is stored in plaintext in profile.json", fr: "Le mot de passe est stocké en clair dans profile.json", de: "Passwort wird unverschlüsselt in profile.json gespeichert", es: "La contraseña se almacena en texto plano en profile.json", ru: "Пароль хранится в открытом виде в profile.json" }),
    clearPassword: t({ en: "Clear password from profile", fr: "Effacer le mot de passe du profil", de: "Passwort aus Profil entfernen", es: "Borrar contraseña del perfil", ru: "Удалить пароль из профиля" }),
    hide: t({ en: "Hide", fr: "Masquer", de: "Ausblenden", es: "Ocultar", ru: "Скрыть" }),
    show: t({ en: "Show", fr: "Afficher", de: "Anzeigen", es: "Mostrar", ru: "Показать" }),
    steamApi: t({ en: "Steam API", fr: "API Steam", de: "Steam API", es: "Steam API", ru: "Steam API" }),
    steamApiDesc: t({ en: "avatar in titlebar & mod update checks", fr: "avatar dans la barre de titre et vérification des mods", de: "Avatar in Titelleiste & Mod-Update-Prüfung", es: "avatar en la barra de título y comprobación de actualizaciones de mods", ru: "аватар в заголовке и проверка обновлений модов" }),
    apiKey: t({ en: "API key", fr: "Clé API", de: "API-Schlüssel", es: "Clave API", ru: "API ключ" }),
    steamId: t({ en: "Steam ID", fr: "Steam ID", de: "Steam-ID", es: "Steam ID", ru: "Steam ID" }),
    battlemetrics: t({ en: "BattleMetrics", fr: "BattleMetrics", de: "BattleMetrics", es: "BattleMetrics", ru: "BattleMetrics" }),
    battlemetricsDesc: t({
      en: "optional, paid subscription only",
      fr: "facultatif, abonnement payant uniquement",
      de: "optional, nur mit kostenpflichtigem Abo",
      es: "opcional, solo con suscripción de pago",
      ru: "необязательно, только платная подписка",
    }),
    apiToken: t({ en: "API token", fr: "Jeton API", de: "API-Token", es: "Token API", ru: "API токен" }),
    yourLocation: t({ en: "Your Location", fr: "Votre position", de: "Dein Standort", es: "Tu ubicación", ru: "Ваше местоположение" }),
    locationDesc: t({ en: "for distance calculation", fr: "pour le calcul de distance", de: "für Entfernungsberechnung", es: "para cálculo de distancia", ru: "для расчёта расстояния" }),
    locationSet: t({ en: "Location set", fr: "Position définie", de: "Standort festgelegt", es: "Ubicación establecida", ru: "Местоположение задано" }),
    openMaps: t({ en: "Open in Google Maps", fr: "Ouvrir dans Google Maps", de: "In Google Maps öffnen", es: "Abrir en Google Maps", ru: "Открыть в Google Maps" }),
    clearLocation: t({ en: "Clear location", fr: "Effacer la position", de: "Standort löschen", es: "Borrar ubicación", ru: "Очистить местоположение" }),
    detecting: t({ en: "Detecting…", fr: "Détection…", de: "Wird erkannt…", es: "Detectando…", ru: "Определение…" }),
    autodetectIp: t({ en: "Auto-detect via IP", fr: "Détection auto via IP", de: "Automatisch per IP erkennen", es: "Autodetectar por IP", ru: "Автоопределение по IP" }),
    manual: t({ en: "Manual:", fr: "Manuel :", de: "Manuell:", es: "Manual:", ru: "Вручную:" }),
    lat: t({ en: "Lat", fr: "Lat", de: "Lat", es: "Lat", ru: "Шир." }),
    lon: t({ en: "Lon", fr: "Lon", de: "Lon", es: "Lon", ru: "Долг." }),
    getTokenAt: t({ en: "Get a token at", fr: "Obtenir un jeton sur", de: "Token erhältlich unter", es: "Obtener token en", ru: "Получить токен на" }),
    locationHelp: t({ en: "Location is used to calculate distance to servers.", fr: "La position est utilisée pour calculer la distance aux serveurs.", de: "Standort wird zur Entfernungsberechnung verwendet.", es: "La ubicación se usa para calcular la distancia a los servidores.", ru: "Местоположение используется для расчёта расстояния до серверов." }),
    cancel: t({ en: "Cancel", fr: "Annuler", de: "Abbrechen", es: "Cancelar", ru: "Отмена" }),
    excludedIps: t({ en: "Excluded IPs", fr: "IPs exclues", de: "Ausgeschlossene IPs", es: "IPs excluidas", ru: "Исключённые IP" }),
    manageExcluded: t({ en: "Manage excluded IPs", fr: "Gérer les IPs exclues", de: "Ausgeschlossene IPs verwalten", es: "Gestionar IPs excluidas", ru: "Управление исключёнными IP" }),
    save: t({ en: "Save changes", fr: "Enregistrer", de: "Speichern", es: "Guardar cambios", ru: "Сохранить изменения" }),
    profileLoadFailed: insert(t({ en: "Failed to load profile: {{error}}", fr: "Échec du chargement du profil : {{error}}", de: "Fehler beim Laden des Profils: {{error}}", es: "Error al cargar perfil: {{error}}", ru: "Не удалось загрузить профиль: {{error}}" })),
    profileSettingsSaved: t({ en: "Settings saved", fr: "Paramètres enregistrés", de: "Einstellungen gespeichert", es: "Configuración guardada", ru: "Настройки сохранены" }),
    profileSettingsSaveFailed: insert(t({ en: "Failed to save settings: {{error}}", fr: "Échec de l'enregistrement des paramètres : {{error}}", de: "Fehler beim Speichern der Einstellungen: {{error}}", es: "Error al guardar configuración: {{error}}", ru: "Не удалось сохранить настройки: {{error}}" })),
    profileOptionToggleFailed: insert(t({ en: "Failed: {{error}}", fr: "Échec : {{error}}", de: "Fehlgeschlagen: {{error}}", es: "Error: {{error}}", ru: "Ошибка: {{error}}" })),
    profileOptionSetFailed: insert(t({ en: "Failed: {{error}}", fr: "Échec : {{error}}", de: "Fehlgeschlagen: {{error}}", es: "Error: {{error}}", ru: "Ошибка: {{error}}" })),
    excludedIpsTitle: t({ en: "Excluded IPs", fr: "IPs exclues", de: "Ausgeschlossene IPs", es: "IPs excluidas", ru: "Исключённые IP" }),
    excludedIpsDesc: t({ en: "Servers from these IPs are hidden from the browser", fr: "Les serveurs de ces IPs sont masqués du navigateur", de: "Server mit diesen IPs werden im Browser ausgeblendet", es: "Los servidores de estas IPs están ocultos del navegador", ru: "Серверы с этих IP скрыты из браузера" }),
    excludedIpsNone: t({ en: "No excluded IPs", fr: "Aucune IP exclue", de: "Keine ausgeschlossenen IPs", es: "No hay IPs excluidas", ru: "Нет исключённых IP" }),
    excludedIpsRemove: insert(t({ en: "Remove exclusion for {{ip}}", fr: "Retirer l'exclusion pour {{ip}}", de: "Ausschluss für {{ip}} entfernen", es: "Quitar exclusión para {{ip}}", ru: "Убрать исключение для {{ip}}" })),
    excludedIpsCountOne: insert(t({ en: "{{count}} IP excluded", fr: "{{count}} IP exclue", de: "{{count}} IP ausgeschlossen", es: "{{count}} IP excluida", ru: "{{count}} IP исключён" })),
    excludedIpsCountOther: insert(t({ en: "{{count}} IPs excluded", fr: "{{count}} IPs exclues", de: "{{count}} IPs ausgeschlossen", es: "{{count}} IPs excluidas", ru: "{{count}} IP исключено" })),
    profileExportTitle: t({ en: "Export profile", fr: "Exporter le profil", de: "Profil exportieren", es: "Exportar perfil", ru: "Экспорт профиля" }),
    profileFilterName: t({ en: "DayZ Community Hub profile", fr: "Profil DayZ Community Hub", de: "DayZ Community Hub-Profil", es: "Perfil de DayZ Community Hub", ru: "Профиль DayZ Community Hub" }),
    profileExported: t({ en: "Profile exported successfully", fr: "Profil exporté avec succès", de: "Profil erfolgreich exportiert", es: "Perfil exportado correctamente", ru: "Профиль успешно экспортирован" }),
    profileExportFailed: insert(t({ en: "Export failed: {{error}}", fr: "Échec de l'export : {{error}}", de: "Export fehlgeschlagen: {{error}}", es: "Error en exportación: {{error}}", ru: "Ошибка экспорта: {{error}}" })),
    profileImportTitle: t({ en: "Import profile", fr: "Importer le profil", de: "Profil importieren", es: "Importar perfil", ru: "Импорт профиля" }),
    profileImportConfirmTitle: t({ en: "Import Profile", fr: "Importer le profil", de: "Profil importieren", es: "Importar perfil", ru: "Импорт профиля" }),
    profileImportConfirmMessage: t({ en: "This will overwrite your current profile, favorites, history and launch options. The app will restart to apply the changes. Continue?", fr: "Cela écrasera votre profil actuel, vos favoris, votre historique et vos options de lancement. L'application redémarrera pour appliquer les modifications. Continuer ?", de: "Dies überschreibt Ihr aktuelles Profil, Favoriten, Verlauf und Startoptionen. Die App wird neu gestartet, um die Änderungen anzuwenden. Fortfahren?", es: "Esto sobrescribirá tu perfil actual, favoritos, historial y opciones de inicio. La aplicación se reiniciará para aplicar los cambios. ¿Continuar?", ru: "Это перезапишет ваш текущий профиль, избранное, историю и параметры запуска. Приложение перезапустится для применения изменений. Продолжить?" }),
    profileImportFailed: t({ en: "Import failed", fr: "Échec de l'import", de: "Import fehlgeschlagen", es: "Error en importación", ru: "Ошибка импорта" }),
    profileResetTitle: t({ en: "Reset to Factory Defaults", fr: "Réinitialiser aux valeurs d'usine", de: "Auf Werkseinstellungen zurücksetzen", es: "Restablecer valores de fábrica", ru: "Сброс к заводским настройкам" }),
    profileResetMessage: t({ en: "This will delete all settings, favorites, history, cached server lists, and launch options — as if the app was never launched. Mods downloaded to your Steam workshop folder are not affected. The app will restart and the setup wizard will reappear.", fr: "Cela supprimera tous les paramètres, favoris, historique, listes de serveurs en cache et options de lancement — comme si l'application n'avait jamais été lancée. Les mods téléchargés dans votre dossier Steam Workshop ne sont pas affectés. L'application redémarrera et l'assistant de configuration réapparaîtra.", de: "Dies löscht alle Einstellungen, Favoriten, Verlauf, zwischengespeicherte Serverlisten und Startoptionen — als wäre die App nie gestartet worden. Heruntergeladene Mods im Steam-Workshop-Ordner sind nicht betroffen. Die App wird neu gestartet und der Einrichtungsassistent erscheint erneut.", es: "Esto eliminará toda la configuración, favoritos, historial, listas de servidores en caché y opciones de inicio — como si la aplicación nunca se hubiera iniciado. Los mods descargados en tu carpeta de workshop de Steam no se afectan. La aplicación se reiniciará y aparecerá el asistente de configuración.", ru: "Это удалит все настройки, избранное, историю, кешированные списки серверов и параметры запуска — как будто приложение никогда не запускалось. Моды, скачанные в папку Steam workshop, не затрагиваются. Приложение перезапустится и снова появится мастер настройки." }),
    profileResetFailed: t({ en: "Reset failed", fr: "Échec de la réinitialisation", de: "Zurücksetzen fehlgeschlagen", es: "Error al restablecer", ru: "Ошибка сброса" }),
  },
} satisfies Dictionary;

export default content;
