import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "setup",
  content: {
    welcomeTitle: t({ en: "Welcome to DayZ Community Hub", fr: "Bienvenue sur DayZ Community Hub", de: "Willkommen bei DayZ Community Hub", es: "Bienvenido a DayZ Community Hub", ru: "Добро пожаловать в DayZ Community Hub" }),
    welcomeSubtitle: t({ en: "A server browser and mod manager for DayZ Standalone", fr: "Un navigateur de serveurs et gestionnaire de mods pour DayZ Standalone", de: "Ein Server-Browser und Mod-Manager für DayZ Standalone", es: "Un navegador de servidores y gestor de mods para DayZ Standalone", ru: "Браузер серверов и менеджер модов для DayZ Standalone" }),
    welcomeFeat1: t({ en: "Browse thousands of live servers", fr: "Parcourir des milliers de serveurs en direct", de: "Tausende Live-Server durchsuchen", es: "Explora miles de servidores en vivo", ru: "Просмотр тысяч серверов в реальном времени" }),
    welcomeFeat2: t({ en: "Manage and update your mods via SteamCMD", fr: "Gérer et mettre à jour vos mods via SteamCMD", de: "Mods über SteamCMD verwalten und aktualisieren", es: "Gestiona y actualiza tus mods vía SteamCMD", ru: "Управление и обновление модов через SteamCMD" }),
    welcomeFeat3: t({ en: "Keep favorites and connection history", fr: "Conserver vos favoris et historique de connexion", de: "Favoriten und Verbindungsverlauf speichern", es: "Guarda favoritos e historial de conexiones", ru: "Хранение избранного и истории подключений" }),
    welcomeFeat4: t({ en: "Launch DayZ directly with one click", fr: "Lancer DayZ directement en un clic", de: "DayZ direkt mit einem Klick starten", es: "Inicia DayZ directamente con un clic", ru: "Запуск DayZ напрямую в один клик" }),
    welcomeHint: t({ en: "This quick setup takes about 1 minute. You can change everything later in account settings.", fr: "Cette configuration rapide prend environ 1 minute. Vous pouvez tout modifier plus tard dans les paramètres.", de: "Diese Einrichtung dauert etwa 1 Minute. Du kannst alles später in den Kontoeinstellungen ändern.", es: "Esta configuración rápida toma aproximadamente 1 minuto. Puedes cambiar todo más tarde en la configuración de cuenta.", ru: "Эта быстрая настройка займёт около 1 минуты. Вы можете изменить всё позже в настройках аккаунта." }),
    steamcmdTitle: t({ en: "SteamCMD", fr: "SteamCMD", de: "SteamCMD", es: "SteamCMD", ru: "SteamCMD" }),
    steamcmdDesc: t({ en: "Required to download and update DayZ mods from the Steam Workshop.", fr: "Requis pour télécharger et mettre à jour les mods DayZ depuis le Steam Workshop.", de: "Erforderlich um DayZ-Mods aus dem Steam Workshop herunterzuladen und zu aktualisieren.", es: "Requerido para descargar y actualizar mods de DayZ desde Steam Workshop.", ru: "Требуется для скачивания и обновления модов DayZ из Steam Workshop." }),
    steamcmdDetecting: t({ en: "Detecting SteamCMD…", fr: "Détection de SteamCMD…", de: "SteamCMD wird erkannt…", es: "Detectando SteamCMD…", ru: "Поиск SteamCMD…" }),
    steamcmdDetected: t({ en: "SteamCMD detected", fr: "SteamCMD détecté", de: "SteamCMD erkannt", es: "SteamCMD detectado", ru: "SteamCMD обнаружен" }),
    steamcmdNotFound: t({ en: "SteamCMD not found", fr: "SteamCMD non trouvé", de: "SteamCMD nicht gefunden", es: "SteamCMD no encontrado", ru: "SteamCMD не найден" }),
    steamcmdLinuxHint: t({ en: "Install SteamCMD with your package manager:", fr: "Installez SteamCMD avec votre gestionnaire de paquets :", de: "Installiere SteamCMD mit deinem Paketmanager:", es: "Instala SteamCMD con tu gestor de paquetes:", ru: "Установите SteamCMD через менеджер пакетов:" }),
    steamcmdLinuxWaiting: t({ en: "Waiting for SteamCMD to be installed…", fr: "En attente de l'installation de SteamCMD…", de: "Warte auf Installation von SteamCMD…", es: "Esperando a que SteamCMD se instale…", ru: "Ожидание установки SteamCMD…" }),
    steamcmdWinHint: t({ en: "You can install SteamCMD automatically or point to an existing installation.", fr: "Vous pouvez installer SteamCMD automatiquement ou pointer vers une installation existante.", de: "Du kannst SteamCMD automatisch installieren oder auf eine existierende Installation verweisen.", es: "Puedes instalar SteamCMD automáticamente o apuntar a una instalación existente.", ru: "Вы можете установить SteamCMD автоматически или указать существующую установку." }),
    steamcmdDownloading: t({ en: "Downloading…", fr: "Téléchargement…", de: "Wird heruntergeladen…", es: "Descargando…", ru: "Скачивание…" }),
    steamcmdInstallAuto: t({ en: "Install SteamCMD automatically", fr: "Installer SteamCMD automatiquement", de: "SteamCMD automatisch installieren", es: "Instalar SteamCMD automáticamente", ru: "Установить SteamCMD автоматически" }),
    steamcmdInstallHint: t({ en: "Downloads from Valve to", fr: "Télécharge depuis Valve vers", de: "Lädt von Valve herunter nach", es: "Se descarga de Valve a", ru: "Скачивается от Valve в" }),
    steamcmdOr: t({ en: "or", fr: "ou", de: "oder", es: "o", ru: "или" }),
    steamcmdBrowse: t({ en: "Browse for steamcmd.exe", fr: "Parcourir pour steamcmd.exe", de: "steamcmd.exe suchen", es: "Buscar steamcmd.exe", ru: "Указать steamcmd.exe" }),
    steamcmdPath: t({ en: "SteamCMD path", fr: "Chemin SteamCMD", de: "SteamCMD-Pfad", es: "Ruta de SteamCMD", ru: "Путь к SteamCMD" }),
    steamcmdOverride: t({ en: "override", fr: "remplacer", de: "überschreiben", es: "cambiar", ru: "изменить" }),
    steamRoot: t({ en: "Steam root folder", fr: "Dossier racine Steam", de: "Steam Hauptordner", es: "Carpeta raíz de Steam", ru: "Корневая папка Steam" }),
    optional: t({ en: "optional", fr: "optionnel", de: "optional", es: "opcional", ru: "необязательно" }),
    autoDetect: t({ en: "Auto-detect", fr: "Détection auto", de: "Automatisch erkennen", es: "Autodetectar", ru: "Автоопределение" }),
    linuxPathHint: insert(t({ en: "Usually {{path}}", fr: "Généralement {{path}}", de: "Normalerweise {{path}}", es: "Normalmente {{path}}", ru: "Обычно {{path}}" })),
    windowsPathHint: insert(t({ en: "Usually {{path}}", fr: "Généralement {{path}}", de: "Normalerweise {{path}}", es: "Normalmente {{path}}", ru: "Обычно {{path}}" })),
    leaveBlank: t({ en: "Leave blank to auto-detect", fr: "Laisser vide pour détection auto", de: "Leer lassen für automatische Erkennung", es: "Dejar en blanco para autodetectar", ru: "Оставьте пустым для автоопределения" }),
    configTitle: t({ en: "Configuration", fr: "Configuration", de: "Konfiguration", es: "Configuración", ru: "Конфигурация" }),
    configDesc: t({ en: "Steam username is required. Everything else is optional.", fr: "Le nom d'utilisateur Steam est requis. Tout le reste est optionnel.", de: "Steam-Benutzername ist erforderlich. Alles andere ist optional.", es: "El nombre de usuario de Steam es obligatorio. Todo lo demás es opcional.", ru: "Имя пользователя Steam обязательно. Всё остальное — необязательно." }),
    steamcmdLogin: t({ en: "SteamCMD login", fr: "Connexion SteamCMD", de: "SteamCMD Anmeldung", es: "Inicio de sesión SteamCMD", ru: "Вход SteamCMD" }),
    username: t({ en: "Username", fr: "Nom d'utilisateur", de: "Benutzername", es: "Usuario", ru: "Имя пользователя" }),
    password: t({ en: "Password", fr: "Mot de passe", de: "Passwort", es: "Contraseña", ru: "Пароль" }),
    passwordCached: t({ en: "leave blank for cached", fr: "laisser vide pour cache", de: "leer lassen für gespeicherte", es: "dejar en blanco para caché", ru: "оставьте пустым для кешированных" }),
    passwordWarning: t({ en: "Password stored in plaintext. Leave blank to use Steam's cached credentials instead.", fr: "Mot de passe stocké en clair. Laissez vide pour utiliser les identifiants en cache de Steam.", de: "Passwort wird unverschlüsselt gespeichert. Leer lassen um Steams gespeicherte Anmeldedaten zu verwenden.", es: "La contraseña se almacena en texto plano. Déjala en blanco para usar las credenciales en caché de Steam.", ru: "Пароль хранится в открытом виде. Оставьте пустым для использования кешированных учётных данных Steam." }),
    steamRequired: t({ en: "Steam username is required for SteamCMD to download and update mods.", fr: "Le nom d'utilisateur Steam est requis pour que SteamCMD télécharge et mette à jour les mods.", de: "Steam-Benutzername ist erforderlich damit SteamCMD Mods herunterladen und aktualisieren kann.", es: "El nombre de usuario de Steam es necesario para que SteamCMD descargue y actualice mods.", ru: "Имя пользователя Steam требуется для SteamCMD для скачивания и обновления модов." }),
    ingameName: t({ en: "In-game name", fr: "Nom en jeu", de: "Spielername", es: "Nombre en el juego", ru: "Имя в игре" }),
    ingamePlaceholder: t({ en: "e.g. Survivor", fr: "ex. Survivor", de: "z.B. Survivor", es: "ej. Superviviente", ru: "напр. Выживший" }),
    ingameHint: insert(t({ en: "Passed as {{flag}} to DayZ.", fr: "Passé comme {{flag}} à DayZ.", de: "Wird als {{flag}} an DayZ übergeben.", es: "Se pasa como {{flag}} a DayZ.", ru: "Передаётся как {{flag}} в DayZ." })),
    steamApi: t({ en: "Steam API Key & ID", fr: "Clé API Steam et ID", de: "Steam API-Schlüssel & ID", es: "Steam API Key e ID", ru: "Steam API Key и ID" }),
    steamApiDesc: t({ en: "Enables avatar display and higher rate limits for mod update checks. You can add these later.", fr: "Active l'affichage de l'avatar et des limites plus élevées pour les vérifications de mods. Vous pouvez ajouter ces infos plus tard.", de: "Aktiviert Avatar-Anzeige und höhere Rate-Limits für Mod-Update-Prüfungen. Du kannst diese später hinzufügen.", es: "Habilita la visualización del avatar y límites más altos para comprobaciones de actualización de mods. Puedes añadirlos más tarde.", ru: "Включает отображение аватара и повышенные лимиты для проверки обновлений модов. Можете добавить позже." }),
    apiKey: t({ en: "API Key", fr: "Clé API", de: "API-Schlüssel", es: "Clave API", ru: "API Key" }),
    steamIdLabel: t({ en: "Steam ID (64-bit)", fr: "Steam ID (64-bit)", de: "Steam-ID (64-bit)", es: "Steam ID (64-bit)", ru: "Steam ID (64-бит)" }),
    bmTitle: t({ en: "BattleMetrics", fr: "BattleMetrics", de: "BattleMetrics", es: "BattleMetrics", ru: "BattleMetrics" }),
    bmDesc: t({ en: "Adds server rankings, status, uptime %, and a 24 h player count graph to every server detail panel.", fr: "Ajoute les classements, statut, disponibilité % et un graphique joueurs 24h à chaque panneau de détails serveur.", de: "Fügt Server-Rankings, Status, Verfügbarkeit % und einen 24h-Spielergraphen zu jedem Server-Detailpanel hinzu.", es: "Añade rankings de servidor, estado, tiempo activo % y un gráfico de jugadores de 24 h al panel de detalles de cada servidor.", ru: "Добавляет рейтинги серверов, статус, аптайм % и график игроков за 24 ч на панель деталей каждого сервера." }),
    bmToken: t({ en: "Personal access token", fr: "Jeton d'accès personnel", de: "Persönlicher Zugangs-Token", es: "Token de acceso personal", ru: "Персональный токен доступа" }),
    doneTitle: t({ en: "You're all set!", fr: "Vous êtes prêt !", de: "Alles bereit!", es: "¡Todo listo!", ru: "Всё готово!" }),
    doneDesc: insert(t({ en: "Click {{button}} to save your profile and start browsing servers.", fr: "Cliquez sur {{button}} pour enregistrer votre profil et commencer à parcourir les serveurs.", de: "Klicke {{button}} um dein Profil zu speichern und Server zu durchsuchen.", es: "Haz clic en {{button}} para guardar tu perfil y empezar a explorar servidores.", ru: "Нажмите {{button}} для сохранения профиля и начала просмотра серверов." })),
    doneButton: t({ en: "Launch app", fr: "Lancer l'app", de: "App starten", es: "Iniciar aplicación", ru: "Запустить приложение" }),
    doneSettingsHint: t({ en: "You can update any of these settings later by clicking your name in the title bar.", fr: "Vous pouvez modifier ces paramètres plus tard en cliquant sur votre nom dans la barre de titre.", de: "Du kannst diese Einstellungen später ändern indem du auf deinen Namen in der Titelleiste klickst.", es: "Puedes actualizar cualquiera de estos ajustes más tarde haciendo clic en tu nombre en la barra de título.", ru: "Вы можете изменить любые из этих настроек позже, нажав на своё имя в заголовке." }),
    doneAboutHint: insert(t({ en: "Check the {{tab}} tab for tips and documentation.", fr: "Consultez l'onglet {{tab}} pour des astuces et la documentation.", de: "Schau im {{tab}}-Tab nach Tipps und Dokumentation.", es: "Consulta la pestaña {{tab}} para consejos y documentación.", ru: "Загляните на вкладку {{tab}} для советов и документации." })),
    back: t({ en: "Back", fr: "Retour", de: "Zurück", es: "Atrás", ru: "Назад" }),
    getStarted: t({ en: "Get started", fr: "Commencer", de: "Los geht's", es: "Empezar", ru: "Начать" }),
    next: t({ en: "Next", fr: "Suivant", de: "Weiter", es: "Siguiente", ru: "Далее" }),
    importProfile: t({ en: "Import profile", fr: "Importer un profil", de: "Profil importieren", es: "Importar perfil", ru: "Импорт профиля" }),
    launch: t({ en: "Launch app", fr: "Lancer l'app", de: "App starten", es: "Iniciar aplicación", ru: "Запустить приложение" }),
    selectSteamRoot: t({ en: "Select Steam root folder", fr: "Sélectionner le dossier racine Steam", de: "Steam Hauptordner auswählen", es: "Seleccionar carpeta raíz de Steam", ru: "Выберите корневую папку Steam" }),
    selectSteamcmd: t({ en: "Select steamcmd binary", fr: "Sélectionner l'exécutable steamcmd", de: "steamcmd Datei auswählen", es: "Seleccionar ejecutable de steamcmd", ru: "Выберите исполняемый файл steamcmd" }),
    importDialogTitle: t({ en: "Import DayZ Community Hub profile", fr: "Importer un profil DayZ Community Hub", de: "DayZ Community Hub Profil importieren", es: "Importar perfil de DayZ Community Hub", ru: "Импорт профиля DayZ Community Hub" }),
    importFilter: t({ en: "DayZ Community Hub profile", fr: "Profil DayZ Community Hub", de: "DayZ Community Hub Profil", es: "Perfil de DayZ Community Hub", ru: "Профиль DayZ Community Hub" }),
    steamcmdFilter: t({ en: "SteamCMD", fr: "SteamCMD", de: "SteamCMD", es: "SteamCMD", ru: "SteamCMD" }),
    steamUsernamePlaceholder: t({ en: "Steam username", fr: "Nom d'utilisateur Steam", de: "Steam Benutzername", es: "Usuario de Steam", ru: "Имя пользователя Steam" }),
    apiKeyPlaceholder: t({ en: "32-character hex key", fr: "Clé hex 32 caractères", de: "32-stelliger Hex-Schlüssel", es: "Clave hex de 32 caracteres", ru: "32-символьный hex-ключ" }),
    steamIdPlaceholder: t({ en: "76561198…", fr: "76561198…", de: "76561198…", es: "76561198…", ru: "76561198…" }),
    bmTokenPlaceholder: t({ en: "eyJhbGci…", fr: "eyJhbGci…", de: "eyJhbGci…", es: "eyJhbGci…", ru: "eyJhbGci…" }),
    browse: t({ en: "Browse", fr: "Parcourir", de: "Durchsuchen", es: "Examinar", ru: "Обзор" }),
  },
} satisfies Dictionary;

export default content;
