import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "shell",
  content: {
    titlebarUpdateAvailable: t({ en: "Update available", fr: "Mise à jour disponible", de: "Update verfügbar", es: "Actualización disponible", ru: "Доступно обновление" }),
    titlebarUpdateAvailableTitle: t({ en: "Launcher update available — click to view", fr: "Mise à jour du lanceur disponible — cliquez pour voir", de: "Launcher-Update verfügbar — klicken zum Anzeigen", es: "Actualización del launcher disponible — haz clic para ver", ru: "Доступно обновление лаунчера — нажмите для просмотра" }),
    titlebarUpdateMods: insert(t({ en: "Update {{count}} mods", fr: "Mettre à jour {{count}} mods", de: "{{count}} Mods aktualisieren", es: "Actualizar {{count}} mods", ru: "Обновить {{count}} модов" })),
    titlebarUpdateModsOne: insert(t({ en: "Update {{count}} mod", fr: "Mettre à jour {{count}} mod", de: "{{count}} Mod aktualisieren", es: "Actualizar {{count}} mod", ru: "Обновить {{count}} мод" })),
    titlebarUpdateModsTitle: insert(t({ en: "Update {{count}} mods — click to open Mods tab and start update", fr: "Mettre à jour {{count}} mods — cliquez pour ouvrir l'onglet Mods", de: "{{count}} Mods aktualisieren — klicken um Mods-Tab zu öffnen und Update zu starten", es: "Actualizar {{count}} mods — haz clic para abrir la pestaña Mods e iniciar la actualización", ru: "Обновить {{count}} модов — нажмите, чтобы открыть вкладку Моды и начать обновление" })),
    titlebarUpdateModsTitleOne: insert(t({ en: "Update {{count}} mod — click to open Mods tab and start update", fr: "Mettre à jour {{count}} mod — cliquez pour ouvrir l'onglet Mods", de: "{{count}} Mod aktualisieren — klicken um Mods-Tab zu öffnen und Update zu starten", es: "Actualizar {{count}} mod — haz clic para abrir la pestaña Mods e iniciar la actualización", ru: "Обновить {{count}} мод — нажмите, чтобы открыть вкладку Моды и начать обновление" })),
    tabServers: t({ en: "Servers", fr: "Serveurs", de: "Server", es: "Servidores", ru: "Серверы" }),
    tabFavorites: t({ en: "Favorites", fr: "Favoris", de: "Favoriten", es: "Favoritos", ru: "Избранное" }),
    tabHistory: t({ en: "History", fr: "Historique", de: "Verlauf", es: "Historial", ru: "История" }),
    tabMods: t({ en: "Mods", fr: "Mods", de: "Mods", es: "Mods", ru: "Моды" }),
    tabNews: t({ en: "News", fr: "Actualités", de: "Neuigkeiten", es: "Noticias", ru: "Новости" }),
    tabConnect: t({ en: "Connect", fr: "Connexion", de: "Verbinden", es: "Conectar", ru: "Подключение" }),
    tabOptions: t({ en: "Options", fr: "Options", de: "Optionen", es: "Opciones", ru: "Опции" }),
    tabOffline: t({ en: "Offline", fr: "Hors ligne", de: "Offline", es: "Sin conexión", ru: "Оффлайн" }),
    tabAbout: t({ en: "About", fr: "À propos", de: "Info", es: "Acerca de", ru: "О программе" }),
    timeJustNow: t({ en: "just now", fr: "à l'instant", de: "gerade eben", es: "ahora mismo", ru: "только что" }),
    timeMinuteAgo: t({ en: "1 minute ago", fr: "il y a 1 minute", de: "vor 1 Minute", es: "hace 1 minuto", ru: "1 минуту назад" }),
    timeMinutesAgo: insert(t({ en: "{{count}} minutes ago", fr: "il y a {{count}} minutes", de: "vor {{count}} Minuten", es: "hace {{count}} minutos", ru: "{{count}} минут назад" })),
    timeHourAgo: t({ en: "1 hour ago", fr: "il y a 1 heure", de: "vor 1 Stunde", es: "hace 1 hora", ru: "1 час назад" }),
    timeHoursAgo: insert(t({ en: "{{count}} hours ago", fr: "il y a {{count}} heures", de: "vor {{count}} Stunden", es: "hace {{count}} horas", ru: "{{count}} часов назад" })),
    timeDayAgo: t({ en: "1 day ago", fr: "il y a 1 jour", de: "vor 1 Tag", es: "hace 1 día", ru: "1 день назад" }),
    timeDaysAgo: insert(t({ en: "{{count}} days ago", fr: "il y a {{count}} jours", de: "vor {{count}} Tagen", es: "hace {{count}} días", ru: "{{count}} дней назад" })),
    timeWeekAgo: t({ en: "1 week ago", fr: "il y a 1 semaine", de: "vor 1 Woche", es: "hace 1 semana", ru: "1 неделю назад" }),
    timeWeeksAgo: insert(t({ en: "{{count}} weeks ago", fr: "il y a {{count}} semaines", de: "vor {{count}} Wochen", es: "hace {{count}} semanas", ru: "{{count}} недель назад" })),
    timeLongAgo: t({ en: "a long time ago", fr: "il y a longtemps", de: "vor langer Zeit", es: "hace mucho tiempo", ru: "давно" }),
    confirmCancel: t({ en: "Cancel", fr: "Annuler", de: "Abbrechen", es: "Cancelar", ru: "Отмена" }),
    confirmDeclineDefault: t({ en: "No, connect anyway", fr: "Non, se connecter quand même", de: "Nein, trotzdem verbinden", es: "No, conectar de todos modos", ru: "Нет, всё равно подключиться" }),
    confirmYes: t({ en: "Yes", fr: "Oui", de: "Ja", es: "Sí", ru: "Да" }),
    confirmConfirm: t({ en: "Confirm", fr: "Confirmer", de: "Bestätigen", es: "Confirmar", ru: "Подтвердить" }),
    langChange: t({ en: "Change language", fr: "Changer de langue", de: "Sprache ändern", es: "Cambiar idioma", ru: "Сменить язык" }),
    langEn: t({ en: "English", fr: "English", de: "English", es: "English", ru: "English" }),
    langDe: t({ en: "Deutsch", fr: "Deutsch", de: "Deutsch", es: "Deutsch", ru: "Deutsch" }),
    langFr: t({ en: "Français", fr: "Français", de: "Français", es: "Français", ru: "Français" }),
    langRu: t({ en: "Русский", fr: "Русский", de: "Русский", es: "Русский", ru: "Русский" }),
    langEs: t({ en: "Español", fr: "Español", de: "Español", es: "Español", ru: "Español" }),
    errorFailed: t({ en: "Failed", fr: "Échec", de: "Fehlgeschlagen", es: "Error", ru: "Ошибка" }),
    initFailed: t({ en: "Initialization Failed", fr: "Échec de l'initialisation", de: "Initialisierung fehlgeschlagen", es: "Error de inicialización", ru: "Ошибка инициализации" }),
    initLoading: t({ en: "Initializing…", fr: "Initialisation…", de: "Wird initialisiert…", es: "Inicializando…", ru: "Инициализация…" }),
    initRetry: t({ en: "Retry", fr: "Réessayer", de: "Erneut versuchen", es: "Reintentar", ru: "Повторить" }),
    noHistory: t({ en: "No history entry to reconnect to", fr: "Aucune entrée d'historique pour reconnecter", de: "Kein Verlaufseintrag zum erneuten Verbinden", es: "No hay entrada de historial para reconectar", ru: "Нет записи истории для переподключения" }),
    windowMinimize: t({ en: "Minimize", fr: "Réduire", de: "Minimieren", es: "Minimizar", ru: "Свернуть" }),
    windowMaximize: t({ en: "Maximize", fr: "Agrandir", de: "Maximieren", es: "Maximizar", ru: "Развернуть" }),
    windowClose: t({ en: "Close", fr: "Fermer", de: "Schließen", es: "Cerrar", ru: "Закрыть" }),
    titlebarServers: t({ en: "Servers", fr: "Serveurs", de: "Server", es: "Servidores", ru: "Серверы" }),
    titlebarPlayersIngame: t({ en: "Players in-game", fr: "Joueurs en jeu", de: "Spieler im Spiel", es: "Jugadores en partida", ru: "Игроков в игре" }),
    titlebarPlayersSteam: t({ en: "Players on Steam", fr: "Joueurs sur Steam", de: "Spieler auf Steam", es: "Jugadores en Steam", ru: "Игроков в Steam" }),
    titlebarEditAccount: t({ en: "Edit account settings", fr: "Modifier les paramètres du compte", de: "Kontoeinstellungen bearbeiten", es: "Editar configuración de cuenta", ru: "Редактировать настройки аккаунта" }),
    titlebarSetupAccount: t({ en: "Set up account", fr: "Configurer le compte", de: "Konto einrichten", es: "Configurar cuenta", ru: "Настроить аккаунт" }),
    titlebarSteamcmdMissing: t({ en: "SteamCMD not found", fr: "SteamCMD non trouvé", de: "SteamCMD nicht gefunden", es: "SteamCMD no encontrado", ru: "SteamCMD не найден" }),
    titlebarAnonymous: t({ en: "anonymous", fr: "anonyme", de: "anonym", es: "anónimo", ru: "аноним" }),
    statusLaunched: insert(t({ en: "Launched: {{name}}", fr: "Lancé : {{name}}", de: "Gestartet: {{name}}", es: "Iniciado: {{name}}", ru: "Запущено: {{name}}" })),
    statusLaunchError: insert(t({ en: "Launch error: {{error}}", fr: "Erreur de lancement : {{error}}", de: "Startfehler: {{error}}", es: "Error de inicio: {{error}}", ru: "Ошибка запуска: {{error}}" })),
    statusOfflineUpdated: t({ en: "Offline mode updated successfully", fr: "Mode hors ligne mis à jour avec succès", de: "Offline-Modus erfolgreich aktualisiert", es: "Modo sin conexión actualizado correctamente", ru: "Оффлайн режим успешно обновлён" }),
    statusUpdateFailed: insert(t({ en: "Update failed: {{error}}", fr: "Échec de la mise à jour : {{error}}", de: "Aktualisierung fehlgeschlagen: {{error}}", es: "Error de actualización: {{error}}", ru: "Ошибка обновления: {{error}}" })),
  },
} satisfies Dictionary;

export default content;
