import { insert, t, type Dictionary } from "intlayer";

const content = {
  key: "stats",
  content: {
    figTime: t({
      en: "Time played",
      fr: "Temps de jeu",
      de: "Spielzeit",
      es: "Tiempo jugado",
      ru: "Время в игре",
    }),
    figSessions: t({
      en: "Sessions",
      fr: "Sessions",
      de: "Sitzungen",
      es: "Sesiones",
      ru: "Сессии",
    }),
    figPlaces: t({ en: "Servers", fr: "Serveurs", de: "Server", es: "Servidores", ru: "Серверы" }),
    figAverage: t({
      en: "Average session",
      fr: "Session moyenne",
      de: "Ø Sitzung",
      es: "Sesión media",
      ru: "Средняя сессия",
    }),
    figLongest: t({
      en: "Longest",
      fr: "La plus longue",
      de: "Längste",
      es: "La más larga",
      ru: "Самая долгая",
    }),
    figStreak: t({ en: "Streak", fr: "Série", de: "Serie", es: "Racha", ru: "Серия" }),
    streakDays: insert(
      t({
        en: "{{count}} d",
        fr: "{{count}} j",
        de: "{{count}} T",
        es: "{{count}} d",
        ru: "{{count}} дн",
      }),
    ),
    streakTitle: insert(
      t({
        en: "Days in a row with play, ending today. Best: {{best}}.",
        fr: "Jours d'affilée avec une partie, jusqu'à aujourd'hui. Record : {{best}}.",
        de: "Tage in Folge mit Spielzeit bis heute. Rekord: {{best}}.",
        es: "Días seguidos jugando, hasta hoy. Récord: {{best}}.",
        ru: "Дней подряд с игрой до сегодня. Рекорд: {{best}}.",
      }),
    ),
    rangeLabel: t({
      en: "Period",
      fr: "Période",
      de: "Zeitraum",
      es: "Periodo",
      ru: "Период",
    }),
    rangeWeek: t({ en: "7 days", fr: "7 jours", de: "7 Tage", es: "7 días", ru: "7 дней" }),
    rangeMonth: t({ en: "30 days", fr: "30 jours", de: "30 Tage", es: "30 días", ru: "30 дней" }),
    rangeYear: t({ en: "1 year", fr: "1 an", de: "1 Jahr", es: "1 año", ru: "1 год" }),
    rangeAll: t({
      en: "All time",
      fr: "Depuis le début",
      de: "Gesamt",
      es: "Desde el inicio",
      ru: "За всё время",
    }),
    playingNow: insert(
      t({
        en: "Playing {{name}} for {{duration}}",
        fr: "En jeu sur {{name}} depuis {{duration}}",
        de: "Spielt auf {{name}} seit {{duration}}",
        es: "Jugando en {{name}} desde hace {{duration}}",
        ru: "В игре на {{name}} уже {{duration}}",
      }),
    ),
    sectionActivity: t({
      en: "Activity",
      fr: "Activité",
      de: "Aktivität",
      es: "Actividad",
      ru: "Активность",
    }),
    activityHint: t({
      en: "Time played each day over the last year, in your time. Darker is longer.",
      fr: "Temps joué chaque jour sur la dernière année, à votre heure. Plus foncé, plus long.",
      de: "Spielzeit pro Tag im letzten Jahr, in deiner Zeit. Dunkler ist länger.",
      es: "Tiempo jugado cada día durante el último año, en tu hora. Más oscuro, más largo.",
      ru: "Время игры по дням за последний год, по вашему времени. Темнее — дольше.",
    }),
    activityCell: insert(
      t({
        en: "{{date}} · {{duration}}",
        fr: "{{date}} · {{duration}}",
        de: "{{date}} · {{duration}}",
        es: "{{date}} · {{duration}}",
        ru: "{{date}} · {{duration}}",
      }),
    ),
    legendLess: t({ en: "Less", fr: "Moins", de: "Weniger", es: "Menos", ru: "Меньше" }),
    legendMore: t({ en: "More", fr: "Plus", de: "Mehr", es: "Más", ru: "Больше" }),
    sectionPlaces: t({
      en: "Where you play",
      fr: "Où vous jouez",
      de: "Wo du spielst",
      es: "Dónde juegas",
      ru: "Где вы играете",
    }),
    showAllPlaces: insert(
      t({
        en: "Show all {{count}}",
        fr: "Afficher les {{count}}",
        de: "Alle {{count}} zeigen",
        es: "Mostrar los {{count}}",
        ru: "Показать все {{count}}",
      }),
    ),
    showFewerPlaces: t({
      en: "Show fewer",
      fr: "Afficher moins",
      de: "Weniger zeigen",
      es: "Mostrar menos",
      ru: "Показать меньше",
    }),
    placeSessions: insert(
      t({
        en: "{{count}} sessions",
        fr: "{{count}} sessions",
        de: "{{count}} Sitzungen",
        es: "{{count}} sesiones",
        ru: "{{count}} сессий",
      }),
    ),
    placeSessionsOne: t({
      en: "1 session",
      fr: "1 session",
      de: "1 Sitzung",
      es: "1 sesión",
      ru: "1 сессия",
    }),
    sectionWhen: t({
      en: "When you play",
      fr: "Quand vous jouez",
      de: "Wann du spielst",
      es: "Cuándo juegas",
      ru: "Когда вы играете",
    }),
    whenHint: t({
      en: "Time played by weekday and hour, in your time.",
      fr: "Temps joué par jour de la semaine et par heure, à votre heure.",
      de: "Spielzeit nach Wochentag und Stunde, in deiner Zeit.",
      es: "Tiempo jugado por día de la semana y hora, en tu hora.",
      ru: "Время игры по дням недели и часам, по вашему времени.",
    }),
    whenCell: insert(
      t({
        en: "{{day}} {{hour}}:00 · {{duration}}",
        fr: "{{day}} {{hour}}h · {{duration}}",
        de: "{{day}} {{hour}}:00 · {{duration}}",
        es: "{{day}} {{hour}}:00 · {{duration}}",
        ru: "{{day}} {{hour}}:00 · {{duration}}",
      }),
    ),
    sectionMaps: t({ en: "Maps", fr: "Cartes", de: "Karten", es: "Mapas", ru: "Карты" }),
    sectionHistory: t({
      en: "Full history",
      fr: "Historique complet",
      de: "Gesamter Verlauf",
      es: "Historial completo",
      ru: "Полная история",
    }),
    historySearch: t({
      en: "Search a server, an address, a map…",
      fr: "Rechercher un serveur, une adresse, une carte…",
      de: "Server, Adresse oder Karte suchen…",
      es: "Buscar un servidor, una dirección, un mapa…",
      ru: "Найти сервер, адрес, карту…",
    }),
    showMore: insert(
      t({
        en: "Show {{count}} more",
        fr: "Afficher {{count}} de plus",
        de: "{{count}} weitere zeigen",
        es: "Mostrar {{count}} más",
        ru: "Показать ещё {{count}}",
      }),
    ),
    historyCount: insert(
      t({
        en: "{{shown}} of {{total}}",
        fr: "{{shown}} sur {{total}}",
        de: "{{shown}} von {{total}}",
        es: "{{shown}} de {{total}}",
        ru: "{{shown}} из {{total}}",
      }),
    ),
    unmeasured: t({
      en: "length unknown",
      fr: "durée inconnue",
      de: "Dauer unbekannt",
      es: "duración desconocida",
      ru: "длительность неизвестна",
    }),
    unmeasuredHint: t({
      en: "A join from before the launcher measured play time: it happened, its length is not known.",
      fr: "Une connexion d'avant la mesure du temps de jeu : elle a eu lieu, sa durée n'est pas connue.",
      de: "Ein Beitritt aus der Zeit vor der Zeitmessung: Er fand statt, seine Dauer ist unbekannt.",
      es: "Una conexión anterior a la medición del tiempo: ocurrió, pero se desconoce su duración.",
      ru: "Вход до того, как лаунчер начал измерять время: он был, но длительность неизвестна.",
    }),
    offlineTag: t({
      en: "Offline",
      fr: "Hors ligne",
      de: "Offline",
      es: "Sin conexión",
      ru: "Офлайн",
    }),
    unknownPlace: t({
      en: "Started outside the launcher",
      fr: "Lancé hors du launcher",
      de: "Außerhalb des Launchers gestartet",
      es: "Iniciado fuera del launcher",
      ru: "Запущено не через лаунчер",
    }),
    running: t({ en: "running", fr: "en cours", de: "läuft", es: "en curso", ru: "идёт" }),
    deleteSession: t({
      en: "Forget this session",
      fr: "Oublier cette session",
      de: "Diese Sitzung vergessen",
      es: "Olvidar esta sesión",
      ru: "Забыть эту сессию",
    }),
    emptyTitle: t({
      en: "No play time yet",
      fr: "Aucun temps de jeu pour l'instant",
      de: "Noch keine Spielzeit",
      es: "Aún sin tiempo de juego",
      ru: "Пока нет времени в игре",
    }),
    emptyHint: t({
      en: "Join a server or an offline map: the launcher writes down how long DayZ runs, where and when.",
      fr: "Rejoignez un serveur ou une carte hors ligne : le launcher note combien de temps DayZ tourne, où et quand.",
      de: "Tritt einem Server oder einer Offline-Karte bei: Der Launcher notiert, wie lange, wo und wann DayZ läuft.",
      es: "Únete a un servidor o a un mapa sin conexión: el launcher anota cuánto, dónde y cuándo funciona DayZ.",
      ru: "Зайдите на сервер или офлайн-карту: лаунчер запишет, сколько, где и когда работала DayZ.",
    }),
    nothingInRange: t({
      en: "Nothing played in this period.",
      fr: "Rien joué sur cette période.",
      de: "In diesem Zeitraum nichts gespielt.",
      es: "Nada jugado en este periodo.",
      ru: "За этот период игр нет.",
    }),
    exportProfile: t({
      en: "Export the profile",
      fr: "Exporter le profil",
      de: "Profil exportieren",
      es: "Exportar el perfil",
      ru: "Экспорт профиля",
    }),
    importProfile: t({
      en: "Import a profile",
      fr: "Importer un profil",
      de: "Profil importieren",
      es: "Importar un perfil",
      ru: "Импорт профиля",
    }),
    exportHint: t({
      en: "Your play history is part of the profile: exporting it keeps these stats, importing brings them back.",
      fr: "Votre historique de jeu fait partie du profil : l'exporter garde ces statistiques, l'importer les ramène.",
      de: "Dein Spielverlauf gehört zum Profil: Exportieren behält diese Statistik, Importieren holt sie zurück.",
      es: "Tu historial de juego es parte del perfil: exportarlo guarda estas estadísticas, importarlo las recupera.",
      ru: "История игр входит в профиль: экспорт сохраняет эту статистику, импорт возвращает её.",
    }),
  },
} satisfies Dictionary;

export default content;
