import { t, type Dictionary } from "intlayer";

const content = {
  key: "theme",
  content: {
    presetChernarus: t({
      en: "Chernarus",
      fr: "Tchernarus",
      de: "Tschernarus",
      es: "Chernarus",
      ru: "Чернарусь",
    }),
    presetTopo: t({
      en: "Survey map",
      fr: "Carte d'état-major",
      de: "Messtischblatt",
      es: "Mapa topográfico",
      ru: "Топокарта",
    }),
    dark: t({ en: "Dark", fr: "Sombre", de: "Dunkel", es: "Oscuro", ru: "Тёмная" }),
    light: t({ en: "Light", fr: "Clair", de: "Hell", es: "Claro", ru: "Светлая" }),
    mixed: t({ en: "Mixed", fr: "Mixte", de: "Gemischt", es: "Mixto", ru: "Смешанная" }),
    custom: t({
      en: "Custom",
      fr: "Personnalisé",
      de: "Benutzerdefiniert",
      es: "Personalizado",
      ru: "Своя",
    }),
    editorTitle: t({
      en: "Custom Theme Editor",
      fr: "Éditeur de thème personnalisé",
      de: "Eigener Theme-Editor",
      es: "Editor de tema personalizado",
      ru: "Редактор своей темы",
    }),
    editorDesc: t({
      en: "Define your own theme using CSS variables",
      fr: "Définissez votre propre thème avec des variables CSS",
      de: "Definiere dein eigenes Theme mit CSS-Variablen",
      es: "Define tu propio tema usando variables CSS",
      ru: "Определите свою тему с помощью CSS-переменных",
    }),
    reset: t({
      en: "Reset",
      fr: "Réinitialiser",
      de: "Zurücksetzen",
      es: "Restablecer",
      ru: "Сбросить",
    }),
    default: t({
      en: "Default",
      fr: "Par défaut",
      de: "Standard",
      es: "Predeterminado",
      ru: "По умолчанию",
    }),
    autosaved: t({
      en: "Auto-saved",
      fr: "Sauvegarde auto",
      de: "Automatisch gespeichert",
      es: "Autoguardado",
      ru: "Автосохранение",
    }),
    done: t({ en: "Done", fr: "Terminé", de: "Fertig", es: "Listo", ru: "Готово" }),
    change: t({
      en: "Change theme",
      fr: "Changer de thème",
      de: "Theme ändern",
      es: "Cambiar tema",
      ru: "Сменить тему",
    }),
    tabColors: t({ en: "Colors", fr: "Couleurs", de: "Farben", es: "Colores", ru: "Цвета" }),
    tabCode: t({ en: "Code", fr: "Code", de: "Code", es: "Código", ru: "Код" }),
    tabPreview: t({
      en: "Preview",
      fr: "Aperçu",
      de: "Vorschau",
      es: "Vista previa",
      ru: "Просмотр",
    }),
    preset: t({ en: "Preset", fr: "Modèle", de: "Vorlage", es: "Plantilla", ru: "Шаблон" }),
    presets: t({ en: "Presets", fr: "Modèles", de: "Vorlagen", es: "Plantillas", ru: "Шаблоны" }),
    presetsLight: t({
      en: "Presets (Light)",
      fr: "Modèles (Clair)",
      de: "Vorlagen (Hell)",
      es: "Plantillas (Claro)",
      ru: "Шаблоны (Светлые)",
    }),
    editCustom: t({
      en: "Edit Custom Theme",
      fr: "Modifier le thème",
      de: "Benutzerdefiniert bearbeiten",
      es: "Editar tema",
      ru: "Редактировать тему",
    }),
    loadPreset: t({
      en: "Load Preset",
      fr: "Charger un modèle",
      de: "Vorlage laden",
      es: "Cargar plantilla",
      ru: "Загрузить шаблон",
    }),
    presetDark: t({ en: "Dark", fr: "Sombre", de: "Dunkel", es: "Oscuro", ru: "Тёмная" }),
    presetGithubDark: t({
      en: "GitHub Dark",
      fr: "GitHub Sombre",
      de: "GitHub Dunkel",
      es: "GitHub Oscuro",
      ru: "GitHub Тёмная",
    }),
    presetGithubLight: t({
      en: "GitHub Light",
      fr: "GitHub Clair",
      de: "GitHub Hell",
      es: "GitHub Claro",
      ru: "GitHub Светлая",
    }),
    presetNeutral: t({
      en: "Neutral",
      fr: "Neutre",
      de: "Neutral",
      es: "Neutro",
      ru: "Нейтральная",
    }),
    presetMidnight: t({
      en: "Midnight",
      fr: "Minuit",
      de: "Mitternacht",
      es: "Medianoche",
      ru: "Полночь",
    }),
    presetForest: t({ en: "Forest", fr: "Forêt", de: "Wald", es: "Bosque", ru: "Лес" }),
    presetBloodMoon: t({
      en: "Blood Moon",
      fr: "Lune de Sang",
      de: "Blutmond",
      es: "Luna de Sangre",
      ru: "Кровавая Луна",
    }),
    presetMilitary: t({
      en: "Military",
      fr: "Militaire",
      de: "Militär",
      es: "Militar",
      ru: "Военная",
    }),
    presetOled: t({
      en: "OLED Black",
      fr: "OLED Noir",
      de: "OLED Schwarz",
      es: "OLED Negro",
      ru: "OLED Чёрная",
    }),
    presetSepia: t({ en: "Sepia", fr: "Sépia", de: "Sepia", es: "Sepia", ru: "Сепия" }),
    presetNord: t({ en: "Nord", fr: "Nord", de: "Nord", es: "Nord", ru: "Nord" }),
    presetDracula: t({ en: "Dracula", fr: "Dracula", de: "Dracula", es: "Dracula", ru: "Dracula" }),
    presetCatppuccin: t({
      en: "Catppuccin Mocha",
      fr: "Catppuccin Mocha",
      de: "Catppuccin Mocha",
      es: "Catppuccin Mocha",
      ru: "Catppuccin Mocha",
    }),
    presetGruvboxDark: t({
      en: "Gruvbox Dark",
      fr: "Gruvbox Sombre",
      de: "Gruvbox Dunkel",
      es: "Gruvbox Oscuro",
      ru: "Gruvbox Тёмная",
    }),
    presetTokyonight: t({
      en: "Tokyo Night",
      fr: "Tokyo Night",
      de: "Tokyo Night",
      es: "Tokyo Night",
      ru: "Tokyo Night",
    }),
    presetTokyonightLight: t({
      en: "Tokyo Night Light",
      fr: "Tokyo Night Clair",
      de: "Tokyo Night Hell",
      es: "Tokyo Night Claro",
      ru: "Tokyo Night Светлая",
    }),
    presetKanagawa: t({
      en: "Kanagawa",
      fr: "Kanagawa",
      de: "Kanagawa",
      es: "Kanagawa",
      ru: "Kanagawa",
    }),
    presetRosepine: t({
      en: "Rosé Pine",
      fr: "Rosé Pine",
      de: "Rosé Pine",
      es: "Rosé Pine",
      ru: "Rosé Pine",
    }),
    presetGruvboxLight: t({
      en: "Gruvbox Light",
      fr: "Gruvbox Clair",
      de: "Gruvbox Hell",
      es: "Gruvbox Claro",
      ru: "Gruvbox Светлая",
    }),
    presetRosepineDawn: t({
      en: "Rosé Pine Dawn",
      fr: "Rosé Pine Dawn",
      de: "Rosé Pine Dawn",
      es: "Rosé Pine Dawn",
      ru: "Rosé Pine Dawn",
    }),
    presetCatppuccinLatte: t({
      en: "Catppuccin Latte",
      fr: "Catppuccin Latte",
      de: "Catppuccin Latte",
      es: "Catppuccin Latte",
      ru: "Catppuccin Latte",
    }),
    presetLight: t({ en: "Light", fr: "Clair", de: "Hell", es: "Claro", ru: "Светлая" }),
    presetOcean: t({ en: "Ocean", fr: "Océan", de: "Ozean", es: "Océano", ru: "Океан" }),
    presetSand: t({ en: "Sand", fr: "Sable", de: "Sand", es: "Arena", ru: "Песок" }),
    presetRose: t({ en: "Rose", fr: "Rose", de: "Rose", es: "Rosa", ru: "Роза" }),
    presetMint: t({ en: "Mint", fr: "Menthe", de: "Minze", es: "Menta", ru: "Мята" }),
    presetLavender: t({
      en: "Lavender",
      fr: "Lavande",
      de: "Lavendel",
      es: "Lavanda",
      ru: "Лаванда",
    }),
    presetTwilight: t({
      en: "Twilight",
      fr: "Crépuscule",
      de: "Dämmerung",
      es: "Crepúsculo",
      ru: "Сумерки",
    }),
    presetMocha: t({ en: "Mocha", fr: "Moka", de: "Mokka", es: "Moca", ru: "Мокко" }),
    presetGroupDark: t({
      en: "Dark Themes",
      fr: "Thèmes sombres",
      de: "Dunkle Themes",
      es: "Temas oscuros",
      ru: "Тёмные темы",
    }),
    presetGroupLight: t({
      en: "Light Themes",
      fr: "Thèmes clairs",
      de: "Helle Themes",
      es: "Temas claros",
      ru: "Светлые темы",
    }),
    export: t({ en: "Export", fr: "Exporter", de: "Exportieren", es: "Exportar", ru: "Экспорт" }),
    import: t({ en: "Import", fr: "Importer", de: "Importieren", es: "Importar", ru: "Импорт" }),
    imported: t({
      en: "Theme imported successfully",
      fr: "Thème importé avec succès",
      de: "Theme erfolgreich importiert",
      es: "Tema importado correctamente",
      ru: "Тема успешно импортирована",
    }),
    importError: t({
      en: "Invalid theme file",
      fr: "Fichier de thème invalide",
      de: "Ungültige Theme-Datei",
      es: "Archivo de tema inválido",
      ru: "Неверный файл темы",
    }),
    exported: t({
      en: "Theme exported",
      fr: "Thème exporté",
      de: "Theme exportiert",
      es: "Tema exportado",
      ru: "Тема экспортирована",
    }),
    colorBase: t({
      en: "Base Colors",
      fr: "Couleurs de base",
      de: "Grundfarben",
      es: "Colores base",
      ru: "Базовые цвета",
    }),
    colorBase100: t({
      en: "Background",
      fr: "Arrière-plan",
      de: "Hintergrund",
      es: "Fondo",
      ru: "Фон",
    }),
    colorBase200: t({
      en: "Surface",
      fr: "Surface",
      de: "Oberfläche",
      es: "Superficie",
      ru: "Поверхность",
    }),
    colorBase300: t({ en: "Border", fr: "Bordure", de: "Rahmen", es: "Borde", ru: "Граница" }),
    colorBaseContent: t({ en: "Text", fr: "Texte", de: "Text", es: "Texto", ru: "Текст" }),
    colorPrimary: t({
      en: "Primary",
      fr: "Primaire",
      de: "Primär",
      es: "Primario",
      ru: "Основной",
    }),
    colorSecondary: t({
      en: "Secondary",
      fr: "Secondaire",
      de: "Sekundär",
      es: "Secundario",
      ru: "Вторичный",
    }),
    colorAccent: t({ en: "Accent", fr: "Accent", de: "Akzent", es: "Acento", ru: "Акцент" }),
    colorStatus: t({
      en: "Status Colors",
      fr: "Couleurs d'état",
      de: "Statusfarben",
      es: "Colores de estado",
      ru: "Цвета статуса",
    }),
    colorSuccess: t({ en: "Success", fr: "Succès", de: "Erfolg", es: "Éxito", ru: "Успех" }),
    colorWarning: t({
      en: "Warning",
      fr: "Avertissement",
      de: "Warnung",
      es: "Advertencia",
      ru: "Предупреждение",
    }),
    colorError: t({ en: "Error", fr: "Erreur", de: "Fehler", es: "Error", ru: "Ошибка" }),
    colorInfo: t({ en: "Info", fr: "Info", de: "Info", es: "Info", ru: "Информация" }),
    colorTerminal: t({
      en: "Terminal",
      fr: "Terminal",
      de: "Terminal",
      es: "Terminal",
      ru: "Терминал",
    }),
    colorTerminalBg: t({
      en: "Background",
      fr: "Arrière-plan",
      de: "Hintergrund",
      es: "Fondo",
      ru: "Фон",
    }),
    colorTerminalBorder: t({
      en: "Border",
      fr: "Bordure",
      de: "Rahmen",
      es: "Borde",
      ru: "Граница",
    }),
    colorLogError: t({ en: "Error", fr: "Erreur", de: "Fehler", es: "Error", ru: "Ошибка" }),
    colorLogWarning: t({
      en: "Warning",
      fr: "Avertissement",
      de: "Warnung",
      es: "Advertencia",
      ru: "Предупреждение",
    }),
    colorLogSuccess: t({ en: "Success", fr: "Succès", de: "Erfolg", es: "Éxito", ru: "Успех" }),
    colorLogInfo: t({ en: "Info", fr: "Info", de: "Info", es: "Info", ru: "Информация" }),
    colorLogDefault: t({
      en: "Default",
      fr: "Défaut",
      de: "Standard",
      es: "Predeterminado",
      ru: "По умолчанию",
    }),
    colorSyntax: t({
      en: "Syntax Highlighting",
      fr: "Coloration syntaxique",
      de: "Syntaxhervorhebung",
      es: "Resaltado de sintaxis",
      ru: "Подсветка синтаксиса",
    }),
    colorSyntaxComment: t({
      en: "Comment",
      fr: "Commentaire",
      de: "Kommentar",
      es: "Comentario",
      ru: "Комментарий",
    }),
    colorSyntaxSelector: t({
      en: "Selector",
      fr: "Sélecteur",
      de: "Selektor",
      es: "Selector",
      ru: "Селектор",
    }),
    colorSyntaxProperty: t({
      en: "Property",
      fr: "Propriété",
      de: "Eigenschaft",
      es: "Propiedad",
      ru: "Свойство",
    }),
    colorSyntaxVariable: t({
      en: "Variable",
      fr: "Variable",
      de: "Variable",
      es: "Variable",
      ru: "Переменная",
    }),
    colorSyntaxString: t({
      en: "String",
      fr: "Chaîne",
      de: "Zeichenkette",
      es: "Cadena",
      ru: "Строка",
    }),
    colorSyntaxNumber: t({ en: "Number", fr: "Nombre", de: "Zahl", es: "Número", ru: "Число" }),
    colorSyntaxFunction: t({
      en: "Function",
      fr: "Fonction",
      de: "Funktion",
      es: "Función",
      ru: "Функция",
    }),
    previewButton: t({ en: "Button", fr: "Bouton", de: "Schaltfläche", es: "Botón", ru: "Кнопка" }),
    previewCard: t({
      en: "Card Example",
      fr: "Exemple de carte",
      de: "Kartenbeispiel",
      es: "Ejemplo de tarjeta",
      ru: "Пример карточки",
    }),
    previewBadge: t({ en: "Badge", fr: "Badge", de: "Abzeichen", es: "Insignia", ru: "Значок" }),
    previewAlert: t({
      en: "Alert Example",
      fr: "Exemple d'alerte",
      de: "Hinweisbeispiel",
      es: "Ejemplo de alerta",
      ru: "Пример уведомления",
    }),
    previewInput: t({ en: "Input", fr: "Saisie", de: "Eingabe", es: "Entrada", ru: "Ввод" }),
    previewSampleText: t({
      en: "Sample text content",
      fr: "Texte d'exemple",
      de: "Beispieltext",
      es: "Texto de ejemplo",
      ru: "Пример текста",
    }),
    colorNeutralGroup: t({
      en: "Neutral",
      fr: "Neutre",
      de: "Neutral",
      es: "Neutro",
      ru: "Нейтральный",
    }),
    colorNeutral: t({
      en: "Neutral",
      fr: "Neutre",
      de: "Neutral",
      es: "Neutro",
      ru: "Нейтральный",
    }),
    colorNeutralContent: t({
      en: "Neutral Text",
      fr: "Texte neutre",
      de: "Neutral Text",
      es: "Texto neutro",
      ru: "Нейтральный текст",
    }),
    colorContentGroup: t({
      en: "Content Colors",
      fr: "Couleurs de contenu",
      de: "Inhaltsfarben",
      es: "Colores de contenido",
      ru: "Цвета контента",
    }),
    colorPrimaryContent: t({
      en: "Primary Text",
      fr: "Texte primaire",
      de: "Primär Text",
      es: "Texto primario",
      ru: "Основной текст",
    }),
    colorSecondaryContent: t({
      en: "Secondary Text",
      fr: "Texte secondaire",
      de: "Sekundär Text",
      es: "Texto secundario",
      ru: "Вторичный текст",
    }),
    colorAccentContent: t({
      en: "Accent Text",
      fr: "Texte accent",
      de: "Akzent Text",
      es: "Texto acento",
      ru: "Акцентный текст",
    }),
    colorInfoContent: t({
      en: "Info Text",
      fr: "Texte info",
      de: "Info Text",
      es: "Texto info",
      ru: "Текст инфо",
    }),
    colorSuccessContent: t({
      en: "Success Text",
      fr: "Texte succès",
      de: "Erfolg Text",
      es: "Texto éxito",
      ru: "Текст успеха",
    }),
    colorWarningContent: t({
      en: "Warning Text",
      fr: "Texte avert.",
      de: "Warnung Text",
      es: "Texto advert.",
      ru: "Текст предупр.",
    }),
    colorErrorContent: t({
      en: "Error Text",
      fr: "Texte erreur",
      de: "Fehler Text",
      es: "Texto error",
      ru: "Текст ошибки",
    }),
    colorAppAccentGroup: t({
      en: "App Accents",
      fr: "Accents de l'app",
      de: "App-Akzente",
      es: "Acentos de app",
      ru: "Акценты приложения",
    }),
    colorAccentMap: t({
      en: "Map Icon",
      fr: "Icône carte",
      de: "Karten-Icon",
      es: "Icono mapa",
      ru: "Иконка карты",
    }),
    colorAccentMods: t({
      en: "Mods Icon",
      fr: "Icône mods",
      de: "Mods-Icon",
      es: "Icono mods",
      ru: "Иконка модов",
    }),
    colorAccentStatServer: t({
      en: "Servers Stat",
      fr: "Stat serveurs",
      de: "Server-Statistik",
      es: "Estad. servidores",
      ru: "Стат. серверов",
    }),
    colorAccentStatPlayers: t({
      en: "Players Stat",
      fr: "Stat joueurs",
      de: "Spieler-Statistik",
      es: "Estad. jugadores",
      ru: "Стат. игроков",
    }),
    colorAccentStatSteam: t({
      en: "Steam Stat",
      fr: "Stat Steam",
      de: "Steam-Statistik",
      es: "Estad. Steam",
      ru: "Стат. Steam",
    }),
    colorAccentUpdate: t({
      en: "Update Badge",
      fr: "Badge màj",
      de: "Update-Abzeichen",
      es: "Insignia actual.",
      ru: "Значок обновл.",
    }),
    colorAccentStale: t({
      en: "Stale Badge",
      fr: "Badge obsolète",
      de: "Veraltet-Abzeichen",
      es: "Insignia obsoleto",
      ru: "Значок устаревш.",
    }),
    colorAccentHighlight: t({
      en: "Highlight",
      fr: "Surbrillance",
      de: "Hervorhebung",
      es: "Resaltado",
      ru: "Подсветка",
    }),
    colorFeatureGroup: t({
      en: "Feature Colors",
      fr: "Couleurs fonct.",
      de: "Feature-Farben",
      es: "Colores función",
      ru: "Цвета функций",
    }),
    colorFeatBrowser: t({
      en: "Browser",
      fr: "Navigateur",
      de: "Browser",
      es: "Navegador",
      ru: "Браузер",
    }),
    colorFeatMods: t({ en: "Mods", fr: "Mods", de: "Mods", es: "Mods", ru: "Моды" }),
    colorFeatStats: t({
      en: "Stats",
      fr: "Statistiques",
      de: "Statistiken",
      es: "Estadísticas",
      ru: "Статистика",
    }),
    colorFeatLaunch: t({
      en: "Launch",
      fr: "Lancement",
      de: "Starten",
      es: "Lanzamiento",
      ru: "Запуск",
    }),
    colorBadgeGroup: t({
      en: "Badge Colors",
      fr: "Couleurs badges",
      de: "Abzeichen-Farben",
      es: "Colores insignia",
      ru: "Цвета значков",
    }),
    colorBadgeRank: t({ en: "Rank", fr: "Rang", de: "Rang", es: "Rango", ru: "Ранг" }),
    colorBadgeStatus: t({ en: "Status", fr: "Statut", de: "Status", es: "Estado", ru: "Статус" }),
    colorBadgeCountry: t({ en: "Country", fr: "Pays", de: "Land", es: "País", ru: "Страна" }),
    colorBadgePlayers: t({
      en: "Players",
      fr: "Joueurs",
      de: "Spieler",
      es: "Jugadores",
      ru: "Игроки",
    }),
    colorBadgeFirstperson: t({
      en: "First Person",
      fr: "Première pers.",
      de: "Erste Person",
      es: "Primera persona",
      ru: "От первого лица",
    }),
    colorBadgeOfficial: t({
      en: "Official",
      fr: "Officiel",
      de: "Offiziell",
      es: "Oficial",
      ru: "Официальный",
    }),
    colorBadgeCustom: t({
      en: "Custom",
      fr: "Personnalisé",
      de: "Benutzerdefiniert",
      es: "Personalizado",
      ru: "Пользоват.",
    }),
    colorUiElementGroup: t({
      en: "UI Elements",
      fr: "Éléments UI",
      de: "UI-Elemente",
      es: "Elementos UI",
      ru: "Элементы UI",
    }),
    colorPortQuery: t({
      en: "Query Port",
      fr: "Port requête",
      de: "Query-Port",
      es: "Puerto consulta",
      ru: "Порт запроса",
    }),
    colorPortGame: t({
      en: "Game Port",
      fr: "Port jeu",
      de: "Spiel-Port",
      es: "Puerto juego",
      ru: "Игровой порт",
    }),
    colorLink: t({ en: "Link", fr: "Lien", de: "Link", es: "Enlace", ru: "Ссылка" }),
    colorScore: t({ en: "Score", fr: "Score", de: "Punktzahl", es: "Puntuación", ru: "Счёт" }),
    colorBest: t({ en: "Best", fr: "Meilleur", de: "Bestzeit", es: "Mejor", ru: "Лучший" }),
    colorOptionGroup: t({
      en: "Option Groups",
      fr: "Groupes options",
      de: "Optionsgruppen",
      es: "Grupos opciones",
      ru: "Группы опций",
    }),
    colorOptDisplay: t({
      en: "Display",
      fr: "Affichage",
      de: "Anzeige",
      es: "Pantalla",
      ru: "Дисплей",
    }),
    colorOptNetwork: t({ en: "Network", fr: "Réseau", de: "Netzwerk", es: "Red", ru: "Сеть" }),
    colorOptLaunch: t({
      en: "Launch",
      fr: "Lancement",
      de: "Start",
      es: "Lanzamiento",
      ru: "Запуск",
    }),
    colorOptInput: t({ en: "Input", fr: "Entrée", de: "Eingabe", es: "Entrada", ru: "Ввод" }),
    colorOptMisc: t({ en: "Misc", fr: "Divers", de: "Sonstiges", es: "Varios", ru: "Разное" }),
    colorTechBrandGroup: t({
      en: "Tech Brands",
      fr: "Marques tech",
      de: "Tech-Marken",
      es: "Marcas tech",
      ru: "Тех. бренды",
    }),
    colorTechTauri: t({ en: "Tauri", fr: "Tauri", de: "Tauri", es: "Tauri", ru: "Tauri" }),
    colorTechSvelte: t({ en: "Svelte", fr: "Svelte", de: "Svelte", es: "Svelte", ru: "Svelte" }),
    colorTechRust: t({ en: "Rust", fr: "Rust", de: "Rust", es: "Rust", ru: "Rust" }),
    colorTechDaisyui: t({
      en: "DaisyUI",
      fr: "DaisyUI",
      de: "DaisyUI",
      es: "DaisyUI",
      ru: "DaisyUI",
    }),
    colorTechTailwind: t({
      en: "Tailwind",
      fr: "Tailwind",
      de: "Tailwind",
      es: "Tailwind",
      ru: "Tailwind",
    }),
    colorWindowGroup: t({
      en: "Window Controls",
      fr: "Contrôles fenêtre",
      de: "Fenstersteuerung",
      es: "Controles ventana",
      ru: "Управление окном",
    }),
    colorBtnClose: t({
      en: "Close Button",
      fr: "Bouton fermer",
      de: "Schließen-Schaltfläche",
      es: "Botón cerrar",
      ru: "Кнопка закрыть",
    }),
    radiusGroup: t({
      en: "Border Radius",
      fr: "Rayon bordure",
      de: "Eckenradius",
      es: "Radio de borde",
      ru: "Радиус границы",
    }),
    radiusBtn: t({ en: "Button", fr: "Bouton", de: "Schaltfläche", es: "Botón", ru: "Кнопка" }),
    radiusBox: t({ en: "Box", fr: "Boîte", de: "Box", es: "Caja", ru: "Блок" }),
    radiusBadge: t({ en: "Badge", fr: "Badge", de: "Abzeichen", es: "Insignia", ru: "Значок" }),
    windowSection: t({ en: "Window", fr: "Fenêtre", de: "Fenster", es: "Ventana", ru: "Окно" }),
    windowRounded: t({
      en: "Rounded",
      fr: "Arrondi",
      de: "Abgerundet",
      es: "Redondeado",
      ru: "Скруглённое",
    }),
    windowBorder: t({ en: "Border", fr: "Bordure", de: "Rahmen", es: "Borde", ru: "Рамка" }),
    windowBorderFocus: t({
      en: "Focused",
      fr: "Focalisé",
      de: "Fokussiert",
      es: "Enfocado",
      ru: "В фокусе",
    }),
    windowBorderBlur: t({
      en: "Unfocused",
      fr: "Non focalisé",
      de: "Unfokussiert",
      es: "Desenfocado",
      ru: "Не в фокусе",
    }),
    logoSection: t({ en: "Logo", fr: "Logo", de: "Logo", es: "Logo", ru: "Логотип" }),
    logoInvert: t({
      en: "Invert logo (for light themes)",
      fr: "Inverser le logo (pour les thèmes clairs)",
      de: "Logo invertieren (für helle Themes)",
      es: "Invertir logo (para temas claros)",
      ru: "Инвертировать логотип (для светлых тем)",
    }),
    cssPlaceholder: t({
      en: "Enter your custom CSS...",
      fr: "Entrez votre CSS personnalisé...",
      de: "Eigenes CSS eingeben...",
      es: "Ingresa tu CSS personalizado...",
      ru: "Введите свой CSS...",
    }),
  },
} satisfies Dictionary;

export default content;
